opentripplanner/OpenTripPlanner

src/main/java/org/opentripplanner/common/model/GenericLocation.java
src/main/java/org/opentripplanner/profile/ProfileRequest.java
src/main/java/org/opentripplanner/routing/core/SimpleIntersectionTraversalCostModel.java

Just added "implements Serializable" in a few places.

Mark a few things serializable, fixes #1663.

---

src/client/js/otp/modules/analyst/AnalystLegendWidget.js
src/client/js/otp/modules/analyst/AnalystModule.js

Make a time surface for a given request, then using the surface ID that is returned to fetch the tiles. Also fixed the analyst legend by requesting the correct URL.

Modified the Analyst web-module to work again by using the TimeSurface API

---

src/main/java/org/opentripplanner/index/IndexAPI.java

To fix #1720. Definitely open to debate on how to best present this via the API; right now it's a separate call from anything else.

Add transfers to the REST API.

---

src/client/js/otp/core/Webapp.js
src/client/js/otp/modules/planner/PlannerModule.js

siteURL is never set from what I can see, siteUrl is used elsewhere. must be typo.
see issue  #1582

siteURL->siteUrl.

---

src/main/java/org/opentripplanner/routing/algorithm/strategies/DefaultRemainingWeightHeuristic.java

I tried to improve the DefaultRemainingWeightHeuristic a bit further by using straight-line distances exclusively (instead of first computing the on-street distance to the closest stop and then comparing it to straight-line distances later) and considering street edges only, as it's possible that a stop gets linked to a road that's in a different location. However, I'm no longer convinced that the old code was actually incorrect.
One issue with this version is that the closest stop in terms of on-street distance isn't necessarily the closest stop in terms of straight-line distance, but this shouldn't impact correctness, unless the current code is also incorrect.
I'm mainly putting this pull request here to prevent the loss of potentially useful work. Someone could compare the old and new …

Fix DefaultRemainingWeightHeuristic distance issue

---

enunciate.xml

For more information on original bug, see:
https://jira.codehaus.org/browse/ENUNCIATE-678

Workaround for enunciate bug 678.

---

src/main/java/com/conveyal/gtfs/model/CalendarDate.java
src/main/java/com/conveyal/gtfs/model/Entity.java
src/main/java/com/conveyal/gtfs/model/FeedInfo.java
src/main/java/com/conveyal/gtfs/model/Frequency.java
src/main/java/com/conveyal/gtfs/model/Service.java
src/main/java/com/conveyal/gtfs/model/StopTime.java

Fixes #1736 , #1738, and #1735.

Fix a few bugs in the GTFS loader

---

pom.xml
src/main/java/org/opentripplanner/geocoder/bano/BanoGeocoder.java
src/test/java/org/opentripplanner/geocoder/bano/BanoGeocoderTest.java

Implementation of the BANO (Base Nationale d'Adresse Ouverte) [API of data.gouv.fr](http://adresse.data.gouv.fr/api/).

Bano geocoder

---

src/client/js/otp/modules/planner/Itinerary.js

... also fix some stop undefined in the print / email  itineraries.

Fix  #1778 -  previous next buttons

---

src/main/java/org/opentripplanner/analyst/ResultSetWithTimes.java
src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
src/main/java/org/opentripplanner/profile/ProfileRouter.java
src/main/java/org/opentripplanner/profile/StopTreeCache.java
src/main/java/org/opentripplanner/routing/spt/DominanceFunction.java
src/test/java/org/opentripplanner/graph_builder/module/osm/TriangleInequalityTest.java

Fix some of the issues related to using the Pareto dominance function, and include histograms in resultsetwithtimes.

Analyst fixes

---

src/main/java/org/opentripplanner/analyst/ResultSetDelta.java
src/main/java/org/opentripplanner/api/parameter/QualifiedMode.java
src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
src/main/java/org/opentripplanner/profile/ProfileRequest.java

Make qualified modes serializable. Also allow creating result set deltas from existing result sets.

Qualified mode analyst fixes

---

src/main/java/org/opentripplanner/analyst/PointSet.java

When loading PointSet from shapefile, allow specifying a property name from which to read feature IDs and a list of property names to load values from. If an ID field is not specified, set feature IDs to index. If property fields are not specified, try to load all properties.
Preserves existing fromShapefile(File) behavior when no fields are specified.

Set ID fields and select property fields when loading PointSet from shapefile

---

src/main/java/org/opentripplanner/routing/edgetype/TimetableSnapshot.java
src/main/java/org/opentripplanner/updater/stoptime/PollingStoptimeUpdater.java
src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
src/main/java/org/opentripplanner/updater/stoptime/WebsocketGtfsRealtimeUpdater.java

Some patches such that a FULL_DATASET GTFS-RT update with no trip updates results in the effects of all previous trip updates being canceled.

GTFS-RT FULL_DATASET message without trip updates support

---

src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/module/osm/PortlandCustomNamer.java
src/main/java/org/opentripplanner/graph_builder/services/osm/CustomNamer.java
src/main/java/org/opentripplanner/reflect/ReflectionLibrary.java
src/main/java/org/opentripplanner/standalone/GraphBuilderParameters.java

This should fix #1797. Also correct a minor warning.

OSM custom namer config using JSON

---

src/main/java/com/google/transit/realtime/GtfsRealtime.java
src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java

This pull request contains the GTFS-RT protocol buffer generated Java class of http://gtfs.ovapi.nl/new/gtfs-realtime.proto, which is closer to the "standard" gtfs-realtime.proto file (only adds TripDescriptor.ScheduleRelationship.MODIFIED).
Also, a bug is fixed where a null-pointer exception would occur when Timetable.createUpdatedTripTimes() can't handle a trip update.
Finally, make OTP a little bit less strict for some GTFS-RT trip updates.

GTFS-RT support for OvApi

---

docs/Scripting.md
docs/index.md

I'm not sure about including scripting as an analyst module (in the index page) as you can also use it for automated testing.

Convert scripting doc from github to new doc.

---

src/main/java/org/opentripplanner/analyst/Histogram.java
src/main/java/org/opentripplanner/analyst/ResultSet.java
src/main/java/org/opentripplanner/analyst/SampleSet.java
src/main/java/org/opentripplanner/analyst/TimeSurface.java
src/main/java/org/opentripplanner/analyst/core/IsochroneData.java
src/main/java/org/opentripplanner/analyst/request/SampleFactory.java
src/main/java/org/opentripplanner/api/resource/SurfaceResource.java
src/main/java/org/opentripplanner/profile/PropagatedTimesStore.java
src/main/java/org/opentripplanner/profile/RepeatedRaptorProfileRouter.java
src/main/java/org/opentripplanner/routing/trippattern/FrequencyEntry.java

Isochrones can now be placed into ResultSets. ResultSets can be passed around with isochrones and/or histograms.

add isochrones to resultset.

---

src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/standalone/GraphBuilderParameters.java

Previously this was set in OpenStreetMapModule.
Not it can be set in json config as:
- staticBikeRental
- staticParkAndRide
- staticBikeParkAndRide
Default values are same as before (staticParkAndRide true, others false)
Fixes #1915.

Added JSON config for static P+R bike share and bike P+R

---

docs/Developers-Guide.md

Added debug_layers description to docs

---

src/client/js/otp/modules/planner/ItinerariesWidget.js

Changes how CAR mode is shown in client.
Currently distance isn't shown. This commit adds it.

Car display fixes

---

src/client/js/otp/core/IndexApi.js

in client. More info in #1947
@abyrd: I think it would be good idea to include it in release.

This is hackish "fix" for error when clicking on bike rental stations

---

src/client/js/otp/modules/bikeshare/BikeStationsWidget.js

Added "Bicycle rental" to Drop off/Pick Up Text in bikesharing client module. Text is translated with same
framework as the rest of client.
Working on #1966.

Added "Bicycle rental" to Drop off/Pick Up

---

src/client/js/otp/modules/planner/ItinerariesWidget.js

It was fixed in #1955. But merging #1917 broke it again.
Here are the changes that were lost. Fixes #1925.

Fixing car display undefined again

---

docs/Configuration.md
src/main/java/org/opentripplanner/updater/bike_rental/BCycleBikeRentalDataSource.java
src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java
src/main/java/org/opentripplanner/updater/bike_rental/CitiBikeNycBikeRentalDataSource.java
src/main/java/org/opentripplanner/updater/bike_rental/GenericXmlBikeRentalDataSource.java
src/main/java/org/opentripplanner/updater/bike_rental/NextBikeRentalDataSource.java
src/main/java/org/opentripplanner/util/xml/XmlDataListDownloader.java

Add support for the [Citi Bike rental JSON feed](http://www.citibikenyc.com/stations/json).

Add NYC Citi and NextBike rental updaters

---

docs/Scripting.md
src/main/java/org/opentripplanner/scripting/api/OtpsEntryPoint.java

Fix scripting missing OtpMain::run() method.

---

src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java

Add a check to ensure that `visibilityPolygon` has vertices.
Resolves #2083

Change to ensure visibilityPolygon has vertices before converting

---

src/main/java/org/opentripplanner/routing/algorithm/strategies/InterleavedBidirectionalHeuristic.java
src/test/java/org/opentripplanner/routing/algorithm/TestParkAndRide.java

Fixes P+R and B+R on depart by searches. Reason for breaking isn't known.
More in #2119 .

Fix for park ride

---

src/main/java/org/opentripplanner/index/model/RouteShort.java

This adds agency name from route to profile transit response and fixes #2096.

Add agencyName to profile response

---

docs/Configuration.md
src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java

KML bike rental upstream

---

src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java

This resolves the compilation error currently present in master.
This makes the changes in #1999 and #2001 compatible with each other.

Fix issue with AgencyId comparsion when applying AlertPatch

---

docs/Configuration.md
src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java
src/main/java/org/opentripplanner/updater/bike_rental/SanFranciscoBayAreaBikeRentalDataSource.java

This is almost exactly the same as the NYC class. Would it be better to perform a refactor to support a common type?

Adding SF bay area bike share

---

src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java

The labels and textfields aren't placed correctly at the moment at the preference panel of the visualizer. See also issue #2230. 
This Pull Request fixes this issue.

Layout preference panel visualizer (fix for issue #2230)

---

src/main/java/org/opentripplanner/gtfs/GtfsLibrary.java

Fix for #2188. Map the TPEG route types 401 and 402 to SUBWAY instead of
RAIL

Change to map TPEG 401 and 402 to subway.

---

src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java
src/main/java/org/opentripplanner/routing/impl/CandidateEdge.java

In some cases the headsign changes during a trip. This fixes issue #2225 so that the leg headsign is more dynamic.

Changed so that headsign for a leg is not always the last stop.

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java

Introduced with https://github.com/opentripplanner/OpenTripPlanner/pull/2294

Fix exception when building graph

---

pom.xml
src/main/resources/logback.xml

Fix logging messages that were being swallowed by JUL.

---

src/main/java/org/opentripplanner/updater/bike_rental/ShareBikeRentalDataSource.java
src/test/java/org/opentripplanner/updater/bike_rental/TestShareBikeRentalStationSource.java

Fix URL parameter parsing when no URL parameters given in SharebikeRentalDataSource.

Sharebike: fix URL parsing when no parameters given

---

src/client/js/otp/modules/planner/PlannerModule.js
src/client/js/otp/util/Itin.js
src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js

This merges changes in PR #1591 and fixes #1553

Makes PR #1591 mergable

---

src/main/java/org/opentripplanner/updater/bike_rental/ShareBikeRentalDataSource.java

Now tests run fine on Windows as well

Fix for #2339

---

docs/Deployments.md

There is a link which is misspelled.

Web Link Typo

---

src/main/java/org/opentripplanner/updater/bike_rental/VCubDataSource.java

Variable names have changed on February 15th in API. Fix them in VCub updater.

Fix VCub updater using new API variable names.

---

src/main/java/org/opentripplanner/graph_builder/module/osm/DefaultWayPropertySetSource.java

See http://wiki.openstreetmap.org/wiki/Tag:highway%3Dcorridor

Make osm highway=corridor pedestrian routable

---

docs/Changelog.md
docs/github_issue_linker.py

I wrote a script which links issues in Changelog to GitHub issues and also run it on current Changelog.

Script to add links to GitHub issues in Changelog

---

docs/Developers-Guide.md

Just fixed a link in the documentation :)

Fix link to geoserver website

---

src/main/java/org/opentripplanner/routing/edgetype/Timetable.java

Adding trip_id to error and debug outputs related to trip matching using GTFS-RT feeds.

Add trip_id information involved in trips matching using GTFS-RT feed.

---

src/client/js/otp/layers/StopsLayer.js
src/client/js/otp/modules/planner/Itinerary.js
src/client/js/otp/util/Itin.js
src/client/js/otp/widgets/transit/StopViewerWidget.js

A few changes that should fix the empty popups among other minor problems. See #2474.

Fix scripts when entity IDs contain colons. Should fix #2474

---

src/main/java/org/opentripplanner/scripting/api/OtpsRoutingRequest.java

Expose maxTransferDistance and maxTransfers through scripting api.

Make maxTransfer* options configurable through scripting api (#2507)

---

src/main/java/org/opentripplanner/graph_builder/module/GtfsFeedId.java

Micro-optimalization: Do not create a String for the CsvReader, as it supports stream+charset in constructor.

Micro-optimalization: Create CSV reader directly from InputStream when reading GTFS feed info

---

src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdater.java
src/main/java/org/opentripplanner/updater/bike_rental/SmooveBikeRentalDataSource.java
src/test/java/org/opentripplanner/updater/bike_rental/TestBikeRentalStationSource.java
src/test/resources/bike/smoove.json

This PR adds a new updater for [Smoove](http://www.smoove-bike.com/) bike rental systems.
Example api endpoint is http://helsinki-fi.smoove.pro/api-public/stations

Add Smoove citybikes updater

---

pom.xml
src/test/java/org/opentripplanner/model/json_serialization/EncodedPolylineJSONSerializerTest.java

upgrade jackson and commons-compress 

---

docs/Developers-Guide.md

Fixes https://github.com/opentripplanner/OpenTripPlanner/issues/2709
- [x ] **issue**: Link to or create an [issue](https://github.com/opentripplanner/OpenTripPlanner/issues) that describes the relevant feature or bug. Add [GitHub keywords](https://help.github.com/articles/closing-issues-using-keywords/) to this PR's description (e.g., `closes #45`).

Update Sun Java code conventions link

---

src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/itinerary/ItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/AccessEgressRouter.java

I have added some javadoc as requested by @abyrd in the Raptor integration pull request (https://github.com/opentripplanner/OpenTripPlanner/pull/2754)

Added javadoc to the Raptor integration

---

docs/Changelog.md
src/main/java/org/opentripplanner/updater/alerts/GtfsRealtimeAlertsUpdater.java
src/main/java/org/opentripplanner/updater/stoptime/GtfsRealtimeHttpTripUpdateSource.java

Send an Accept: header appropriate for a protobuf response.

---

src/test/java/org/opentripplanner/geocoder/bano/BanoGeocoderTest.java

Closes #2798 (Failing BANO geocoder test)

Fix Failing BANO geocoder test.

---

docs/Changelog.md
pom.xml

Corrects surefire test fail during build [#2816](https://github.com/opentripplanner/OpenTripPlanner/issues/2816)

Fixes surefire test fail during build #2816

---

docs/Changelog.md
docs/Configuration.md
src/main/java/org/opentripplanner/graph_builder/module/osm/UKWayPropertySetSource.java
src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java

Adds UK Way Property Set, issue [#2818](https://github.com/opentripplanner/OpenTripPlanner/issues/2818)

Adds UK Way Property Set #2818

---

docs/Changelog.md
src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java

Fixes https://github.com/opentripplanner/OpenTripPlanner/issues/2371
This was cherry-picked from dev-1.x.
I will add a line in the changelog, which I think we forgot in the dev-1.x branch.

Add a fix to StreetTransitLink to allow transfers between stops.

---

docs/Changelog.md
docs/Configuration.md
src/main/java/org/opentripplanner/api/common/RoutingResource.java

This PR is cherrypicked from #2809.

Add documentation for PlannerResource#mode (cherry picked)

---

.travis.yml
docs/Getting-OTP.md

Minor doc update: Change from "Java 8" to "Java 11" in doc.

---

docs/Changelog.md
docs/Configuration.md
src/main/java/org/opentripplanner/graph_builder/module/osm/UKWayPropertySetSource.java
src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java

Uk way property set

---

src/main/java/org/opentripplanner/routing/algorithm/raptor/itinerary/ItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/RaptorRouter.java
src/main/java/org/opentripplanner/routing/bike_rental/TimeBasedBikeRentalFareService.java
src/main/java/org/opentripplanner/routing/fares/AddingMultipleFareService.java
src/main/java/org/opentripplanner/routing/impl/DefaultFareServiceImpl.java
src/main/java/org/opentripplanner/routing/impl/DutchFareServiceImpl.java
src/main/java/org/opentripplanner/routing/impl/NycFareServiceImpl.java
src/main/java/org/opentripplanner/routing/impl/Ride.java
src/main/java/org/opentripplanner/routing/impl/RideMapper.java
src/main/java/org/opentripplanner/routing/services/FareService.java
src/test/java/org/opentripplanner/routing/fares/MultipleFareServiceTest.java

This should fix #2884. In testing, routing succeeds and results have an attached fare.
Based on a recent conversation, I also changed the RaptorRouter so it first creates the Itinerary, then attaches the Fare to the Itinerary in a subsequent step (not inside the ItineraryMapper).

Fix stop lookup in dev-2.x fare calculation

---

README.md

add links to google groups in README

---

docs/Changelog.md
src/main/java/org/opentripplanner/transit/raptor/api/request/ArrivalAndDeparturePreference.java
src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParams.java
src/main/java/org/opentripplanner/transit/raptor/api/request/SearchParamsBuilder.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/WorkerLifeCycle.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/DestinationArrivalPaths.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/besttimes/BestTimes.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/CostCalculator.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SearchContext.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/workerlifecycle/LifeCycleEventPublisher.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/workerlifecycle/LifeCycleSubscriptions.java
src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/CostCalculatorTest.java
src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/RoundTrackerTest.java

This PR build on _Otp2 limit transit service period #2926_ and should be rreviewed and merged after that.

Unexpected wait cost between access and transit

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java

Otp2 transmodel changes

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitData.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreator.java
src/main/java/org/opentripplanner/routing/core/RoutingContext.java
src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
src/test/java/org/opentripplanner/routing/algorithm/TestBanning.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java

This will reimplement that functionality for banning/whitelisting of routes/agencies that was already in OTP1. In the RoutingRequest it works the same as in OTP1. The only change is that I have added a method that takes a collection of routes and returns the ones that are banned.
The RaptorRoutingRequestTransitDataCreator class uses this set of banned routes in order to filter routes before routing happens. This filter works the same way as the mode-filter.
We also might want to refactor the methods for banning routes in the RoutingRequest. Now it takes in a string, which is in turn passed to the RouteMatcher and only there is it documented how the string is parsed.

Otp2 reimplement banning/whitelisting of routes/agencies

---

src/main/java/org/opentripplanner/model/plan/WalkStep.java

Fix infinite recursion in WalkStep#addAlerts

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java

RaptorPathToItineraryMapper tripShortName fix

---

pom.xml

This is the OTP1 version of #3039 . I have done no additional testing on it. Are you able to look at this, @fpurcell ?

Update geospatial repository url

---

pom.xml

This updates the remaining two repos to use HTTPS. This is a requirement in some build systems.

Otp2 update repository urls

---

pom.xml

- [x ] **roadmap**: Check the [roadmap](https://github.com/orgs/opentripplanner/projects/1) for this feature or bug. If it is not already on the roadmap, PLC will discuss as part of the review process.
This is the OTP1 version of #3043

Update onebusaway-release repo to use https

---

src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilder.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilderTest.java

Add `MaxLimitFilter` when min and max limits are identical

---

docs/examples/Readme.md
docs/examples/entur/Readme.md
docs/examples/entur/build-config.json
docs/examples/entur/otp-config.json
docs/examples/entur/router-config.json

Provide example config and setup for Entur.

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java

This make the Transmodel Schema brosable after upgrading the GraphQL library. 
The PR add the Relay PageInfo type needed to support paging functionality.

Critical bugfix to the Entur Sandbox GraphQL Transmodel API

---

src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java
src/main/java/org/opentripplanner/model/plan/ItinerariesCalculateLegTotals.java
src/main/java/org/opentripplanner/model/plan/Itinerary.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/ItinerariesHelper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/routing/core/RoutingContext.java
src/main/java/org/opentripplanner/routing/error/TrivialPathException.java
src/test/java/org/opentripplanner/routing/TestHalfEdges.java

Do not throw if access or egress legs are trivial

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLItineraryImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPlanImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
src/ext/resources/legacygraphqlapi/schema.graphqls
src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java

Fixes and minor improvemtns for legacy GraphQL API

---

docs/Configuration.md

Document `finland` way property set. This is follow-up to #3096

Document `finland` way property set

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLFeedImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
src/main/java/org/opentripplanner/gtfs/mapping/FeedInfoMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
src/main/java/org/opentripplanner/index/IndexAPI.java
src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
src/test/java/org/opentripplanner/gtfs/mapping/FeedInfoMapperTest.java

Also fixes issue with invalid id in `FeedInfo` for feeds without explicit ids.

Legacy GraphQL API fixes 

---

src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
src/ext/resources/legacygraphqlapi/schema.graphqls
src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
src/main/java/org/opentripplanner/api/parameter/Qualifier.java

Add `PICKUP` and `DROPOFF` as qualifiers for car mode.

Fix Pickup and Dropoff qualifiers for car mode

---

src/main/java/org/opentripplanner/standalone/OTPMain.java

Fix for issue #3241 : SLF4J/JUL configuration

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java
src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java
src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java

Otp2 set trip operator

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java

Building visibility graphs for areas can take a significant amount of time of the OSM build process. This PR adds the ProgressTracker to this process.

Add progress tracker to areas visibility calculation

---

docs/Changelog.md
docs/Configuration.md
src/main/java/org/opentripplanner/model/plan/Leg.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/AdjustedCost.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/GroupBySimilarity.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilder.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/GroupBySimilarLegsFilter.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/OtpDefaultSortOrder.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/SortFilter.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/SortOnAdjustedCost.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/SortOnGeneralizedCost.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainMapper.java
src/main/java/org/opentripplanner/routing/api/request/GroupBySimilarityParams.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/standalone/config/GroupBySimilarityMapper.java
src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/AdjustedCostTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/GroupBySimilarLegsFilterTest.java

Prioritize "direct" routes over transfers in group-filters

---

docs/Changelog.md
src/main/java/org/opentripplanner/api/resource/PlannerResource.java
src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilder.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/RemoveWalkOnlyFilter.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/FilterTransitWhenDirectModeIsEmpty.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/RaptorRequestMapper.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/RemoveWalkOnlyFilterTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptor/router/FilterTransitWhenDirectModeIsEmptyTest.java

Remove poor transit results for short trips, when walking is better

---

mkdocs.yml

This just fixes an incorrect title in the mkdocs.yml file.

Fix title in mkdocs.yml

---

.github/pull_request_template.md

This PR update the pull request template.
- **Issue**: No
- **Unit tests**: No, doc only
- **Code style**: Yes 
- **Documentation**: Yes
- **Changelog**: No, doc only.
<details>
<summary>Checklist notes</summary>
- Link to or create an [issue](https://github.com/opentripplanner/OpenTripPlanner/issues) that  describes the relevant feature or bug. Add [GitHub keywords](https://help.github.com/articles/closing-issues-using-keywords/) to this PR's description (e.g., `closes #45`).
- Clean code and small bugfixes do not need issues. 
- Write a few words on how the new code is tested. Are unit tests added/updated, any manual verification done. Performance? 
- Design the code, so it is unit testable and test on the smallest appropriate unit. 
- Test must pass [the continuous integration …

doc: Update the PR Template

---

src/main/java/org/opentripplanner/routing/framework/DebugAggregator.java

A few minor changes to `DebugAggregator` logging:
* incorrect values were logged for the last two stages, which is fixed
* line drawing characters are added to show the dependencies between elements
* values are aligned
Before:
```
17:34:17.652 DEBUG (DebugAggregator.java:51) Routing initialization took 0 ms
17:34:17.671 DEBUG (DebugAggregator.java:58) Direct street routing took 19 ms
17:34:17.699 DEBUG (DebugAggregator.java:67) Filtering tripPatterns took 28 ms
17:34:17.726 DEBUG (DebugAggregator.java:76) Access/egress routing took 27 ms
17:34:17.784 DEBUG (DebugAggregator.java:85) Main routing took 58 ms
17:34:17.790 DEBUG (DebugAggregator.java:93) Creating itineraries took 6 ms
17:34:17.790 DEBUG (DebugAggregator.java:100) Transit routing took total 119 ms
17:34:17.791 DEBUG …
```

Beautify DebugAggregator log output

---

intellij-code-style.xml

The old code style had some issues with line breaking, but after the latest release of Intellij 2020.3.3 on March 15. 2021 this problem seems to be much better. I have updated the code-style to the new Intellij version and changed a few of the line breaking settings to make it work as closely to the code-standard we have. 
We should use this for a while, and if it turn out to work ok, we should at some point reformat the entire codebase.

Code style updated.

---

docs/Configuration.md
src/main/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculator.java

A minor documentation update related to https://github.com/opentripplanner/OpenTripPlanner/pull/3367 
- Updated Configuration.md

Improve documentation regarding new coefficients

---

src/main/resources/internals_no.properties

This PR just adds a couple of Norwegian translations to the `internals_no.properties` file

Added some Norwegian translations

---

ARCHITECTURE.md

Hi folks,
Thank you very much for creating and maintaining this repository and please accept my appreciation.
This PR shall improve the readability of the file [ARCHETECTURE.md](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/ARCHITECTURE.md) by adjusting grammar and mode of expression.
I do not have adjusted the change log yet as I do not know the procedure for documentation.
Please feel free to checkout and merge this PR.
Cheers!

adjusted architecture documentation to improve readability

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/main/java/org/opentripplanner/routing/impl/DelegatingTransitAlertServiceImpl.java

Adds a GraphQL-request to lookup a situation (TransitAlert) by its situationNumber.

Lookup situation by

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java

Added support for cornercase: Alerts with "passing" StopConditions tagged on line and stop. These were previously ignored.

Fixed handling of alerts tagged on line/route and stops with "passing" StopCondition

---

docs/Changelog.md
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/TripToTripTransfer.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransfersPermutationService.java
src/main/java/org/opentripplanner/transit/raptor/api/path/IntermediatePathLeg.java
src/main/java/org/opentripplanner/transit/raptor/util/PathStringBuilder.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/T2TTransferDummy.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransfersPermutationServiceTest.java
src/test/java/org/opentripplanner/transit/raptor/util/PathStringBuilderTest.java

This PR fixes the #3491. 
This PR also adjust the generalized-cost if the access is FLEX. Transfer-cost was not added for the first transit after a FLEX ride.
closes #3491
Regression unit tests are added to prevent similar errors to happen in the future.
Yes

Otp2 fix back travel

---

src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java

Making Flex additive to transit vs. either/or (transit OR Flex). Since Flex is coded as a submode of Transit, I felt it was also consistent with the codebase that these be additive vs. exclusive of each other. Thoughts welcomed.

Change to make Flex additive to transit vs. either/or

---

src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
src/main/java/org/opentripplanner/netex/mapping/StopMapper.java

This adds mapping of the StopPlace and Quay descriptions to the NeTEx import. Both the OTP model and the Transmodel API already account for this.
Tested manually by importing the Norwegian NeTEx data

Map NeTEx StopPlace and Quay descriptions

---

README.md

This PR update the outdated README file with respect to the OTP 2.0 release. There are no code changes.

Update README with correct information about the v2.0.0 release.

---

src/main/java/org/opentripplanner/analyst/scenario/SkipStop.java
src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java
src/main/java/org/opentripplanner/index/model/TripTimeShort.java
src/main/java/org/opentripplanner/routing/edgetype/Timetable.java
src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java

Return stop sequence in **/trips/{tripId}/stoptimes** API

Include stop_sequence in 1.x index API stop_times (#3528)

---

.github/pull_request_template.md

Updated to ask contributors to join the development meetings and ask for more detail in linked issues / summary paragraphs.

Expand pull request template

---

docs/sandbox/MapboxVectorTilesApi.md

In #3595 @hannesj has changed the name of an enum value. This needs to be reflected in the documentation, too. 
n/a
n/a
n/a
It's just about the documentation.
Added.

Update documentation for bike/vehicle rental vector tiles

---

docs/Configuration.md

This is a simple update of the configuration documentation. 
Fixes #3579

doc: Fix board/light slack doc

---

src/ext/java/org/opentripplanner/ext/interactivelauncher/Model.java
src/ext/java/org/opentripplanner/ext/interactivelauncher/views/DataSourcesView.java
src/ext/java/org/opentripplanner/ext/interactivelauncher/views/MainView.java
src/ext/java/org/opentripplanner/ext/interactivelauncher/views/OptionsView.java

- Sandbox InteractiveOTPMain: sort input data directories
- fix: Bind check-boxes to model and update status-bar when model is changed.
_This is a pure Sandbox update_

Improve and fix the InteractiveOtpMain [changelog skip]

---

docs/Developers-Guide.md

Document the changelog workflow in the developer guideline. 
No issue

doc: Update Developers-Guide.md with changelog workflow [changelog skip]

---

src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java

Using the provided `timeRange` in a StopTimes-search to calculate the number of days to be used in the search.
Closes #3740

Calculating number of days to use in StopTimes-request

---

docs/sandbox/MapboxVectorTilesApi.md
src/ext-test/java/org/opentripplanner/ext/vectortiles/VehicleParkingsLayerTest.java
src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/DigitransitVehicleParkingPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingsLayerBuilder.java

Adds VehicleParking layer option to vector tiles sandbox
Related to #3432
Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Developers-Guide.md#code-style)?
Yes
Updated sandbox documentation
Updated sandbox changelog

Add VehicleParking layer option to vector tiles sandbox [changelog skip]

---

docs/Configuration.md
src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
src/test/java/org/opentripplanner/standalone/config/NodeAdapterTest.java

Fixes transfersRequests parameter validation and the parameter's documentation.
No issue as this is a minor problem.
None
Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Developers-Guide.md#code-style)? 
Yes
Improved existing documentation.
No need as this was a minor issue

Transfer requests finetuning [changelog skip]

---

src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilter.java
src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilterTest.java

Allow filtering on servicejourney mode & submode through transmodel API.
[issue](https://github.com/opentripplanner/OpenTripPlanner/issues/3842)
Closes #3842

Mode & submode filter for NeTEx Service Journeys

---

src/main/java/org/opentripplanner/api/common/RoutingResource.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/RaptorRequestMapper.java
src/main/java/org/opentripplanner/routing/api/request/DebugRaptor.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/transit/raptor/RaptorService.java
src/main/java/org/opentripplanner/transit/raptor/api/request/DebugRequestBuilder.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/SystemErrDebugLogger.java
src/test/java/org/opentripplanner/routing/api/request/DebugRaptorTest.java
src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransitData.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java

When Raptor debugger is useful when investigating:
- Path is expected, but not returned
- Understand how Raptor works
- Why you get a path that is not expected
No
✅ 
✅ 
✅

feat: Enable Raptor stop-arrivals event debugging [changelog skip]

---

docs/sandbox/LegacyGraphQLApi.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLBikeRentalStationImpl.java

We noticed that bike rental stations now return a state. However this doesn't take into account if they are free-floating vehicles.
This PR fixes this.
none
none
yes
none

Take free-floating vehicles into account when calculating state [changelog skip]

---

pom.xml
src/main/java/org/opentripplanner/visualizer/ShowGraph.java

This lib is used in the visualizer, and the update compiles - but no test is performed.
The old version is no longer present in MavenCentral.
Not relevant
Not relevant

Update org.processing:core from 1.0.7 to 2.2.1 [changelog skip]

---

docs/sandbox/LegacyGraphQLApi.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLAgencyImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLFeedImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPlaceImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRouteImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/package.json
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/yarn.lock

Updated legacy GraphQL API codegen dependencies and it fixed an old issue with enum args.
No issue
Not needed
Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Codestyle.md)?
Yes
Not needed
Added for sandbox

Update graphql codegen dependencies to fix issue with enum args [changelog skip]

---

src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/TransitRouter.java
src/main/java/org/opentripplanner/routing/error/RoutingValidationException.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/BikeRentalSnapshotTest.java

This adds a try/catch to figure out where the NPE in the flaky BikeRentalSnapshotTest happens.
Relates to #3884 but doesn't actually solve it.
n/a
yes
n/a
n/a

Add try/catch to find the problem of the flaky BikeRentalSnapshotTest [changelog skip]

---

src/main/java/org/opentripplanner/model/TripPattern.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TransitLayer.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TripPatternWithRaptorStopIndexes.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/constrainedtransfer/TransferIndexGenerator.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerUpdater.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TripPatternMapper.java

Add support for creating constrained transfers from real-time generated patterns.
closes #3877
Not updated
✅ 
No changes required.

Add support for creating constrained transfers from real-time generated patterns

---

src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
src/main/java/org/opentripplanner/routing/graph/kryosupport/JavaImmutableListSerializer.java
src/main/java/org/opentripplanner/routing/graph/kryosupport/JavaImmutableSetSerializer.java
src/main/java/org/opentripplanner/routing/graph/kryosupport/KryoBuilder.java
src/main/java/org/opentripplanner/routing/graph/kryosupport/MakeKryo.java

Explain in one or two sentences what this PR achieves.
Not Issues, but this is a problem in #3899.
TODO
✅

feat: Fix problem with Kryo and Java immutable Set and List [changelog skip]

---

src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TripPatternForDate.java

Move from stream to iterator based filtering. This improves the performance by ~3%.
✅ 
None needed

Optimize filtering of trips in TripPatternForDate [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java

Solve issue with cancellations from ET messages not being processed correctly.
[3914](https://github.com/opentripplanner/OpenTripPlanner/issues/3914)
- No new tests included
- Follows guideline for codestyle
- No new documentation (since this is only a bugfix)

Ensure that cancellation is mapped as it should [changelog skip]

---

src/main/java/org/opentripplanner/common/model/P2.java

The override annotation has been added to the toString method of p2 class.

feat: Set override for toString method in p2 class [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
src/main/java/org/opentripplanner/model/TripTimeOnDate.java
src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java

Ensure that realtime messages are not overriding headsignVias in TripTimes

Via headsign bugfix

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/GroupOfLinesType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/LineType.java
src/main/java/org/opentripplanner/gtfs/mapping/BrandingMapper.java
src/main/java/org/opentripplanner/model/GroupOfRoutes.java
src/main/java/org/opentripplanner/model/Route.java
src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
src/main/java/org/opentripplanner/netex/index/NetexEntityIndex.java
src/main/java/org/opentripplanner/netex/index/api/NetexEntityIndexReadOnlyView.java
src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
src/main/java/org/opentripplanner/netex/mapping/BrandingMapper.java
src/main/java/org/opentripplanner/netex/mapping/GroupOfRoutesMapper.java
src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
src/main/java/org/opentripplanner/util/OTPFeature.java
src/test/java/org/opentripplanner/model/BrandingTest.java
src/test/java/org/opentripplanner/model/GroupOfRoutesTest.java
src/test/java/org/opentripplanner/netex/mapping/GroupOfRoutesMapperTest.java
src/test/java/org/opentripplanner/netex/mapping/RouteMapperTest.java

- Added mapping for GroupOfLines
- Exposed GroupOfLines in Transmodel API
closes #3917
New unit tests for new mapping functionality:
- RouteMapper
- GroupOfLinesMapper
- Code follow style guidelines
- Java docs for new classes and new methods

OTP support for NeTEx GroupOfLines

---

src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/main/java/org/opentripplanner/util/OTPFeature.java

Add null pointer checks to mapping algorithm for GroupOfLines mapping

Solve problems with GroupOfLines mapping [changelog skip]

---

src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
src/main/java/org/opentripplanner/netex/mapping/StopMapper.java
src/test/java/org/opentripplanner/netex/mapping/StopAndStationMapperTest.java

- Inject current StopPlace
- Remove lookup on StopPlace from Station.Id
- Remove injected map of StopPlace by versions
Change strategy to get parent StopPlace from given Quay as suggested in #3945 .
- Updated Unit tests

Add StopPlace parent to Quay [changelog skip]

---

src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/module/GraphCoherencyCheckerModule.java

This module creates build issues, when the graph connectivity is invalid

Re-add GraphCoherencyCheckerModule

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java

Change request mapping method to use proper field name for wheelchairAccessible.

Solve problem with "wheelchairAccessible" [changelog skip]

---

src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java

- NeTEx mapping
- Unit test
Add missing NeTEx mapping to Trip.WheelchairBoarding from ServiceJourney.
closes #4042 
One simple unit test check so it changes from default to WheelchairBoarding.POSSIBLE

NeTEx mapping of WheelchairBoarding from ServiceJourney to Trip

---

docs/sandbox/LegacyGraphQLApi.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRentalVehicleImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLRentalVehicleTypeImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
src/ext/resources/legacygraphqlapi/schema.graphqls
src/main/java/org/opentripplanner/routing/vehicle_rental/RentalVehicleType.java

This returns the GBFS form factor in the GraphQL query for `rentalVehicles` 
none
none
yes
Added type documentation to the GraphQL schema.
Not sure if this should be [changelog skip] or not.
/cc @miles-grant-ibigroup

Add GBFS form factors to GraphQL API

---

src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java

- 
Ensure that timepoint information propagates during realtime updates
N/A
N/A
N/A

Fix problem with time points [changelog skip]

---

pom.xml
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java

Removes unused dependencies particularly around shapefiles.
Sadly it doesn't make much of a difference in terms of file size of the resulting fat jar.
Nevertheless, it's good to remove unused stuff.
Relates to #2623 (not sure if you can say it closes it)
n/a
n/a
n/a
skip

Remove unused dependencies [changelog skip]

---

src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessTemplate.java

In https://github.com/opentripplanner/OpenTripPlanner/commit/6a5580f5d2419db059dcd15221a64f8054738fbe a change was made on the flex router which should have been a pure refactoring. However it caused the time shifts to be applied to the wrong direction. This fixes that, and adds an integration test for that
Depends on #4084 
Added

Fix time shifting bug in flex direct router [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java

Enables finding a trip using a DatedServiceJourneyId from an incoming SIRI message.

Added SIRI trip matching for DatedServiceJourneyId [changelog skip]

---

src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/OptimizeTransferService.java

This fix return the path found by Raptor if the Optimized transfer service fail to create a new path. This is not fixing the real problem, but allow to use the optimized transfers service. 
Note! The fix wraps each path, in a result set with many paths only the ones failing will be replaced with the original.
This is a quick fix to avoid crashing, but do not fix the issue: #4091
No tests are added.
✅ 
✅ 
✅

Fix: Hot fix to avoid crash during routing in optimized transfers [changelog skip]

---

docs/sandbox/TransmodelApi.md
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
src/main/java/org/opentripplanner/routing/DatedServiceJourneyHelper.java
src/main/java/org/opentripplanner/routing/RoutingService.java
src/main/java/org/opentripplanner/routing/graph/GraphIndex.java

Expose datedServiceJourney from EstimatedCall in Transmodel API. Also, fixes #3977

Expose datedServiceJourney from EstimatedCall [changelog skip]

---

docs/sandbox/MapboxVectorTilesApi.md
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
src/main/java/org/opentripplanner/model/Timetable.java
src/main/java/org/opentripplanner/model/TripPattern.java

Read the headsign properly for frequency-only patterns in vector tiles API.
closes #4119

Read headsign for frequency-only patterns in vector tiles API [changelog skip]

---

src/main/java/org/opentripplanner/model/calendar/ServiceDate.java
src/main/java/org/opentripplanner/model/calendar/impl/CalendarServiceDataFactoryImpl.java

- Remove deprecated method
- Remove redundant code

Code cleanup [changelog skip]

---

src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGenerator.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferServiceAdaptor.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripSchedule.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorTest.java
src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransferPoint.java
src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransitData.java

In case trip passes through the stop more than once, make sure that TripGenerator does not only include the first visit as possible transfer but other ones as well. 
closes #4124 
- Written new unit tests for the cases that this PR covers
Formatted with maven plugin
- Added new java docs and modified existing ones

TransferGenerator fix [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java

- Ensure that OTP does not create any alerts on LineRef while processing FramedVehicleJourneys

Solve bug in SiriAlertsUpdateHandler [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
src/main/java/org/opentripplanner/model/Timetable.java
src/main/java/org/opentripplanner/model/TimetableSnapshot.java
src/main/java/org/opentripplanner/model/TripTimeOnDate.java
src/main/java/org/opentripplanner/routing/TripTimesShortHelper.java

Remove usage of graph/routing service and make sure we pass in the narrowest possible type into the functions, so that testing doesn't need to create as much boilerplate, but can focus on actual unit testing.

Refactor TimetableHelper in order to make testing easier [changelog skip]

---

pom.xml
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLplaceAtDistanceImpl.java

I wanted to try if input parameter deprecation is working in the newest version (could not get it to work) but since I did the upgrade anyway, I thought I contribute it upstream anyway.
None.
None.
Yes.
n/a

Upgrade graphql-java to version 18

---

src/main/java/org/opentripplanner/gtfs/mapping/StationMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/StopMapper.java
src/main/java/org/opentripplanner/util/TranslationHelper.java

If a stop had null description and translations for some other fields, build crashed with null pointer exception.
No issue
None
Have you followed
the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Codestyle.md)
?
Yes
Not needed
Not needed

Fix npe in null stop description translation [changelog skip]

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
src/main/java/org/opentripplanner/model/TripTimeOnDate.java

Exposes the attribute `PredictionInaccurate` from SIRI ET in the TransmodelAPI

Expose SIRI ET PredictionInaccurate in Transmodel-API

---

src/ext/java/org/opentripplanner/ext/parkAndRideApi/ParkAndRideResource.java
src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParking.java

Previously IBI's sandbox API would return multiple entries for each P+R parking lot because it operated on entrance vertices. This PR fixes it.
n/a
n/a
@miles-grant-ibigroup

Fix IBI's P+R API [changelog skip]

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java

Changes a log line to be only shown with debug log level as it's logged every time an itinerary search is done.

Change log level of a debug log line

---

src/client/js/otp/config.js
src/client/js/otp/core/Map.js
src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
src/main/java/org/opentripplanner/gtfs/mapping/PathwayMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/PathwayModeMapper.java
src/main/java/org/opentripplanner/inspector/PathwayEdgeRenderer.java
src/main/java/org/opentripplanner/inspector/TileRendererManager.java
src/main/java/org/opentripplanner/model/Pathway.java
src/main/java/org/opentripplanner/model/PathwayMode.java
src/main/java/org/opentripplanner/routing/edgetype/PathwayEdge.java
src/test/java/org/opentripplanner/gtfs/mapping/PathwayMapperTest.java
src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
src/test/java/org/opentripplanner/routing/edgetype/PathwayEdgeTest.java

I had to debug GTFS pathways today but it was hard to figure out what was going on as there were lots of other traversal lines being displayed on top of it.
Therefore I decided to write a separate debug layer that helps me figuring out what is going on.
none
n/a
yes

Add debug layer just for pathways

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
src/ext-test/java/org/opentripplanner/ext/fares/impl/MultipleFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/AddingMultipleFareService.java
src/ext/java/org/opentripplanner/ext/fares/impl/DutchFareServiceImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLfareComponentImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLfareImpl.java
src/main/java/org/opentripplanner/api/mapping/FareMapper.java
src/main/java/org/opentripplanner/routing/core/Fare.java
src/main/java/org/opentripplanner/routing/core/Money.java

The type `Money` is unnecessarily mutable and verbose. It's a good candidate to convert to a record.

Make Money a record

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java

Pass in MeterRegistry to RaptorRequestMapper.
closes #4302

Fix RAPTOR metrics reporting

---

src/main/java/org/opentripplanner/transit/model/site/FlexLocationGroupBuilder.java
src/main/java/org/opentripplanner/transit/model/site/GroupOfStationsBuilder.java

In #4326 we introduced a small bug, in which kryo was not able to properly deserialize the graph. This fixes the issue

Fix serialization of FlexLocationGroup and GroupOfStations

---

src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java
src/ext/java/org/opentripplanner/ext/flex/FlexIndex.java
src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
src/ext/java/org/opentripplanner/ext/flex/FlexTripsMapper.java
src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/FlexTripBuilder.java
src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripBuilder.java
src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTripBuilder.java
src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
src/main/java/org/opentripplanner/model/OtpTransitService.java
src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java
src/main/java/org/opentripplanner/transit/service/TransitModel.java

Migrate FlexTrip to the new model.
Part of #4002 
:white_check_mark:
No

Convert FlexTrip to TransitEntity2

---

src/main/java/org/opentripplanner/graph_builder/module/osm/AtlantaWayPropertySetSource.java
src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java
src/test/java/org/opentripplanner/graph_builder/module/osm/AtlantaWayPropertySetSourceTest.java

For their deployment in Atlanta IBI needs a few modifications to the walk permissions so put them into their own way property set.

Add Atlanta WayPropertySetSource

---

src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java
src/main/java/org/opentripplanner/api/model/ApiRouterInfo.java
src/main/java/org/opentripplanner/api/resource/BikeRental.java
src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdater.java
src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
src/test/java/org/opentripplanner/graph_builder/module/VehicleParkingLinkingTest.java
src/test/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdaterTest.java

Replaces the generic services map in the Graph object by dedicated fields
None
No

Use dedicated fields for services in Graph object

---

src/main/java/org/opentripplanner/standalone/config/ItineraryFiltersMapper.java
src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
src/test/java/org/opentripplanner/standalone/config/NodeAdapterTest.java

We try to read in a nested key from a text node. This fails, so read in the text directly.

Fix reading of transitGeneralizedCostLimit

---

src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java

Allows configuring defaults for `maxAccessEgressDuration`, `searchWindow`, `timetableView` in `router-config.json`.

Allow configuring maxAccessEgressDuration, searchWindow, timetableView

---

src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/test/java/org/opentripplanner/util/lang/IntUtilsTest.java

After getting stuck with other things I found it best to just create a PR for two small refactorings:
- Reminding fixes for a PR that is already merged
- Unit test in IntUtils 
No issue
Yes
No

Clean code

---

src/main/java/org/opentripplanner/graph_builder/module/ValidateAndInterpolateStopTimesForEachTrip.java

This should have been a part of #4388, but for some reason the push failed, and it got merged without this commit.
Apply feedback related to the previous PR

Improve limits in ValidateAndInterpolateStopTimesForEachTrip

---

docs/BuildConfiguration.md
docs/RouterConfiguration.md
src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java

Contains documentation updates and fixes.
Minor documentation pr so no issue.
Touches some comments in unit tests.
Updates documentation.

Documentation updates and fixes

---

test/performance/norway/build-config.json

Fix the configuration of the Norwegian speed test to align it with the new build configuration format.
No
No

Fix Norwegian speed test configuration

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
src/main/resources/internals_no.properties
src/main/resources/internals_sv.properties

This PR fixes two minor bugs
- Missing format type for Norwegian and Swedish translations
- Mismatching return type for leg duration in Transmodel GraphQL API

Minor fixes

---

src/main/java/org/opentripplanner/updater/UpdaterConstructionException.java
src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoader.java

Allow the `GbfsFeedLoader` to throw exception on invalid data, and not crash the application on startup
Fixes https://github.com/opentripplanner/OpenTripPlanner/issues/4436

Catch exceptions from updater configuration

---

CODE_CONVENTIONS.md

This PR update the CODE_CONVENTIONS with doc on builders and adds an example.

Update code conventions doc on builders

---

src/main/java/org/opentripplanner/graph_builder/module/osm/WayProperties.java

Fixes npe issue in safety values.
fixes #4527
Maybe TODO
Not needed
Not needed

Fix npe in way properties

---

docs/Deployments.md

- Added deployment documentation for Skånetrafiken

Add skanetrafiken to deployment docs

---

src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java

Couple of minor clean-ups/optimizations identified during the OTP workshop in Skåne

Cleanup in A*

---

docs/sandbox/MapboxVectorTilesApi.md
src/ext-test/java/org/opentripplanner/ext/vectortiles/StopsLayerTest.java
src/ext-test/java/org/opentripplanner/ext/vectortiles/VehicleParkingGroupsLayerTest.java
src/ext-test/java/org/opentripplanner/ext/vectortiles/VehicleParkingsLayerTest.java
src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerTest.java
src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingGroupsLayerTest.java
src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingsLayerTest.java
src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/VehicleRentalLayerTest.java
src/ext/java/org/opentripplanner/ext/vectortiles/I18NStringMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/LayerBuilderFactory.java
src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/StationsLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/DigitransitVehicleParkingGroupPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/DigitransitVehicleParkingPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/StadtnaviVehicleParkingPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingGroupsLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingsLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalPlacesLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalStationsLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalVehiclesLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/DigitransitRealtimeVehicleRentalStationPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/DigitransitRentalVehiclePropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/DigitransitVehicleRentalPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/DigitransitVehicleRentalStationPropertyMapper.java
src/test/java/org/opentripplanner/transit/raptor/api/view/BoardAndAlightTimeTest.java

* Translatable fields are now translated based on accept-language header
* Added DigitransitRealtime for vehicle rental stations
* <b>Changed old vehicle parking mapper to be Stadtnavi</b>
* Added a new Digitransit vehicle parking mapper with no realtime information and less fields
This pr is based on https://github.com/opentripplanner/OpenTripPlanner/pull/4510 and should be merged after it.
Sandbox change so no issue
Added tests
Added changelog for sandbox

Translations for vector tiles sandbox

---

src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java

Solve problem with null pointers in TimetableHelper

---

README.md
doc-templates/Configuration.md
docs/Basic-Tutorial.md
docs/Configuration.md
docs/Developers-Guide.md
docs/Getting-OTP.md
docs/ReleaseChecklist.md
src/main/java/org/opentripplanner/model/projectinfo/OtpProjectInfo.java

Update version numbers in docs, this should be in the 2.2 release, but we forgot.

Update version numbers in doc.

---

docs/sandbox/SiriAzureUpdater.md
src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java

- Add log for SIRI heartbeat message to SiriAzureETUpdater & SiriAzureSXUpdater
- Change url log to uri in SiriAzureETUpdater & SiriAzureSXUpdater
- Change log level for removing outdated trip patterns to DEBUG
N/A
N/A
- Added new entry to Sandbox module changelog

Changed logs in realtime modules

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternForDate.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestRouteData.java

Apply two potential optimizations
closes #4590

Optimize routing data filtering 

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java

In the Transmodel API's `StopPlace` type's `estimatedCalls` field has a possibility to filter down calls by line and destination display. This expects that there is a line + destination display combination only to be at one of the stops. Extract the functionality and use it also for the stream combining the results from all the quays.

Extract limitPerLineAndDestinationDisplay and use also for combined stream

---

src/main/java/org/opentripplanner/common/geometry/HashGridSpatialIndex.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransfersMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
src/main/java/org/opentripplanner/routing/graph/index/EdgeSpatialIndex.java
src/main/java/org/opentripplanner/routing/graph/index/StreetIndex.java
src/main/java/org/opentripplanner/transit/raptor/api/path/Path.java
src/main/java/org/opentripplanner/transit/service/StopModelIndex.java

We looked at a memory snapshot in the Thursdays's dev meeting and identified some low hanging fruits for memory optimizations. Fix these.

Minor memory optimizations

---

src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java

The GraphVisualizer is updated so that it can successfully start: avoids accessing the graph before it is ready along with time formatting errors.

GraphVisualizer: update to successfully start

---

docs/sandbox/VehicleRentalServiceDirectory.md

I found a typo in the documentation and this pull request fixes the typo.

[TASK] Fixed Typo

---

docs/Governance.md

Update list of PLC members

---

src/ext-test/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchemaTest.java
src/ext/graphql/transmodelapi/schema.graphql

Add a test for keeping the schema in the code updated.

Add test for keeping Transmodel GraphQL schema in sync

---

src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSource.java
src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSourceParameters.java
src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/GbfsDataSourceParameters.java
src/ext/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSource.java
src/ext/java/org/opentripplanner/ext/vilkkubikerental/VilkkuBikeRentalDataSourceParameters.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSource.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/VehicleRentalDataSourceFactory.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/params/GbfsVehicleRentalDataSourceParameters.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/params/VehicleRentalDataSourceParameters.java

In preparation for the geofencing zones I noticed that these classes can be converted to records saving quite a bit of code passing the values around.

Convert vehicle rental source parameters to records

---

src/main/java/org/opentripplanner/graph_builder/module/osm/ElevatorProcessor.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/graph_builder/module/osm/ParkingProcessor.java

Just like I did with the parking code, this PR extracts the handling of elevators out of OpenStreetMapModule into a separate class.
This is aimed at making it easier to oversee the control flow in OpenStreetMapModule.

Extract elevator handling into separate class

---

src/main/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapper.java
src/test/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapperTest.java

Small adjustments to finland walk safety values when crossing without traffic lights
No issue
Updated
Not needed
Not needed

Minor adjustments to finland walk safety

---

mkdocs.yml

Change tab to spaces

---

src/main/java/org/opentripplanner/api/common/RoutingResource.java

Bugfix: do not add elements to immutable list

---

src/main/java/org/opentripplanner/standalone/config/ConfigModel.java
src/test/java/org/opentripplanner/transit/speed_test/SpeedIntegrationTest.java
src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java

This fixes the Flex Speed Integration test

Make the SpeedIntegrationTest run in isolation with respect to OTPFeatures

---

src/main/java/org/opentripplanner/api/common/RoutingResource.java
src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
src/test/java/org/opentripplanner/api/common/PlannerResourceTest.java

This fixes the case of no `mode` parameter being provided to the REST API. 
Closes #4748 
Added.

Set default value when mode parameter is null

---

docs/sandbox/SiriAzureUpdater.md

Added contact email for Skånetrafiken developer team

Added contact email for Siri Azure Updater sandbox module

---

src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java

This PR fixes a NPE in the ORCA fare calculator and cleans up the code a bit.

Fix NPE in ORCA fare calculator

---

docs/sandbox/SiriAzureUpdater.md
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java

- If messages from history endpoint could not be processed, try fetching from the endpoint again.
N/A
N/A
Added new entry to changelog in sandbox documentation

Update Azure updaters

---

docs/RouteRequest.md
docs/RouterConfiguration.md
src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
src/test/resources/standalone/config/router-config.json

There was no documentation or example config for this, so I added it.

Add documentation for unpreferred agencies and routes

---

docs/Presentations.md
mkdocs.yml

Adds  a new docs page for presentations related to OTP.
No issue

Add docs for presentations related to OTP

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLAlertImpl.java

Fixes NPE problem in legacy GraphQL API when alert header is null.
TODO

Fix NPE in alert header usage

---

src/ext-test/java/org/opentripplanner/ext/flex/FlexTest.java
src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripTest.java
src/ext-test/java/org/opentripplanner/ext/flex/trip/UnscheduledTripTest.java
src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
src/main/java/org/opentripplanner/model/StopTime.java

Currently these kind of trips result in too long pessimistic drive time. As we know a single time, we can just pretend like it is a stop with a zero-minute window
Added unit tests for the behaviour.

Use UnscheduledTrip for flex trips with one scheduled and one unscheduled stop.

---

docs/Basic-Tutorial.md

Hi folks,
I hope this finds you well. Thank you so much for providing and maintaining this repository. Please feel free to study, use, share or improve this pull request for the documentation.
Cheers!

feat: make documentation release independent

---

doc-templates/Configuration.md
doc-templates/UpdaterConfig.md
docs/Configuration.md
docs/UpdaterConfig.md

Hi folks,
I hope this finds you well. Thank you so much for providing and maintaining this repository. Please feel free to study, use, share or improve this pull request for the documentation.
I fixed some typo's in the Configuration.md file.
Cheers!

Update Configuration.md [ci skip]

---

src/main/java/org/opentripplanner/street/search/state/StateData.java
src/test/java/org/opentripplanner/street/search/state/StateTest.java

It fixes the initial state of the CAR_RENT mode so that it actually works.
Closes #4932
Added.

Fix initial A* state of car rental

---

src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java

Remove "NOT IMPLEMENTED" from Transmodel GraphQL-docs since features are actually implemented.

Update GraphQL-docs 

---

src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorSerializer.java
src/test/java/org/opentripplanner/model/plan/pagecursor/PageCursorTest.java

This improve error handling and logging in two places, see code.
No issue.
Unit test updated.
Not relevant.

Improve error logging

---

docs/sandbox/SiriAzureUpdater.md
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java

This PR solves a bug in SiriAzureETUpdater. It also improves logging for processing of history data.
N/A
Change documented in Sandbox article for AzureUpdater.

Azure updater bugfix

---

src/main/java/org/opentripplanner/model/Timetable.java
src/test/java/org/opentripplanner/model/TimetableTest.java
src/test/java/org/opentripplanner/updater/trip/TripUpdateBuilder.java

Yesterday I helped @derhuerst to debug a GTFS-RT feed he was producing and noticed that OTP doesn't return the validation information about invalid arrival/departure times as well as it could.
This PR changes that and adds tests for this behaviour.
Added.

Improve GTFS-RT feed debugging for invalid arrival/departure time

---

docs/sandbox/TravelTime.md

Adding an example request and a few tipps.
Closes #5066

Add example URL for travel isochrones docs [ci skip]

---

src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java

The SIRI-ET Google PubSub updater creates a new subscription on startup and delete it on shutdown.
If the OTP instance is stopped before the shutdown hooks have completed, the subscription may still exist when the instance is restarted.
In the current implementation this will cause a crash.
This PR ensures that subscription names are unique so that restarted instances get a fresh subscription.
In addition a prefix is added to the subscription name to facilitate log analysis.
No
No

Create unique SIRI-ET PubSub subscription

---

src/ext-test/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapperTest.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/PreferencesMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/BikePreferencesMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/ItineraryFilterPreferencesMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/StreetPreferencesMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/TransferPreferencesMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/TransitPreferencesMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/WalkPreferencesMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/TransportModeSlack.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/StreetModeDurationInputType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
src/main/java/org/opentripplanner/routing/api/request/preference/StreetPreferences.java

Fix bug in maxDirectDurationForMode, the wrong default value was used
No
Yes
No changes
No
No

Otp2 fix max direct duration for mode

---

src/main/java/org/opentripplanner/netex/support/stoptime/AbstractStopTimeAdaptor.java
src/main/java/org/opentripplanner/netex/validation/ServiceJourneyNonIncreasingPassingTime.java
src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
src/test/java/org/opentripplanner/netex/validation/ServiceJourneyNonIncreasingPassingTimeTest.java

During refactoring and cleanup of the #5081 I introduced an error in the validation. This fixes it.
No
✅ 
No
No
No

Fix error in flex validation

---

src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripPatternType.java

No issue.
No tests added.
API doc updated.

Replace `walkDistance` with `streetDistance` in TransmodelAPI

---

src/main/java/org/opentripplanner/raptor/rangeraptor/transit/RaptorSearchWindowCalculator.java

This PR improves a log message to investigate issue #5211
#5211
No
No

Improve logging message for negative travel time

---

docs/ReleaseChecklist.md

Add checklist item for GitHub maintenance in release checklist

---

pom.xml

Update service bus dependencies

Update service bus dependencies

---

.github/ISSUE_TEMPLATE/roadmap_epic.md

Typo correction in the roadmap template

Fix type in Roadmap epic template

---

CODE_CONVENTIONS.md

This PR adds a couple of sentences to the code conventions. 
🟥 
🟥 
✅  
🟥 
🟥

Use American English [ci skip]

---

src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java

Change a few verbose log messages from info to debug level in the siri azure updaters.
Trivial change, no need for tests.
No

Siri azure updaters: Reduce some log levels

---

src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java
src/test/java/org/opentripplanner/graph_builder/module/GtfsModuleTest.java

Together with @daniel-heppner-ibigroup we debugged a very confusing IBI deployment: graph build was successful but OTP would crash at runtime because transfers referred to non-existing entities.
It turned out that a GTFS feed had feed_info.feed_id set to 3 which collided with the auto-generated id for another feed.
Since this was very confusing to debug, I'm adding some code which disallows the same feed id from being used twice.
Javadoc

Prevent feed id from being used twice

---

docs/Frontends.md

Fix DebugUi config documentation. This was changed in #5602

Fix DebugUi doc [ci skip]

---

client-next/src/hooks/useServerInfo.ts
client-next/src/hooks/useTripQuery.ts

Fixes to use named import. For yet-unknown reasons, have to disable an eslint rule for the import as well.

Fix imports

---

doc-templates/sandbox/VehicleRentalServiceDirectory.md
docs/sandbox/VehicleRentalServiceDirectory.md
src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/VehicleRentalServiceDirectoryFetcher.java
src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/api/NetworkParameters.java
src/main/java/org/opentripplanner/standalone/config/sandbox/VehicleRentalServiceDirectoryFetcherConfig.java

I need to be able to override the parameter `allowKeepingRentedVehicleAtDestination` in the rental vehicle directory.
Autogenerated.
added.
cc @hbruch

Allow configuration of allowKeepingAtDestination in rental vehicle directory

---

doc/user/Data-Sources.md

When creating a pull request, please follow the format below. For each section, *replace* the
guidance text with your own text, keeping the section heading. If you have nothing to say in a
particular section, you can completely delete the section including its heading to indicate that you
have taken the requested steps. None of these instructions or the guidance text (non-heading text)
should be present in the submitted PR. These sections serve as a checklist: when you have replaced
or deleted all of them, the PR is considered complete. As of 2021, most regular OTP contributors
participate in our twice-weekly conference calls. For all but the simplest and smallest PRs,
participation in these discussions is necessary to facilitate the review and merge process. Other
developers can ask …

Update Data-Sources.md with new links to GTFS.org from MobilityData [ci skip]

---

client/package-lock.json
client/package.json

Renovate/vite 6.x

---

application/src/main/java/org/opentripplanner/apis/vectortiles/DebugStyleSpec.java
application/src/main/java/org/opentripplanner/apis/vectortiles/model/StyleBuilder.java
application/src/main/java/org/opentripplanner/inspector/vector/edge/EdgePropertyMapper.java
application/src/main/java/org/opentripplanner/inspector/vector/vertex/VertexPropertyMapper.java
application/src/test/resources/org/opentripplanner/apis/vectortiles/style.json

Adds elevation to vertices and maximum slope to edges in the debug UI. Additionally, a maximum slope debug map layer is added.
This pr is built on top of #6434 
No issue
No
No
From title

Add maximum slope debug layer

---

application/src/test/java/org/opentripplanner/updater/siri/SiriRealTimeTripUpdateAdapterTest.java

This PR adds 2 unit tests to cover problematic corner cases with SIRI real-time updates:
When a scheduled trip is modified then cancelled, it should be reverted to its initial times and stop sequence.
This applies also to added trips (not present in scheduled data) that should be reverted to their initial state.
No

Add unit tests for SIRI cancellation

---

script/CUSTOM_RELEASE_README.md

Update custom release script documentation.
🟥  No issue
🟥  Doc update
✅ 
🟥  No code change

Add doc for making the first custom release

---

application/src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
application/src/main/java/org/opentripplanner/transit/service/StopTimesHelper.java

This PR just fixes some variable names in accordance with https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/doc/dev/Dictionary.md#stop-references
Stop Index should be the global index of a stop.
Stop Position is the local index of a stop in the pattern.
Nope

Fix some stop variable names

---

application/src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
application/src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java

This PR updates the ORCA fare model to correctly produce Fares V2 data, with FareProducts and DependentFareProducts being used to correctly represent the data for the new UI components.

Rewrite Orca fare model to generate fare offers
