src/main/java/org/opentripplanner/standalone/CommandLineParameters.java

This is needed so that command line parameters can be built programatically in projects that depend on OTP.

mark all command line parameters public.

---

src/main/java/org/opentripplanner/analyst/TimeSurface.java
src/main/java/org/opentripplanner/api/resource/SurfaceResource.java

Micro-modification on TimeSurface.
- Remove unused variable.
- Remove deprecated TODO comment (related to the changes made to the accumulative sampler to decorrelate off-road distance and cell size.)
- Make a method private in SurfaceResource.
I think it could be nice in the future to be able to create a sample grid from any source (SPT or int[] array or whatever that gives a value for a vertex), and to allow a TimeSurface to be more generic: either storing a sample value for each vertex or a sampled surface. If the TimeSurface public interface is "getTime(Vertex)" this should be feasible.

Timesurface hacks

---

src/main/java/org/opentripplanner/graph_builder/impl/map/MapBuilder.java
src/main/java/org/opentripplanner/routing/edgetype/TripPattern.java
src/main/java/org/opentripplanner/standalone/OTPConfigurator.java

I compared those mapbuilder with one in 0.11.x and geometries are the same.
I compared then with shapely.
What I don't like is:
Currently they are made when getGeometry() is called. I could move this to constructor but trips can also be added with add functions.
Geometries are created based on the code in StreetlesStopLinker which I'm not sure how it works.
For Mapbuilder transit index needs to be created
In 0.11 this was with `TransitIndexService transit = graph.getService(TransitIndexService.class);` but in master it seems that `index` graph function does this task so I added it in MapBuilder and removed transitIndex dependency.
I added Mapbuilder in standaloneOTP if OSM and GTFS files exist.

Fixed map builder

---

src/client/index.html
src/client/js/otp/core/IndexApi.js
src/client/js/otp/core/Webapp.js
src/client/js/otp/layers/StopsLayer.js
src/client/js/otp/layers/layers-templates.html
src/client/js/otp/modules/planner/ItinerariesWidget.js
src/client/js/otp/modules/planner/PlannerModule.js
src/client/js/otp/util/Itin.js
src/client/js/otp/widgets/transit/RouteBasedWidget.js
src/client/js/otp/widgets/transit/StopFinderWidget.js
src/client/js/otp/widgets/transit/StopViewerWidget.js
src/client/js/otp/widgets/transit/TripViewerWidget.js
src/client/js/otp/widgets/transit/widgets-transit-templates.html
src/client/js/otp/widgets/tripoptions/RoutesSelectorWidget.js
src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js
src/main/java/org/opentripplanner/api/common/RoutingResource.java

This tries to address #1509,
with minimal implementation to adapt the client code to the new Index API.
I tried to reflect the new api name also in client code (IndexApi.js instead of TransitIndex.js) but we can also directly refactor the TransitIndex.js.
Get rid of several agencyId as new object identifiers already include it in the form agencyId:objectId
Other changes should leverage on enhancements from the Api side, e.g.:
- routeList on Stop, to show in the popup
- pattern name, more concise than pattern description
- pattern on Trip, to avoid iterating on route patterns trips searching for which pattern the trip belongs to
- findById and findByName endpoints (maybe /index/stops?name=abc*  or some other RESTFul uri)
but I think is worth waiting for the ongoing GTFS rework.
PS: the PR …

adapt client to new Index API

---

src/main/java/org/opentripplanner/index/IndexAPI.java

Previously we could get the geometry for a specific trip by using `variantForTrip`, but as it is deprecated, we need something else to get the geometry for a specific trip. As it is missing from the index API, we propose two new endpoints, one for getting the geometry for a specific trip pattern and the second one using the first one providing the geometry for a specific trip (as the pattern is not included in the other API responses). 
They are split into separate geometries for each hop, as we only need the geometries before boarding the vehicle and after alighting it, as they are not provided by the planner API. If the whole line is needed, the polylines can easily be combined after being decoded.

Add geometries endpoint for trip and pattern in index API

---

src/main/java/org/opentripplanner/index/IndexAPI.java
src/main/java/org/opentripplanner/index/model/TripTimeShort.java
src/main/java/org/opentripplanner/routing/graph/GraphIndex.java

Currently the stop times for a single stop is quite in a dire state. 
- It doesn't return the correct times, but times for the first stop
- It returns one stoptime each for the previous, current and next service date
- It does not return real-time stoptimes
- It does not return any indication for which service date the stoptime is for.
This branch reworks how the stoptimes are fetched. Instead of using getNextTrip in Timetable, it iterates through all trip patterns that pass along the stop and adds all stoptimes for the previous, current and next service dates, which have not yet happened into a priority queue and fetches the N soonest departures for the pattern.

Improve stoptimes in the index API

---

src/main/java/org/opentripplanner/analyst/TimeSurface.java
src/main/java/org/opentripplanner/api/resource/ProfileResource.java
src/main/java/org/opentripplanner/profile/AnalystProfileRouterPrototype.java
src/main/java/org/opentripplanner/profile/ProfileRequest.java
src/main/java/org/opentripplanner/profile/ProfileRouter.java

QueryParameters are not serializable, and we need to pass serialized profile requests around in OTPA-cluster.

Flatten profile requests

---

src/main/java/org/opentripplanner/analyst/request/SampleGridRenderer.java
src/main/java/org/opentripplanner/routing/spt/SPTWalker.java

This pull request contains some changes made for the DREAL PACA project that could be merged back to master:
- Javascript OTPA client library.
- TimeGrid API upgrade for use with new OTPServer stuff.
- Correct a few bugs in the SPTWalker (in case of multi-states SPT, the process was dependent on the vertex states list order). Sample only final states.
- Enable path parsers in the SPT sampling process.
- Distinguish between offroad speed and average speed along edge in the SPT sampler. The two speeds can be different (offroad is a walk speed, average speed along edge can be faster or way slower), this was causing subtle issues in some rare occurences.
- Skip trips w/o services (caused by some invalid GTFS files). Do not try to process them as they will throw a NPE later on.

DREAL project fixes and javascript library

---

src/main/java/org/opentripplanner/index/IndexAPI.java

This is useful in large-scale deployments, where the full route list of all agencies can grow pretty big.

Add support for fetching all routes of an agency

---

src/main/java/org/opentripplanner/analyst/PointFeature.java

So that we don't use memory address equality. PointFeatures are compared inside the conveyal/otpa-cluster project to figure out which origins have returned from the compute cluster.

Add equals() and hashCode() to PointFeature.

---

src/main/java/org/opentripplanner/common/StreetUtils.java
src/main/java/org/opentripplanner/graph_builder/impl/osm/WalkableAreaBuilder.java
src/main/java/org/opentripplanner/routing/edgetype/AreaEdge.java
src/main/java/org/opentripplanner/routing/edgetype/EdgeWithCleanup.java
src/main/java/org/opentripplanner/routing/edgetype/LegSwitchingEdge.java
src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
src/main/java/org/opentripplanner/routing/graph/Edge.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/routing/graph/Vertex.java
src/test/java/org/opentripplanner/api/resource/TestRequest.java
src/test/java/org/opentripplanner/routing/core/TestOnBoardRouting.java
src/test/java/org/opentripplanner/routing/core/TestTransfers.java

This pull request addresses issue #1607. It should also fix some lingering memory leaks which were unfortunately introduced by the turn restriction optimizations.

Add removeEdge() method to Graph class and cleanup

---

src/main/java/org/opentripplanner/common/LuceneIndex.java
src/main/java/org/opentripplanner/index/GeocoderResource.java

Add support for:
- auto-complete using PrefixQuery
- searching for stop clusters
- specifying what category (stops, clusters, street corners) we are interested in
- add stop code and id to stop results
This can be used to replace functionality that was provided by stopsByName in the old API.

Improve geocoder

---

src/client/index.html
src/client/js/otp/core/GeocoderBag.js
src/client/js/otp/core/GeocoderBuiltin.js

otp.core.GeocoderBag is an alternative to the otp.core.GeocoderBuiltin geocoder. It will add a geocoder that can make requests to a BAG instance or any similar API
USAGE: Replace or add the geocoder config inside config.geocoders in config.js
* BAG is a Dutch acronym for Basic Address Data and is a Netherlands-specific geo database.
* On top of this dataset (in combination with other data-sets ) an open source geocoder has been developed
* More information about the geocoder can be found http://blog.plannerstack.org/shop/bag42-vm/ or at https://github.com/calendar42/bag42/

Client: Added a Bag geocoder that can be enabled in the config

---

src/main/java/org/opentripplanner/index/model/StopShort.java

Allows us to show the user-visible stop code when querying for the nearest stops.

Add stop code in index API response

---

src/main/java/org/opentripplanner/graph_builder/impl/map/BusRouteStreetMatcher.java
src/main/java/org/opentripplanner/routing/edgetype/factory/GTFSPatternHopFactory.java

makeGeometry in TripPattern now doesn't creates geometry if it isn't created from shape files,
same with BusRouteStreetMatcher.
This improves BusRouteStreetMatcher, because matching was very weird previously when geometry wasn't created from shapefiles. I don't know if geometry is used anywhere else where it is needed even if it is as crow flies.

Fixes BusRouteStreetMatcher matching when trip geometry is generated

---

src/client/js/otp/modules/planner/ItinerariesWidget.js

stopId.id never exists, as stopId is a string. Furthermore since it's meant to be the internal ID and stopCode is the ID that users could understand, it makes more sense to use that instead.

Fix trip itinerary showing stop as #undefined

---

src/main/java/org/opentripplanner/standalone/CommandLineParameters.java
src/main/java/org/opentripplanner/standalone/GrizzlyServer.java

This is a proposal to serve external files (in the file system) on a "/local" URL, adding a non-cached Grizzly static http handler.
I'm not sure about the name of the option "--clientFiles", maybe another name could be better. The same for the URL path "/local", and whether this change is properly implemented (maybe there could be a better way). Another option would be to serve them in the root context if the option is enabled, disabling the default embedded (classpath) files.

Add "--clientFiles" option to serve local files by http.

---

src/main/java/org/opentripplanner/updater/bike_park/KmlBikeParkDataSource.java
src/test/java/org/opentripplanner/updater/bike_park/TestKmlBikeParkSource.java
src/test/resources/bike/NSFietsenstallingen_folder.kml

KML bike-rental data source read "placemarks" as bike rental stations. The XPath was assuming no "Folder". This PR make the KML source support both with and without Folders.

Bike P+R: Allow KML data source to have optional placemark folders.

---

src/main/java/org/opentripplanner/routing/graph/Graph.java

Removing looping edges (for example RentABikeOn/OffEdge) is causing a NPE: the same edge was added multiple times in the list, the second loop iteration on the same edge was causing a NPE, due to `edge::hashCode()` function relying on from/to vertex to be non-null.

Fix #1781. Removal of looping edges throws NPE.

---

src/main/java/org/opentripplanner/common/MavenVersion.java
src/main/java/org/opentripplanner/standalone/CommandLineParameters.java
src/main/java/org/opentripplanner/standalone/OTPMain.java

Fixes #1766
Adds a new flag to enable version output of the current `otp.jar`.
`--version` enables output of version and prints all version bits by default.
```
$ java -jar otp.jar --version
version: 1.0.0-SNAPSHOT
major: 1
minor: 0
patch: 0
qualifier: SNAPSHOT
commit: 5baeb0da96f679cfb7c6d7b8dea192a127f83b35
```

Add --version flag to output current version

---

src/client/js/otp/core/IndexApi.js
src/client/js/otp/widgets/transit/StopViewerWidget.js
src/main/java/org/opentripplanner/routing/graph/GraphIndex.java

Several fixes that basically leverage on last @hannesj improvement to the IndexAPI in f0086dfc5463037e1c085e1b0b6dc7d7bb369506
It is now possible to change  the date in the widget, visualize all stoptimes in the given date;
the list automatically scrolls to the stoptime nearest the search time or the time given by the itinerary widget.
This also fixes #1791, by adding both serviceId and tripId to the Api response.
The most notable change is the one concerning the local timezone on stoptimes in a055bd4880ded1f63b3916acdd4d90b7557a1545  :
former code relies on the formatItinTime util function which in turn relies on the otp.config.timeOffset which is not always set; as a result I was getting wrong stoptimes, shifted by 1 hour.
But instead of warring about applying and then trying to …

Fix stoptimes visualization in StopViewerWidget 

---

src/client/js/otp/core/Webapp.js
src/client/js/otp/modules/planner/PlannerModule.js

Previously each parameter was saved only ones in client when parsing
querystrings.
This appears to be a problem when using intermediatePlaces.
Now each parameter is saved as before, but if it appears again list is
created from values and then send to server.
Fixes #1784.
I don't know how this parsing is used in analyst or if it maybe breaks something else.

Adds support for list parameters in client querystring

---

src/main/java/org/opentripplanner/routing/edgetype/StreetTraversalPermission.java

ALL and PEDESTRIAN_AND_BICYCLE_AND_CAR both had values 4|2|1
since #1772. Fixes #1874

Removes redundant streetTraversalPermissions

---

src/main/java/org/opentripplanner/graph_builder/module/osm/DefaultWayPropertySetSource.java

This adds car permission to roads which are Unclassified and have
bike=designated. 
This fixes #1878 because it changes permissions for road so that it has a car permission. But it adds new problem.
Now this [road](http://www.openstreetmap.org/way/114741006) is usable by car even though it has `motor_vehicle=no` [osm tag](https://wiki.openstreetmap.org/wiki/Key:motor_vehicle). This tag isn't supported in OTP only `motorcar` [OSM tag](https://wiki.openstreetmap.org/wiki/Key:motorcar) is. Should I add support for this tag in this PR or new one?

Unclassified road with bike=designated was missing CAR permission

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OSMFilter.java
src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java

It is checked everywhere where support for motorcar is checked.
https://wiki.openstreetmap.org/wiki/Key:motor_vehicle. Fixes some problems which were made visible in #1880 .

Adds support for OSM tag motor_vehicle

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OSMFilter.java
src/test/java/org/opentripplanner/openstreetmap/model/OSMWayTest.java

Tests for new motor_vehicle permission in #1881 and Car support in highway unclassified with bicycle=designated in #1878  and #1880.
It also fixes checking if CAR/WALK/BIKE permissions are explicitly allowed instead of just allowing them if they exist and aren't explicitly denied.
Previously road with tags `access=no` and `foot=private` had foot permissions now it doesn't.
If Access is yes and `foot=private` walk permissions still exists. I don't know if I should add this also since I'm not sure this is even possible. (public road with only certain modes of travel access private)

Adds OSM tags tests

---

src/main/java/org/opentripplanner/standalone/OTPMain.java

Tests all pass.
After adding in this commit, autoscan appears to work as intended when specified on the command line.

Fixes #1892 check for routerIds before checking their length to prevent NPE

---

src/main/java/org/opentripplanner/index/IndexAPI.java
src/main/java/org/opentripplanner/routing/graph/GraphIndex.java

Currently there is no way to search for stopTimes at a specific time in the future for a specific stop. This PR adds the ability to configure the query parameters for the /stops/{stopId}/stoptimes API endpoint.

Expose query parameters for the StopTime Index API

---

src/main/java/org/opentripplanner/routing/impl/StreetVertexIndexServiceImpl.java

Incorrect MAX_DISTANCE_FROM_STREET_DEGREES computation. See #1932.

Fix #1932.

---

src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java
src/main/java/org/opentripplanner/routing/impl/StreetVertexIndexServiceImpl.java
src/main/java/org/opentripplanner/routing/vertextype/StreetVertex.java

Now corner generation code is used on each from/to vertex in each leg not only origin and destination. This makes nicer names. And osm:node:id isn't shown anymore in  client.
This fixes #1950 and #1957.
But it can show some interesting instructions:
> 1. CYCLE 317 feet to corner of path and steps
>2. WALK 101 feet to corner of underpass and steps
It is not exactly a corner of path and steps. And it just sounds weird to have a corner of steps and x.

Nicer names when changing modes

---

src/main/java/org/opentripplanner/standalone/GraphBuilderParameters.java

to stationTransfers. It is named stationTransfers in documentation and
as a parameter name. Most of parameters have same name and config name.
Fixes #1993.

MINOR: Renames config parameter parentStationTransfers

---

src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java

Adds generation of routeTextColor for GTFS files with route which have color but not textColor.
TextColor is black for light colors and white for dark color. Color brightness is calculated with formula:
`sqrt( 0.299*Red^2 + 0.587*Green^2 + 0.114*Blue^2 )` from [stack overflow](https://stackoverflow.com/questions/596216/formula-to-determine-brightness-of-rgb-color).
Fixes #2016

Route text colors

---

docs/Basic-Usage.md
docs/Developers-Guide.md
docs/Troubleshooting-Routing.md

* Adds a "Debugging routing results" chapter to the Basic-Usage.md. This includes for now information about the Debug layers and how to interpret them.
* Moves instructions how to enable the debug layer from the Developers-Guide.md to the Basic-usage.md. Using the the debug-layers doesn't require developer skills.

Update debug layer usage

---

src/main/java/org/opentripplanner/analyst/request/IsoChroneRequest.java
src/main/java/org/opentripplanner/analyst/request/IsoChroneSPTRendererAccSampling.java
src/main/java/org/opentripplanner/analyst/request/SampleGridRenderer.java
src/main/java/org/opentripplanner/analyst/request/SampleGridRequest.java
src/main/java/org/opentripplanner/api/resource/LIsochrone.java
src/main/java/org/opentripplanner/api/resource/TimeGridWs.java
src/main/java/org/opentripplanner/common/geometry/AccumulativeGridSampler.java

Some changes made in #1440 were not merged back to master, but they can be useful. This modification is to decouple off-road distance to grid size in isochrone computation. We can now specify the two parameters independently. This has the side effect of making the "samples set closing" process more resilient (removing some "magic" constant).
Also replace "d0" by easier to read "offRoadDistanceMeters". Add a few comments.

Decouple off-road dist param from grid size.

---

src/main/java/org/opentripplanner/standalone/CommandLineParameters.java
src/main/java/org/opentripplanner/standalone/GrizzlyServer.java

This is handy when developing static client files, without this option you need to restart OTP grizzly server to see the file modification in the client browser.

Add option "--disableFileCache" for development.

---

src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java
src/test/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverterTest.java

I discovered that OTP sometimes returns itineraries consisting of a single leg having a mode of LEG_SWITCH. LEG_SWITCH is an internal construct that should never be shown to the outside world. Upon further investigation, it turned out that issue was being caused by trying to plan from a street location connected directly to a stop to that stop's parent station. This gives a path consisting only of edges with modes null and LEG_SWITCH. Because these results aren't useful anyway (no actual walking directions are returned), I propose that we just act as if this is a trivial trip.
Forward ported from a GoAbout branch. I couldn't run the full test suite because I don't have Java 8 installed, but the new tests themselves certainly pass.

Fix LEG_SWITCH bug

---

src/main/java/org/opentripplanner/graph_builder/AnnotationsToHTML.java
src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/standalone/GraphBuilderParameters.java

I changed how annotations are created.
Each class of annotations now has its own file. But if multiple classes of annotations have low number of annotations they are still grouped in file called rest. So that there aren't a bunch of files with 1-5 annotations.
New build-config parameter is added "maxHtmlAnnotationsPerFile". And if number of annotations in one class is too large it is split in multiple files.
Value is by default 1000. @abyrd and @andreyz Please test it with files which have large number of annotations and please tell me what would be sensible default.
This is connected with #1510  and #2010.
WIP because if it works correctly I need to clean the code a little bit and add more comments and remove some logging.

HTML annotations large number of annotations support

---

src/main/java/org/opentripplanner/routing/spt/DominanceFunction.java

This was preventing computing a path using two different bike rental networks. We need to disable state comparison when in "bike rented state" and networks are not compatible.
For more details, see this thread:
https://groups.google.com/d/msg/opentripplanner-users/KlW9V_KdaDw/jRzIVdf3JC8J

Do not compare states with bike of distinct networks.

---

src/main/java/org/opentripplanner/graph_builder/AnnotationsToHTML.java
src/main/java/org/opentripplanner/graph_builder/annotation/BikeParkUnlinked.java
src/main/java/org/opentripplanner/graph_builder/annotation/BikeRentalStationUnlinked.java
src/main/java/org/opentripplanner/graph_builder/annotation/ConflictingBikeTags.java
src/main/java/org/opentripplanner/graph_builder/annotation/GraphBuilderAnnotation.java
src/main/java/org/opentripplanner/graph_builder/annotation/StopNotLinkedForTransfers.java
src/main/java/org/opentripplanner/graph_builder/annotation/StreetCarSpeedZero.java
src/main/java/org/opentripplanner/graph_builder/annotation/TurnRestrictionException.java
src/main/java/org/opentripplanner/graph_builder/annotation/TurnRestrictionUnknown.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java

Improves HTML annotations based on @abyrd ideas and fixes #2088:
- Annotations are moved to own folder
- Adds index file to annotations
- removes old annotation files before creating new ones
- Doesn't group different classes of annotations
- Adds support for HTML in annotations (all annotations are now supported):
- BikeParkUnlinked
- BikeRentalStationUnlinked
- ConflictingBikeTags
- StreetCarSpeedZero
- TurnRestrictionException
- TurnRestrictionUnknown
- StopNotLinkedForTransfers
- escapes HTML tags in msg strings for annotations that don't support HTML messages
- annotations aren't created with Javascript anymore
- nicer list of annotations and title in HTML
- cleaned a code added some comments and renamed some variables

Improved Html annotations

---

src/main/java/org/opentripplanner/api/model/RouterInfo.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/util/TravelOption.java
src/main/java/org/opentripplanner/util/TravelOptionsMaker.java
src/test/java/org/opentripplanner/util/TravelOptionsMakerTest.java

This is server part of automatic list of travel by modes. The goal is for the client to only show supported travel by modes and extra options (bike sharing, park & ride, bike & ride) on specific server.
Some examples of transit travelBy options are: `"TRANSIT,WALK"`, Park & Ride `"CAR_PARK,WALK,TRANSIT"` which is quite complex, but bicycle needs only `"BICYCLE"`.
This can be solved in 2 ways.
One is to send to client which transit modes are supported and if P & R, B & R or bike sharing are supported and is up to the client to create correct list of those and to name them.
Another is to create a list of values to be send ("TRANSIT,WALK", "BICYCLE") and names for them on the server itself. This would be better kept in since with the rest of server code than combining it on client.
Currently …

Dynamic list of supported travel by modes

---

src/client/scripting.html
src/main/java/org/opentripplanner/api/resource/ScriptResource.java

* Fix typo: `otp` vs `opt`
* Catch all `Throwable` for easier debug when something fails in scripting.

Fix scripting typo

---

src/main/java/org/opentripplanner/api/common/RoutingResource.java

Previously they weren't used so OTP sometimes preferred walking down/up
the stairs with bike which is hard.
Fixes #1768
I noticed that bikeWalking options aren't applied at all in building routing request in RoutingResource.
Correct bikeWalking options are made only when [setModes](https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/routing/core/RoutingRequest.java#L485) is called on routingRequest. But this function is never called when request is build in planner request, because modes are set with setMode one by one from list of qualified modes in [applyToRoutingRequest](https://github.com/opentripplanner/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java#L47).
The result is that bikeWalking …

Actually use different stair reluctance when walking with bike

---

src/main/java/org/opentripplanner/graph_builder/annotation/TurnRestrictionBad.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/graph_builder/module/osm/TurnRestrictionTag.java

Previously if turn restrictions weren't created because from/to edges
were missing or edges weren't the correct angle they were silently
ignored. This commit adds those skipped turn restrictions to log and
adds them to graph annotations
Fixes #2159

Add graph annotations when turn restrictions are skipped

---

src/main/java/org/opentripplanner/index/IndexAPI.java

Fixes #2162. In Index API call for all clusters and for specific stop
clusters. Stop clusters were not lazy initialized.
They should be according to code comments and they were in profile
routing and lucene search.

Fix bug when stopClusters weren't lazy initialized everywhere

---

src/main/java/org/opentripplanner/api/model/RouterInfo.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/test/java/org/opentripplanner/api/resource/RoutersTest.java

Added the transitServiceStarts and transitServiceEnds timestamps to the BuildInfo object. This info will then be available for the users through the API. Very useful when the user needs to know the date range supported by the currently running graph.

Added transit start and end timestamps to the BuildInfo object

---

src/main/java/org/opentripplanner/routing/core/RoutingRequest.java

Change to lookup the agency id through the route instead of the trips id field which contains the feed id in multi agency feeds.
As explained in #2057 and related to the migration to a proper feed id in #1999

Fix banning of agencies in multi agency feeds, resolves #2057

---

src/main/java/org/opentripplanner/util/TranslatedString.java

Need to be able to iterate through available translations. Useful for exposing them through e.g. GraphQL API

Add getters for languages and translations

---

src/client/index.html

leaflet cannot be loaded with other scripts. 
It breaks the L.Icon.Default.imagePath regular expression
Analyst's webinterface was broken by that

Workaround for Leaflet L.Icon.Default.imagePath detection

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java

Fixes NullPointerException at OpenStreetMapModule.java:948 in expression `level.shortName`, where `level` can be `null`.
This exception prevented graph building process.
`

Return default OSM level for way if not found

---

pom.xml
src/main/java/org/opentripplanner/routing/trippattern/RealTimeState.java
src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java

As discussed in #1722, add the enum RealTimeState to the TripTimes object.
Note that for example a MODIFIED GTFS-RT trip update may result in one TripTimes object getting the real-time state CANCELED and another TripTimes object getting the real-time state MODIFIED.

Add real time state to trip times

---

.gitignore

`otp` was probably meant for only the `/otp` in the root dir of the project. This caused me some issues when finding changed and added files in e.g. `src/client/js/otp` This might help with i18n.

.gitignore was not specific enough, causing missing files in status.

---

src/main/java/org/opentripplanner/index/IndexGraphQLSchema.java
src/main/java/org/opentripplanner/index/model/TripTimeShort.java

Canceled trips are taken into account in itinerary searches, but are not marked as such in REST or GraphQL APIs. This commit adds the API support for showing the realtime state.

Add realtimeState to TripTimeShort and GraphQL

---

docs/index.md

I found some small errors at the index.md documentation page, as mentioned in #2214.
This PR fixes these broken links.
This PR is a cleaned version of #2215, without the (useless) "merge remote-tracking branch" commits.

Small hyperlink fixes of #2214

---

src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/model/GtfsBundle.java
src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
src/main/java/org/opentripplanner/routing/edgetype/factory/GTFSPatternHopFactory.java
src/main/java/org/opentripplanner/standalone/GraphBuilderParameters.java

This is distance between stops that are considered a trip which can be
made without transfers between last stop of one trippattern and first
stop on next. It is made with same vehicle. Previously it was
hardcodded as 200 m now it is configurable
And should be quickfix for #2226.

This makes max interline distance configurable

---

src/main/java/org/opentripplanner/routing/core/FareRuleSet.java
src/main/java/org/opentripplanner/routing/impl/SeattleFareServiceFactory.java

We would like for fares in the Puget Sound region to be specified in GTFS rather than hardcoded into SeattleFareServiceFactory.java. This will allow fare changes to be rolled out without a complete rebuild of OTP. Changes in how fares are calculated may still require new code, but simple changes in price such as the KCM $0.25 fare hike on 3/1 will not.
- Remove hardcoded fares. (These are being added to GTFS upstream)
- Add senior/youth fare prices as extra column in fare attributes. See [pull request](https://github.com/conveyal/onebusaway-gtfs-modules/pull/1) to conveyal/onebusaway-gtfs-modules.
- Remove processGTFS agency separation. No longer necessary because of new feed ID feature in OpenTripPlanner.
For more info please see mailing list …

Changes to SeattleFareServiceFactory so fares can be specified in GTFS.

---

src/main/java/org/opentripplanner/graph_builder/linking/OriginDestinationLinker.java
src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java
src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
src/test/java/org/opentripplanner/routing/TestHalfEdges.java

When edges are split in origin/destination point request this is saved in RoutingRequest and if both requests would split same edge TrivialPathException is thrown.

Throws trivialPath exception if start/end point is at the same edge

---

src/client/js/otp/config.js
src/client/js/otp/util/Itin.js
src/main/java/org/opentripplanner/api/resource/SIsochrone.java
src/main/java/org/opentripplanner/routing/core/TraverseMode.java
src/main/java/org/opentripplanner/routing/core/TraverseModeSet.java
src/main/java/org/opentripplanner/routing/impl/CandidateEdge.java
src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
src/test/java/org/opentripplanner/routing/core/TraverseModeSetTest.java
src/test/java/org/opentripplanner/routing/edgetype/StreetTraversalPermissionTest.java
src/test/java/org/opentripplanner/routing/edgetype/loader/TestPatternHopFactory.java

I removed the Busish and Trainish modes in the code as was proposed by @abyrd in issue #2218.
Regarding the questions about the Cable Car I had:
* The modes Bus + Walk are used if you select the "Bus only" option. Cable Car was removed here. If this change should be reverted, please let me now so I can fix it.
* The Cable Car mode receives the StreetEdge.CLASS_OTHER_PLATFORM platform class (originally also the case)
* The Cable Car mode options haven't been tested since I'm not able to find a suitable map or GTFS feed which uses this mode

Removed Busish + Trainish modes (fixes #2218)

---

pom.xml
src/test/java/org/opentripplanner/graph_builder/module/linking/LinkingTest.java

This commit fixes the issue described here: https://groups.google.com/forum/#!topic/opentripplanner-users/NVmdO1J00aI
The issue has been that the Grizzly kernel threads have locked up at 100% CPU after a while and in the end the server stops responding. This seems to be been caused by the issue described here: https://java.net/jira/browse/GRIZZLY-1712
By updating to 2.18 of Jersey we have no longer seen this behavior in our running instance of OTP.

Updated to 2.18 of Jersey to fix hanging threads in Grizzly. 

---

src/main/java/org/opentripplanner/graph_builder/module/osm/Area.java
src/main/java/org/opentripplanner/graph_builder/module/osm/AreaGroup.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
src/main/java/org/opentripplanner/graph_builder/module/osm/Ring.java

This PR makes the graph builder ignore problems with `LinearRing`s in OSM data. It handles them in the same way as other data problems in `Area`, `Ring`, etc., which is to say ignore them without logging.
This commit also moves `RingConstructionException` from `Area` to `Ring`, which seems a more logical location.
Fixes #2293.

Ignore exceptions reading OSM LinearRing data

---

src/main/java/org/opentripplanner/api/resource/Routers.java
src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/routing/impl/MemoryGraphSource.java
src/main/java/org/opentripplanner/standalone/OTPMain.java

Fix #2184. Solves also the following:
* Allow the use of embeded router-config when posting a graph over the API.
* Allow the use of router-config.json when posting a ZIP to build over the API.
* Simplify code a bit.
Tested the following scenario, with and without a router-config.json file present:
* Graph building in a file, then startup (most common use)
* Graph building in memory and serving right away (--inMemory option)
* Graph building offline and posting a graph via API
* Zipping data with router-config and posting a zip via API

Rework embedded router config

---

src/main/java/org/opentripplanner/graph_builder/module/EmbedConfig.java
src/main/java/org/opentripplanner/routing/impl/InputStreamGraphSource.java
src/main/java/org/opentripplanner/routing/services/GraphService.java
src/test/java/org/opentripplanner/routing/impl/GraphServiceTest.java

I recently discovered that the embedded configurations (`build` and `router`) are not loaded in OTP, if an existing graph is posted to the server via `POST /routers/save?routerId=myRouter @graph.obj`.
This PR fixes this missing feature by loading the `routerConfig` if the respective file `router-config.json` is not found on the file system but is embedded to the graph already.

Load embedded config for existing graphs

---

src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/module/PruneFloatingIslands.java
src/main/java/org/opentripplanner/standalone/GraphBuilderParameters.java

Instead of having the parameters for the two floating islands settings hardcoded, this PR adds them to the list of build parameters.

PruneFloatingIslands with build parameters

---

src/main/java/org/opentripplanner/graph_builder/module/osm/DefaultWayPropertySetSource.java

If you're interested, this is in response to #2374 where I was unable to route on a highway=living_street. This PR opens up highway=* to allow all modes as the default, with specific exceptions for e.g. highway=cycleway or highway=footpath already covered in the file. 
The file comments indicate that it's meant to be Portland specific, whereas my problem was in California. Feel free to reject as irrelevant. Thanks for looking.

Re #2374. Allow Cars on highway=*;bicycle=designated

---

src/main/java/org/opentripplanner/index/IndexGraphQLSchema.java

As discussed in #2224 , the headsign element is missing from GraphQL. Added by this PR.
Partly replaces PR #2358, which contained too much clutter.

Added headsign attribute for stoptimes in GraphQL

---

src/main/java/org/opentripplanner/standalone/GrizzlyServer.java

This PR moves the call to `HttpServer.shutdown` to a JVM shutdown hook, in order to gracefully shut down the Grizzly server in case a TERM signal is received.

Add shutdown hook to gracefully shut down Grizzly

---

src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
src/main/java/org/opentripplanner/standalone/Router.java

As discussed in #2364, this PR introduces the possibility to cluster stops based on parent stations, rather than by geographical proximity. This has proved to work well in our test environment here in Oslo.

Optional stop clustering by parent station or geography

---

src/main/java/org/opentripplanner/routing/graph/GraphIndex.java

Seems we were too quick with merging #2383. Some tests perform clustering before the graph is built, and this reveals a NullPointerException, which is handled in this PR.

Fixed NullPointerException if clustering before graph creation

---

src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
src/test/java/org/opentripplanner/routing/core/RoutingRequestTest.java

The current code is actually matching on feed ID instead of the route's agency ID.

Fix preferred/unpreferred agency matching

---

src/main/java/org/opentripplanner/routing/graph/GraphIndex.java

`GraphIndex.stopTimesForStop()` (called from the `/stops/{stopId}/stoptimes` API call) searches for times on the previous day, current day, and next day. This is incorrect if the `startTime` parameter is a time on future or past day. This commit fixes that behavior.

Bugfix in GraphIndex.stopTimesForStop

---

src/main/java/org/opentripplanner/analyst/ResultSet.java

This results in travel times to individual points being included in the results for `/surfaces/{surfaceId}/indicator?detail=true`. I verified that they are not included without `detail=true`.
Let me know if you'd like a test and, if so, where it would make sense to add.
See #2416 and [discussion on opentripplanner-users][1]
[1]: https://groups.google.com/d/msg/opentripplanner-users/BcbEYSMHnfo/q6Ecm8-jBwAJ

Serialize times from ResultSet

---

src/main/java/org/opentripplanner/routing/edgetype/factory/GTFSPatternHopFactory.java

When a parent station is listed as the to or from station in transfers.txt, this PR creates transfers
to/from all child stops.
Currently, parent station transfers cause OTP to crash because there are no graph vertices associated with these stations. This patch causes it to instead expand parent station transfers into transfers between all child stops of those parent stations. The only concern here is that it could lead to large transfer tables, but I don't really see a way around that.
Fixes #2404 and possibly #2406.

Add code to expand transfers to/from stations.

---

.travis.yml

Please don't merge unless travis succeeds.

Don't attempt to decrypt keys on PRs; it'll just make the build fail

---

src/main/java/org/opentripplanner/api/resource/GraphPathToTripPlanConverter.java
src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java
src/main/java/org/opentripplanner/routing/core/StateEditor.java
src/test/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitterTest.java
src/test/java/org/opentripplanner/routing/core/StateEditorTest.java

Solves #2421 
When finding the closest vertex to the destination for park
and ride , the traverse mode must be 'walk' and not 'car'.

Fix bugs in park and ride search

---

src/main/java/org/opentripplanner/index/IndexAPI.java
src/main/java/org/opentripplanner/index/IndexGraphQLSchema.java
src/main/java/org/opentripplanner/routing/graph/GraphIndex.java

IndexAPI (and GraphQL) has apparently had no method to filter away calls in StopTimes that have no boarding (piclupType = 1). This change ignores these stops in stopTimesForStop(). If some implementations still need to show these calls, we can of course make it configurable.
Partly replaces PR #2358, which contained too much clutter.

Filtering non-pickup calls

---

src/main/java/org/opentripplanner/index/IndexAPI.java
src/main/java/org/opentripplanner/routing/edgetype/factory/GTFSPatternHopFactory.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/routing/graph/GraphIndex.java

We have found it useful to be able to access GTFS [FeedInfo](https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#feed_infotxt) information from OTP's API, in order to ensure that an OTP instance is serving fresh data. I think this could be useful for other OTP users as well.
This PR will serialize FeedInfo objects from GTFS feeds into the OTP graph, and expose them via a new call `/otp/routers/default/index/feeds/{feedId}` in IndexAPI. If the given feed ID does not exist, or that feed does not supply `feed_info.txt`, the call will return a 404 (though of course I'm open to feedback on this behavior).

Expose FeedInfo objects via IndexAPI

---

src/main/java/org/opentripplanner/routing/impl/DefaultFareServiceImpl.java
src/main/java/org/opentripplanner/routing/impl/SeattleFareServiceFactory.java
src/main/java/org/opentripplanner/routing/impl/SeattleFareServiceImpl.java

For KCM, take the maximum of fares on adjacent legs, rather than adding them.
This was rewritten from my first pass to minimize changes to DefaultFareServiceImpl, & reuse SeattleFareServiceImpl.
Discussed on the mailing list here: https://groups.google.com/forum/#!topic/opentripplanner-dev/70siIXQPYxw

KCM transfers - use maximum fare of two adjacent legs 

---

src/main/java/org/opentripplanner/routing/algorithm/AStar.java
src/main/java/org/opentripplanner/routing/core/RoutingRequest.java
src/main/java/org/opentripplanner/routing/core/StateData.java
src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java

This PR aims to solve the issues described in #1361.
A full  reversed search is made to compact the legs. Enabling the reversed search will of course influence performance, since an additional search is made. However, performance has not been an issue after running this patch for the graph in Norway (Oslo and national graphs) for a couple of months.

Compact legs by reversed search

---

src/main/java/org/opentripplanner/routing/impl/NycFareServiceImpl.java

Fares from here: http://web.mta.info/nyct/fare/FaresatAGlance.htm
Expensive Express fares have not changed: http://transportation.westchestergov.com/bee-line/fares-and-metrocard

Update fares in NycFareServiceImpl

---

src/main/java/org/opentripplanner/common/geometry/SphericalDistanceLibrary.java
src/main/java/org/opentripplanner/graph_builder/annotation/StopLinkedTooFar.java
src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java

Currently only stops that are not linked (because they are more than 1000m from a walkable edge) are reported. However, we have found it is also useful to report stops that are linked, but the distance is still significant. This can help us discover errors in stop coordinates or incomplete parts of the OSM network.

Added HTML report for stops with a snap distance over 20m

---

src/main/java/org/opentripplanner/util/HttpUtils.java

Replace deprecated `DefaultHTTPClient` with `HttpClientBuilder`.
Fixes #2450.

remove/update deprecated HTTPClient code, adding missing ciphers for SSL

---

docs/Deployments.md

The Atlanta Regional Commission has been running an OpenTripPlanner instance for the past two years or so to support the atltransit.org website.  MARTA has also been utilizing this instance for their website's trip planner.

add Atlanta to list of deployments

---

.github/CODEOWNERS

See https://help.github.com/articles/about-codeowners/ and the new @opentripplanner/plc team

PRs will now be reviewed & approved by PLC

---

pom.xml

- Upgrades Commons, HTTP Components & Math to latest versions (no compatibility issues)
- Explicitly adds Commons Codec w/version greater than 1.4 to fix the issue I was encountering [c.f. this SO answer](https://stackoverflow.com/questions/7688644/java-lang-nosuchmethoderror-org-apache-commons-codec-binary-base64-encodebase64).
I found that these changes fixed my issue in #2573

Re #2753 Upgrade Apache Deps

---

docs/Changelog.md
pom.xml

This pull request updates the onebusaway-gtfs dependency to the latest version.

Addresses #2636: Update onebusaway-gtfs to latest version from OBA project

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OSMFilter.java

The tag filtering logic happens in many places witch for me is very hard to understand. It needs refactoring, and a natural start to this, is to create a unit test with the contract/rules. But this is  a big task. When I tried to fix this issue, I first added one line to the `DefaultWayPropertySetSource`: (`props.setProperties("highway=razed", StreetTraversalPermission.NONE);`). This did not have the expected result. I debugged this until I understood that there is no clear precedence between the rules - at least for me to grasp in a few hours. The `OSMFilter#getPermissionsForEntity` method might return *not* `NONE` even if the input parameter `StreetTraversalPermission def` is `NONE`. This is just a small pice of the puzzle, so I went on and fixed it another way (see code).
To be …

Support OSM highway=razed tag

---

docs/Changelog.md
docs/Configuration.md

- closes #2526
---
At @interline-io, we've found it a recurring challenge to keep track of possible OTP config options. We put together some tables internally a while back. They're probably useful to others, so this PR adds to them to the public documentation.

Improve configuration docs

---

docs/Configuration.md
src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
src/main/java/org/opentripplanner/standalone/GraphBuilderParameters.java

Allows using other units than meters in source elevation data by adding elevationUnitMultiplier build parameter. This is related to issue #2651 

Add elevationUnitMultiplier builder parameter

---

.travis.yml

This PR adds a deploy stage to the continuous integration process that uploads the shaded jar file for any successful CI performed on the primary repo (i.e., PR builds from forks will not be uploaded). The jar files uploaded are:
- `otp-${git-description}.jar` (e.g. `otp-v1.3.0-54-g169c39d.jar`) and
- `otp-latest-${branch-name}.jar` (e.g., `otp-latest-deploy-builds-to-s3.jar `)

Deploy builds to s3

---

src/main/java/org/opentripplanner/graph_builder/linking/SimpleStreetSplitter.java
src/main/java/org/opentripplanner/routing/core/RoutingContext.java
src/main/java/org/opentripplanner/routing/edgetype/OnBoardDepartPatternHop.java
src/main/java/org/opentripplanner/routing/edgetype/SampleEdge.java
src/main/java/org/opentripplanner/routing/edgetype/TemporaryEdge.java
src/main/java/org/opentripplanner/routing/edgetype/TemporaryFreeEdge.java
src/main/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdge.java
src/main/java/org/opentripplanner/routing/impl/StreetVertexIndexServiceImpl.java
src/main/java/org/opentripplanner/routing/location/TemporaryStreetLocation.java
src/main/java/org/opentripplanner/routing/vertextype/OnboardDepartVertex.java
src/main/java/org/opentripplanner/routing/vertextype/SampleVertex.java
src/main/java/org/opentripplanner/routing/vertextype/TemporarySplitterVertex.java
src/main/java/org/opentripplanner/routing/vertextype/TemporaryVertex.java
src/main/java/org/opentripplanner/routing/vertextype/TemporaryVertexDispose.java
src/main/java/org/opentripplanner/util/DateUtils.java
src/test/java/org/opentripplanner/routing/TestHalfEdges.java
src/test/java/org/opentripplanner/routing/core/RoutingContextDestroyTest.java
src/test/java/org/opentripplanner/routing/core/RoutingContext_Destroy_Test.java
src/test/java/org/opentripplanner/routing/graph/TemporaryConcreteEdge.java
src/test/java/org/opentripplanner/routing/vertextype/TemporaryVertexDisposeTest.java

Fix memory leak in routing context destroy.

---

docs/Changelog.md
src/main/java/org/opentripplanner/api/model/Itinerary.java
src/main/java/org/opentripplanner/api/model/Leg.java
src/main/java/org/opentripplanner/api/model/Place.java
src/main/java/org/opentripplanner/api/model/RouterInfo.java
src/main/java/org/opentripplanner/api/model/RouterList.java
src/main/java/org/opentripplanner/api/model/TripPlan.java
src/main/java/org/opentripplanner/api/model/WalkStep.java
src/main/java/org/opentripplanner/api/model/alertpatch/AlertPatchCreationResponse.java
src/main/java/org/opentripplanner/api/model/alertpatch/AlertPatchResponse.java
src/main/java/org/opentripplanner/api/model/alertpatch/AlertPatchSet.java
src/main/java/org/opentripplanner/api/model/alertpatch/LocalizedAlert.java
src/main/java/org/opentripplanner/api/model/error/TransitError.java
src/main/java/org/opentripplanner/api/resource/BikeRentalStationList.java
src/main/java/org/opentripplanner/api/resource/InspectorLayersList.java
src/main/java/org/opentripplanner/api/resource/Response.java
src/main/java/org/opentripplanner/api/resource/ServerInfo.java
src/main/java/org/opentripplanner/geocoder/GeocoderResults.java
src/main/java/org/opentripplanner/routing/alertpatch/Alert.java
src/main/java/org/opentripplanner/routing/alertpatch/AlertPatch.java
src/main/java/org/opentripplanner/routing/bike_rental/BikeRentalStation.java
src/main/java/org/opentripplanner/routing/edgetype/TripPattern.java

This removes XML annotations from response objects, so Jackson reverts to default behavior (before 2.7.4). In particular, generic collections do not use wrapper tags anymore. Jackson uses the typical JSON annotations to name the XML tags. 

Fix #2685: Remove XML annotations from response objects

---

pom.xml

I think we forgot to update the OTP version number in `pom.xml`.
OTP version changed from 1.4.0-SNAPSHOT to 2.0.0-SNAPSHOT.

Update OTP version to 2.0.0-SNAPSHOT

---

pom.xml

This is the same change as I have pull requested for OTP1. It removed an unused repository and adds https to another.
https://github.com/opentripplanner/OpenTripPlanner/pull/2774

Remove repo, add https for 2.0

---

src/main/java/org/opentripplanner/api/resource/PlannerResource.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/itinerary/ItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/AccessEgressRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/Transfer.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TransitLayer.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransfersMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/TransferWithDuration.java

Similarly to #2776 this updates the RAPTOR itinerary/leg decoration to more closely match 1.x.
The first four commits are simple refactors / bug fixes, but the last two are bit more complex.
* In the commit for filling in the trip headsign (87a1e58) the original `TripTime` needs to be used, which doesn't seems as straightforward as it could be. Is there a reason `TripSchedules` don't reuse the existing `TripTimes`? Would it be possible to store the boarding/alighting pattern stopIndex on the `TransitPathLeg`s?
* For accurately recreating non-transit legs (7213851) the edges stored on the `SimpleTransfer` are used in combination with the existing `GraphPathToTripPlanConverter`. With this the walk steps, leg segmentation and calculations match 1.x and the non-transit itineraries.
To be …

Extend 2.x itinerary decoration to better match 1.x

---

src/main/java/org/opentripplanner/common/geometry/GeometryUtils.java
src/test/java/org/opentripplanner/common/geometry/GeometryUtilsTest.java

This PR breaks out the small bug fix to `GeometryUtils.java` made in Coord's PR (#2596).
This line in `convertPath`:
`coords[i++] = new Coordinate(p.getLatitude(), p.getLongitude());`
had the wrong coordinate order. The definition of the Coordinate constructor is:
`public Coordinate(double x, double y)`
The `convertPath` function is used only in GeoJSON -> JTS conversion for Polygons and LineStrings, and this PR will correct those conversions.

Fix JTS coordinate order for Polygons/Polylines

---

docs/Changelog.md
src/test/java/org/opentripplanner/geocoder/bano/BanoGeocoderTest.java

Avoid worrying if the response included "é" or "e".

Slightly relax string match in geocoder test

---

docs/Changelog.md
src/main/java/com/google/transit/realtime/GtfsRealtime.java

allow big GTFS-realtime feeds by increasing protobuf size limit to 2G

---

.travis.yml
docs/Changelog.md
src/main/java/com/google/transit/realtime/GtfsRealtime.java
src/main/java/org/opentripplanner/routing/trippattern/FrequencyEntry.java
src/main/java/org/opentripplanner/updater/alerts/GtfsRealtimeAlertsUpdater.java
src/main/java/org/opentripplanner/updater/stoptime/GtfsRealtimeHttpTripUpdateSource.java
src/test/java/org/opentripplanner/geocoder/bano/BanoGeocoderTest.java
src/test/java/org/opentripplanner/routing/trippattern/FrequencyEntryTest.java

This PR simply cherry-picks all commits from #2540, #2739, #2799, and #2797 (which were included in the OTP v1.4 release) over onto OTP2.

Port 1.4 fixes to OTP2

---

docs/Changelog.md
src/main/java/org/opentripplanner/common/geometry/CompactElevationProfile.java
src/main/java/org/opentripplanner/common/geometry/CompactLineString.java
src/main/java/org/opentripplanner/common/geometry/GeometryUtils.java
src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/module/map/BusRouteStreetMatcher.java
src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
src/main/java/org/opentripplanner/index/IndexAPI.java
src/main/java/org/opentripplanner/index/IndexGraphQLSchema.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/AccessEgressRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/TransferToAccessEgressLegMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/Transfer.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransfersMapper.java
src/main/java/org/opentripplanner/routing/edgetype/SimpleTransfer.java
src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
src/main/java/org/opentripplanner/routing/edgetype/StreetWithElevationEdge.java
src/main/java/org/opentripplanner/routing/edgetype/TripPattern.java
src/main/java/org/opentripplanner/routing/edgetype/factory/PatternHopFactory.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
src/main/java/org/opentripplanner/standalone/GraphBuilderParameters.java
src/test/java/org/opentripplanner/common/geometry/CompactElevationProfileTest.java
src/test/java/org/opentripplanner/common/geometry/CompactLineStringTest.java

After doing some memory profiling of OTP, we found that a lot of space is taken up by LineStrings. This affects both graph size and the memory requirement to run OTP. It is especially important for very large graphs, since you may run into a limit to the file size supported by the Kryo serializer.
Note that this is based on [#2794 ](https://github.com/opentripplanner/OpenTripPlanner/pull/2794), so only the last commit is relevant for this particular pull request.
The following changes have been made:
The geometries in SimpleTransfer and Raptor Transfer objects have been removed. In the first case they were saved as LineStrings, and in the second as Coordinate arrays. Since we already have a list of edges, it is possible to just combine these whenever we need the complete geometry. This is …

Remove redundant LineStrings in order to save memory

---

docs/Basic-Tutorial.md
docs/Intermediate-Tutorial.md

OTP.org's tutorial pages point to HTTP API documentation (from OTP version 1.0.0) that is slightly out-of-date and (more importantly) is missing request-response examples present in later doc versions (that do the heft of illustrating the usefulness of each endpoint). It was confusing to me as a new-to-OTP developer reading the 1.0.0 documentation that was linked, until I found that version 1.4.0 was the most recent released Git tag and tried to update the URL path in my browser. (Unfortunately, [it doesn't seem like `apidoc` is serving](http://dev.opentripplanner.org/apidoc/) a `latest` alias that could be used instead of hardcoding to `1.4.0`.)
I also couldn't quite grok whether such a `./doc`-only PR should be made to `dev-1.x`, `master`, or both `dev-1.x` and `dev-2.x` branches, so …

Update tutorial links to documentation, to use version 1.4.0 instead of 1.0.0

---

src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java

This PR Fixes #2815 by allowing the traversal of two StreetTransit links after another as long as the StreetTransitLinks are for different stops respectively. This allows the creation of SimpleTransfers during the graph build phase and also the proper output of SimpleTransfers in results.

Add a fix to StreetTransitLink to allow transfers between stops with the same GPS coordinate.

---

docs/Changelog.md
docs/Configuration.md
src/main/java/org/opentripplanner/api/common/RoutingResource.java

Since this is purely about documentation I took the liberty to remove the PR checklist. I hope this is acceptable.
I was confused about the mode parameter, and especially about the qualifiers like BICYCLE_PARK and BICYCLE_RENT so I experimented and dug through the code.
The documentation contained in the PR are the result of my findings.
I'm very happy to discuss the format and content.
Thanks for OTP - it's a great piece of software!

Add documentation for PlannerResource#mode

---

docs/Changelog.md
src/main/java/org/opentripplanner/updater/alerts/GtfsRealtimeAlertsUpdater.java
src/main/java/org/opentripplanner/updater/stoptime/GtfsRealtimeHttpTripUpdateSource.java

Seems like application/x-google-protobuf and application/octet-stream are not the only types that feed publishers use. I added couple of other popular ones. Also more crucially, fixed the separator between different options that prevented wildcard (`*/*`) matcher from working in certain servers. 
Fixes https://github.com/opentripplanner/OpenTripPlanner/issues/2839.

Fix accept header

---

docs/Configuration.md

docs/configuration.md edited to correctly reference the uk waypropertyset - Issue #2856 

Update for uk wayPropertySet

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java

This updates the Transmodel GraphQL schema to conform to the Entur clients. This change is needed so that we can test deployments of OTP2 at Entur.
This only changes sandbox code, and should therefore only require approval from the same organization.

Update TransmodelAPI sandbox feature as code owner

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java

This updates the Transmodel GraphQL schema to conform to the Entur clients. This change is needed so that we can test deployments of OTP2 at Entur.
This only changes sandbox code, and should therefore only require approval from the same organization.
Continuation of [#2890 ](https://github.com/opentripplanner/OpenTripPlanner/pull/2890)

Update TransmodelAPI sandbox feature as code owner (2)

---

README.md

Add links in the README documentation to the google user groups. No changes to code.
This is a port of a PR merged into dev-1.x (#2915)

add links to google groups in README

---

src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/main/java/org/opentripplanner/graph_builder/DataImportIssuesToHTML.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/RaptorRouter.java
src/main/java/org/opentripplanner/standalone/config/ConfigFile.java
src/main/java/org/opentripplanner/updater/stoptime/WebsocketGtfsRealtimeUpdater.java

Number of placeholders does not match number of args in logging call inspections (IntelliJ code inspection used to fix this).

Code cleanup - Number of placeholders does not match number logging args

---

docs/index.md

We have started to get questions on were to find the OTP2 documentation and the version button on the documentation page is a bit difficult to see, so I though it would be useful to at least have some links to the different versions on the front page.

Add links to master, 1.x and 2.x documentation on the front page

---

src/main/java/org/opentripplanner/common/geometry/CompactLineString.java
src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java

Closes #2962 
Also adds check if shape_dist_traveled does not exit for shapes, and progresses to interpolate the shapes based on closest points for each stop, similar to how the shapes are calculated, if no shape_dist_traveled exists in stop_times.

Do not throw NPE if linestring is null in CompactLineString

---

src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/Stops.java
src/main/java/org/opentripplanner/transit/raptor/util/paretoset/ParetoSet.java
src/main/java/org/opentripplanner/transit/raptor/util/paretoset/ParetoSetWithMarker.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java
src/test/java/org/opentripplanner/transit/raptor/util/paretoset/ParetoSetWithMarkerTest.java

This is a change to the Stops.listArrivalsAfterMarker method. Instead of creating an ArrayList of StopArrivals after the marker, it instead uses Arrays.copyOfRange. This method is called over 8 million times in a long-distance search on the Norwegian graph over a long time range. For my test search the total time spent in this method decreases from 1.31 s to 0.44 s. This should not affect functionality at all.

Optimize copying of states to the next round

---

src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/options/SpeedTestCmdLineOpts.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/options/SpeedTestConfig.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/testcase/Place.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/StreetSearch.java
src/test/resources/raptor/speedtest/norway/README.md
src/test/resources/raptor/speedtest/norway/speed-test-config.json

**This PR only modify the SpeedTest.**
This PR add the possibility to configure the SpeedTest using a config file _speed-test-config.json_. The only configurable property added is the `testDate`. The `testDate` is used to set witch date all test cases travel requests are made. This was previously hardcoded in the code. We want this to be configurable and follow the test input. It is important to run the test for a given date to get consistent results (regression testing). This also allow for creating multiple set setups with different cases and data. 
An alternative was to make the date part each test case _travelSearch.csv_, but this would be harder to maintain when the graph is updated and you want to run the test for a different day. If needed we could add date the the …

Otp2 speed test add options

---

src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/DebugFilterChain.java
src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorRequest.java
src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorRequestBuilder.java
src/main/java/org/opentripplanner/transit/raptor/api/request/SearchDirection.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/configure/RaptorConfig.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SearchContext.java
src/main/java/org/opentripplanner/transit/raptor/service/DebugHeuristics.java
src/main/java/org/opentripplanner/transit/raptor/service/HeuristicSearchTask.java
src/main/java/org/opentripplanner/transit/raptor/service/RangRaptorDynamicSearch.java
src/main/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculator.java
src/main/java/org/opentripplanner/transit/raptor/service/RequestAlias.java
src/test/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculatorTest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestProfile.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java

This PR fixes 2 bugs to the Dynamic Search Window calculation:
- Calculate the search window correct if both earliest-departure-time(EDT) and latest-arrival-time(LAT) is set. The searchWindow should be: LAT - EDT - minTravelTime.
- Fix the RangRaptorDynamicSearch so that if both earliest-departure-time and latest-arrival-time is set only the reverse search is performed and the search-window is calculated correctly. 

Bugfix on dynamic search-window

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java

The RaptorPathToItineraryMapper calculates walk legs by iterating over the legs the way it is done in AStar. This can differ from the times originally used in the Raptor routing. This pull request causes the mapper to ignore the start and end times from iterating over the legs and instead use the Raptor times.

Use Raptor calculation of leg start/end times

---

docs/Changelog.md
src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
src/main/java/org/opentripplanner/model/TripPattern.java
src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
src/main/java/org/opentripplanner/updater/stoptime/TripPatternCache.java

This adds a methods to the TripPattern class that will copy the geometry from another TripPattern to the current one. It checks if each hop is between the same stops before copying that hop geometry. If the stops are different, a straight-line hop-geometry will be used instead.
This method is called in the TripPatternCache.getOrCreateTripPattern and SiriTripPatternCache.getOrCreateTripPattern method in order to copy the geometries when a TripPattern is replaced by another.

Copy geometries from previous TripPattern when doing real-time updates

---

src/main/java/org/opentripplanner/routing/edgetype/SimpleTransfer.java

This fixes an error in the SimpleTransfer, where the getDistanceMeters() method was not overridden, resulting in 0 being returned from Edge. This in turn sometimes caused access/egress legs to not be mapped before there is a check on the distance being larger than 0. This has been tested in the Entur deployment of OTP2.

Override getDistanceMeters for SimpleTransfer

---

src/client/i18n/messages.pot
src/client/js/otp/modules/multimodal/MultimodalPlannerModule.js
src/client/js/otp/modules/planner/ItinerariesWidget.js
src/client/js/otp/modules/planner/PlannerModule.js
src/client/js/otp/modules/planner/planner-style.css
src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js
src/client/js/otp/widgets/tripoptions/tripoptions-templates.html
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java
src/main/java/org/opentripplanner/api/mapping/ItineraryMapper.java
src/main/java/org/opentripplanner/api/mapping/SystemNoticeMapper.java
src/main/java/org/opentripplanner/api/mapping/TripSearchMetadataMapper.java
src/main/java/org/opentripplanner/api/model/ApiItinerary.java
src/main/java/org/opentripplanner/api/model/ApiSystemNotice.java
src/main/java/org/opentripplanner/model/SystemNotice.java
src/main/java/org/opentripplanner/model/plan/Itinerary.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilder.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/DebugFilterChain.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/MaxLimitFilter.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainBuilderTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/MaxLimitFilterTest.java

This is used for debugging the itinerary-filter-chain. When the request 'debugItineraryFilter' is set, Itineraries are tagged instead of removed from the result set.
- Enable the old 'weight' and 'generalizedCost' in the Transmodel API.

Otp2 Tag Itinerary with SystemNotieces 

---

src/main/java/org/opentripplanner/api/configuration/APIEndpoints.java
src/main/java/org/opentripplanner/api/resource/Routers.java

The GET RouterInfo enpoint is added to OTP 2. This endpoint provided some meta info about the graph needed by the bundeled OTP client.The full functionallity of the old API is not included, only the GET methods and the it ignore the `{routerId}` and return the info about the `default` router (witch) is the only router available.
- [ x ] **formatting**:Yes. 
- [ x ] **documentation**: All JavaDoc on old code is updated to explain the regression.

Add back the 'otp/routers' REST endpoint to be backward compatible with OTP1.

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java

…metry
This adds an additional check for stop index when extracting the part of the trip geometry that is actually boarded. Only checking for time would cause problems in some cases where subsequent stops had the same arrival or departure time. This would cause the geometry not to be drawn all the way to the correct board/alight stop.

Fix trip geometry bug

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelIndexGraphQLSchema.java

This is a small fix to the transmodel sandbox API that was made necessary by #3035. The API expects the Id part of the FeedScopeId.

Authority id fix

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java

RaptorPathToItineraryMapper Place stopIndex fix

---

.travis.yml

The Travis CI configuration contains a notification section that sends messages to a Conveyal Slack channel. This causes us to be notified of every build of every fork and branch of OpenTripPlanner. This includes a lot of private repos, and can get noisy. This PR removes this Slack integration.
This is a port of #3057 over to the dev-2.x branch.

Remove Slack notifications from 2.x

---

docs/Changelog.md
docs/Configuration.md
src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/module/ned/DegreeGridNEDTileSource.java
src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
src/main/java/org/opentripplanner/graph_builder/module/ned/GeotiffGridCoverageFactoryImpl.java
src/main/java/org/opentripplanner/graph_builder/module/ned/NEDDownloader.java
src/main/java/org/opentripplanner/graph_builder/module/ned/NEDGridCoverageFactoryImpl.java
src/main/java/org/opentripplanner/graph_builder/module/ned/UnifiedGridCoverage.java
src/main/java/org/opentripplanner/graph_builder/services/ned/ElevationGridCoverageFactory.java
src/main/java/org/opentripplanner/graph_builder/services/ned/NEDTileSource.java
src/main/java/org/opentripplanner/routing/edgetype/StreetWithElevationEdge.java
src/main/java/org/opentripplanner/standalone/GraphBuilderParameters.java
src/main/java/org/opentripplanner/util/ElevationUtils.java
src/test/java/org/opentripplanner/geocoder/bano/BanoGeocoderTest.java
src/test/java/org/opentripplanner/graph_builder/module/ElevationModuleTest.java

This PR dramatically speeds up the calculations in the ElevationModule of the graph builder modules. It does so by:
- Optimizing as many calculations of elevations for a street edge as possible.
- Adding the ability to read/write cached elevation data
- After graph building, a file with a lookup of the cached elevation for a coordinate sequence can be written
- In subsequent graph builds, this file can be loaded and the cached data can be used.
- custom graph build parameters can be entered to enable or disable reading or writing of this data. The default is to read, but not to write.
In addition to the performance improvements, this PR also has changes that:
- tolerate areas where elevation tiles are …

Elevation calculation speed-up

---

README.md

Updates  the links to point to http://docs.opentripplanner.org/ rather than http://opentripplanner.readthedocs.org/
closes #3060

Update outdated documentation links

---

src/main/java/org/opentripplanner/model/TimetableSnapshot.java
src/main/java/org/opentripplanner/routing/graph/GraphIndex.java

The GraphIndex.getPatternsFroStop method collects patterns from both the GraphIndex itself and from the current TimetableSnapshot. The javadoc for the TimetableSnapshot.patternsForStop incorrectly said that it only contained new trip patterns, when it also contains updated trip patterns. This PR updates the javadoc and changes the GraphIndex.getPatternsFroStop method to use a set instead of a list to avoid duplicate patterns being returned.

Prevent duplicate stop times entries caused by realtime updates

---

src/main/java/org/opentripplanner/common/geometry/PackedCoordinateSequence.java
src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java

I tried to see if it'd be any better to use the Kryo library for the cached elevations file since it's used for the Graph.obj file. Looks like this will save a little bit of processing time and file size.

Use Kryo library for cached elevation serialization/deserialization

---

docs/Changelog.md
docs/Configuration.md
docs/OTP2-MigrationGuide.md
src/main/java/org/opentripplanner/datastore/OtpDataStoreConfig.java
src/main/java/org/opentripplanner/datastore/configure/DataStoreFactory.java
src/main/java/org/opentripplanner/datastore/file/FileDataSourceRepository.java
src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
src/main/java/org/opentripplanner/standalone/config/StorageConfig.java
src/main/java/org/opentripplanner/standalone/configure/OtpDataStoreConfigAdapter.java
src/main/java/org/opentripplanner/transit/raptor/api/request/DynamicSearchWindowCoefficients.java

This PR contain a few minor updates to configuration and to the documentation.
- Make the local file type resolver configurable with pattern for matching OSM, DEM, GTFS and NETEX files.
- Extensive configuration updates.
- Added missing changelog item for #2891.

Make the local file resolver configurable and update various documentation

---

src/main/java/org/opentripplanner/netex/loader/NetexBundle.java
src/main/java/org/opentripplanner/netex/loader/NetexXmlParser.java

Use `DataSource#asInputSteam()` for parsing NeTEx documents to avoid
loading the whole document into memory with `asBytes()`.

Use input streams instead of byte[] when parsing NeTEx files

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
src/main/java/org/opentripplanner/api/mapping/LegMapper.java
src/main/java/org/opentripplanner/api/model/ApiLeg.java
src/main/java/org/opentripplanner/model/plan/Leg.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TripSchedule.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/TripPatternForDates.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/TripScheduleWithOffset.java

`LegMapper` is updated to use the service date of the `TripSchedule` to correctly fill out `leg.serviceDate`. For this to be possible, `TripSchedule` is extended with a `getServiceDate()` method which exposes the service date (`LocalDate`) in `TripScheduleWithOffset` throught `TripPatternForDate` / `TripPatternForDates`.
Closes #3126 

Fill out Leg#serviceDate using the relevant TripSchedule

---

src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
src/main/java/org/opentripplanner/routing/api/response/InputField.java

The `RoutingErrorCode.OUTSIDE_SERVICE_PERIOD` exists (and existed in OTP1), but is currently not implemented. 
`graph#transitFeedCovers(Date)` is used to verify if the request is covered by the used transit data.

Return OUTSIDE_SERVICE_PERIOD for transit trips outside the data validity

---

src/main/java/org/opentripplanner/gtfs/GtfsLibrary.java

This is a minimal solution for #2280. It does not add a special taxi mode, it just treats them as buses so the GTFS import won't crash when the data contains a route with a taxi extended mode.
A more complete solution to this exists in #2373, but development seems to have stalled at a point where it was awaiting a few changes. Also, I'm not sure if there will be implications to adding new modes
I plan to port this over to OTP2. Considering OTP2 is used in Nordic countries, who are likely to import the Swedish data that has the taxi routes, I would defer to users there including @t2gran and others at Entur on whether we should finish up the other PR #2373. OTP2 will be able to import Netex data though so probably won't even use these GTFS extended route codes.

Return BUS for taxi extended route types, fixes #2280

---

src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java

This two bugs in the NeTEx import. The first was that the NeTEx parser never added the GroupOfLine entities to the NetexIndex. The other was that the networkIdByGroupOfLineId added networkId and groupId in the reverse order.
The result of this was that Lines that connected to Authority through GroupOfLines instead of via Network directly got set to the default Authority (name N/A). This can be seen in the NetexImportDataIndex.lookUpNetworkForLine method.
I have tested this by importing the Norwegian NeTEx file and doing API calls from the Entur client.

Correctly add GroupOfLines

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java

In #3144 we removed the trivial path exception, and made it possible for (sub)itineraries in a RAPTOR search to have no legs. Unfortunately there is a check, which makes sure subItineraries in transfers always has exactly one leg. 
When there are two stops in separate feeds so that they link to the same vertex, no leg is generated for a transfer between them, and an error is thrown. This adds a separate check for empty itineraries, which bypasses the check and fixup of that leg.

 Do not throw error when a transit subItinerary has no legs

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
src/ext/resources/legacygraphqlapi/schema.graphqls

Add `searchWindow` query parameter to legacy GraphQL API. This is same as Transmodel query parameter, but unit is seconds, because legacy GraphQL API's response `searchWindowUsed` is also in seconds.

Add searchWindow query parameter to legacy GraphQL API

---

src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java

This is a small fix to the NeTEx import, so that additional networks are also imported. Without this, agency information will not be imported for some data providers.
This has been tested on the Norwegian NeTEx data set.

Parse additionalNetworks in NeTEx import

---

docs/Changelog.md
src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
src/main/java/org/opentripplanner/updater/stoptime/TripPatternCache.java

Do not overwrite id on TripPattern, but rather leave the generated id as is. This will fix the issue below, as there are no longer collisions in fetching Timetables for TripPatterns, as the hash and equals are based on the id.
Also fix a bug in date comparison when removing old data.

Do not overwrite TripPattern ids

---

docs/Changelog.md
src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
src/main/java/org/opentripplanner/model/FareZone.java
src/main/java/org/opentripplanner/model/StopTimeKey.java
src/main/java/org/opentripplanner/model/Timetable.java
src/main/java/org/opentripplanner/model/TimetableSnapshot.java
src/main/java/org/opentripplanner/model/TransitEntity.java
src/main/java/org/opentripplanner/model/TripPattern.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerUpdater.java
src/main/java/org/opentripplanner/updater/GtfsRealtimeFuzzyTripMatcher.java
src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
src/main/java/org/opentripplanner/updater/stoptime/TripPatternCache.java
src/test/java/org/opentripplanner/netex/NetexLoaderSmokeTest.java

This pull request is done based on discussions on the OTP dev meeting last Thursday. It contains the following:
- Do not overwrite `TripPattern` ids
- Make TransitEntity `equals` and `hashCode` final, removing the three implementations extending those.
- Store original trip pattern on trip patterns created from realtime updates
- Cache or move expensive calculations outside loops in realtime updaters
- Fix purging of old data, so it is run only on actual day changes
- Fix TimetableSnapshot by only adding modified patterns to the cache of new patterns and make it explicitly a `SetMultimap `, so the same pattern is not added more than once.

Realtime updater optimisations and fixes

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/Transfer.java

This is the minimal amount of changes to make transit routing work on graphs that were built without OSM data. The `AccessEgressRouter` will currently only snap to the nearest stop (with no walk time). This can result in not finding any routes, if it snaps to the wrong stop.
A more complete fix will involve refactoring the NearbyStopFinder, so that the `AccessEgressRouter` does not call the `findNearbyStopsViaStreets` method directly. This will also involve making the `findNearbyStops` method work with multiple start vertices.
We can discuss in the meeting tomorrow whether this should be merged or not.

Do not throw NPEs when routing without OSM data

---

docs/Changelog.md
src/main/java/org/opentripplanner/model/StopLevel.java
src/main/java/org/opentripplanner/model/TripPattern.java

- Make `StopLevel` Serializable.
- The `TripPattern#getGeometry()` should return null, not fail with a NPE when there is no geometry - no matter the cause.

Fix issue #3195 - Build and load GTFS files for San Francisco Bay Area.

---

pom.xml
src/main/java/org/opentripplanner/netex/loader/mapping/TripPatternMapper.java
src/main/java/org/opentripplanner/netex/loader/parser/ServiceCalendarFrameParser.java
src/main/java/org/opentripplanner/netex/loader/parser/SiteFrameParser.java
src/main/java/org/opentripplanner/netex/loader/parser/TimeTableFrameParser.java
src/main/java/org/opentripplanner/netex/support/DayTypeRefsToServiceIdAdapter.java
src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java

The 1.0.11 support DateServiceJourneys(DSJs), and this update of the library allow us to import netex files with DSJs without crashing. The DSJ offer an alternative way to add calendar data, and Service Journeys with DSJ do not have DayTypeAssignments. In the previous version this was required. Also some of the returned datatypes have changes, so whenever these are used the code had to be updated. 
**NOTE This PR do NOT add support for DSJ, it only allow us to parse Netex files with DSJs without crashing - DSJs are ignored.**
Only the NeTEx import code is touched by this PR - no changes is done to the OTP core.

Upgrade org.entur:netex-java-model to 1.0.11 (from 1.0.8)

---

README.md

Perhaps "a quick introduction" was meant to link to what is now "Basic Tutorial", but I think the home page of the docs lays out the options better, and this reduces maintenance needed at the readme, lets you focus on the docs.
I did not create an issue for this; the URL that is 404 is visible here in the change.

Remove link "a quick introduction" in readme (which currently is 404)

---

docs/Changelog.md
src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/module/map/BusRouteStreetMatcher.java

This PR fixes a small bug in the graph build and add a progress tracker to the BusRouteStreetMatcher:
- Bugfix - The `BusRouteStreetMatcher` and `TransitToTaggedStopsModule` graph builder modules are not run if the graph is build in two steps. So, if you first build a _streetGraph.obj_ file, and the build the _graph.obj_ these modules are not run. The bug is independent of the config `matchBusRoutesToStreets` setting.
- Add progress tracking to BusRouteStreetMatcher.

Otp2 add progress bar to bus route street matcher

---

src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java

When trips are added in SIRI Realtime, the field `ExternalLineRef` is no longer required - will fall back to `LineRef`.

No longer require externalLineRef on added trips - SIRI Updaters

---

src/test/java/org/opentripplanner/graph_builder/module/osm/TestOpenStreetMapGraphBuilder.java

Avoid system default locale in unit tests to make tests pass regardless of system settings. OTP as server software should avoid using system locale settings, but locale defaults are configurable as explained in docs/Configuration.md

Avoid system default locale in unit tests

---

docs/Configuration.md
docs/OTP2-MigrationGuide.md

This PR update the Migration gude and the configuration doc.

doc: Improve the build config documentation in the MigrationGuide.

---

docs/Changelog.md
docs/Configuration.md
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/ServerInfoType.java
src/main/java/org/opentripplanner/api/resource/ServerInfo.java
src/main/java/org/opentripplanner/common/ProjectInfo.java
src/main/java/org/opentripplanner/model/Timetable.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/routing/edgetype/ParkAndRideEdge.java
src/main/java/org/opentripplanner/routing/edgetype/ParkAndRideLinkEdge.java
src/main/java/org/opentripplanner/routing/graph/Edge.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/routing/graph/Vertex.java
src/main/java/org/opentripplanner/routing/trippattern/FrequencyEntry.java
src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
src/main/java/org/opentripplanner/routing/vertextype/BikeParkVertex.java
src/main/java/org/opentripplanner/routing/vertextype/BikeRentalStationVertex.java
src/main/java/org/opentripplanner/routing/vertextype/ParkAndRideVertex.java
src/main/java/org/opentripplanner/standalone/OTPMain.java
src/main/java/org/opentripplanner/standalone/OtpStartupInfo.java
src/main/java/org/opentripplanner/standalone/config/ConfigLoader.java
src/main/java/org/opentripplanner/standalone/config/EnvironmentVariableReplacer.java
src/test/java/org/opentripplanner/standalone/config/EnvironmentVariableReplacerTest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java

There is not issue for this PR. The PR provide:
-  a cleanup of the MavenInfo class in OTP
- Cleanup: The `serialVersionUID` in a class should change when the class change, not depend on the Maven version
number. The serialized graph on the other hand can have a check on the Maven version number to see if two graphs
are complient.
- MavenInfo is renamed ProjectInfo - it holds info avout the Maven project version as well as som Git info.
- Documentation on the environment substitution. This is just mentioned in the Configuration.md, but not clearly 
described, now it is.
- Include ProjectInfo in the configuration substitution as well as the environmental variables substitution.  
- I have changed the 3 version number from `incremental` to `patch`, using the [terminology on …

Insert project info in configuration files

---

docs/javadoc/README.md
pom.xml

I got the JavaDoc plugin to work locally by setting the JAVA_HOME env variable. But it do not work on the CI build. So instead of spending more time to get this to work, the next option was to disable it. I followed the guideline from Maven Central and made the a fake javadoc jar with a README.md file witch explain why we do not provide any java doc. The [README](https://github.com/opentripplanner/OpenTripPlanner/blob/3360a0b92a2d3154c1b59675aaec3f3ccaac911f/docs/javadoc/README.md) is part of this PR.

Provide a fake JavaDoc jar with readme

---

docs/Changelog.md
docs/Governance.md

There are only two commits, both of which only affect documentation. These were changes made to master to update the default published documentation which we also want to be part of 2.0.

Port dangling commits from master to 2.0-rc

---

src/ext/java/org/opentripplanner/ext/interactivelauncher/InteractiveOtpMain.java
src/ext/java/org/opentripplanner/ext/interactivelauncher/views/OptionsView.java

This is a small bugfix on the InteractiveOtpMain. The "[ ] save" checkbox was ignored and changing the value had no effect. This PR fixes this by setting the value on the model.  

InteractiveOtpMain save flag not set.

---

src/main/java/org/opentripplanner/transit/raptor/service/RangRaptorDynamicSearch.java

A travel search sometimes return without any metadata even if there is a path outside the search window. This happens with a McRaptor search if the first heuristics search succeed, but not the last. The meta-data can be set from the first heuristic search, enabling the client to search again with a new search-window (next/previous).

bugfix: No trip metadata returned when path exist outside search-window

---

src/main/java/org/opentripplanner/model/TripPattern.java

Fix geometry response to contain full data up to last stop
`TripPattern`'s `getGeometry` was missing the hop geometry to the last stop because loop offset bug.

Fix TripPattern geometry response to contain full data up to last stop

---

src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java

Sandbox-changes only
When the fuzzy-matcher fails to find a result for a provided id for an Alert, `null` is returned. When this is not handled, a NullPointerException occurs that causes the rest of the alerts in the same update to be ignored.

OTP2: Handle that fuzzy-matches may not be found

---

src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/ValidityPeriodType.java
src/main/java/org/opentripplanner/routing/alertpatch/TimePeriod.java
src/main/java/org/opentripplanner/routing/alertpatch/TransitAlert.java
src/main/java/org/opentripplanner/updater/alerts/AlertsUpdateHandler.java

Open ended alerts/situations should return _null_, not _epoch 0_ as endTime.

Returning 'null' when endTime is not set

---

src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerUpdater.java

This fixes a bug in the TransitLayerUpdater, where a Trip that was cancelled by a realtime update, but was not replaced with another Trip, would not be removed.
This has been tested in the Entur deployment of OTP2.

Fix bug in TransitLayerUpdater

---

docs/OTP2-MigrationGuide.md
src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/LineType.java
src/main/java/org/opentripplanner/model/Route.java
src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerUpdater.java
src/main/java/org/opentripplanner/updater/bike_rental/datasources/GbfsBikeRentalDataSource.java
src/main/java/org/opentripplanner/updater/bike_rental/datasources/GenericJsonBikeRentalDataSource.java
src/main/java/org/opentripplanner/util/OTPFeature.java

This PR adds support for GBFS auto discovery of endpoints, which brings the updater closer to GBFS 2.1 compatibility. It also turns off floating bike support by default, as it is contains a memory leak and is not safe to use.

Add support for GBFS auto discovery of endpoints

---

src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
src/main/java/org/opentripplanner/netex/mapping/calendar/DatedServiceJourneyMapper.java
src/main/java/org/opentripplanner/netex/mapping/support/ServiceAlterationFilter.java
src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java
src/test/java/org/opentripplanner/netex/mapping/calendar/DatedServiceJourneyMapperTest.java

This prevents `ServiceJourneys` with `ServiceAlteration` `CANCELLATION` or `REPLACED` from being imported. Also, even though we do not have full `DatedServiceJourneySupport`, I have also added a check that prevents DSJs with `ServiceAlteration` `CANCELLATION` or `REPLACED` from being imported.

Do not map trips with ServiceAlteration CANCELLATION or REPLACED

---

src/test/java/org/opentripplanner/datastore/file/DirectoryDataSourceTest.java

Correctly close files during `DirectoryDataSourceTest.testIO` so that the file may be deleted afterwards.

Fix IO test failure on windows (#2950)

---

docs/Configuration.md
src/main/java/org/opentripplanner/datastore/DataSource.java
src/main/java/org/opentripplanner/datastore/FileType.java
src/main/java/org/opentripplanner/datastore/file/FileDataSourceRepository.java
src/main/java/org/opentripplanner/graph_builder/GraphBuilderDataSources.java
src/main/java/org/opentripplanner/standalone/config/StorageConfig.java
src/test/java/org/opentripplanner/datastore/OtpDataStoreTest.java

This PR improve the file loading (storage) by:
- Support for relative file names in the configuration. Resolved relative to the OTP base path.
- Fix NullPointerException if a is relative(could happen before also).
- Removed unused OTP_STATUS file type + small cleanups.

Support relative file URIs for accessing local files

---

src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryFilterChainTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/RemoveWalkOnlyFilterTest.java

Dev-2.x does not compile at the moment.

Fix: Test not working after auto merging of PRs: #3335 and #3337

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStoptimeImpl.java
src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/JourneyWhiteListed.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/TimetabledPassingTimeType.java
src/main/java/org/opentripplanner/api/mapping/TripTimeMapper.java
src/main/java/org/opentripplanner/model/TripTimeShort.java
src/main/java/org/opentripplanner/routing/StopTimesHelper.java
src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java

This PR does the following:
- Make all fields in TripTimeShort private final
- Add the isRecordedStop field from TripTimes. This marks whether the realtime fields represent expected or actual times.
- Implement getters for actualDepartureTime and actualArrivalTime
- Use these getters in the transmodel api

Add support for actualArrivalTimes and actualDepartureTimes

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java

This fixes #3277, by saving OSM nodes even if they contain bicycel rental/parking tags.

Save all nodes even if they contain bikeRental/bikeParking tags

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternIdGenerator.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/JourneyPatternType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
src/main/java/org/opentripplanner/api/mapping/TripMapper.java
src/main/java/org/opentripplanner/gtfs/GenerateTripPatternsOperation.java
src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
src/main/java/org/opentripplanner/model/Direction.java
src/main/java/org/opentripplanner/model/Trip.java
src/main/java/org/opentripplanner/model/TripPattern.java
src/main/java/org/opentripplanner/netex/DirectionMapper.java
src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
src/main/java/org/opentripplanner/updater/GtfsRealtimeFuzzyTripMatcher.java
src/main/java/org/opentripplanner/updater/stoptime/TripPatternCache.java
src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderLimitPeriodTest.java
src/test/java/org/opentripplanner/netex/NetexBundleSmokeTest.java

This changed the `directionId` field in the `Trip` class to a new `Direction` enum.
>   UNKNOWN(-1),
>   OUTBOUND(0),
>   INBOUND(1),
>   CLOCKWISE(0),
>   ANTICLOCKWISE(1);
GTFS fields 0 and 1 are mapped to OUTBOUND and INBOUND. In addition CLOCKWISE and ANTICLOCKWISE are mapped to 0 and 1. This follows from the GTFS specification.
> 0 - Travel in one direction (e.g. outbound travel).
> 1 - Travel in the opposite direction (e.g. inbound travel).

Add Direction enum to OTP model and add Netex mapping

---

pom.xml
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequestType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
src/main/java/org/opentripplanner/model/Trip.java
src/main/java/org/opentripplanner/model/TripAlteration.java
src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
src/main/java/org/opentripplanner/netex/mapping/TripServiceAlterationMapper.java
src/main/java/org/opentripplanner/netex/mapping/calendar/DatedServiceJourneyMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TripPatternForDate.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreator.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilter.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilterTest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java

This PR builds on #3332
- Imports ServiceAlterations on ServiceJourney and saves them in a new field on Trip.
- Adds a new filter on TripTimes, using the functionality added in #3332, which allows cancelled trips to be filtered out.
- Adds includePlannedCancellations parameter in the transmodel api
- Removes an obsolete test and adds a new test
- Have the newWithFilteredTripTimes return null if all TripTimes are filtered out
- Have the filterActiveTripPatterns stream filter out all TripPatternForDate objects that are null

Otp2 include planned cancellations

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java

This fixes the mapping to fill out `Place.platformCode` with `Stop.platformCode` instead of `Stop.code`.

Correctly fill out platformCode during itinerary mapping

---

src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/TripPatternForDate.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TripPatternForDateMapper.java
src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreatorTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilterTest.java

This updates `TripPatternForDate#tripTimes` to contain a `List<TripTimes>` instead of an array so as to make the code cleaner based on comments in https://github.com/opentripplanner/OpenTripPlanner/pull/3332#discussion_r568939735.
The performance implications of this change have not yet been tested.

RAPTOR: migrate TripPatternForDate#tripTimes to a List

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/LineType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
src/main/java/org/opentripplanner/netex/issues/DayTypeScheduleIsEmpty.java
src/main/java/org/opentripplanner/netex/issues/ObjectNotFound.java
src/main/java/org/opentripplanner/netex/mapping/TripCalendarBuilder.java
src/main/java/org/opentripplanner/netex/mapping/calendar/DatedServiceJourneyMapper.java
src/main/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapper.java
src/main/java/org/opentripplanner/netex/validation/DSJOperatingDayNotFound.java
src/main/java/org/opentripplanner/netex/validation/DSJServiceJourneyNotFound.java
src/main/java/org/opentripplanner/netex/validation/JourneyPatternNotFoundInSJ.java
src/main/java/org/opentripplanner/netex/validation/PassengerStopAssignmentQuayNotFound.java
src/main/java/org/opentripplanner/standalone/config/ConfigLoader.java
src/test/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapperTest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/options/SpeedTestConfig.java

Make it possible to configure the graph file in the SpeedTest. This reuses the configuration loader used by OTP. This enables environment variable filtering and absolute and relative file paths. For example, this allows graph filenames to include the serialization version number, so multiple graphs can coexist for different versions or commits of OTP.
There are some minor changes in the Transmodel API and in the Netex import:
- Transmodel GraphQL API - Add ServiceAlteration to SJ.
- Netex - Add import issue for emtpy DayType.

Otp2 speed test imprive graph loding

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/TransferWithDuration.java
src/main/java/org/opentripplanner/transit/raptor/api/path/TransferPathLeg.java
src/main/java/org/opentripplanner/transit/raptor/api/view/TransferPathView.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/arrivals/TransferStopArrival.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ForwardPathMapper.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ReversePathMapper.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/AccessStopArrivalState.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/StopArrivalState.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/Stops.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/view/StopsCursor.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/stoparrivals/view/Transfer.java
src/test/java/org/opentripplanner/transit/raptor/_data/stoparrival/StopArrivalsTestData.java
src/test/java/org/opentripplanner/transit/raptor/_data/stoparrival/Walk.java

Currently RAPTOR paths don't contain the `RaptorTransfer` actually used, so `TransferPathLeg` leg is modified to contain a reference to the `RaptorTransfer` which was used to construct it.
This allows the itinerary generation from the paths to be cleaner since there is an explicit transfer object to use (`RaptorPathToItineraryMapper#mapTransferLeg`).

RAPTOR: keep track of used RaptorTransfers during traversal

---

docs/Changelog.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
src/main/java/org/opentripplanner/model/SimpleTransfer.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/Transfer.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransfersMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/TransferWithDuration.java
src/main/java/org/opentripplanner/routing/edgetype/PathwayEdge.java
src/main/java/org/opentripplanner/routing/graph/Edge.java
src/main/java/org/opentripplanner/routing/graphfinder/NearbyStop.java

Pathway edges may have a length of zero with an explicit `traversalTime`, which is incorrectly handled as having a duration and length of `0`.
With this PR when constructing RAPTOR transfers the "time-only" aspect of the transfer is summed in addition to the "distance / speed-dependent" aspect. For this a `distanceIndependentTime` is added to `SimpleTransfer` / `Transfer`.
closes #3357
No new tests are added. The changes were manually tested.
No changes are made to the documentation.
> A pathway's `traversal_time` is used when calculating the duration of transfers [#3357](https://github.com/opentripplanner/OpenTripPlanner/issues/3357).

Handle pathways with only traversal_time set

---

src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java

If levels are not defined for GTFS pathway elevators (`pathway_mode=5`), then WalkStep generation will fail with an NPE.
This avoids that by not only checking if there is a `StationElement`, but also if it has a `levelName` defined when determining the level name for onboard/offboard vertices.
closes #3362 
No test were modified.
No documentation was updated.
No item is added to the changelog.

Use the station name for pathway levels if no value is provided

---

src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/TransitLayerUpdater.java

This fixes a method call in the TransitLayerUpdater. The `getTripPatternsStartingOnDateCopy` and `getTripPatternsRunningOnDateCopy` were mixed up, and based on the naming of the value being computed called `tripPatternsRunningOnDateMapCache`, it is obvious what the correct method call would be.
This caused trips not to be found in some cases when a trip crossed midnight.

Use correct method to update tripPatternsRunningOnDateMapCache

---

docs/Changelog.md
docs/Configuration.md
src/main/java/org/opentripplanner/standalone/config/TransitRoutingConfig.java
src/main/java/org/opentripplanner/transit/raptor/api/request/DynamicSearchWindowCoefficients.java
src/main/java/org/opentripplanner/transit/raptor/api/view/Heuristics.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/McRangeRaptorWorkerState.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/McTransitWorker.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/PatternRide.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/heuristics/HeuristicsAdapter.java
src/main/java/org/opentripplanner/transit/raptor/service/RangRaptorDynamicSearch.java
src/main/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculator.java
src/test/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculatorTest.java

This PR contain:
- Fix: The cost calculation did not calculate board and wait cost correctly for the first transit boarding. This would only be a problem if FLEX access and normal transit would compete by cost.
- Improvement: Improve dynamic search window calculation #3366
closes #3366 
Unit tests updated and SpeedTest run to verity the performance unchanged.
- JavaDoc, Changelog.md and Configuration.md updated

Otp2 fix add cost for first alight slack

---

docs/Getting-OTP.md
docs/sandbox/LegacyGraphQLApi.md
docs/sandbox/MapboxVectorTilesApi.md

(I hope you can forgive me for not following the usual PR form, but this PR is tiny.)
Today I tried out the Legacy GraphQL API and it works really well. Well done for that.
The documentation was a little thin on the ground so I took upon myself to flesh it out.
I also noticed that the instructions to download snapshots are outdated as the code is built and deployed to Github now. However, if you follow the link to the packages page it's not actually possible to download the very newest snapshots. It seems that Github simply cannot display more than a few assets.
I also fixed a few typos.

Improve documentation for LegacyGraphQLApi

---

src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java

This PR renames a variable that really seems like it ought to be called `egressStops` instead of `accessStops`. It also removes a comment that is not present for the `accessStops` calculation so that these two places of code are consistent.
N/A
No changes to tests.
Yep
No extra documentation need for correcting spelling/grammar.
Entry to changelog probably not needed.

Rename variable to be say egress instead of access

---

src/main/java/org/opentripplanner/transit/raptor/RaptorService.java
src/main/java/org/opentripplanner/transit/raptor/service/HeuristicSearchTask.java
src/main/java/org/opentripplanner/transit/raptor/service/RangeRaptorDynamicSearch.java

This PR fixes a few spellings. There was a class called `RangRaptorDynamicSearch` that has been renamed to `RangeRaptorDynamicSearch`. Also, a number of misspellings and grammar within the `RangeRaptorDynamicSearch` are also corrected.
N/A
No changes to tests.
Yep
No extra documentation need for correcting spelling/grammar.
Entry to changelog probably not needed.

Fix a few spelling and grammar errors

---

docs/Developers-Guide.md

We were interested in using the OTP2 REST API, but struggled to find the REST API docs in the current OTP2 documentation. Eventually we found the OTP1 REST API docs URL and plugged in the OTP2 version numbers to stumble on it.
We looked at a lot of the documentation, including this Developer Guide file and:
* http://docs.opentripplanner.org/en/dev-2.x/Basic-Tutorial/
* http://docs.opentripplanner.org/en/dev-2.x/OTP2-MigrationGuide/#rest-api
* http://docs.opentripplanner.org/en/dev-2.x/Version-Comparison/
...among others but couldn't find any reference (the links that are there point to the source files on GitHub). 
This PR adds a link to the OTP2 REST API docs in the Developer Guide to make it more visible to developers.
Apologies if there is already a link to this somewhere else and we …

docs: Add OTP2 REST API docs URL to the Developer Guide

---

src/main/java/org/opentripplanner/common/StreetUtils.java
src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
src/main/java/org/opentripplanner/graph_builder/module/TransitToTaggedStopsModule.java
src/main/java/org/opentripplanner/graph_builder/module/stopsAlerts/UnconnectedStop.java
src/main/java/org/opentripplanner/inspector/TraversalPermissionsEdgeRenderer.java
src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLink.java
src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntranceLink.java
src/main/java/org/opentripplanner/routing/edgetype/StreetTransitLink.java
src/main/java/org/opentripplanner/routing/edgetype/StreetTransitStopLink.java
src/main/java/org/opentripplanner/routing/edgetype/TransitEntranceLink.java
src/main/java/org/opentripplanner/visualizer/ShowGraph.java
src/test/java/org/opentripplanner/graph_builder/linking/LinkStopToPlatformTest.java
src/test/java/org/opentripplanner/graph_builder/module/FakeGraph.java
src/test/java/org/opentripplanner/graph_builder/module/linking/LinkingTest.java
src/test/java/org/opentripplanner/routing/edgetype/loader/TestGeometryAndBlockProcessor.java

`StreetTransitLink` and `TransitEntranceLink` share a significant amount of code, so the common part is extracted into a base class (`StreetTransitEntityLink`).
The classes are also renamed:
* `StreetTransitLink` -> `StreetTransitStopLink`
* `TransitEntranceLink` -> `StreetTransitEntranceLink`
closes #3388
No changes.
No changes.
No changes.

Refactor StreetTransitLink and TransitEntranceLink to share common code

---

src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java

This fixes and oversight where the booking infos would not be copied over when a TripTimes object is copied as part of a realtime update.
No issue

Also copy bookingInfo when copying TripTimes

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStoptimeImpl.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/JourneyWhiteListed.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/TimetabledPassingTimeType.java
src/main/java/org/opentripplanner/model/TripTimeShort.java

This only changed the Transmodel sandbox API. If a Trip had a planned cancellation, it would not show up on the EstimatedCallType. This adds an additional check in the API to account for this.
This is a bug fix for #3340

Also check Trip cancellation for EstimatedCallType

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java

Itinerary legs may in special cases not contain all `intermediateStops` even though it was requested using `showIntermediateStops = true`.
This updates the itinerary mapping to use _stop indices_ instead of the `arrivalTime` when collecting `intermediateStops`.
It also fills in `Place#stopSequence`, which was a related `TODO` in the code.
closes #3408
No changes.
No changes.
None.

Extract intermediate stops with indices and fill in stopSequence

---

src/client/js/otp/config.js

Some of the map layers in the debug client don't work because of missing API keys or invalid ssl certificate on the remote tile server. This PR disables non-working map layers and changes the default map layer to `OSM Standard Tiles`
See issue #3407
The change was manually tested in the debug client locally.

Disable non-working map layers and change default

---

src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/StreetSearch.java

This fixes a bug where the `fromOrigin` argument provided to the `VertexLinker` should be inverted.

Fix inverted arguments for VertexLinker in SpeedTest

---

src/client/js/otp/config.js
src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/routing/core/State.java
src/main/java/org/opentripplanner/routing/core/StateEditor.java
src/main/java/org/opentripplanner/routing/edgetype/CarPickupableEdge.java
src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLink.java
src/main/java/org/opentripplanner/routing/spt/DominanceFunction.java
src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
src/test/java/org/opentripplanner/routing/algorithm/TestCarPickup.java

CarPickup contains a few inconsistencies (based on #3389), which this fixes:
* Adds _Kiss and Ride (car drop off)_ and _Ride and Kiss (car pickup)_ options to the client
* Correctly clones the `stateData` when the `carPickupState` changes and copies the value of `carPickupState` when reversing a `State`
* Renames `StateEditor#setTaxiState()` to `StateEditor#setCarPickupState()`
* Handles `arriveBy` searches in `StreetTransitEntityLink`
* Adds parallel initial states so that the forward/reverse searches may result in the same path. This implicitly also allows walk-only itineraries so a station only reachable by walking all the way is now an accepted possibility.
A depart at search may end in a `IN_CAR` or `WALK_FROM_DROP_OFF` state. To achieve the same path an `arriveBy` search needs to …

CarPickup tests and related fixes

---

.github/workflows/cibuild.yml

After having introduced a new dependency (Junit 5) I noticed that it is being downloaded in each CI run:
https://github.com/opentripplanner/OpenTripPlanner/pull/3417/checks#step:5:13
This is because the cache key configured is fixed and doesn't change when the dependencies change and at the end of the run the newly downloaded dependencies are not added to the cache.
```
Post job cleanup.
Cache hit occurred on the primary key maven-local-repo, not saving cache.
```
https://github.com/opentripplanner/OpenTripPlanner/pull/3417/checks#step:10:1
This PR fixes this by using the configuration from the official example: https://github.com/actions/cache/blob/main/examples.md#java---maven
If left as is this problem will exacerbate in the future.

[CI] Make cache key depend on the contents of pom.xml

---

src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java

The recent changes to the street linker module removed the check for pathways when linking stops to the street networks. This restores the check.
Stops with pathways don't need to be linked to the street network, since they are connected to entrances which are linked.
closes #3420
No changes.
No changes.
None.

Do not link stops connected by pathways in StreetLinkerModule

---

src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/McTransitWorker.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ForwardPathMapper.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/path/ReversePathMapper.java
src/test/java/org/opentripplanner/transit/raptor/_data/RaptorTestConstants.java
src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransfer.java
src/test/java/org/opentripplanner/transit/raptor/moduletests/D01_TimeDependentAccessTest.java

Adds tests for time restricted access in RAPTOR, with an example implementation in `TestTransfer`.
Three cases are covered:
It would seem that ([documentation](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTransfer.java#L36)):
* `RaptorTransfer#earliestDepartureTime(requestedDepartureTime)` needs to return a value `>= requestedDepartureTime`
* `RaptorTransfer#latestArrivalTime(requestedArrivalTime)` needs to return a value `<= requestedArrivalTime`
closes #3385
No changes required.
None.

RAPTOR: add tests for time restricted access

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java

This changes the Transmodel sandbox API to also include child stop places with without parent stop places even when filtering på `parent`. This functionality is according to existing documentation.

Include stop places without parents

---

docs/Changelog.md
docs/Troubleshooting-Routing.md
src/main/java/org/opentripplanner/inspector/NoThruTrafficEdgeRenderer.java
src/main/java/org/opentripplanner/inspector/TileRendererManager.java
src/main/java/org/opentripplanner/inspector/TraversalPermissionsEdgeRenderer.java

This updates the debug layers:
* Adds an explicit debug layer for no thru traffic restrictions on edges. The `traversal permissions` layer already contains this information, but is not as explicit.
* Updates the `Traversal permissions` layer to display all edges -- if an edge is not a `StreetEdge` it is displayed in orange as a link edge.
* Updates the transit stop coloring in `Traversal permissions` to include all transit nodes (stops, entrances, pathways, boarding areas)
closes #3443 
None.
`Troubleshooting-Routing.md` is updated with details of the new layer.
> Add no thru traffic debug layer [#3443](https://github.com/opentripplanner/OpenTripPlanner/issues/3443)

Add no-thru traffic debug layer

---

docs/Changelog.md
src/main/java/org/opentripplanner/graph_builder/issues/Graphwide.java
src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java

When trying out the cached elevation file feature introduced by @evansiroky a while back, the following exception stopped my graph build.
```
java.util.UnknownFormatConversionException: Conversion = ')'
at java.base/java.util.Formatter.checkText(Formatter.java:2732) ~[na:na]
at java.base/java.util.Formatter.parse(Formatter.java:2718) ~[na:na]
at java.base/java.util.Formatter.format(Formatter.java:2655) ~[na:na]
at java.base/java.util.Formatter.format(Formatter.java:2609) ~[na:na]
at java.base/java.lang.String.format(String.java:2897) ~[na:na]
at org.opentripplanner.graph_builder.issues.Graphwide.getMessage(Graphwide.java:15) ~[otp-shaded.jar:1.1]
at org.opentripplanner.graph_builder.DataImportIssueStore.add(DataImportIssueStore.java:24) ~[otp-shaded.jar:1.1]
at …
```

Fix reading cached elevation files

---

src/client/js/otp/config.js
src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/routing/RoutingService.java
src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/AccessEgressRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/DirectFlexRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/DirectStreetRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilter.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
src/main/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdge.java
src/main/java/org/opentripplanner/routing/graph/Edge.java
src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java
src/test/java/org/opentripplanner/routing/algorithm/StreetModeLinkingTest.java

Linking `CAR` and `CAR_PARK` edges sometimes results in edges which were not car accessible being chosen, which meant that no trip plan was returned.
This fixes the issue, with a few side-effects:
* the lifecycle of `RoutingRequests` in `RoutingWorker` is explicit using try-with-resources. A few modifications were required so that itineraries could be generated after temporary edges were removed.
* the list of modes in the debug client is simplified to reflect how it should be specified
* an NPE during bike-rental planning with data from OSM is fixed
closes #3428 
No changes -- linking with the modes available in UI was manually tested.
No changes.
None.

Correctly link edges where streets which allow cars are required

---

src/client/js/otp/modules/multimodal/MultimodalPlannerModule.js
src/client/js/otp/util/Itin.js
src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js

The selectors for _max walk/bike/car distance_ were not displayed in all cases.
This corrects the logic so that the distance may be specified for each mode. A selector for _max car distance_ is added.
#3407
The changes were manually tested.
No changes.
None.

Fix handling of maxWalkDistance in the client

---

src/test/java/org/opentripplanner/util/ProgressTrackerTest.java

This fixes the `ProgressTracker` unit test, so it does not fail, even if the unit tests halts for a while. The ´ProgressTracker´is a utility and OTP do not depend on it been accurate, so having a water proof test of the timer inside it is not necessary - it only causes noice. 
closes #3435 
This only changes on unit test.
- The codestyle is followed.
- No documentation or changelog item is added.

fix: Progress tracker unit test

---

docs/sandbox/Flex.md
src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/StreetFlexPathCalculator.java
src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessEgressTemplate.java

This PR changes the caching of the StreetFlexPathCalculator so that it is also optimized for egress searches. When doing access searches, we would have lots of different searches from the same origin vertex to many destinations. This was improved earlier by doing a one-to-many search and caching the entire SearchPathTree. This would fail when doing flex egress searches, as in that case the destination with be the same, while the origin was different.
A new parameter has been added to the StreetFlexPathCalculator constructor, to specify which direction the one-to-many search and caching should be done. The FlexRouter then instantiate a StreetFlexPathCalculator for each direction.
In addition, a fix from #3439 which prevents duplicate direct flex itineraries has been included. …

Fix performance issues with the StreetFlexPathCalculator

---

src/client/js/otp/config.js

Enables debug layers in layer dialogue by default. We think this makes sense since this is after all a debug client.
Relates to #3407
Tested manually

Show debug layers by default in layer dialogue

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java

The Legacy GraphQL API currently creates a `new RoutingRequest()` for each request, which doesn't allow setting defaults within `router-config.json`. This updates the API to clone the `defaultRoutingRequest` so that the defaults are applied.
N/A
N/A
N/A
N/A

Reuse the default routing request within the Legacy GraphQL API

---

src/main/java/org/opentripplanner/standalone/config/package.md

Hi folks,
This PR shall improve the readability of the file [package.md](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/src/main/java/org/opentripplanner/standalone/config/package.md) by adjusting grammar and mode of expression.
Please feel free to use, study, share or improve this PR.
Cheers!

Config.package.md: adjusted documentation to improve readability

---

docs/Configuration.md
src/ext/java/org/opentripplanner/ext/bikerentalservicedirectory/BikeRentalParameters.java
src/ext/java/org/opentripplanner/ext/bikerentalservicedirectory/BikeRentalServiceDirectoryFetcher.java
src/main/java/org/opentripplanner/standalone/config/updaters/BikeRentalUpdaterConfig.java
src/main/java/org/opentripplanner/updater/bike_rental/BikeRentalUpdaterParameters.java
src/main/java/org/opentripplanner/updater/bike_rental/datasources/GbfsBikeRentalDataSource.java

For GBFS v2.2 auto-discovery a path suffix of `gbfs` is hardcoded in `GbfsBikeRentalDataSource`, which doesn't allow using a custom file name.
This modifies to auto-discovery logic to use the supplied `url` as the path to the auto-discovery file.
closes #3441
No changes.
The documentation is updated to document both the usage of auto-discovery, and that the full path to `gbfs.json` should be passed as a parameter, which allows the file to have a differing name.
No changes.

Use the provided url for GBFS auto-discovery when configuring a bike rental updater

---

src/main/java/org/opentripplanner/updater/bike_rental/datasources/GbfsBikeRentalDataSource.java

Currently free-floating bike rental stations are created for all bicycles within [GBFS free_bike_status.json](https://github.com/NABSA/gbfs/blob/v2.2/gbfs.md#free_bike_statusjson).
This limits the creation of bikes to cases where `lon` and `lat` are defined and `stationId` is blank.
closes #3442
N/A
No changes.
No changes.

Don't create free-floating bikes for GBFS bikes at stations

---

.travis.yml

The Travis CI configuration contains a notification section that sends messages to a Conveyal Slack channel. This causes us to be notified of every build of every fork and branch of OpenTripPlanner. This includes a lot of private repos, and can get noisy. This PR removes this Slack integration.

Remove Conveyal Slack Travis build notification

---

docs/sandbox/MapboxVectorTilesApi.md
src/ext/java/org/opentripplanner/ext/vectortiles/LayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/bikerental/BikeRentalLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/StationsLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerBuilder.java
src/main/java/org/opentripplanner/standalone/config/VectorTileConfig.java

When trying out @hannesj great vector tiles feature in OTP2 we noticed the some of our bike rental icons are clipped when they are on a tile layer.
I was wondering why this didn't happen for the stops and the stations layer and the reason was that they had an expansion factor of 0.25 and the bike rental layer one of 0.1.
This PR fixes that.

Sandbox: Increase expansion factor of bike rental vector layer

---

src/main/java/org/opentripplanner/inspector/EdgeVertexTileRenderer.java
src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java

The rendering of the traversal debug layer is modified so that:
1. the rendering of vertices is ordered so that `StreetVertex` is painted first, and other vertices are layered on top. With these changes less-common (stops, bike rental, parking, ...) vertices are not covered by intersections.
2. the rendering of edges is ordered so that edges without geometry, non-street edges and finally streed edges are painted. With this change there is less clutter and layering between the rendered eges.
3. Edges without geometry are added to `StreetVertexIndex` using a straight line so that the edges may be displayed in all tiles.
Before:
After:
None.
No changes.
None.
None.

Sort and deterministically display edges without geometry in the traversal permissions debug layer

---

src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/FlexAccessEgressAdapter.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/AccessEgressMapper.java

Reversing FLEX egress may fail with an NPE when reversing the path to create itineraries.
This fixes that by reversing the states within `FlexAccessEgressAdapter` so that is happens while the temporary edges are still connected to the graph. This is also how normal egress paths are handled.
closes #3484
None.
N/A
N/A

Fix flex egress itinerary generation to not fail with an NPE

---

src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java

This is a small PR witch reduced the log level for Real-Time updates when the input data is of poor quality. The log level is  changed from error to warning. These error "spam" our Entur log, and causes "real" errors to drown - no actions. 
There are no issue, tests or doc for this simple PR.

fix: Reduce log level for RT update

---

docs/sandbox/LegacyGraphQLApi.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/README.md

Noticed that there was already a changelog for this sandbox feature in a different folder and I created a new one in an earlier pull request. This just merges the new one into the old one so the changelog is in the same place as for other sandbox features.
- This is just documentation update
- Updates changelog for a sandbox feature

Merge two changelogs for LegacyGraphQLApi

---

src/main/java/org/opentripplanner/routing/edgetype/BikeParkEdge.java
src/main/java/org/opentripplanner/routing/edgetype/ParkAndRideLinkEdge.java
src/main/java/org/opentripplanner/routing/edgetype/StreetBikeParkLink.java
src/main/java/org/opentripplanner/routing/edgetype/StreetBikeRentalLink.java
src/main/java/org/opentripplanner/routing/graphfinder/DirectGraphFinder.java
src/main/java/org/opentripplanner/routing/graphfinder/NearbyStop.java
src/main/java/org/opentripplanner/routing/graphfinder/PatternAtStop.java
src/main/java/org/opentripplanner/routing/graphfinder/PlaceAtDistance.java
src/main/java/org/opentripplanner/routing/graphfinder/StreetGraphFinder.java
src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
src/test/java/org/opentripplanner/routing/graphfinder/DirectGraphFinderTest.java
src/test/java/org/opentripplanner/routing/graphfinder/StreetGraphFinderTest.java

Currently the `StreetGraphFinder` doesn't find nearby bike rental stations.
The feature checks from `*Link` edges are removed, so that the appropriate vertices may be reached, while also making sure that the rental/parking edges have a check for the required features.
closes #3469
A test is added for both `DirectGraphFinder` and `StreetGraphFinder`.
No changes.
None.

Update StreetGraphFinder to find nearby bike rental stations

---

src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
src/main/java/org/opentripplanner/routing/api/request/RequestModes.java
src/test/java/org/opentripplanner/api/parameter/QualifiedModeSetTest.java

The handling of OTP1 _qualified modes_ is modified, so that:
* only a single street mode may be specified
* but if `WALK` is provided also provided it is ignored if another street mode is provided.
This should allow most OTP1 mode requests to work, where `WALK` always had to be specified. Currently `BICYCLE_RENT,WALK` results in `WALK` mode being used, with this `BICYCLE_RENT` will be used regardless of ordering.
#3500
Unit tests are added to verify behavior.
No changes.
No changes.

Backward compatible handling of multiple on-street modes

---

docs/sandbox/MapboxVectorTilesApi.md

This is an extremely simple PR that only adds a newline to the README in order so that the list is rendered correctly.

Add empty to line to correctly display list

---

src/ext/java/org/opentripplanner/ext/flex/FlexLegMapper.java
src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLBookingInfoImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLBookingTimeImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLContactInfoImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
src/ext/resources/legacygraphqlapi/schema.graphqls
src/main/java/org/opentripplanner/gtfs/mapping/BookingRuleMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/StopTimeMapper.java
src/main/java/org/opentripplanner/model/BookingInfo.java
src/main/java/org/opentripplanner/model/BookingTime.java
src/main/java/org/opentripplanner/model/StopTime.java
src/main/java/org/opentripplanner/model/plan/Leg.java
src/main/java/org/opentripplanner/netex/mapping/BookingInfoMapper.java
src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
src/test/java/org/opentripplanner/gtfs/mapping/StopTimesMapperTest.java

Currently OTP2 has support for a single `BookingInfo` per `StopTime`, while GTFS has support for a separate field for pickup and drop off.
* The internal OTP2 `StopTime` is extended to have dropoff and pickup `BookingInfo` fields
* A mapper for [GTFS `BookingRule`s](https://github.com/MobilityData/gtfs-flex/blob/master/spec/reference.md#gtfs-bookingrules) is added to the internal OTP2 model
* The NeTEx mapper is modified to fill both dropoff and pickup values with the same value
* The Legacy GraphQL API is modified to contain both `BookingInfo`s
* The Transmodel GraphQL API always returns the pickup booking info
closes #3498
None.
No changes.
No changes.

Map GTFS BookingRules to BookingInfo for pickup and drop off

---

src/main/java/org/opentripplanner/index/IndexAPI.java

Debug client expects stops and trips to be present on patterns, but index api returned "short" model. This PR changes the api to return the detailed model.
#3407 
The change was manually tested.

fix: debug client trip widget was broken due to missing data

---

.github/workflows/cibuild.yml
pom.xml

This updates the GitHub Actions `deploy` step and the maven configuration to deploy to the actually used fork instead of `opentripplanner/OpenTripPlanner` in every case.
Without this builds of `dev-2.x` fail in forks due to not having permission to deploy to `opentripplanner/OpenTripPlanner` ([example](https://github.com/realCity/OpenTripPlanner/runs/2737946387?check_suite_focus=true#step:6:462), and [successful build](https://github.com/realCity/OpenTripPlanner/actions/runs/903331163))

GitHub Actions: deploy to the actually used repository / fork

---

src/main/java/org/opentripplanner/gtfs/mapping/BookingRuleMapper.java

The GTFS `BookingRule` mapper switched up the mapping of `pickup_message` and `drop_off_message` when creating `BookingInfo`s. This corrects the mapping.

Correct GTFS BookingRule message mapping

---

src/client/js/otp/locale/en.json
src/client/js/otp/locale/no.json
src/client/js/otp/modules/multimodal/MultimodalPlannerModule.js
src/client/js/otp/modules/planner/PlannerModule.js
src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js

Adds a textarea input to the TripOptionsWidget in the debug client, which allows adding arbitrary query parameters to the REST call in the following format:
```
key=value
anotherKey=anotherValue
#comments=allowed
```
which are translated to the following and appended to the API query parameters:
```
key=value&anotherKey=anotherValue
```
#3407 
This change was manually tested.

Additional parameters in trip request in debug client

---

docs/sandbox/LegacyGraphQLApi.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
src/ext/resources/legacygraphqlapi/schema.graphqls

The "Legacy GraphQL API" allows searching for nearby places and filtering by mode (`filterByModes`). Any `TraverseMode` may be specified, but it must be converted to `TransitMode`, which causes errors despite the query being valid. This is a simple solution to handle these errors, without significantly changing the API.
N/A - manually tested.
N/A
N/A

Filter modes for the nearest query to avoid errors in the Legacy GraphQL API

---

src/main/java/org/opentripplanner/util/LocalizedString.java
src/main/java/org/opentripplanner/util/ResourceBundleSingleton.java
src/main/resources/internals_hu.properties
src/test/java/org/opentripplanner/ConstantsForTests.java
src/test/java/org/opentripplanner/routing/algorithm/TestAStar.java
src/test/java/org/opentripplanner/routing/algorithm/TestFares.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java
src/test/java/org/opentripplanner/util/LocalizedStringTest.java

Certain tests failed depending on the ordering or system locale.
* `ResourceBundle` is used to translate strings which by default fallbacks to the system locale. Explicitly disabling the fallback locale makes the used locale deterministic
* `GraphSerializationTest` failed if the graph was used due to `transient` fields being populated when creating a `Router`. A new `Graph` is always created for the serialization tests.

Correct locale handling in resource bundles

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java

Now and then we would get alerts on non-transit legs. This happened when searching to/from a stop and the alert was added to the stop itself. We do not want these alerts on non-transit legs.
This PR adds a check to the top of the AlertToLegMapper::addAlertPatchesToLeg method that returns if the leg is not a transit leg.
No issue
Tested manually

Do not add alert patches to legs that are not transit legs

---

src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java

When searching for flex trips the closest `StopLocation` is found without checkout the pick up / drop off type. This means that it might not actually be usable for boarding / alighting.
This is fixed by updating `closestFlexTrip()` to make sure that the found stop/trip combinations can be used for boarding / alighting as intended.
None.
No changes.
No changes.

Flex: check pickup/dropoff restrictions before finding the closest stop

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/TimetabledPassingTimeType.java
src/main/java/org/opentripplanner/model/TripTimeShort.java

This allows the transmodel API to fetch notices on `PassingTime` and `EstimatedCall`. A new method has been added to StopTimeShort in order to provide the correct key for the `getNoticesByEntity` method.
Tested manually

Allow fetching notices on stop times

---

src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java

It is rarely used, but access and egress mode can actually be null. This fixes two equality checks so that they don't throw NPEs in that case.

Fix NPE when checking for access/egress mode

---

src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/main/java/org/opentripplanner/routing/graph/Graph.java

When adding a trip in realtime-data, it is added to the graph, but it also needs to be added to the graph-index to be considered when calculating possible trips.

Adding support for including realtime-added trips in trip-requests

---

src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/FilterTransitWhenDirectModeIsEmpty.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/street/DirectStreetRouter.java
src/main/java/org/opentripplanner/routing/api/request/RequestModes.java
src/main/java/org/opentripplanner/routing/api/request/StreetMode.java
src/main/java/org/opentripplanner/routing/edgetype/StreetTransitEntityLink.java
src/test/java/org/opentripplanner/routing/algorithm/raptor/router/FilterTransitWhenDirectModeIsEmptyTest.java

It is not commonly used, but it is possible to set access/egress mode to null. This will terminate the access/egress searches immediately. This means you will only be able to travel from the specified stop/station ids. If a coordinate is specified, you will not get any results.
This PR fixes a NPE in the StreetTransitEntityLink when the `nonTransitMode` is null.
We should probably discuss a way to make this more explicit, but in the meantime I think this PR should be merged.

Fix NPE when access/egress mode not specified

---

src/main/java/org/opentripplanner/model/transfer/TransferService.java

This reduces the log level on the log message that occurs when two transfers are imported and one of them is dropped.

Reduce log-level to warning on transfer colliding message

---

docs/sandbox/LegacyGraphQLApi.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLBikeRentalStationImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
src/ext/resources/legacygraphqlapi/schema.graphqls
src/main/java/org/opentripplanner/routing/bike_rental/BikeRentalStation.java
src/main/java/org/opentripplanner/routing/bike_rental/BikeRentalStationUris.java
src/main/java/org/opentripplanner/updater/bike_rental/datasources/GbfsBikeRentalDataSource.java

Currently the deep-links for renting bikes in GBFS are not parsed -- this modifies the parsing to:
* store the deep-links on `BikeRentalStation`
* and adds the new values to the LegacyGraphQL API
closes #3507 
No changes.
No changes.
No changes -- an entry is added for the LegacyGraphQL API.

Store / Add GBFS rental URIs to the internal model / legacy API

---

docs/Changelog.md
src/main/java/org/opentripplanner/routing/spt/DominanceFunction.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/BikeRentalSnapshotTest.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java

Don't allow loops in A* computations for bikes. They can lead to timeouts when the start/destination is near with a high number of visibility edges.
closes #3564 
none
Yes
Yes
Yes

Don't allow A* loops for bicycles

---

docs/Changelog.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
src/main/java/org/opentripplanner/api/common/RoutingResource.java
src/main/java/org/opentripplanner/graph_builder/module/osm/DefaultWayPropertySetSource.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRequestTransferCache.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
src/test/java/org/opentripplanner/graph_builder/module/osm/NorwayWayPropertySetSourceTest.java
src/test/java/org/opentripplanner/routing/edgetype/TestTriangle.java
src/test/java/org/opentripplanner/routing/edgetype/loader/TestGeometryAndBlockProcessor.java
src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java

This PR restricts the traversal of `mtb:scale` tagged ways:
mtb:scale=0 - Pedestrian and bicycle
mtb:scale=1 - Pedestrian only
mtb:scale=2 - Pedestrian only
mtb:scale=3 - No traversal
mtb:scale=4 - No traversal
mtb:scale=5 - No traversal
mtb:scale=6 - No traversal
It also renames the `RoutingRequest.optimize` field to `bicycleOptimizeType` and sets the default to `SAFE` instead of `QUICK`.
Also, the Transmodel API now reads the correct field when applying `bicycleOptimizeType` to the `RoutingRequest`.
No issue
Added new unit tests for the WayPropertySource
Added changelog

Do not allow bicycle traversal on ways tagged with mtb:scale

---

docs/Troubleshooting-Routing.md
src/ext/java/org/opentripplanner/ext/reportapi/resource/ReportResource.java
src/ext/resources/reportapi/report.html

After some feedback from the users of the bicycle safety report and documentation I improved both.
The change in the Java file is a fix for an embarrassing oversight: the method param was unused and hence the route was never actually served by OTP.
n/a
Yes.
n/a
n/a (or is it?)

Improve bicycle safety report and documentation 

---

docs/Changelog.md
pom.xml
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStoptimeImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
src/main/java/org/opentripplanner/model/StopTime.java
src/main/java/org/opentripplanner/model/Timetable.java
src/main/java/org/opentripplanner/model/TripTimeOnDate.java
src/main/java/org/opentripplanner/routing/StopTimesHelper.java
src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
src/test/java/org/opentripplanner/model/TimetableTest.java
src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java

This build on top of #3571.
Because Raptor only checks whether stops can be boarded/alighted on the `TripPattern` level, we need to do the actual cancellations in the `StopPattern` instead of the `TripTimes`.
This PR does the following:
- Change the `Stop` field on TripTimeOnDate to `TripPattern`. This allows checks for cancellations on the `Pattern` level.
- Change the SIRI implementation to cancel stops at the `StopPattern` level. This will make the Siri implementation create a new `TripPattern` for that `Trip`.
- Mark in the GTFS-RT implementation where cancelations at the `TripPattern` level is missing.
- Simplify the Transmodel API calls for `forBoarding` and `forAlighting` by replacing the more complex logic with a call to `PickUpType.isRouteable()`.
- Add back the cancellation …

Cancel individual stop on StopPattern instead of TripTimes

---

docs/Changelog.md
src/main/java/org/opentripplanner/model/transfer/TransferPriority.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/TripToTripTransfer.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathService.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizedPathFactory.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathServiceConstrainedTest.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathServiceTest.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TestTransferBuilder.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorDummy.java
src/test/java/org/opentripplanner/transit/raptor/_data/RaptorTestConstants.java

When Raptor return a path with a transfer at another stop then the optimal stop to transfer, then optimized transfer service will find the correct stop/path, but the transfer information is not attached to the new path in a correct way. The OptimizedPath map of transfers(transfersTo) are updated with the correct transfer, but the key used is the old leg, not the new. This causes the lookup to fail later.
No issue is created for this "small" bugfix.
The second commit add extensive unit-tests for this case. It also improve the tests on TransferPriority, witch was not properly tested. The tests are "semi" high level. They test the OptimizePathService, low level tests already exist. 
Only JavaDoc is updated.
`Changelog.md` is updated.

Fix bug in optimize transfer service decorating path

---

docs/Changelog.md
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java

Currently the `stopPlaces` data fetcher returns a collection off `Station` objects, if no ids are given as filters, while the data fetchers for the `StopPlace` expects to handle instances of `MonoOrMultiModalStation`. This fixes the issue by applying a correct mapper between the two types.
Added

Map Station to correct Transmodel type

---

docs/Changelog.md
src/main/java/org/opentripplanner/netex/mapping/BookingInfoMapper.java
src/test/java/org/opentripplanner/netex/mapping/BookingInfoMapperTest.java

Currently not all types of PurchaseWhenEnumeration are mapped in BookingInfoMapper. This PR adds support for `ADVANCE_AND_DAY_OF_TRAVEL` and `TIME_OF_TRAVEL_ONLY`
Add new enum values to existing tests
Added

Add new types of PurchaseWhenEnumeration in BookingInfoMapper

---

src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
src/main/java/org/opentripplanner/gtfs/mapping/PathwayMapper.java

A problem was reported on the dev mailing list where a null pointer exception was thrown by a logging statement, which was triggered by calling toString on a null value. The person reporting the bug hinted that the to_stop_id of the pathway in question referred to a station node, which seems to be invalid input data based on pathways.txt guidance documents. In the pathway mapper, we just silently store null or incorrect values as nulls in the internal model.
Simply using the logging framwork's `{}` placeholder avoids the immediate problem with the logging. It should log null values correctly without trying to call toString on them.
However, this could still confuse the user. The log message implies that that the to-stop of the pathway is missing, but in fact it's probably just of an …

Log warnings on missing/invalid pathways

---

src/client/js/otp/modules/planner/ItinerariesWidget.js

The route details are missing in some cases in the debug client, and so this PR makes two minor changes so that is is always shown:
1. The leg details only contains the `agencyName`, since the API doesn't have a `route` field:
The details are extended to included the `routeShortName` and `routeLongName` if set.
2. Adds the `mode`, `agencyName`, `routeShortName` and `routeLongName` (if set) to the summary item tooltips:
None.
N/A
No changes.
None.

Show route names in the debug client

---

src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js

The debug client has _itinerary links_ so that the plans may be linked to, reproduced. In certain cases the links aren't restored correctly in the UI:
* the `Wheelchair accessible trip` and `Show filtered itineraries` check boxes are always checked
* the parameters set from `Additional parameters` is not filled out
This fixes both problems by:
* correctly parsing the boolean values from the url
* storing the list of values set from `Additional properties` in the url so that the texbox may be repopulated
No changes.
No changes.
No changes.

Correct the handling of itinerary links in the debug client

---

src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java

Minor changes in sandbox for SIRI-handling.
SIRI ET-updates with only "RecordedCalls" have been explicitly ignored although existing code already support these. (E.g. updates that flag arrival at last stop.) 
This PR allows these to be processed as any other update.

Do not skip update just because there are no EstimatedCalls

---

src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java

When creating #3596 I didn't notice a key difference between the Entur fork and upstream OTP: Entur has made the `TransitMode` a class with submodes whereby in upstream it's an enum. What makes this a little problematic that it still compiled because the imports were not touched!
That's why the previous check if a line/route is a ferry was never true as object identity was never the same. `equals` would also be unlikely to help as for that to work the submodes would have to be identical.
For this reason I'm using the Netex enum rather than the `TransitType`.
I've now used the Entur fork to check for the result and get what I expect, namely routes like this:

Use Netex enums to check for ferries

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLAPI.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPI.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
src/main/java/org/opentripplanner/api/json/GraphQLResponseSerializer.java

After updating the Jackson version, I noticed that the Transmodel API started omitting nulls when serializing. This is not permitted according to the [GraphQL specification](https://spec.graphql.org/June2018/#sec-Value-Completion). This PR applies a similar fix, which has been in place for [`LegacyGraphQLAPI`](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLAPI.java#L53-L56) since before. It changes the serialization config for all OTP APIs when using the Transmodel API, but I did not find a solution, which would be used only for the duration of the API call.

Serialize nulls in Transmodel GraphQL API

---

src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ForwardTransitCalculator.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ReverseTransitCalculator.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TransitCalculator.java
src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTripPattern.java
src/test/java/org/opentripplanner/transit/raptor/moduletests/A02_SingeRouteRestrictionsTest.java

Add boardingPossibleAt and alightingPossibleAt in TransitCalculator and use these in raptor the raptor search. Tis way they are swapped in the reverse search, checking for the correct permission.
Fixes #3621
Added failing unit test

Fix reverse raptor search with boarding/alighting restrictions

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/sx/PtSituationElementType.java

Sandbox-changes only.
Adds support for returning InfoLinks provided in SIRI SX in the Transmodel-API.

Entur add infolinks to transmodel api

---

src/ext/java/org/opentripplanner/ext/flex/FlexLegMapper.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPlaceImpl.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PlanPlaceType.java
src/main/java/org/opentripplanner/api/mapping/PlaceMapper.java
src/main/java/org/opentripplanner/model/Station.java
src/main/java/org/opentripplanner/model/plan/Place.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/test/java/org/opentripplanner/GtfsTest.java
src/test/java/org/opentripplanner/model/plan/PlaceTest.java
src/test/java/org/opentripplanner/model/plan/PlanTestConstants.java
src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap

This pull request changes the internal model, in order to have a reference to `Stop` object in the `Place` object, rather than having just individual fields copied over. This is needed for filtering, where we need access to the parent station form the leg, which is not included today.
At the same time I refactored some places generating `Place` objects, as well as alert mapping for legs.
No changes. Needed to add annotation for JSON serialization in Station, in order not to have cyclical references serialized.
No updates needed
Was a bullet point added to the [changelog file](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Changelog.md) with description and link to the linked issue?

Add reference to Stop in Place

---

docs/Changelog.md
docs/Configuration.md
src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/routing/api/request/StreetMode.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/routing/graphfinder/NearbyStop.java
src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTransfer.java
src/test/java/org/opentripplanner/graph_builder/module/DirectTransferGeneratorTest.java
src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorTest.java
src/test/java/org/opentripplanner/routing/graphfinder/StreetGraphFinderTest.java

Extend the handling of pre-calculated on-street transfers to support additional modes, options besides the default `WALK`. 
The `RoutingRequest`s can be specified in `build-config.json` which will be used to collect the possible transfers:
```
"transferRequests": [
{ "modes": "WALK"    },
{ "modes": "WALK",   "wheelchairAccessible": true },
{ "modes": "BICYCLE" }
]
```
The length of the transfers are restricted by `maxTransferDurationSeconds` -- if set to 30 minutes, than the transfers will included 30 minutes of walking or 30 minutes of bicycling.
closes #3324
`DirectTransferGeneratorTest` is added with tests which account for `TripPattern`s along with street-network and straight line transfers. 
`Configuration.md` contains the new property.
>  Allow transfers to …

Support multiple modes for on-street transfers

---

pom.xml

It upgrades onebusaway-gtfs to the latest version in order to parse the very latest GTFS example files available at https://github.com/MobilityData/gtfs-flex/tree/master/spec
The GTFS-Flex spec has recently changed and those files currently return a parsing error when used for building a graph.
What has changed?
The fields
- `meanDurationOffset`
- `meanDurationFactor`
- `safeDurationOffset`
- `safeDurationFactor`
Are now floats rather than ints.
It is implemented in this commit: https://github.com/OneBusAway/onebusaway-gtfs-modules/commit/7721f3452aed7a8bbc84469deeded1c856eff2d9#diff-c19f726eee451b193725895b8c0254b5a2f8859f0355ed1d5f8c74f55292b9f9
n/a
None changed. Should I add one?
n/a
n/a
Should I add it?

Upgrade OBA gtfs to 1.3.101

---

docs/Changelog.md
src/main/java/org/opentripplanner/netex/issues/StopPlaceWithoutQuays.java
src/main/java/org/opentripplanner/netex/mapping/BookingInfoMapper.java
src/main/java/org/opentripplanner/netex/mapping/BookingMethodMapper.java
src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
src/main/java/org/opentripplanner/transit/raptor/api/request/RaptorRequest.java

This PR fixex a NPE in the NeTEx import. Booking methods `OTHER` is mapped to `null`, witch again causes the NeTEx import to fail and the graph build to terminate. 
There are also a few other minor changes to improve the error handling and logging.
The `com.esotericsoftware.minlog.Log` was used in the BookingInfoMapper, this is clearly a mistake and I searched for other usages of the Log class. It was used in the `org.opentripplanner.transit.raptor.api.request.RaptorRequest` as well, this was also fixed.
We have not created an issue for this simple fix. 
No tests are added.
✅

bug: Fix NPE in NeTEx Booking Method mapping

---

src/ext-test/java/org/opentripplanner/ext/transmodelapi/model/TransportModeSlackTest.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/TransportModeSlack.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/SlackProvider.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java

`TraverseMode` and `TransitMode` were used interchangeably in `boardSlackForMode` / `alightSlackForMode`. This is corrected to always use `TransitMode`.
`SlackProvider` uses the ordinals in `TraverseMode` when constructing the per-mode array, but uses `TransitMode` ordinals when accessing it.
closes #3688 
N/A
N/A

Correct usage of boardSlackForMode / alightSlackForMode

---

src/main/java/org/opentripplanner/netex/mapping/TransferMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/SlackProvider.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/ConstrainedBoardingSearch.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGenerator.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RoutingStrategy.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/SlackProvider.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/McTransitWorker.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/NoWaitTransitWorker.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/StdTransitWorker.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/configure/StdRangeRaptorConfig.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SlackProviderAdapter.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/TransitCalculator.java
src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SlackProviderAdapterTest.java

This PR contains several small fixes and refactorings for issues found during testing of the new constrained transfer support. Most of it is related to alight- and board-slack.
- Respect transfer slack in Optimize transfer. The correct slack between to trips A and B, is A´s alight-slack + transfer-slack + B´s board-slack. Previously transfer-slack was not added, witch made it possible to board trips with insufficient transfer-time. This more of a theoretical problem, because it would not likely be the best transfer - and for the path to exist a better option exist. 
- When searching for a constrained transfer from a given trip to a pattern, we stopped the search when on the first trip found. But, this trip would not necessarily run on the given service  day, so the search should continue …

Fix several small bugs with transfers and board and alight slack [changelog skip]

---

src/client/js/otp/modules/multimodal/MultimodalPlannerModule.js
src/client/js/otp/modules/planner/ItinerariesWidget.js
src/client/js/otp/modules/planner/PlannerModule.js
src/client/js/otp/modules/planner/planner-style.css
src/client/js/otp/util/Itin.js
src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js

The debug client is extended with a few features to ease its usage. If any are controversial, I can split this into separate PRs.
1. URL handling is updated so that
* the `boolean` parameters and the `additional parameters` fields are always restored correctly
* the current parameters are saved to the browser history using `pushState()`, with which the browser URL always reflects the actual trip plan. This also allows the back/forward buttons to navigate between different searches.
2. For non-transit legs in addition to the distance the duration is also displayed: 
3. The existing option to display the `intermediateStops` is enabled: 
4. For transit legs the `tripId` / `routeId` / `serviceDate` fields are displayed:
5. The boarding and alighting `stopCode` (or `stopId`) is updated to …

debug-client: add url handling and extend the displayed fields

---

docs/sandbox/ActuatorAPI.md
src/main/java/org/opentripplanner/api/mapping/BookingInfoMapper.java
src/main/java/org/opentripplanner/api/mapping/BookingMethodMapper.java
src/main/java/org/opentripplanner/api/mapping/BookingTimeMapper.java
src/main/java/org/opentripplanner/api/mapping/ContactInfoMapper.java
src/main/java/org/opentripplanner/api/mapping/LegMapper.java
src/main/java/org/opentripplanner/api/model/ApiBookingInfo.java
src/main/java/org/opentripplanner/api/model/ApiBookingMethod.java
src/main/java/org/opentripplanner/api/model/ApiBookingTime.java
src/main/java/org/opentripplanner/api/model/ApiContactInfo.java
src/main/java/org/opentripplanner/api/model/ApiLeg.java

Expose the fields pickup and dropoff booking info, which are returned by flex legs, to the REST API.
As per convention, I copied all the classes from the model package.
Instances of `LocalTime` are converted to seconds since midnight as the REST API expresses all times like this. Am I seeing this correct?
No issue.
Are there tests for this layer? If yes, I'd love to add one.
Yes.
Lots of JavaDoc added.

Add pickup and dropoff booking info to REST API

---

docs/Changelog.md
src/main/java/org/opentripplanner/routing/algorithm/raptor/router/TransitRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitData.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRoutingRequestTransitDataCreator.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTransitDataProvider.java
src/main/java/org/opentripplanner/transit/raptor/service/RangeRaptorDynamicSearch.java
src/main/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculator.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransitData.java
src/test/java/org/opentripplanner/transit/raptor/service/RaptorSearchWindowCalculatorTest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java

Update the heuristic search to use the EDT and LAT from the selected transit coverage instead of the calculated search window. This makes it possible to always get results, if they exist within the filtered transit data. Previously if there was any waiting during the trip, it might not show up in the reverse heuristic, as the latest arrival time might be too conservative for those.
Fixes #3662 
Fixes #3663
Updated to match the new functionality
Only internal workings were updated 
Added

Use the whole duration of the filtered transit data for the raptor heuristic search

---

.github/workflows/automatic-changelog.yml

In order to not activate the automatic changelog in downstream forks, add a check so that the workflow is only run inside the repo owned by the "opentripplanner" org.
No issue.
n/a
n/a
n/a

Only run automatic changelog in the upstream repository [changelog skip]

---

src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java

After merging https://github.com/opentripplanner/OpenTripPlanner/pull/3719, the graph build started to fail due to invalid string formatting. This fixes those places where invalid format specifiers were used.
None changed
Style followed
None needed

Fix string formatting in NeTEx import issue report [changelog skip]

---

docs/sandbox/ActuatorAPI.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
src/ext/java/org/opentripplanner/ext/readiness_endpoint/MicrometerGraphQLInstrumentation.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
src/ext/java/org/opentripplanner/ext/transmodelapi/support/GqlUtil.java

Add performance monitoring usable via the Actuator API for the GraphQL APIs. This is done using a graphql-java instrumentation, which is added to the field resolvers marked using the `timingData` directive in the schema, as well as to query parsing, validation and execution.
Relates to #2958
None added
Formatted using IDEA autoformatter
TODO

Add Micrometer monitoring for GraphQL [changelog skip]

---

src/ext-test/java/org/opentripplanner/ext/flex/FlexTest.java
src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java

In a previous PR I broke the `mvn install` functionality as I was using relative paths rather than loading a ressource. This fixes the problem.

Use reusable method to fix the build [changelog skip]

---

docs/sandbox/TransmodelApi.md
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java

This fixes filtering lines by a list of ids, even tough `flexibleOnly` has a default value set. This worked before adding the new argument with a default value.
The feature-is sandbox-only and the sandbox changelog is updated.

Transmodel API: Allow filtering by a list of ids [changelog skip] 

---

src/main/java/org/opentripplanner/model/plan/Place.java
src/test/java/org/opentripplanner/model/plan/PlaceTest.java

In https://github.com/opentripplanner/OpenTripPlanner/pull/3480 a small bug was introduced, whereby the Place factory would throw an error, if null coordinates were used, due to the type being migrated form the boxed type to the primitive type.  This reverts that change, and adds a small test for avoiding regressions.

Do not throw NPE in Place constructor [changelog skip]

---

src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java
src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java

@t2gran has alerted me to the fact that `ScheduledDeviatedTripTest` fails when running `mvn install`. We at first thought that it's because I not using a resource loader when loading the GTFS file.
Today I saw the problem again and after some head scratching I noticed that I made the wrong assumption about the `getStops` method. It returns a `Set<Stop>` not an ordered list, as I had assumed. So I fixed the test by taking this into account.
n/a
Tests were fixed :)
Yes.
Added Javadoc.

Fix flex tests by taking into account that stops are a Set [changelog skip]

---

src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
src/ext/java/org/opentripplanner/ext/actuator/ActuatorAPI.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdater.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/updater/GraphUpdater.java
src/main/java/org/opentripplanner/updater/GraphUpdaterConfigurator.java
src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
src/main/java/org/opentripplanner/updater/WriteToGraphCallback.java
src/main/java/org/opentripplanner/updater/alerts/GtfsRealtimeAlertsUpdater.java
src/main/java/org/opentripplanner/updater/stoptime/MqttGtfsRealtimeUpdater.java
src/main/java/org/opentripplanner/updater/stoptime/PollingStoptimeUpdater.java
src/main/java/org/opentripplanner/updater/stoptime/WebsocketGtfsRealtimeUpdater.java
src/main/java/org/opentripplanner/updater/street_notes/WFSNotePollingGraphUpdater.java
src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdater.java
src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java

Logging the first time all updaters report being initialized and instance is ready to process requests. This makes it easier to calculate complete startup-time.

Logging first time instance reports it is ready to use

---

src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js
src/main/java/org/opentripplanner/api/common/RoutingResource.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/routing/edgetype/StreetVehicleParkingLink.java
src/main/java/org/opentripplanner/routing/edgetype/StreetVehicleRentalLink.java
src/main/java/org/opentripplanner/routing/edgetype/VehicleRentalEdge.java
src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParking.java
src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalPlace.java
src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
src/test/java/org/opentripplanner/routing/algorithm/BikeRentalTest.java
src/test/java/org/opentripplanner/routing/algorithm/CarParkAndRideTest.java
src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
src/test/java/org/opentripplanner/routing/algorithm/ParkAndRideTest.java

Four new parameters are added to `RoutingRequest` and `RoutingResource`, which allow limiting the used vehicle rental / parking place by `network` / `tags`:
* `allowedVehicleRentalNetworks` / `bannedVehicleRentalNetworks`
* `requiredVehicleParkingTags` / `bannedVehicleParkingTags`
A few missing parameters are also added to `RoutingResource`: `bikeParkCost`, `bikeParkTime`, `carParkCost`, `carParkTime`.
For vehicle rental:
* if there are only banned networks, everything not banned is allowed
* if there are allowed networks, only those may be used
* if there are both allowed and banned networks, banning takes precedence
For vehicle parking -- tags are currently created from OSM tags (`fee`, `supervised`, `covered`, `surveillance`):
* if `requiredVehicleParkingTags` is specified, than all …

Allow limiting the used vehicle rentals and parkings

---

src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/RouteMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/TransitModeMapper.java
src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
src/test/java/org/opentripplanner/gtfs/mapping/FareRuleMapperTest.java
src/test/java/org/opentripplanner/gtfs/mapping/FrequencyMapperTest.java
src/test/java/org/opentripplanner/gtfs/mapping/RouteMapperTest.java
src/test/java/org/opentripplanner/gtfs/mapping/StopTimesMapperTest.java
src/test/java/org/opentripplanner/gtfs/mapping/TransferMapperTest.java
src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java

Naive support for miscellaneous service route type (17xx) from GTFS. It is now handled as BUS instead of crashing build.
closes #3754
Tested manually
Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Developers-Guide.md#code-style)? 
Yes
RoutingModes.md is the only relevant file I can think of but it might be updated at some point when support for submodes is added.
From title

Handle miscellaneous service as BUS instead of crashing build

---

src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTail.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTailTest.java
src/test/java/org/opentripplanner/transit/raptor/_data/stoparrival/BasicPathTestCase.java

When the transit tails for a Raptor path with a flex egress were calculated it a transfer leg was attempted to be cast to an egress leg which threw an exception.
If we get a transfer we then skip to the next leg.
closes #3761 
Unit test added.
yes
n/a

Bugfix: ClassCastException when planning flex routes

---

src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
src/main/java/org/opentripplanner/netex/mapping/StopMapper.java

Add mode from parent StopPlace for Quays in Netex mapper. It seems we already had the correct mapper, but it was not used anywhere.
Mapper already has unit test coverage
Code style followed
No need to update

Add mode from parent StopPlace for Quays in Netex mapper

---

src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/routing/edgetype/StreetTraversalPermission.java

When profiling the walkable area builder, I also took a look at the routing performance, and found these two low hanging fruits for performance increases.
There are two potential additional easy wins, which should be looked at
- Moving turn restrictions from graph to edges
- Not using a HashSet in `RaptorRoutingRequestTransitData#routeIterator`

Minor performance improvements

---

docs/sandbox/TransmodelApi.md
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java

Add filtering by private code to the Transmodel GraphQL API for service journeys. This is a regression from OTP1

Restore ability to filter by private code [changelog skip]

---

src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java
src/main/java/org/opentripplanner/util/ProgressTracker.java

I noticed that when building a Norway graph 7 out of 20 minutes is taken up computing the trip pattern geometries. This process is run serially when it's quite parallelisable.
With these minor modifications I managed to reduce the graph build time from 20 to 13 minutes on my 16 core test machine.
n/a
yes
n/a

Parallelise computing of trip pattern geometries

---

src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java

Since https://github.com/opentripplanner/OpenTripPlanner/pull/3720 the boarding/alighting constraints for unscheduled trips are checked from the wrong stop index. This fixes that 
None
Code style followed
No updates required

Fix checking allowed boarding/alighting for unscheduled flex trips

---

src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/linking/VertexLinker.java
src/main/java/org/opentripplanner/graph_builder/module/osm/Ring.java
src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
src/main/java/org/opentripplanner/openstreetmap/model/OSMNode.java
src/main/java/org/opentripplanner/routing/edgetype/AreaEdgeList.java
src/main/java/org/opentripplanner/standalone/configure/OTPAppConstruction.java
src/test/java/org/opentripplanner/graph_builder/module/osm/RingTest.java

As discussed in OTP meeting last week, we decided to do performance improvements for the walkable area builder at a later stage. This pull request contains two of those. The first one is limiting the visibility nodes to only use convex points in a polygon. This reduces the build time of the Norwegian graph from ~3 minutes and 45 seconds to ~2min 15 seconds. The second one caches the way properties, which further reduces the build time to ~2minutes.
This also fixes a couple of issues with the builder:
- Do not split edges less than 10 cm.
- Make sure that all area edges are connected properly
- Run island pruning only after stop linking, even when building the street graph separately
- Add issue about unconnected areas
Unit test for calculating convex points in a polygon added
Code style …

Walkable area builder improvements

---

src/main/java/org/opentripplanner/model/StopPattern.java

Remove hardcoded alighting/boarding allowed on first/last stop.
closes #3734
No changes
Followed
No changes needed

Remove hardcoded alighting/boarding on first/last stop

---

src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTestRequest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/options/SpeedTestConfig.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/transit/EgressAccessRouter.java
src/test/resources/raptor/speedtest/norway/speed-test-config.json

The `maxWalkDistanceMeters` in the SpeedTest was passed into the NearByStopFined as `maxWalkDurationSeconds`. This is of cause very confusing. This PR changes the SpeedTest config parameter name to reflect what it is used for.
No, issue for this.
The SpeedTest is a test without unit tests :-)
✅ 
Example config updated as well as JavaDoc
No

refactor: Rename SpeedTest config parameter to maxWalkDurationSeconds [changelog skip]

---

pom.xml

See vulnerability [LOGBACK-1591](http://logback.qos.ch/news.html)
Minor update of the OTP logging framework used, due to a security vulnerability in the previous version.
Let me reiterate that this is not the same thing as the log4j vulnerability - far from it!
You have to create an extremely unsecured environment in order for this to be used for remote code execution.
Nevertheless, lets upgrade to remove this pretty contrived vulnerability.
closes #3785
Not relevant
Not relevant
No
This "day-to-day maintenance" and not included in the changelog.

Update logback dependency to 1.2.8 (1.2.5) [changelog skip]

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLBikeParkImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLCarParkImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
src/ext/resources/legacygraphqlapi/schema.graphqls

Adds tags and openingHours (not yet implemented) to CarPark and BikePark types in legacy graphQL API for backwards compatability with hsldevcom OTP1 API.
Not needed here as minor changes.
Not needed.
Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Developers-Guide.md#code-style)? 
yes
Not needed
Not needed

Add tags and openingHours to CarPark and BikePark in legacy api [changelog skip]

---

docs/Configuration.md
src/main/java/org/opentripplanner/standalone/config/ConfigLoader.java
src/main/java/org/opentripplanner/standalone/config/IncludeFileDirective.java
src/test/java/org/opentripplanner/standalone/config/IncludeFileDirectiveTest.java

This feature make it possible to inject the content of another file into a configuration file. It make it possible to keep part of the configuration in separate files. To include the content of a file use `${includeFile:FILE_NAME}`. The `FILE_NAME` must be the name of a file in the configuration directory. Relative paths are not supported. 
<p>
To allow both files (the configuration file and the injected file) to be valid JSON files a special case is supported; If the include file directive is quoted, then the quotes are removed if the text inserted is valid JSON. We check that the text to inject start with a `{` and ends with `}`. 
Variable substitution is performed on the configuration file after the include file directive; Hence
variable substitution is also performed on the text in …

Add support for include-file-directive in config files.

---

docs/Configuration.md
docs/examples/entur/build-config.json
src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/model/GtfsBundle.java
src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
src/test/java/org/opentripplanner/GtfsTest.java

As discussed in the dev meeting today we decided the parameter `useTransfersTxt`. Reasons for removal are the following:
- the name is wrong: it doesn't enable or disable the transfers.txt but the calculation of the OSM transfers 
- none of us found a use case were turning off the OSM transfers was a good idea
Instead we want to implement a fallback logic like this:
- if we have a transfer in transfers.txt use that
- if not then use pathways.txt
- if not then use OSM based transfers
This will happen in a separate PR.
n/a
n/a
Yes.
Documentation removed.

Remove build parameter 'useTransfersTxt'

---

src/main/java/org/opentripplanner/index/IndexGraphQLSchema.java

stoptimesForServiceDate query errors as omitNonPickups is missing as argument fixed this by adding omitNonPickups as argument in schema. Also added stopIndex and blockId to StopTime type for return.
Closes #3774

Fix NPE in stoptimesForServiceDate query

---

src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java

In my previous PR #3766 I converted a single instance of HashMap to a ConcurrentHashMap. I tested this with the Norway graph and that worked.
However, today I tried it out with another data set and saw the following error:
```
Caused by: java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1900)
at java.base/java.util.HashMap$TreeNode.putTreeVal(HashMap.java:2079)
at java.base/java.util.HashMap.putVal(HashMap.java:634)
at java.base/java.util.HashMap.put(HashMap.java:608)
at org.opentripplanner.graph_builder.module.geometry.GeometryAndBlockProcessor.getSegmentGeometr …
```

Improve concurrency handling in GeometryAndBlockProcessor [changelog skip]

---

src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java

This reduced the memory consumption for StopTimes with ca 20%
for the Norwegian NeTEx dataset (26.7'-> 22.6' StopPattern entries).
Explain in one or two sentences what this PR achieves. 
There is no issue for this.
No
✅ 
No.
This is a none-functonal change; Hence not included in the changelog.

Reduce memory usage by deduplicate StopTimes in NeTEx import. [changelog skip]

---

src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java

Currently Netex feeds only support reading in a fixed stop time even for flex trips. There is a [workaround](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java#L298-L317) for converting these to flex windows. There has been since a clarification on the standard regarding how to read these windows. This adds support for reading those.
None changed
Code style followed
No updates required

Read in flex window from Netex feeds

---

docs/sandbox/TransmodelApi.md
src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/PlaceAtDistanceType.java

Currently the `nearest` query does not find any multiModal stop places, as the search in the index is done on the wrong type (`MonoOrMultiModalStation` vs `Station`). This refactors the search for parent stop places to fix this.
None changed
✅ 
None needed

Fix issue with fetching parent StopPlaces in nearest query in Transmodel API [changelog skip]

---

src/main/java/org/opentripplanner/routing/RoutingService.java

Allow routing without a transit graph. This patch fixes a null pointer exception when reading the time zone from the (non-existant) transit layer by using the existing helper function in the graph object.
I have tested the change by routing on a graph without transit data.
Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Developers-Guide.md#code-style)?

Fix NPE when routing on a graph without transit data.

---

docs/sandbox/TransmodelApi.md
src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/LineType.java

There was an invalid cast in the Transmodel API. We should fetch the id under the `Route` entity instead
None changed
✅ 
None needed

Fix invalid cast in situations resolver for line in Transmodel API [changelog skip]

---

.github/workflows/cibuild.yml
README.md
pom.xml

It adds and agent to the JVM when executing the tests on CI and uploads the coverage reports to codecov.io a free cloud service to display coverage data.
Here is an example of how it looks like: https://codecov.io/gh/leonardehrenfried/OpenTripPlanner/tree/1292b054aa86d2aaafa9bea478d66397241cade9/src/main/java
no issue.
n/a
n/a
I've added a badge to the readme.

Capture code coverage with jacoco and codecov.io

---

src/main/java/org/opentripplanner/model/plan/Leg.java

Change the `Leg` mapper, so that the `mode` is read from the `Trip`, instead of the `Route`. The `mode` getter in trip will fallback to the route, if it is not overridden.
Fixes #3818
Not changed
✅ 
None required

Read leg mode from trip, instead of route

---

src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap

Currently we use the internal object for the snapshot tests. This changes the tests to utilize the REST API models instead.
Updated
✅ 
None needed

Use API mapping in snapshot tests

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
src/main/java/org/opentripplanner/model/plan/Leg.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java

Currently the matching for the estimated calls sometimes fail. This simplifies the logic and stores the proper stop indices in the leg. These indices could be used in the future to remove things from the `Leg`, which could be fetched in the mappers.
None changed
✅ 
None needed

Store stop indices in leg and use them to simplify logic in TripTimeShortHelper

---

src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java

Previously only trips that were in patterns created from real-time updaters, or which did not contain any real-time updates were returned when fetching all stop times for the requested stop. This fixes the issue by returning trips from all patterns, and filtering the ones which were replaced by another patterin deeper in the call hierarchy.
Fixes #3816
None changed
✅ 
None required

Include all trips in `stopTimesForStop`

---

src/main/java/org/opentripplanner/transit/raptor/api/path/PathBuilderLeg.java

There is no issue for this `one-liner`.  We(Entur) got this error witch should never happen when doing a system test of the latest release. We played back 100.000 requests so it is difficult to find out witch of these requests witch caused the error. So this PR improves the logging for the singe case. 
<details>
<summary>Stacktrace</summary>
<pre>
Caused by: java.lang.IllegalStateException: null
at org.opentripplanner.transit.raptor.api.path.PathBuilderLeg.timeShiftTransferTime(PathBuilderLeg.java:391)
at org.opentripplanner.transit.raptor.api.path.PathBuilderLeg.timeShiftThisAndNextLeg(PathBuilderLeg.java:228)
at org.opentripplanner.transit.raptor.api.path.PathBuilder.lambda$timeShiftAllStreetLegs$1(PathBuilder.java:203)
at java.base/java.util.stream.Stream$2.forEachRemaining(Stream.java: …

fix: Log more for Unexpected leg type before TransferLeg [changelog skip]

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/inspector/TraversalPermissionsEdgeRenderer.java
src/main/java/org/opentripplanner/inspector/WheelchairEdgeRenderer.java
src/main/java/org/opentripplanner/routing/edgetype/ElevatorHopEdge.java

This PR implements support  horizontally moving elevators.
closes #3749
No new tests added, verified with manual testing.
Used the intellij formatting rules
Not needed ?
From title

Simple implementation of horizontally moving elevators (Elevator way)

---

.github/pull_request_template.md

Update the link to Code Style article.
Trim whitespace on line endings (Automatically done by editor. Has no effect on rendered markdown.)

Update link to code style in PR template [changelog skip]

---

src/ext-test/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdaterTest.java

When concatenating "user.dir" with the "file://" pattern on Windows, you get mixed path separators like:
```
file://C:\git-projects\OpenTripPlanner/src/ext-test/resources/vehicleparking/parkapi/parkapi-reutlingen.json
```
...which causes the file not to be found and the test to fail.
This patch simplifies the string used to load the test file for the Park API test to avoid mixed path separators on Windows.
Based on https://github.com/leonardehrenfried/OpenTripPlanner/commit/012c0b7ea7ee7947db29bf47a70d264fce08cb1a.
Closes https://github.com/opentripplanner/OpenTripPlanner/issues/3839

fix: Avoid mixed path separators on Windows in Park API test

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java

The PR #3750 did not consider elevator which are modeled as areas, without explicitly being defined as such. This adds filtering for these kind of elevators, eg. https://www.openstreetmap.org/way/503412863 or https://www.openstreetmap.org/way/187719215
Closes #3847
None changed
✅ 
None changed

Filter out elevator ways that are also implicit areas

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripPatternType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java

Narrow down non-null types to improve schema and docs. 
Correct usage of GraphQLNonNull makes the life easier for consumers who generate their clients based on introspection.
No tests done whatsoever!
Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Developers-Guide.md#code-style)? 
Yes. 
Some dangling whitespaces have been removed by my IDE. I don't see anything mentioned about this in the Codestyle Guide, so I guess that's OK?

Narrow down non-null types to improve schema and docs

---

src/main/java/org/opentripplanner/api/mapping/PlaceMapper.java
src/main/java/org/opentripplanner/api/model/ApiPlace.java
src/main/java/org/opentripplanner/model/plan/Place.java

Remove unused field `orig` from `Place`. As the field is always null, and null is not serialized in the Rest API, it is never used anywhere.
None changed
✅ 
None needed

Remove unused field `orig` from `Place` [changelog skip]

---

docs/sandbox/TransmodelApi.md
src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/BookingArrangementType.java

Currently we can't get the `bookWhen` enum from the api, which is used in Netex data, and which the consumers expect to get when fetching booking information. This PR adds logic for trying to deduce correct enum for bookWhen based on the reverse mapping of the different possibilities of how it is mapped.
Non changed
✅ 
None updated

Deduce enum for bookWhen in Transmodel API [changelog skip]

---

src/main/java/org/opentripplanner/standalone/config/updaters/VehicleParkingUpdaterConfig.java

Today we merged in the vehicle parking updater that @optionsome has upstreamed in #3796 - thanks for this!
I encountered a exception when trying out the ParkAPI support:
```
Feb 02 13:24:33 dev build-graph[3636]: java.lang.NullPointerException: null
Feb 02 13:24:33 dev build-graph[3636]:         at java.base/java.util.ArrayList.<init>(ArrayList.java:179)
Feb 02 13:24:33 dev build-graph[3636]:         at org.opentripplanner.standalone.config.updaters.VehicleParkingUpdaterConfig.create(VehicleParkingUpdaterConfig.java:65)
Feb 02 13:24:33 dev build-graph[3636]:         at org.opentripplanner.standalone.config.UpdatersConfig.<init>(UpdatersConfig.java:101)
Feb 02 13:24:33 dev build-graph[3636]:         at org.opentripplanner.standalone.config.RouterConfig.<init>(RouterConfig.java:58)
Feb 02 …
```

Fix vehicle parking updater for ParkAPI [changelog skip]

---

src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java

I merged upstream OTP into one of my downstream forks and we saw the following stack trace when generating vector tiles with null values:
```
Feb 02 15:00:26 dev da267ea3c15b[17630]: 14:00:26.046 ERROR (OTPExceptionMapper.java:39) Unhandled exception
Feb 02 15:00:26 dev da267ea3c15b[17630]: java.lang.NullPointerException: null
Feb 02 15:00:26 dev da267ea3c15b[17630]:         at java.base/java.util.Objects.requireNonNull(Objects.java:221)
Feb 02 15:00:26 dev da267ea3c15b[17630]:         at java.base/java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:827)
Feb 02 15:00:26 dev da267ea3c15b[17630]:         at java.base/java.util.Map.of(Map.java:1349)
Feb 02 15:00:26 dev da267ea3c15b[17630]:         at org.opentripplanner.ext.vectortiles.layers.stops.DigitransitStopPropertyMapp …
```

Allow for null values in vector tiles mapper [changelog skip]

---

src/main/java/org/opentripplanner/routing/edgetype/StreetWithElevationEdge.java
src/test/java/org/opentripplanner/routing/edgetype/PlainStreetEdgeTest.java

This resolves a minor bug in `StreetWithElevationEdge` where `getElevationProfile()` didn't return a profile matching the edge's length.
Added a single unit test.
:ballot_box_with_check:

Correct elevation profile handling in StreetWithElevationEdge [changelog skip]

---

pom.xml
src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
src/main/java/org/opentripplanner/index/IndexAPI.java
src/main/java/org/opentripplanner/routing/RoutingService.java
src/main/java/org/opentripplanner/standalone/config/IncludeFileDirective.java
src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
src/test/java/org/opentripplanner/routing/algorithm/raptor/transit/mappers/StopIndexForRaptorTest.java

Lombok was introduced because of the `@Delegate` pattern, but the library do not work with Dagger DI, witch we also want to use. The usage is limited to one class.
THIS IS A PURE REFACORING
No
No
Yes
No

Otp2 remove lombok [changelog skip]

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/graph_builder/module/osm/VertexAndName.java
src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java

The OSM parser fails if the duration for elevators contain something else then a number. It might be that this should contain number of seconds, but OTP need to handle other values without crashing. 
No issue
No unit tests added.
✅ 
No doc added, bug fix.

Fix number format exception for elevator duration parsing OSM data

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/api/OptimizedPath.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/api/TransferOptimized.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTail.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferOptimizedFilterFactory.java
src/main/java/org/opentripplanner/transit/raptor/util/PathStringBuilder.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/api/OptimizedPathTest.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTailTest.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainServiceTest.java

The Optimized transfer calculate a wait-time-optimized-cost for each possible combination of transfers for a given path. It does so to find the pest places to do the transfer, avoiding back travel and short transfer times. The existing implementation did not take into account the walking cost for the different transfers. In most cases this is ok, because long walking transfers leave less time to do the transfer, but not in all cases - see issue. This fixes this be just adding the generalized cost to the wait-time-optimized-cost (both have the same cost unit/scale - seconds). 
NOTE! The optimized transfer service is configured and needs to be tuned again, after this PR is merged.
closes #3834
Updated
✅ 
✅

Include generalizedCost in the optimized transfers wait-time cost

---

docs/sandbox/TransmodelApi.md
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java

This PR contains three separate fixes/new features for the Transmodel GraphQL API.
- Fix coercion of default parameter
- Expose stopPositionInPattern on EstimatedCall
- Allow selecting first or last quays in a ServiceJourney
None changed
✅ 
Inline documentation updated

Minor Transmodel GraphQL API improvements [changelog skip]

---

docs/Configuration.md
src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/netex/NetexModule.java
src/main/java/org/opentripplanner/netex/configure/NetexConfig.java
src/main/java/org/opentripplanner/standalone/config/BuildConfig.java

Expose maxStopToShapeSnapDistance as build-config.json parameter so that it is no longer hard-coded.
No new tests included.
Follows code style.
Documented new parameter in Java docs and Configuration.md

Expose maxStopToShapeSnapDistance as build-config.json parameter

---

src/ext/java/org/opentripplanner/ext/interactivelauncher/Model.java

Sandbox: InteractiveOtpMain.
Add warning if if the root dir starting InteractiveOtpMain contains config.
No
No
✅ 
No

Log warning if the rootdir contain configuration. [changelog skip]

---

src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java

This PR adds functionality for reading in-seat transfers from GTFS files per the draft specification.
Relates to https://github.com/google/transit/pull/303
None added
✅ 
None required

Implement in-seat transfers per GTFS draft

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/Transfer.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RaptorRequestTransferCache.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
src/main/java/org/opentripplanner/routing/edgetype/StreetWithElevationEdge.java
src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap

Currently stairs are traversed using the same speed as regular horizontal ways. This adds a specific factor which slows down  stair traversal by a configurable factor
Currently traversal between two platforms in Oslo S takes less than two minutes, which is unrealistic. Much of this is due to the stairs being too quick to traverse.
None added (yet)
✅ 
None required

Add stairsTimeFactor to StreetEdge

---

src/main/java/org/opentripplanner/netex/mapping/ServiceLinkMapper.java

Checks null pointer if service link by serviceLinkRef not found netex ServiceLinkMapper .
Not relevant
- Not relevant
yes
- Not relevant

Fixes NPE in Netex ServiceLinkMapper [changelog skip]

---

src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/comparator/SortOrderComparator.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/filter/RemoveDeletionFlagForLeastTransfersItinerary.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/comparator/SortOnNumberOfTransfersTest.java

We want to make sure we always keep the itinerary with the least number of transfers when doing a group by filter, as the cost is not always the most important factor when filtering relatively similar itineraries.
Here the direct itinerary was filtered away previously.
This is built on some commits from #3828, in order to avoid merge conflicts.
closes #3801
Added test for the new comparator
✅ 
None required

Make sure we keep the itinerary with the least number of transfers when grouping the itineraries

---

src/main/java/org/opentripplanner/model/StopPattern.java
src/main/java/org/opentripplanner/model/TripPattern.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/constrainedtransfer/TransferIndexGenerator.java

Adds validation for indexing constrained transfers so that it can handle situations where a route doesn't have a stop specified in a transfer in every pattern.
closes #3867
Should they be added?
Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Codestyle.md)?
Yes
not needed
From title

Don't expect every pattern in a route to have the specified stop with constrained transfers

---

src/main/java/org/opentripplanner/api/mapping/WalkStepMapper.java
src/main/java/org/opentripplanner/api/model/ApiWalkStep.java
src/main/java/org/opentripplanner/model/plan/WalkStep.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap

This extracts the `StatesToWalkStepsMapper` from `GraphPathToItineraryMapper`, in order to make it easier to reason about. Also the various parts of the mapping process are separated into functions, which make the process easier to understand.
We also add information whether a walk step requires the bike to be walked. For now, it is exactly the same on the leg, but in a future PR, we will change the behaviour, so that a leg can require walking the bike only for some steps.
No changes needed
✅ 
No public facing changes
To exclude the PR from the changelog add `[changelog skip]` in the …

Extract StatesToWalkStepsMapper from GraphPathToItineraryMapper [changelog skip]

---

src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLGeometryImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopGeometriesImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/graphql-codegen.yml
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
src/main/java/org/opentripplanner/api/mapping/LegMapper.java
src/main/java/org/opentripplanner/common/geometry/GeometryUtils.java
src/main/java/org/opentripplanner/model/plan/Leg.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/test/java/org/opentripplanner/routing/street/BarrierRoutingTest.java
src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
src/test/java/org/opentripplanner/routing/street/CarRoutingTest.java
src/test/java/org/opentripplanner/routing/street/SplitEdgeTurnRestrictionsTest.java

Currently the internal model for the leg stores the geometry in an encoded format, which needs to be decoded and encoded again for the GraphQL APIs. Instead we should store a jts geometry, and do the required mapping in the API layer.
Updated to match the new internal API
✅ 
None needed

Store a proper Geometry on the leg, not an encoded version [changelog skip]

---

src/main/java/org/opentripplanner/transit/raptor/api/path/Path.java
src/main/java/org/opentripplanner/transit/raptor/api/path/TransitPathLeg.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTransferConstraint.java
src/test/java/org/opentripplanner/transit/raptor/api/path/PathTest.java

Filter out transfers with stay seated when calculating the number of transfers on a path
closes #3887
Updated path test
✅ 
None needed

Account for stay seated transfers when calculating the number of transfers

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/DestinationDisplayType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
src/main/java/org/opentripplanner/model/StopTime.java
src/main/java/org/opentripplanner/model/TripTimeOnDate.java
src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java
src/main/java/org/opentripplanner/routing/trippattern/Deduplicator.java
src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
src/test/java/org/opentripplanner/netex/mapping/StopTimesMapperTest.java
src/test/java/org/opentripplanner/routing/trippattern/DeduplicatorTest.java

Support for NeTEx via's (with transmodel GraphQL API). According to [Transmodel Documentation](https://enturas.atlassian.net/wiki/spaces/PUBLIC/pages/728563886/network#DestinationDisplay).
[#3886](https://github.com/opentripplanner/OpenTripPlanner/issues/3886)
- New unit tests inside _src/test/java/org/opentripplanner/routing/trippattern/DeduplicatorTest.java_
- New unit tests inside _src/test/java/org/opentripplanner/netex/mapping/StopTimesMapperTest.java_
Follows recommended code style.
- Added Java docs for new methods.

Add support for NeTEx VIA's

---

docs/Configuration.md
src/main/java/org/opentripplanner/util/OTPFeature.java

Under high load the parallel routing may lead to an entire cluster of OTP servers to go down.
We believe this happens because new connections are accepted, but the request threads block
each other, waiting for available threads to fork out. The number of accepting threads in
the Grizzly Server is 1.25x as many as cores. This is previously tested to perform well
and give the best throughput for a synchronous request handler. When switching to a
ParallelRouting strategy we need to retest this.
See #3920
NOT APPLICABLE
Updated

Turn ParallelRouting off

---

src/ext/java/org/opentripplanner/ext/flex/FlexLegMapper.java
src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLLegImpl.java
src/main/java/org/opentripplanner/api/mapping/LegMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java
src/main/java/org/opentripplanner/model/PickDrop.java
src/main/java/org/opentripplanner/model/plan/Leg.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java

Currently the pickup/drop off information is stored as a string in the Leg, and needs to be mapped multiple times. This changes it to use the correct Enum until the API level, where correct mapping is done.
Also expose the information from the FlexTrip interface in the correct enum type.
Pure refactoring, none needed
✅ 
None needed

Use PickDrop enum in Leg and FlexTrip [changelog skip]

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripPatternType.java

This makes the _entries_ of the following three lists non-nullable:
* `TripPattern.legs`
* `Leg.intermediateEstimatedCalls`
* `Leg.serviceJourneyEstimatedCalls`

Make some list entries non-null in schema/docs

---

src/main/java/org/opentripplanner/model/modes/AllowedTransitMode.java
src/main/java/org/opentripplanner/routing/algorithm/raptor/transit/request/RoutingRequestTransitDataProviderFilter.java

After merging #3844, we noticed a slowdown in the transit data creation. When profiling, I noticed that the reason is the creation of extremely many streams, when most of the times, no submode filters are used, and a simple Set lookup would suffice. This implements that.
This brings transit data creation down from 96 ms to 75 ms, which is a total reduction of 5% in the SpeedTest.
None, required, pure optimization.
✅ 
None needed

Optimize transit data creation when only main modes are in specified request [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java

Ensure that OTP does not override times from SIRI ET messages.
[#3909](https://github.com/opentripplanner/OpenTripPlanner/issues/3909)
This is a minor fix. No unit tests needed.
Following code style.
This is a minor fix. No documentation needed.

Remove ET realtime override code

---

src/main/java/org/opentripplanner/model/plan/Leg.java

In #3837 The type of alerts for a leg was narrowed to be always non-null. This conflicted with #3896, where the default value was set to null. This fixes the issue, by always returning an empty set.
Fixes #3933

Fix default value for transit alerts

---

src/main/java/org/opentripplanner/graph_builder/issues/IgnoredGtfsTransfer.java
src/main/java/org/opentripplanner/graph_builder/issues/InvalidGtfsTransfer.java
src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java
src/test/java/org/opentripplanner/gtfs/mapping/TransferMapperTest.java

Currently having an invalid GTFS `transfers.txt` can stop the graph build. This makes two minor changes:
* avoids an NPE if the `Transfer` couldn't be processed
* adds elements to the `DataImportIssueStore` when a `Transfer` couldn't be processed
Closes #3937 
No changes.
No changes.

Add invalid GTFS transfers to the issue store [changelog skip]

---

src/ext/java/org/opentripplanner/ext/interactivelauncher/InteractiveOtpMain.java
src/ext/java/org/opentripplanner/ext/interactivelauncher/Model.java
src/ext/java/org/opentripplanner/ext/interactivelauncher/views/MainView.java
src/ext/java/org/opentripplanner/ext/interactivelauncher/views/OptionsView.java
src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
src/main/java/org/opentripplanner/visualizer/ShowGraph.java

The sandbox interactive laucher is extended with a checkbox for the visualizer:
A few related minor bugs are fixed:
* the interactive launcher had an empty status bar (with the OTP CLI commands) on start
* the rendered edges / vertices is extended to contain the currently used set
Some of the functionality doesn't work, but it can be used to check the graph connectivity:

Add the visualizer to the interactive launcher

---

src/main/java/org/opentripplanner/model/TripTimeOnDate.java

In #3897 a bug was introduced, where the midnight of the service day was calculated wrong. This fixes the issue.

Fix date handling for estimated calls for service journey on specific date in Transmodel API

---

src/main/java/org/opentripplanner/common/Histogram.java

An integer conversion that was going to fall into disuse in the Histogram class has been refactored.
- Two integer converters cannot be used in future java upgrades

feat: refactor a deprecated integer conversion in Histogram class

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/TimetabledPassingTimeType.java

It seems like #3883 missed the usage of `DestinationDisplay` in `TimetabledPassingTime`. This fixes the usage of that class.

Fix data fetcher for destinationDisplay in TimetabledPassingTime [changelog skip]

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
src/main/java/org/opentripplanner/netex/mapping/StopMapper.java
src/main/java/org/opentripplanner/netex/mapping/WheelChairMapper.java
src/test/java/org/opentripplanner/netex/mapping/StopAndStationMapperTest.java

- NeTEx mapping to internal model
- Fix GraphQl to return integer on WheelChairBoarding
- Unit test
Maps NeTEx `WheelChairAccess` to internal `Stop.wheelChairBoarding`.
closes #3926 
One unit test with different values added to cover all cases of mapping.

NeTEx mapping for WheelChairBoarding

---

src/main/java/org/opentripplanner/common/TurnRestriction.java
src/main/java/org/opentripplanner/graph_builder/linking/VertexLinker.java
src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
src/main/java/org/opentripplanner/routing/edgetype/TemporaryPartialStreetEdge.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/test/java/org/opentripplanner/routing/edgetype/StreetEdgeTest.java

When splitting edges and the related turn restrictions, the `from` / `to` directions weren't fully accounted for. This updates the code to correctly copy the turn restrictions with added tests.
When splitting edges:
* there are permanent and temporary splits. The original turn restrictions don't need to be removed for temporary splits.
* splitting edges doesn't always result in two edges, and so the `first` and `second` edges may be missing.
* the `first` and `second` split parts need to have turn restriction copied differently.
may be related to #3947
Test are added for edge splitting + turn restrictions in `StreetEdgeTest`
:ballot_box_with_check:

Account for from/to splitting when copying turnRestrictions [changelog skip]

---

src/main/java/org/opentripplanner/util/NonLocalizedString.java
src/test/java/org/opentripplanner/model/plan/PlaceTest.java

As previously discussed, we never want the `NonLocalizedString` to be initialized with a null value. This adds a check, and trows a runtime error, which can be used to fix the implementation.

Make sure NonLocalizedString is correctly initialized [changelog skip]

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/BannedInputType.java
src/main/java/org/opentripplanner/api/common/RoutingResource.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilterTest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java

Trip banning was not implemented when moving from OTP1 to OTP2. This implements it, and fixes the descriptions in the Transmodel API for the unimplemented banned types.

Implement trip banning

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearch.java

For data sets which have a huge number of constrained transfers (see #3950), the `Stream` in `ConstrainedBoarding` search is actually a bottleneck.
```
10:20:59.409 DEBUG (DebugTimingAggregator.java:232) ┌  Routing initialization           :     0 ms
10:20:59.409 DEBUG (DebugTimingAggregator.java:232) ├  Direct street routing            :     2 ms
10:20:59.409 DEBUG (DebugTimingAggregator.java:232) ├  Direct flex routing              :     0 ms
10:20:59.409 DEBUG (DebugTimingAggregator.java:232) │┌ Creating raptor data model       :    88 ms
10:20:59.409 DEBUG (DebugTimingAggregator.java:232) │├ Access routing (325 accesses)    :    31 ms
10:20:59.409 DEBUG (DebugTimingAggregator.java:232) │├ Egress routing (91 egresses)     :     7 ms
10:20:59.409 DEBUG (DebugTimingAggregator.java:232) …
```

Convert stream to list for constrained boarding search [changelog skip]

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/RaptorTransferIndex.java

Quite a bit of time is spent on iterating the transfers for each stop, especially in the reverse heuristic. This improves the reverse heuristic by around 5% and the total search by around 2%

Make raptor transfer lists immutable for faster iteration [changelog skip]

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java

These `Leg` types should not be nullable. This PR updates the GrahphQL schema types. And fixes a typo!

Make distance, duration, directDuration non-null [changelog skip]

---

src/ext/java/org/opentripplanner/ext/flex/FlexibleTransitLeg.java
src/main/java/org/opentripplanner/model/plan/Itinerary.java
src/main/java/org/opentripplanner/model/plan/Leg.java
src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
src/main/java/org/opentripplanner/model/plan/StreetLeg.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveBikerentalWithMostlyWalkingFilter.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByTripIdAndDistance.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByTripIdAndDistanceTest.java

Distance It is always non-null, so it is nicer to use a native, rather than the boxed type.
Relates to #3982

Use native type for distance, as it is always defined[changelog skip]

---

src/main/java/org/opentripplanner/netex/mapping/StopTimesMapper.java

In #3800, we enabled reading flex opening hours from the correct fields. However those could later be overridden by the previous hack. This disables the hack, if times have been set.

Do not override already set flex window [changelog skip]

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternWithRaptorStopIndexes.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitData.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTransitDataProvider.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreatorTest.java
src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTransitData.java

This is an optimization, with approximately 12% routing performance improvement in the SpeedTest.
The first commit optimizes the routeIterator, by calculating an index for each pattern, and using those indexes rather than references when combining all patterns from reached stops.
The second commit adds two bisets, which contain information whether boarding and alighting is allowed at each stop along the pattern.

Optimize routeIterator by adding a pattern index and pre-calculating allowed stops [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
src/main/java/org/opentripplanner/updater/WriteToGraphCallback.java
src/test/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdaterTest.java

Currently the updater is marked ready before the initial updates are applied. This fixes that

Make SiriETGooglePubsubUpdater wait for runnable completition [changelog skip]

---

pom.xml

This updates the maven plugins needed for building the REST API docs.
The background for this is that IBI has decided to become the maintainer of the REST API.
closes #2161
/cc @demory @t2gran @abyrd

Update enunciate and site plugin in order to build API docs [changelog skip]

---

src/main/java/org/opentripplanner/model/TripPattern.java

In case journey stop point is updated to different one do not reduce journey geometry to stop-to-stop straight line. Instead use original journey pattern and just patch first and last point to locations of new stop point. This happens only if both stop points lies within same parent station
N/A
No unit tests (as currently there are no tests for TripPattern class).
Yes
Updated method java doc for modified method.

Modify TripPattern logic for updating stop-to-stop geometry

---

src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
src/main/java/org/opentripplanner/netex/NetexModule.java
src/test/java/org/opentripplanner/model/impl/OtpTransitServiceBuilderLimitPeriodTest.java

As discussed in the dev meeting, this ignores invalid references to shapes, sets them to `null` instead and adds a an issue to the issue store.
closes #3520
none
yes

Ignore invalid references to shapes [changelog skip]

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
src/main/java/org/opentripplanner/api/common/RoutingResource.java
src/main/java/org/opentripplanner/routing/core/BicycleOptimizeType.java

This has not worked as expected for a very long time. You should use `transferCost` instead.
It is a breaking change for the Transmodel API. If you want I can make it backwards-compatible.
None
None
Yes
None
Skip

Remove optimize=TRANSFERS

---

src/main/java/org/opentripplanner/index/IndexAPI.java

@t2gran's PR #4010 made some fields in `IndexApi` final. Apparently Jersey doesn't like that:
```
MultiException stack 1 of 3
java.lang.IllegalArgumentException: The field field(boolean detail in org.opentripplanner.index.IndexAPI) may not be static, final or have an Annotation type
at org.jvnet.hk2.internal.Utilities.findInitializerFields(Utilities.java:1484)
at org.jvnet.hk2.internal.DefaultClassAnalyzer.getFields(DefaultClassAnalyzer.java:94)
at org.glassfish.jersey.inject.hk2.JerseyClassAnalyzer.getFields(JerseyClassAnalyzer.java:223)
at org.jvnet.hk2.internal.Utilities.getInitFields(Utilities.java:227)
at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:133)
at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:156)
at …
```

Make IndexApi fields non-final again [changlelog skip]

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/AuthorityType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/JourneyPatternType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/LineType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/TimetabledPassingTimeType.java

I suspect that these lists of `situations` and `notices` cannot have `null` as entries. Therefore the schema should reflect this.
Schema diff:
```diff
-[Notice]!
+[Notice!]!
```
```diff
-[PtSituationElement]!
+[PtSituationElement!]!
```

Make all situations & notices entries non-null [changelog skip]

---

src/main/java/org/opentripplanner/api/mapping/StopMapper.java
src/main/java/org/opentripplanner/model/StopLocation.java

Calling toString could lead to a NPE since it's now an I18NString.
Alternative approaches:
- return `Optional<I18NString>`
- add method `defaultUrl`
none
none
yes
n/a
skip

Fix mapping of URL in REST API [changelog skip]

---

src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/main/java/org/opentripplanner/netex/mapping/RouteMapper.java
src/main/java/org/opentripplanner/netex/mapping/TransportModeMapper.java
src/main/java/org/opentripplanner/netex/mapping/TripMapper.java
src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
src/test/java/org/opentripplanner/netex/mapping/TransportModeMapperTest.java
src/test/java/org/opentripplanner/netex/mapping/TripMapperTest.java

This just make the NeTEx mod mapping a bit more robust, dropping Lines and ServiceJournyes with unknown main mode. An issue is written to the issue report. Earlier the entire import crashed. 
No issue.
✅ 
I had this problem with an old data set, which now works fine.
✅ 
No

Handle unsupported modes gracefully by logging to issue store. [changelog skip]

---

src/client/js/otp/util/Itin.js

The `walkingBike` flag was moved from `Leg` to `WalkStep`, but there is no indication in the debug client of its value. This adds a🚶 to steps which have `walkingBike` set.

debug-client: add 🚶 to walkingBike steps [changelog skip]

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilterTest.java

If filtering trips for bikes allowed / wheelchair accessible (/ planned cancellation) only the first condition would be checked, using the valued of the first enabled condition. This allowed non-matching trips through.
closes #4022
A new test is added for combined conditions.

Check all conditions when filtering trips [changelog skip]

---

src/main/java/org/opentripplanner/graph_builder/issues/NegativeDwellTime.java
src/main/java/org/opentripplanner/gtfs/RepairStopTimesForEachTripOperation.java

Currently we try to fix invalid stop times. This has caused multiple issues, as the fixed times are not guaranteed to be coherent. Rather than trying to fix the bugs, instead we'll filter out trips with invalid stop times, and record those in the issue store.

Don't try to repair trips with negative dwell or driving times, drop them instead

---

src/main/java/org/opentripplanner/graph_builder/model/GtfsBundle.java
src/main/java/org/opentripplanner/util/HttpUtils.java

While investigating an issue with HTTP timeouts for graph updaters I noticed a completely unused field in GtfsBundle: presumably it was used to download GTFS feeds via HTTP. It doesn't work anymore so I removed it and some code that only this feature used.
n/a
Yes
n/a
skip

Remove unused field GtfsBundle#url [changelog skip]

---

src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
src/ext/java/org/opentripplanner/ext/flex/template/FlexAccessTemplate.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/AlertToLegMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
src/main/java/org/opentripplanner/routing/core/State.java
src/main/java/org/opentripplanner/routing/spt/GraphPath.java
src/test/java/org/opentripplanner/GtfsTest.java
src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
src/test/java/org/opentripplanner/routing/street/BarrierRoutingTest.java
src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
src/test/java/org/opentripplanner/routing/street/CarRoutingTest.java
src/test/java/org/opentripplanner/routing/street/SplitEdgeTurnRestrictionsTest.java

In preparation for the inversion of `RoutingRequest` and `RoutingContext`, I want to remove any unnecessary access to the `Graph` and `RoutingContext` from `GraphPath`. Fortunately it is only used in the itinerary mappers, and it is easy enough to convert these to instead be instantiated in the router using the pieces of the graph they require. None of the mappers require actual access to the graph, but only to some services bound to it, which can be acquired through dependency injection in the future.

Avoid reading Graph/RoutingContext from GraphPath [changelog skip]

---

src/ext-test/java/org/opentripplanner/ext/vectortiles/StopsLayerTest.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
src/main/java/org/opentripplanner/model/Stop.java

Fixes a translation issue in vector tiles sandbox stops layer.
Minor sandbox problem so don't need an issue
Added
Have you followed the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Codestyle.md)?
Yes
Not needed
Not needed

Sandbox vector tiles stop name translation fix [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
src/main/java/org/opentripplanner/util/HttpUtils.java

The current timeout doesn't actually work and this fixes that.
If you want to test this you can use the following config: https://github.com/leonardehrenfried/otp2-setup/blob/main/atlanta/router-config.json#L22-L28
The vehicle positions feed https://bustime.cobbcounty.org/gtfsrt/vehicles actually never sends any data so it's a good test case.
Now that the timeout actually works we can debate if 5 seconds is actually too short a value.
Any opinions?
none
none
yes

Fix HTTP client timeout [changelog skip]

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/main/java/org/opentripplanner/api/common/RoutingResource.java
src/main/java/org/opentripplanner/model/FeedScopedId.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/transit/raptor/api/view/ArrivalView.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/MultiCriteriaRoutingStrategy.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/arrivals/TransferStopArrival.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/arrivals/TransitStopArrival.java
src/test/java/org/opentripplanner/GtfsTest.java
src/test/java/org/opentripplanner/routing/algorithm/TestBanning.java

The raptor implementation has fields in `RoutingResource` to enable debug logging to stderr, but the implementation required knowing the raptor integer ids.
This modifies the implementation to included mapping from `stopId`s to the raptor integer ids on a per-request basis. This allows using the debugging functionality from the debug client.
* `debugRaptorStops` - expects a list of `FeedScopedId`s separated by commas (`,`)
```
debugRaptorStops=BKK:F00379
```
* `debugRaptorPath` and `debugRaptorPathFromStopIndex` -- expects a list (path) of `FeedScopedId`s separated by commas (`,`), along with an index in the path from which to enable debugging
```
debugRaptorPath=BKK:F00373,BKK:F003015
debugRaptorPathFromStopIndex=1
```
A few related typo fixes are also included.
:question: Should these …

Expose Raptor debug functionality in the debug client / rest api [changelog skip]

---

src/client/index.html
src/client/js/otp/modules/planner/PlannerModule.js
src/client/js/otp/util/Itin.js

This makes the walking polylines in the debug client more visible after they changed colour in #3908.
I also upgraded the ancient leaflet version to the latest one.
none
none
none
none
skip

Make walking lines more visible in debug client [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyQuery.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyType.java
src/main/java/org/opentripplanner/model/TimetableSnapshot.java
src/main/java/org/opentripplanner/model/TripOnServiceDate.java
src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
src/main/java/org/opentripplanner/netex/NetexModule.java
src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/main/java/org/opentripplanner/netex/mapping/TripCalendarBuilder.java
src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
src/main/java/org/opentripplanner/netex/mapping/TripPatternMapperResult.java
src/main/java/org/opentripplanner/netex/mapping/calendar/DatedServiceJourneyMapper.java
src/main/java/org/opentripplanner/routing/DatedServiceJourneyHelper.java
src/main/java/org/opentripplanner/routing/RoutingService.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/routing/graph/GraphIndex.java
src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
src/test/java/org/opentripplanner/netex/mapping/TripCalendarBuilderTest.java
src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java
src/test/java/org/opentripplanner/netex/mapping/calendar/DatedServiceJourneyMapperTest.java

Created a new object `TripOnServiceDate` to represent a DatedServiceJourney and adds these to the graph index by creating two new maps. 
One is indexed using datedServiceJourneyId and the other using a tuple of tripId and serviceDate. Both return a single TripOnServiceDate.
TripOnServiceDates are also indexed in TimetableSnapshots for when there are realtime updates.
A new GraphQL endpoint is added called datedServiceJourney with which you can retrieve a datedServiceJourney from the graph index (or TimetableSnapshot if there are realtime updates) using a datedServiceJourneyId.
Additionally a field is added to the LegType where you can now retrieve the datedServiceJourney used in that leg aswell following the same logic as above.
A new unit test was added asserting that TripOnServiceDate …

Add support for NeTex DatedServiceJourneys

---

src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java

Previously, we parsed flexible lines to routes, only when the `FlexRouting` feature was turned on. However, these routes may include scheduled trips, which should be included. The actual creation of flexible trips is still guarded in [NetexModule](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/src/main/java/org/opentripplanner/netex/NetexModule.java#L88-L92), so no additional flexible trips are generated, when the feature is off.

Always parse Netex flexible lines

---

src/main/java/org/opentripplanner/index/IndexAPI.java

@miles-grant-ibigroup has reported bug in the REST API where an internal model type is erroneously returned instead of the correct API type.
Looking at the [1.5 implementation](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-1.x/src/main/java/org/opentripplanner/index/IndexAPI.java#L458), I think `ApiTripTimesShort` is the correct type to return.
None
No
yes
no
skip

Map to ApiTripTimesShort in REST API response [changelog skip]

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleWithOffset.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestRouteData.java

Optimise `TripScheduleWithOffset` creating from `TripPatternForDates.getTripSchedule(int)`. re-using data from TripPatternForDates instead of finding the actual `TripTimes`.
The  `TripTimes` is selected only when needed later for the `RaptorPathToItineraryMapper` and only on relevant trips.
c.f.  https://github.com/opentripplanner/OpenTripPlanner/issues/3814#issuecomment-1082862994
```
Before:
Worker: 
==> mc_destination : [  552,  525,  526,  530 ] Avg: 533.3
Total:  
==> mc_destination : [  755,  712,  715,  718 ] Avg: 725.0
After:
Worker: 
==> mc_destination : [  523,  511,  509,  507 ] Avg: 512.5
Total:  
==> mc_destination : [  729,  703,  700,  697 ] Avg: 707.3
```

Optimise TripPatternForDates.getTripSchedule(int) - TripScheduleWithOffset [changelog skip]

---

docs/sandbox/TransmodelApi.md
src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/MultilingualStringType.java

Make language nullable in MultilingualString, in the Transmodel API.

Make language nullable in MultilingualString, as it is not set in NonLocalizedString [changelog skip]

---

src/main/java/org/opentripplanner/openstreetmap/model/OSMNode.java

OpenStreetmap strictly guides modeling of train stations in such a way, that station geometry does not have a natural counterpart node for a train stop. A train stop therefore gets linked to the closest edge of the street network. This is often a very bad choice because the stop  might link with a highway intended for motor vehicles instead of the actual railway platform. 
In this pull request, an existing graph build time parameter 'extra', which is passed between build modules, is extended to contain information about public transit platforms. An existing stop code - OSM ref tag matching rule is extended to guide the stop linking to primarily use dedicated platform geometry. This PR also changes the whole stop code - OSM ref linking to be a configurable option. 
The actual low level …

Link platforms also against railway=platform

---

pom.xml
src/main/java/org/opentripplanner/model/Stop.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternWithRaptorStopIndexes.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TransitDataProviderFilter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreatorTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilterTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestRouteData.java
src/test/resources/mmri/2b/stops.txt

- If requested wheelchair trip, check on boarding/alightning if possible on stop
- Unit test Raptor wheelchair accessibility
If a trip search is done from a StopPoint to another and in GraphQl the parameter wheelhairAccessible is true then we find trips that should not be found because the stop is not considered accessible for wheelchair.
closes #4044 
Unit test in Raptor module, new class following instructions in markup document. Test going between stops where one stop has no access for wheelchair.

Consider Wheelchair boarding/alightning when routing from or to directly to a stop

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStoptimeImpl.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/TripTimeShortHelper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/LegType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
src/main/java/org/opentripplanner/api/mapping/TripTimeMapper.java
src/main/java/org/opentripplanner/model/TripTimeOnDate.java
src/main/java/org/opentripplanner/model/plan/Leg.java
src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
src/main/java/org/opentripplanner/model/plan/legreference/LegReference.java
src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializer.java
src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceType.java
src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegs.java
src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegsFilter.java
src/main/java/org/opentripplanner/routing/stoptimes/AlternativeLegs.java
src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
src/test/java/org/opentripplanner/GtfsTest.java
src/test/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializerTest.java
src/test/java/org/opentripplanner/routing/stoptimes/AlternativeLegsTest.java

This PR adds an implementation for re-fetching legs, and fetching "alternative legs", i.e. trips which use the same origin/destination station and depart prior/after the current leg.
Module test added for the new functions.
✅ 
Added documentation to the GraphQL schema.

Add an implementation for fetching alternative legs

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripSchedule.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearch.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleAlightSearch.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleBoardSearch.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleSearchFactory.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripSearchTimetable.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTimeTable.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripScheduleBoardOrAlightEvent.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripScheduleSearch.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ForwardTransitCalculator.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/ReverseTransitCalculator.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripAssert.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleAlightSearchTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleBoardSearchTest.java
src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestRoute.java
src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTripSearchTimetable.java

Searching for a trip to board at a particular stop is Transit Model dependent, it could possible take request parameters into account as well as being adapted to an optimized data structure; This PR move the trip search and all interfaces out of Raptor and into the Transit Raptor Adaptor layer. 
part of  #4002
Unit tests are moved as well, no new tests added. But, some test now reuse the TripSearch instead of mocking this, the search is made generic enough so it can be reused in the Raptor tests - operating on a different model. 
✅ 
✅  I have tried to update all relevant Java documentation.

Refactor trip search [changelog skip]

---

src/main/java/org/opentripplanner/transit/raptor/util/paretoset/ParetoSet.java

When looking for HotSpot in long searches, I've seen that the ParetoCheck for Heuristics and Arrival takes a lot of time, most of the time the result is to reject the test (qualify/add). I've seen that in order to reject a path, it would in general do between 10 or 20 times more 'leftDominanceExist' call, so they go through the list and test several elements not-dominating before finding one that dominate the result.
I quickly tried to keep a reference to the last element that fully dominated an input, in hope that this element will also dominate the next input.
This brings a general small improvements in perf-test with sometimes huge improvement on long searches (see test case 34 going from 3.7s to 2.9s).
I think that this is probably due to one of the criteria (i.e. probably …

Shortcut in ParetoCheck add/check for performance [changelog skip]

---

src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java

Currently some of our datasets have invalid DatedServiceJourneyRefs referencing back to themselves. This filters out these cases.

Remove self-referring DatedServiceJourneyRefs [changelog skip]

---

README.md
src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
src/main/java/org/opentripplanner/model/calendar/ServiceDate.java
src/main/java/org/opentripplanner/model/calendar/impl/CalendarServiceDataFactoryImpl.java
src/main/java/org/opentripplanner/updater/stoptime/PollingStoptimeUpdater.java
src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
src/test/java/org/opentripplanner/ConstantsForTests.java
src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java
src/test/java/org/opentripplanner/model/TimetableTest.java
src/test/java/org/opentripplanner/model/calendar/impl/CalendarServiceDataFactoryImplTest.java
src/test/java/org/opentripplanner/routing/algorithm/AStarTest.java
src/test/java/org/opentripplanner/routing/algorithm/FaresTest.java
src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java

Previously all tests for the realtime updates were completely disabled and this PR reactivates them.
It also reduces the usages of `GtfsContext` which I would like to remove eventually.
I recognize that these tests are not really unit tests, more integration or module tests but they do provides useful test scenarios nontheless. I fully expect to help migrate these once the refactoring of the transit layer progresses.
none
yes :)
yes
n/a
skip

Reactivate GTFS-RT tests [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java

Allow single SIRI SX-messages to fail in runtime without affecting/skipping the rest of the messages in the list.
Sandbox-changes only.

Allow single SIRI-situations to fail without affecting others

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/SlackProvider.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/MinSafeTransferTimeCalculator.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGenerator.java
src/main/java/org/opentripplanner/transit/raptor/api/path/PathBuilderLeg.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/Flyweight.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorSlackProvider.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTransitDataProvider.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripPattern.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorTripScheduleSearch.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/SlackProvider.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/MultiCriteriaRoutingStrategy.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SearchContext.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SlackProviderAdapter.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorTest.java
src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTripPattern.java
src/test/java/org/opentripplanner/transit/raptor/rangeraptor/transit/SlackProviderAdapterTest.java

Before the SlackProvider toke a RaptorTripPattern as an argument to the boardSlack/alightSlack
methods, this add an implicit responsibility to the RaptorTripPattern, by adding the slackIndex()
method to RaptorTripPattern we make this responsibility explicit, and at the same time decouple
the dependency from the SlackProvider to RaptorTripPattern.
This PR also contain an annotation to document that some of the Raptor API methods should used 
the flyweight design pattern for returned objects.
✅ 
Updated
✅ 
JavaDoc Updated
This also give us a small performance boost (6 %) (running test-cases tagged with `transit`):
```
Test case ids       : [  1   2   3   4  5   6   7   8   9  10  11 12 13  14  15 16 17  18  19 20  21  22   23  24  25   26  27  28  29  30  31  32  33   34  35   36]
Number of …
```

Refactor, explicit slackIndex on RaptorTripPattern [changelog skip]

---

src/main/java/org/opentripplanner/model/modes/AllowedTransitMode.java
src/test/java/org/opentripplanner/model/modes/AllowedTransitModeTest.java

Ensure that Transmodel GraphQL UNKNOWN submode matches on nulls as well. This is needed to ensure that filter works with GTFS data.
GTFS trips does always have netex submode that is null. This means that no matter which submode filter we set, those trips will always be filtered out (there will be no match on null).
Created some tests for AllowedTransitMode class
Formatted with maven plugin
No new documentation added.

Fix problem with submode filter

---

src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java

closes #4100 4100
In release 2.1 there is still a error logged that frequencies are not supported.
Remove the logged error because frequencies are supported. 
See #4100

Remove log error that frequencies are not supported [changelog skip]

---

src/main/java/org/opentripplanner/model/plan/Itinerary.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/ItinerariesHelper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRequestTransferCache.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/routing/core/RoutingContext.java
src/main/java/org/opentripplanner/routing/edgetype/PathwayEdge.java
src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java

This changes the behaviour when an edge has steeper slope than the `maxWheelchairSlope`. Previously, if no path was found, the limit was dropped and the search was re-done. In this PR the behaviour is changed, and instead a cost factor is applied, if the slope is too steep.
- Should we apply also a time penalty
- Should the cost be a static cost per request, per edge or a multiplier?

Make maxWheelchairSlope not a hard cut-off, but apply a cost instead

---

src/main/java/org/opentripplanner/model/Timetable.java
src/main/java/org/opentripplanner/updater/stoptime/GtfsRealtimeHttpTripUpdateSource.java
src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
src/test/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSourceTest.java

This improves the logging of the GTFS-RT update process so that it always contains the feed id and trip id. It also adds some very basic statistics about the update success rate.
Logs look now like this:
```
13:20:12.374 WARN (TimetableSnapshotSource.java:1141) [feedId: mtba, tripId: mtba:504749] Failed to apply TripUpdate.
13:20:12.374 WARN (TimetableSnapshotSource.java:1141) [feedId: mtba, tripId: mtba:499199] Graph doesn't contain stop id 'de:14713:12994' of trip update, skipping.
13:20:12.374 WARN (TimetableSnapshotSource.java:1141) [feedId: mtba, tripId: mtba:499199] Failed to apply TripUpdate.
13:20:12.374 WARN (TimetableSnapshotSource.java:1141) [feedId: mtba, tripId: mtba:927487] Graph doesn't contain stop id 'de:14713:11404' of trip update, skipping.
13:20:12.374 WARN …
```

Improve logging of GTFS-RT updates [changelog skip]

---

src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
src/main/java/org/opentripplanner/model/OtpTransitService.java
src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java
src/main/java/org/opentripplanner/netex/NetexModule.java
src/main/java/org/opentripplanner/standalone/OTPMain.java
src/test/java/org/opentripplanner/model/impl/OtpTransitServiceImplTest.java

Reverts https://github.com/opentripplanner/OpenTripPlanner/commit/3bb43a730ceb1476588be3103b522f88e6383267 and reimplements it by only crashing the build when there are transit data sets given but none of them have active data.
closes #4063
Not added
Have you followed
the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Codestyle.md)
?
Yes
Maybe not needed
From title

Only crash build if none of the transit data sets have active data [changelog skip]

---

src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
src/main/java/org/opentripplanner/model/plan/Itinerary.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/comparator/SortOrderComparatorTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/MaxLimitFilterTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveTransitIfStreetOnlyIsBetterFilterTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/RemoveWalkOnlyFilterTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/TransitGeneralizedCostFilterTest.java

When refactoring the itinerary in #4028 another bug was introduced where timeshifted flex itineries had an incorrect generalized cost of -1. This happened because during copying of the instance the variable was not set.
In this PR I'm making the variable generalized cost final so you must set it when constructing an Itinerary.
It also updates tests which were setting the cost after instantiation and migrates a few of them to Junit 5.
non
Test added.
yes
none
skipped

Fix generalized cost of flex direct legs [changelog skip]

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java

In #4041, I made an error when creating the routing context for traversing Transfers. This is wrong in arrive-by searches. This PR makes use of the correct RoutingRequest.

Use correct routing request when traversing transfers [changelog skip]

---

src/main/java/org/opentripplanner/api/model/ApiPatternDetail.java
src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
src/main/java/org/opentripplanner/model/Timetable.java
src/main/java/org/opentripplanner/model/TripPattern.java
src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
src/main/java/org/opentripplanner/routing/graphfinder/DirectGraphFinder.java

This PR aims to clean the wrong usage of internal packages that might be subject of changes, to commonly used guava implementation that is the desired standard in the project.
There is no real functional changes in this PR and it's sole purpose is to cleanup and use the right impl.

Switch from internal jcommander implementation usage to guava [changelog skip]

---

pom.xml

That report generation takes time, slowing down the overall build. Reports are definitely useful, but do you need them every time you run the build. We can conditionally disable generating test reports by setting `<disableXmlReport>true<disableXmlReport>`. If you need to generate reports, just add `-DcloseTestReports=false` to the end of mvn build command.
=====================
If there are any inappropriate modifications in this PR, please give me a reply and I will change them.

How about turning off the default build reports generation feature [changelog skip]

---

src/ext-test/java/org/opentripplanner/ext/vectortiles/VehicleParkingsLayerTest.java
src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkToVehicleParkingMapper.java
src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdater.java
src/main/java/org/opentripplanner/graph_builder/module/osm/NoteProperties.java
src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
src/main/java/org/opentripplanner/updater/alerts/AlertsUpdateHandler.java
src/main/java/org/opentripplanner/util/TranslatedString.java
src/main/java/org/opentripplanner/util/TranslationHelper.java
src/test/java/org/opentripplanner/util/TranslatedStringTest.java

Currently we discard the translation language, if only one message is provided. This adds a flag to `TranslatedString#getI18NString` to select if the language information should be preserved even in those cases. It also adds a second flag to prevent memory leaks when used at runtime.
closes #4110
✅

Preserve language in SIRI/GTFS-RT alert messages

---

pom.xml

Upgrading dependency `siri-protobuf-mapper` - only used in sandbox-class _SiriETGooglePubsubUpdater_.
(Upgrade required for mapping SIRI-object "_RecordedCall.Expected*Time_")

Upgrade siri-protobuf-mapper

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/StopIndexForRaptor.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/DefaultCostCalculator.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/StopPriorityCostCalculator.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/DefaultCostCalculatorTest.java
src/test/java/org/opentripplanner/transit/raptor/_data/api/TestPathBuilderTest.java

Ensure that we do not use transfer priority to apply cost on board/alight events that are not transfers. 
This improve/fixes the issue #4078, but make the logic redundant. Ideally we should just have one way of doing this, not one way for NeTEx and one for GTFS. But, porting this to the "GTFS way" have performance challanges that need to be resolved first - NOT before the Transit model refactoring. 
Added new unit test cases for changed logic.
yest
No new documentation added since this is just a bugfix

Use board/aligh cost only for transits

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java

There is a TODO in the code, that some valid results are discarded. This fixes that by fetching some more data and limiting it afterwards.

Fix departuresPerTripPattern when limitOnDestinationDisplay is true [changelog skip]

---

src/main/java/org/opentripplanner/graph_builder/issues/TripDegenerate.java
src/main/java/org/opentripplanner/gtfs/GenerateTripPatternsOperation.java

Flex trips are added to the routing graph via the `FlexTrip` but if they only have a single `StopLocatation` or `LocationGroup` then they don't end up in the API.
This PR fixes that.
n/a
none
n/a
skip

Generate trip patterns for flex trips [changelog skip]

---

src/main/java/org/opentripplanner/netex/mapping/StationMapper.java

Some Netex profiles allow the name type not to be defined. Previously this caused an NPE, which this PR fixes. As the type is an enum, it is safe to use the equals sign for comparison.

Guard against null nameType in Netex mapper [changelog skip]

---

src/main/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModule.java
src/main/java/org/opentripplanner/util/LocalizedString.java
src/test/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModuleTest.java

In #4116 I introduced a bug that I noticed when looking at the [logs of the speed test](https://github.com/opentripplanner/OpenTripPlanner/runs/6270408339?check_suite_focus=true):
```
java.lang.NullPointerException: Cannot invoke "org.opentripplanner.util.I18NString.toString()" because the return value of "org.opentripplanner.routing.graph.Edge.getName()" is null
at org.opentripplanner.routing.algorithm.mapping.StatesToWalkStepsMapper.processState(StatesToWalkStepsMapper.java:186)
at org.opentripplanner.routing.algorithm.mapping.StatesToWalkStepsMapper.generateWalkSteps(StatesToWalkStepsMapper.java:87)
at org.opentripplanner.routing.algorithm.mapping.GraphPathToItineraryMapper.generateLeg(GraphPathToItineraryMapper.java:400)
at org.opentripplanner.routing.algorithm.mapping.GraphPathToItine …
```

Fix platform edge name [changelog skip]

---

src/ext/resources/legacygraphqlapi/schema.graphqls
src/main/java/org/opentripplanner/api/common/RoutingResource.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java

As discussed, update documentation for walkReluctance parameter to reflect usual expected values and add a comment on performance impact.
https://github.com/opentripplanner/OpenTripPlanner/issues/4090

Adapt documentation for walkReluctance, comment on performance [changelog skip]

---

docs/sandbox/SiriAzureUpdaters.md

There are two files describing the Azure Service Bus integration. Remove the one not linked from the sandbox listing.

Remove duplicated documentation file [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/DateMapper.java

Currently we get a lot of non-increasing times due to either the bus leaving before it's assigned time or being expected to arrive late at the final stop. This is due to either recorded or expected arrival or departure time being missing, so that the scheduled time is used instead. Instead we should use the actual or expected departure or arrival time to fill in the missing time.

Fallback to recorded/expected arrival/departure time if other one is missing in SIRI-ET

---

src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsStationInformationMapper.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSource.java
src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSourceTest.java
src/test/resources/gbfs/helsinki/station_information.json

Adds validation that GBFS stations have required fields and ignoring those that don't instead of ignoring all stations if any have issues.
closes #4148
Updated tests
Have you followed
the [suggested code style](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/Codestyle.md)
?
Yes
Not needed
Not needed

Filter out GBFS stations that are missing required information [changelog skip]

---

docs/RouterConfiguration.md

This PR provides documentation, on how GBFS headers can be configured in the `router-config.json`
In one Google Group discussion, we discussed how to configure headers and authorization on GBFS feeds.
Sometimes GBFS Feeds need headers. For those use cases, there is already the functionality to add headers. This PR just adds documentation for this feature.
https://groups.google.com/g/opentripplanner-dev/c/WrW1siP7njk
- edited `docs/RouterConfiguration.md` to document, how to pass GBFS request headers

doc: add headers GBFS config doc

---

pom.xml
src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
src/main/java/org/opentripplanner/routing/edgetype/StreetElevationExtension.java
src/test/java/org/opentripplanner/routing/edgetype/TriangleTest.java

Not an "effective distance", which heavily distorts hilly streets.
Currently the distances are over-reported heavily in hilly areas, due to the "effective distance" being used. The effective distance is based on energy usage required for traversing the edge.

Use actual distance for walk distance in StreetEdge

---

codecov.yml

In a previous developer meeting we talked about including the codecov report when opening PRs. This PR enables it.
An example of such a report looks like this: https://docs.codecov.com/docs/pull-request-comments
Lets discuss this at the dev meeting.

Enable codecov report on PRs [changelog skip]

---

src/main/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModule.java
src/main/resources/logback.xml

This pull request expands the standard logback configuration with an inclusion of an optional log configuration. It provides a very lightweight solution for OTP users to implement their own custom logging needs. The optional inclusion does not require any changes to an existing logging setup.
Also, debug logging of OSM boarding location matching with transit stops is made more detailed. The new log line is useful for all OTP users who wish to debug stop matching. 
As an example, at HSL OTP instance, the debug level logging for OSM boarding location matching is activated in the additional log configuration and log lines are redirected to a separate file. The generated file provides a way to automatically monitor success rate of the mentioned stop matching process.

Option to add customized logging features [changelog skip]

---

src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java
src/test/java/org/opentripplanner/routing/algorithm/StreetModeLinkingTest.java

Currently, when doing a search with a car from a stop id, the linker links it directly to the stop vertex. This is not desirable, as the vertices are connected to edges, which are not car-traversable. Instead, we should do the regular temporary vertex linking process with the stop coordinates. This PS fixes this.
Updated `StreetModeLinkingTest`

Do not link cars to stop vertices in routing

---

docs/sandbox/TransmodelApi.md
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/GeometryMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/JourneyPatternType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/network/StopToStopGeometryType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/util/EncodedPolylineBeanWithStops.java

in Transmodel GraphQL API app new graphql object with stop-to-stop geometries on trip pattern
So it can be fetched by following query:
```
{
line(id: "...") {
journeyPatterns {
stopToStopGeometries {
fromQuay {
id
stopPlace {
id
}
}
toQuay {
id
stopPlace {
id
}
}
pointsOnLink {
length
points
}
}
}
}
}
```
We need to be able to fetch from OTP geometries for trip patterns so that they are divided into stop-to-stop chunks.
It have to look something like this:
```
[
{
fromStop: A
toStop: B 
geometry: "..."
},
{
fromStop: B
toStop: C
geometry: "..."
},
{
fromStop: C
toStop: D
geometry: "..."
}
]
```
I have a question regarding Transmodel graphQL api. We have a new requirement on our API and we need to be able to fetch geometries for trip patterns / lines divided into specific stop-to-stop …

Split journey pattern geometries [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
src/main/java/org/opentripplanner/model/TripTimeOnDate.java
src/main/java/org/opentripplanner/routing/trippattern/OccupancyStatus.java
src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java

Propagates the Occupancy-value from SIRI ET (SIRI 2.0 - which is very basic) to the Transmodel GraphQL-API.
closes #3167

Add Siri realtime occupancy info

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java

There is a flag, `filterByInUse` which can be specified in the `nearest` query in the Transmodel API. However it has not been implemented. This PR implements it, as it was in OTP1.

Add support filterByInUse in nearest query in Transmodel API [changelog skip]

---

src/main/java/org/opentripplanner/api/mapping/PlaceMapper.java
src/main/java/org/opentripplanner/api/model/ApiPlace.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/ElevationSnapshotTest.snap

IBI has added the field `networks` to their fork of OTP1. Since we are currently migrating to OTP2, we would - as the official maintainers of the REST API - like to add this field to the upstream API. 
Yes, returning a list that only ever has a single item is strange but is in line with the rest of the REST API.
@miles-grant-ibigroup Can you confirm that this is in the correct place?
(The reason for not migrating to GraphQL already is that IBI has a middleware component which relies on the REST API)

Add rental networks to REST API [changelog skip]

---

src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorSerializer.java
src/test/java/org/opentripplanner/model/plan/pagecursor/PageCursorTest.java

I've noticed that some times clients pass in an empty string for the page cursor. In these cases we should probably not crash, but treat it as not providing a page cursor at all, thus the deserializer should return null.

Return null when deserializing empty page cursor [changelog skip]

---

src/main/java/org/opentripplanner/model/TimetableSnapshot.java

Mark Timetables with removed TripTimes as dirty in order to clean them up in the TransitLayerUpdater
See the related issue for an explanation of the use case

Replaced TripPatterns leave unwanted Timetables [changelog skip]

---

src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/DateMapper.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/DateMapperTest.java

Make sure that OTP uses right timezone when calculating operating day date based on times from ET message. This PR also adds missing date adjustment for EstimatedCalls
Internally OTP transit modules uses operating day date together with seconds after midnight to define departure and arrival times. Currently there is a bug in Siri module which in some cases causes updater to add an extra 24 hours to times. 
For example, if following ET message is sent to OTP:
```
<RecordedCall>
<StopPointRef>SE:276:Quay:9022012080040049</StopPointRef>
<Order>1</Order>
<Cancellation>false</Cancellation>
<AimedDepartureTime>2022-05-12T00:43:00+02:00</AimedDepartureTime>
<ActualDepartureTime>2022-05-12T00:43:27+02:00</ActualDepartureTime>
</RecordedCall>
```
Internally, *AimedDepartureTime* will be converted …

Solve problems with timezones in Siri Updater module [changelog skip]

---

src/main/java/org/opentripplanner/gtfs/RepairStopTimesForEachTripOperation.java

Code which filters bad stop time sequences now correctly replaces the invalid stop time list with empty list.
fixes #4114

OTP2 no longer crashes on invalid GTFS stop time sequences

---

src/main/java/org/opentripplanner/common/OsmLinkGenerator.java
src/main/java/org/opentripplanner/common/OsmUrlGenerator.java
src/main/java/org/opentripplanner/graph_builder/issues/PrunedIslandStop.java

Adds a link to the HTML issue report so that you can jump directly to the place in OSM to see what is wrong.
It produces URLs like these: https://www.openstreetmap.org/?mlat=19.59292&mlon=-99.25773000000001#map=19/19.59292/-99.25773

Improve HTML message for a stop linked to an island [changelog skip]

---

src/ext-test/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchemaTest.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java

The Transmodel GraphQL API stoped working after the GraphQL lib update earlier. This fixes the problem. The Schema builder had changed slightly. There are no changes to the schema it selt.
closes #4209
One unit test on building the schema is added.
✅

Fix TransmodelGraphQLSchema after GraphQL lib update [changelog skip]

---

docs/sandbox/TransmodelApi.md
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyQuery.java

Support a new use case, where the user can query new DSJs for old DSJs, which are replacing the old ones, that might be eg. on an issued ticket.

Add possibility to filter dated service journeys by replacementFor in the Transmodel API [changelog skip]

---

pom.xml
src/test/java/org/opentripplanner/test/support/PolylineAssert.java
src/test/java/org/opentripplanner/updater/alerts/AlertsUpdateHandlerTest.java

It migrates the last remaining test to Junit 4 and removes the compatibility jar.
#3402
It's just tests
Autoformatted.
n/a
skip

Remove JUnit 4 [changelog skip]

---

src/main/java/org/opentripplanner/model/TripPattern.java
src/test/java/org/opentripplanner/graph_builder/module/GtfsModuleTest.java
src/test/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessorTest.java
src/test/resources/testagency/trips.txt

This PR also returns frequency-based trips when getting all trips in `TripPattern#scheduledTripsAsStream`. This means that when computing geometries the frequency trips are also included.
Fixes #4202
added.
autoformatted.
n/a

Fix geometries for frequency-based trips [changelog skip]

---

src/client/js/otp/config.js
src/client/js/otp/core/Map.js
src/client/js/otp/modules/multimodal/MultimodalPlannerModule.js
src/client/js/otp/modules/planner/PlannerModule.js

- When restoring the debug UI from a URL zoom to the bounds of the first itinerary returned.
- Store the selected map layer in the URL and restore the selected layer, too.
n/a
n/a
autoformatted.
cc @FrancoisG-WIMT

When restoring debug UI from URL, zoom to route bounds and keep selected map layer [changelog skip]

---

.github/pull_request_template.md
.github/workflows/automatic-changelog.yml
.github/workflows/post-merge.yml

When the label "bump serialization version" is added to a PR, then a CI job automatically bumps the serialization version id in pom.xml and pushes it to Github.
An example of what it looks like is https://github.com/leonardehrenfried/OpenTripPlanner/commit/01eb045a4ae172bb818695cde2e0ead4672c664d
Fixes #4003

Automatically bump serialization version id [changelog skip]

---

src/test/java/org/opentripplanner/routing/algorithm/mapping/TransitSnapshotTest.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap

We disabled a snapshot test when we migrated to Java 17 as the floating point arithmetic was machine-dependent. Now that we are actually rounding the floating point numbers this should no longer be a problem. :crossed_fingers:

Reactivate snapshot test

---

src/main/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModule.java

#4244 reports that sometimes a name could not be generated for a boarding location. When fixing this I also noticed that there could be cases where a duplicate vertex label was generated, which I also fixed.
closes #4244

Fix name and label for OsmBoardingLocationVertex

---

src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/filter/TransitAlertFilter.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingRequestToFilterChainMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/filter/TransitAlertFilterTest.java
src/test/java/org/opentripplanner/routing/street/BarrierRoutingTest.java
src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
src/test/java/org/opentripplanner/routing/street/CarRoutingTest.java
src/test/java/org/opentripplanner/routing/street/SplitEdgeTurnRestrictionsTest.java

Currently the transit alert mapping is spread out in multiple places in the code. Replace these by a single filter mapper.

Move transit alert mapping to itinerary filter chain

---

src/main/java/org/opentripplanner/graph_builder/issues/MissingShapeGeometry.java
src/main/java/org/opentripplanner/graph_builder/issues/ShapeGeometryTooFar.java
src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryAndBlockProcessor.java

GTFS shape geometry errors are now reported by more detailed issues.  Polyline shape generation no longer unnecessarily duplicates the issue for every stop interval - only one issue is generated.

Report better issues from shape geometry errors

---

src/main/java/org/opentripplanner/routing/core/State.java
src/main/java/org/opentripplanner/routing/core/StateEditor.java
src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java

Currently the state for the A-star algorithm uses milliseconds for time. As we always set or increment the state by full seconds, and use seconds for the weight, I simplified the code, to store the times in full seconds, similar to how RAPTOR state stores them.

Use full seconds for A-star state

---

src/ext/java/org/opentripplanner/ext/datastore/gs/GsFileDataSource.java
src/ext/java/org/opentripplanner/ext/datastore/gs/GsOutFileDataSource.java

The goal of this PR is to prevent failure to upload graph building artifacts to Google Cloud Storage due to transient network issues/ server errors as described in issue #4268
By default the Google Storage client library does not retry failed upload operations.
See https://cloud.google.com/storage/docs/retry-strategy#java for more details about which operations are retried by default.
To activate retry on error, it is necessary to make the operation "conditionally idempotent" by detecting concurrent update:
- if the blob already exists in the target bucket and must be updated: check that the blob version ("generation") did not change between the beginning and the end of the upload operation.
- if the blob does not exist yet in the target bucket and must be created: check that the blob …

Configure idempotent upload to Google Cloud Storage

---

src/main/java/org/opentripplanner/api/mapping/FareMapper.java
src/main/java/org/opentripplanner/api/mapping/ItineraryMapper.java
src/main/java/org/opentripplanner/api/model/ApiCurrency.java
src/main/java/org/opentripplanner/api/model/ApiFare.java
src/main/java/org/opentripplanner/api/model/ApiFareComponent.java
src/main/java/org/opentripplanner/api/model/ApiFareType.java
src/main/java/org/opentripplanner/api/model/ApiItinerary.java
src/main/java/org/opentripplanner/api/model/ApiMoney.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/ElevationSnapshotTest.snap
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap

In order to be able to freely change the internal fare model, I added a mapping layer between it and the REST API response.
none
I've updated the snapshot test expectation. You may have noticed that I changed the snapshot expectation: this is because I took extra care that the API response matches what is currently on dev-2.x.
It turns out that the snapshot test does a slightly different serialization of the currency as the REST API. I added annotations to make sure it does the same thing.

Add mapping layer between REST API and internal fare model

---

docs/BuildConfiguration.md
docs/sandbox/Fares.md
src/ext-test/java/org/opentripplanner/ext/fares/FaresConfigurationTest.java
src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceImpl.java
src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareService.java
src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceFactory.java
src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
src/main/java/org/opentripplanner/routing/fares/FareServiceFactory.java
src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
src/test/java/org/opentripplanner/standalone/config/BuildConfigTest.java

Adds a custom fare calculator that is being used in Houston.
It calculates prices based on a so-called free transfer window.
It also restores a feature that was probably lost when migrating to OTP2: combining interlined legs for the purpose of fare calculation. We might want to debate the semantics of this as they are not clear to me and I'm kinda guessing.
Added.
Added.
This is a port to OTP2 of the original IBI PR: https://github.com/ibi-group/OpenTripPlanner/pull/66

Add Houston fare calculator

---

docs/OTP2-MigrationGuide.md

This just fixes some parameter names in documentation.

Fix param names in docs

---

docs/sandbox/LegacyGraphQLApi.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
src/ext/resources/legacygraphqlapi/schema.graphqls

Implements allowedBikeRentalNetworks while deprecating it in legacy GraphQL API and adds allowedVehicleRentalNetworks and bannedVehicleRentalNetworks.
Minor sandbox change so not needed.
Not needed
Updated in sandbox

Vehicle rental network whitelisting and banning for legacy API

---

pom.xml

Updated from 2.13.2 to 2.13.3. Intellij complained.
No.

Update Jackson to 2.13.3, fix security vulnerability

---

src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java

Adds null checks to avoid NPEs when there are no services for a date.
closes #4291
Should they be added somewhere?
Not needed
Not needed

Fix npe when no services for a date

---

docs/sandbox/LegacyGraphQLApi.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPlaceImpl.java

Filters place types in legacy GraphQL API so that a bike park type is not returned if a vehicle parking has no bicycle spaces and car park type is not returned if a parking has no car spaces.
No issue as minor sandbox adjustment
No
No
Added for sandbox

Filter out parks with no bike/car spaces for legacy type

---

src/main/java/org/opentripplanner/model/plan/Itinerary.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/filter/RemoveDeletionFlagForLeastTransfersItinerary.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/filter/GroupByFilterTest.java

Last week I was debugging a problem with the filter chain and I was wondering why my previously flagged itinerary was still included in the result.
Then the penny dropped: there is a filter that undeletes itineraries again!
This PR makes this explicit so that in the future debugging becomes a little easier.
n/a
Tests adjusted.

Make it explicit when an itinerary's deletion flags are removed

---

src/ext/java/org/opentripplanner/ext/accessibilityscore/AccessibilityScoreFilter.java
src/ext/java/org/opentripplanner/ext/flex/FlexibleTransitLeg.java
src/main/java/org/opentripplanner/model/Timetable.java
src/main/java/org/opentripplanner/model/plan/Leg.java
src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/frequency/FrequencyBoardOrAlightEvent.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
src/main/java/org/opentripplanner/routing/trippattern/TripTimes.java
src/main/java/org/opentripplanner/updater/GtfsRealtimeMapper.java
src/main/java/org/opentripplanner/updater/stoptime/TimetableSnapshotSource.java
src/main/proto/gtfs-realtime.proto
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilterTest.java

This allows the wheelchair accessibility of trips to be updated using GTFS-realtime. To do so the wheelchair accessibility information is added to `TripTimes`.
The proto changes are proposed in https://github.com/google/transit/pull/340
BKK (Budapest, Hungary) has a GTFS-realtime TripUpdates feed which includes these values ([txt](https://go.bkk.hu/api/query/v1/ws/gtfs-rt/full/TripUpdates.txt) / [pb](https://go.bkk.hu/api/query/v1/ws/gtfs-rt/full/TripUpdates.pb))
closes #4252 
The existing filtering unit tests are updated.
No changes.

Support real-time updated wheelchair accessibility for trips

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLAPI.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
src/main/java/org/opentripplanner/api/common/RoutingResource.java
src/main/java/org/opentripplanner/index/IndexAPI.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
src/main/java/org/opentripplanner/routing/api/request/RoutingRequest.java
src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
src/main/java/org/opentripplanner/standalone/OTPMain.java
src/main/java/org/opentripplanner/standalone/api/HttpRequestScoped.java
src/main/java/org/opentripplanner/standalone/api/OtpServerContext.java
src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
src/main/java/org/opentripplanner/standalone/configure/OTPAppConstruction.java
src/main/java/org/opentripplanner/standalone/configure/OTPApplicationFactory.java
src/main/java/org/opentripplanner/standalone/server/DefaultServerContext.java
src/main/java/org/opentripplanner/standalone/server/MetricsLogging.java
src/main/java/org/opentripplanner/standalone/server/OTPWebApplication.java
src/main/java/org/opentripplanner/standalone/server/Router.java
src/main/java/org/opentripplanner/util/time/DurationUtils.java
src/test/java/org/opentripplanner/TestServerContext.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/SnapshotTestBase.java
src/test/java/org/opentripplanner/routing/street/BarrierRoutingTest.java
src/test/java/org/opentripplanner/routing/street/BicycleRoutingTest.java
src/test/java/org/opentripplanner/routing/street/CarRoutingTest.java
src/test/java/org/opentripplanner/routing/street/SplitEdgeTurnRestrictionsTest.java
src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java

Make the `OtpServerContext` handle HTTP request scope. The context injected into each HTTP Resource (per HTTP request), will hold request scoped components - so it become safe to modify these and to fetch them as many times from the scope as the resource needs too - without cashing it in the resource. We will use this to enforce consistency. We use lazy-init to create expensive components in the context. If the Resource is multi-threaded it need to synchronize access to all request-scoped components.
This build on to of #4301 
Next: The OtpServerContext should only be injected into Resources, not in other places. So, we should inject the config and services used to non resource components. Then we should replace the usage of `getTransitModel()` with `getTransitService()` in all resources. …

Otp2 make otp server context req scoped

---

src/main/java/org/opentripplanner/updater/GraphUpdaterConfigurator.java
src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java

The invalid GBFS located at https://gbfs.hopr.city/api/gbfs/20 is giving IBI a bit of trouble. In order to help debugging the problem, I'd like to improve the logging of the exceptions.
If you apply this patch, then you see the following error:
```
13:51:49.569 WARN (GraphUpdaterConfigurator.java:106) Failed to setup updater GbfsVehicleRentalDataSource{url: 'https://gbfs.hopr.city/api/gbfs/20'}
java.lang.RuntimeException: Feed contains duplicate url for feed station_information. Urls: https://gbfs.hopr.city/api/gbfs/20/station_information, https://gbfs.hopr.city/api/gbfs/20/station_information
at org.opentripplanner.updater.vehicle_rental.datasources.GbfsFeedLoader.<init>(GbfsFeedLoader.java:79)
at org.opentripplanner.updater.vehicle_rental.datasources.GbfsVehicleRentalDataSource.setup(Gbf …
```

Improve logging of GBFS parsing errors

---

src/main/java/org/opentripplanner/api/mapping/AlertMapper.java
src/main/java/org/opentripplanner/routing/alertpatch/TransitAlert.java

In GTFS-RT the transit alert start/end dates are optional but the API mapper throws an error when this is actually the case:
```
11:59:08.649 ERROR (PlannerResource.java:103) System error
java.lang.NullPointerException: Cannot invoke "java.time.Instant.toEpochMilli()" because "instant" is null
at java.base/java.util.Date.from(Date.java:1363)
at org.opentripplanner.api.mapping.AlertMapper.mapToApi(AlertMapper.java:44)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at …
```

Take nullable transit alert dates into account

---

src/main/java/org/opentripplanner/model/StreetNote.java
src/main/java/org/opentripplanner/routing/services/notes/MatcherAndStreetNote.java
src/test/java/org/opentripplanner/ConstantsForTests.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/ElevationSnapshotTest.snap
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java

The Portland graph used for testing doesn't have any way properties set. Once way properties were added to the graph, the round trip serialization failed due to the `StaticStreetNoteService` which used a `Map<Edge, ...>` to store the notes. So the related fields are now ignored.
With these changes:
* the Portland test graph has differing street types (and better resembles a _real_ graph)
* the graph round-trip serialization test passes
* and interning `StreetNote`s is fixed
The way properties were needed for adding tests for #4317

Use way-properties for the Portland test graph

---

docs/sandbox/LegacyGraphQLApi.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
src/main/java/org/opentripplanner/model/StopPattern.java
src/main/java/org/opentripplanner/model/TimetableSnapshot.java
src/main/java/org/opentripplanner/model/TripPattern.java

Includes departures with skipped stops for stopTimesForPattern query in the legacy GraphQL API. If a realtime update contains skipped stops, a new pattern with a new code is created but it makes sense to include the stop times from the new pattern in the query for the original pattern.
Contains a few new methods in non-sandbox code.
Minor sandbox improvement so no issue
None
Not needed
Added for sandbox

Include trips with skipped stops in stopTimesForPattern query

---

src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalStation.java
src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalSystem.java
src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalVehicle.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFreeVehicleStatusMapper.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsStationStatusMapper.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsSystemInformationMapper.java

Sadly there are many invalid GBFS feeds out there which send an incorrect timezone.
Examples:
- https://gbfs.hopr.city/api/gbfs/20/system_information
- https://gbfs.spin.pm/api/gbfs/v1/atlanta/system_information
Unfortunately, the validator doesn't validate this yet: https://github.com/MobilityData/gbfs-validator/issues/76
This causes OTP to completely reject the feed.
Since we actually don't really need the timezone I've skipped parsing it and using an `Instant` instead.

Remove parsing of GBFS timezones

---

src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java
src/ext-test/java/org/opentripplanner/ext/vectortiles/StopsLayerTest.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
src/ext/java/org/opentripplanner/ext/parkAndRideApi/ParkAndRideResource.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerBuilder.java
src/main/java/org/opentripplanner/api/mapping/StopMapper.java
src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
src/main/java/org/opentripplanner/index/IndexAPI.java
src/main/java/org/opentripplanner/routing/RoutingService.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/routing/graphfinder/DirectGraphFinder.java
src/main/java/org/opentripplanner/routing/graphfinder/NearbyStop.java
src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java
src/main/java/org/opentripplanner/transit/model/site/Stop.java
src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
src/main/java/org/opentripplanner/transit/service/StopModelIndex.java
src/main/java/org/opentripplanner/transit/service/TransitModel.java
src/main/java/org/opentripplanner/transit/service/TransitService.java
src/test/java/org/opentripplanner/routing/TestHalfEdges.java
src/test/java/org/opentripplanner/routing/graph/RoutingServiceTest.java
src/test/java/org/opentripplanner/routing/graphfinder/DirectGraphFinderTest.java
src/test/java/org/opentripplanner/routing/graphfinder/StreetGraphFinderTest.java

Currently we index `Stop`s in two places, `StreetVertexIndex` and `StopModelIndex`. This removes the first usage, and converts all to use the one in `StopModelIndex`. Also, it changes from indexing `TransitStopVertex ` to indexing `Stop`s

Remove duplicate stop index from Graph

---

.github/workflows/performance-test.yml

Since the speed tests are a lot slower now that I have added another data set, I'm tuning the config so that Norway runs first.
Also, we don't want to run the speed test for commits that just bump the serialization version.
I will use my admin priviledges to merge this without review.

Run Norway first in the speed test, don't run for version bumps

---

src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoader.java

Right now if an exception is thrown during download of GBFS data, the input stream is not closed causing a resource leak. How bad this is is actually up for debate but I'm investigating a production issue that could be related.
Maybe related to #2811
n/a

Use try-with-resources for GBFS loading, improve logging

---

test/performance/baden-wuerttemberg/build-config.json
test/performance/norway/build-config.json

Due to #4355, we can't build the speed test graphs since https://github.com/opentripplanner/OpenTripPlanner/pull/4320 was merged. Fix the issue by hardcoding the time zones.

Explicitly set timezones for speed test

---

src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
src/test/java/org/opentripplanner/transit/model/network/TripPatternTest.java

After merging #4338 the graph build runs into the following error:
```
15:47:57.452 INFO (TripPatternNamer.java:73) Generating unique names for stop patterns on each route.
15:47:57.467 ERROR (OTPMain.java:59) An uncaught error occurred inside OTP: Name has already been set
java.lang.IllegalStateException: Name has already been set
at org.opentripplanner.transit.model.network.TripPattern.initName(TripPattern.java:114)
at org.opentripplanner.graph_builder.module.TripPatternNamer.generateUniqueNames(TripPatternNamer.java:151)
at org.opentripplanner.graph_builder.module.TripPatternNamer.buildGraph(TripPatternNamer.java:32)
at org.opentripplanner.graph_builder.GraphBuilder.run(GraphBuilder.java:167)
at org.opentripplanner.standalone.OTPMain.startOTPServer(OTPMain.java:140)
at …
```

Fix init of trip pattern name

---

src/main/java/org/opentripplanner/graph_builder/module/TripPatternNamer.java

After https://github.com/opentripplanner/OpenTripPlanner/commit/bae9de1b8d7a52ce0628e9ed34a310bee1058ba2 we make sure that the pattern name is only set once. Some Netex feeds provide names for the JourneyPatterns, so that we need to filter out the patterns that already have a name set. Previously we would have overridden these, causing an error after the commit was included.

Do not try to rename patterns with already existing names

---

src/main/java/org/opentripplanner/transit/service/StopModel.java

When there is only FlexStopLocations in the graph then building the graph fails as the center point of the transit stops cannot be computed.
To solve it I'm checking if there are any vertices in the list before computing.

Fix building of graphs with only FlexStopLocations

---

src/ext/java/org/opentripplanner/ext/vehicletostopheuristics/VehicleToStopSkipEdgeStrategy.java

When investigating #4351 I noticed that sometimes stops are visited twice by A* so the counting of the maximum score for the VehicleToStopHeuristics were incorrect.
Fixes #4351.
cc @hbruch

Count stops only once in VehicleToStopHeuristics

---

src/main/java/org/opentripplanner/routing/core/TemporaryVerticesContainer.java
src/test/java/org/opentripplanner/routing/algorithm/StreetModeLinkingTest.java

If the origin and destination share any vertices, the user is already at their destination, and the result is a trivial path.
Closes #4350

Throw RoutingValidationException if origin and destination are the same

---

src/ext/java/org/opentripplanner/ext/vehicletostopheuristics/VehicleToStopSkipEdgeStrategy.java
src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java

A user has reported that she cannot find the Bike + Ride route that she is looking for.
She deactivated the subway mode and wanted to cycle directly to the faster suburban train, like this:
However, she received no route because the search was terminated earlier due to the allowed modes not being respected.
This fixes that problem.

Take allowed modes in VehicleToStopHeuristics into account

---

src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/FlexAccessEgressAdapter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitLayer.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferIndexGenerator.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferPointForPatternFactory.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/AccessEgressMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransfersMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TripPatternMapper.java
src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
src/main/java/org/opentripplanner/transit/model/site/FlexLocationGroup.java
src/main/java/org/opentripplanner/transit/model/site/FlexStopLocation.java
src/main/java/org/opentripplanner/transit/model/site/Stop.java
src/main/java/org/opentripplanner/transit/model/site/StopLocation.java
src/main/java/org/opentripplanner/transit/service/StopModelIndex.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearchTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestRouteData.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestTransitCaseData.java
src/test/java/org/opentripplanner/transit/service/StopIndexMock.java

Currently we have a separate StopIndex , that is created runtime, in order to be able to create patterns for RAPTOR in graph build, we need to add these indices to the transit mode. This PR does that.
Part of #4002

Add Stop Location index to transit model

---

src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java

This PR solves a bug which caused transmodel GraphQL **trip** query results to not contain any realtime data despite that OTP did register those updates and they are available through **serviceJourney** query.
`closes #4341 `
No new unit tests added
No new documentation added

Bugfix for missing realtime problem

---

src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
src/ext-test/java/org/opentripplanner/ext/flex/UnscheduledTripTest.java
src/main/java/org/opentripplanner/gtfs/RepairStopTimesForEachTripOperation.java

Right now there is a feature to "repair" GTFS trips which contain nonsensical data. Among the checks there is one for trips that contain fewer than two stops. In a regular static GTFS trip this makes sense but in flex trip this is actually valid so this "repair" should not happen for flex trips.
Note: I spoke to the OTP team at IBI and they are in favour of disabling this repair module by default. 
n/a
Added.

Fix stop time repair for trips with single flex stop

---

docs/sandbox/TransmodelApi.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLTripImpl.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/DatedServiceJourneyType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/ServiceJourneyType.java
src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
src/main/java/org/opentripplanner/routing/TripTimesShortHelper.java
src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
src/main/java/org/opentripplanner/transit/service/TransitService.java

Fix NPE in the Transmodel API, and expose the necessary information via the DatedServiceJourney type instead.
Currently we get an error, if we try to fetch scheduled stops for a trip, which is created by the realtime updater.

Do not crash Transmodel API when pattern for trip is not found

---

src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
src/main/java/org/opentripplanner/transit/service/StopModel.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/support/AssertSpeedTestSetup.java

This PR fixes an issue with the SpeedTest failing, because the StopModelIndex is not initialized. This is a bug make the CI SpeedTest fail, so it is good to fix it ASP, then I will make a better cleanup in the #4371.
No.
No.
I have added more logging to the OTP build/startup and an assertions that prevent the SpeedTest from running if no transit data exist. The assertion comes with a good explanation to what might be wrong and what config parameters to check(it prints the values as well). I think this is better than writing more doc.

Otp2 patch ci test

---

src/client/js/otp/modules/planner/ItinerariesWidget.js

The API returns `alerts` for non-transit legs, but those are currently not display in the debug client. With these changes, alerts are shown for all leg types.

debug-client: display street notes

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleWithOffset.java
src/main/java/org/opentripplanner/routing/graphfinder/NearbyStop.java

This avoids an NPE and corrects the format string in `toString()` methods.

Correct toString() methods for NearbyStop, TripScheduleWithOffset

---

pom.xml
src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java

There are three bugs in the Transmodel API that this fixes
- Coercion is run twice (https://github.com/graphql-java/graphql-java/issues/2819) 
- Update to graphql-java 18.3
- `MonoOrMultiModalStation` is no longer a `TransitEntity`, which caused a cast exception. Fix the cast
- `Duration.ofSeconds` takes a `Long` as input, fix the cast

Fix bugs in Transmodel API

---

src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/VehicleRentalDataSourceFactory.java

Enable user to configure "vilkku" as a bike-rental updater (build-config.json).
This PR contains commit which accidentally was left out from previous PR https://github.com/opentripplanner/OpenTripPlanner/pull/4381 - although it was included in the build which manual testing was done against.
- Test suite passes.

Add missing bike rental service configuration 'vilkku' to data source factory

---

src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
src/main/java/org/opentripplanner/model/Timetable.java
src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
src/test/java/org/opentripplanner/routing/trippattern/TripTimesTest.java

Improve logging in following places
- Calculate duration properly in `ElevationModule`, as it can take tens of minutes. Also log when the tracked period ends. It can take tens of seconds to do the rest of the processing.
- Do not log error in `TripTimes#timesIncreasing`. Instead return the erroneous stop index, and use it in the parent to log the invalid stop index.

Improve logging

---

CODE_CONVENTIONS.md
docs/sandbox/SiriUpdator.md

This PR updates the naming conventions for builder (discussed in yesterdays dev meeting) and package structure described in issue #4285.
Document the package naming convention part of #4285. I will update the issue, referencing the code conventions after this PR is merged. 
No.
Yes.

Otp doc update

---

src/main/java/org/opentripplanner/common/RepeatingTimePeriod.java
src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderFactory.java
src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OSMDatabase.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/openstreetmap/OSMOpeningHoursParser.java

Skip Opening hours if no time-zone configured. Log a warning, that timeZone should be added to the build config.
closes #4355
Migrated
To exclude the PR from the changelog add the label `skip changelog` to the PR.
If you have made changes to the way the routing graph is serialized, for example by renaming a field
in one of the edges, then you must add the label `bump serialization id` to the PR. With this label
Github Actions will increase the field `otp.serialization.version.id` in `pom.xml`.

Skip opening hours if no time-zone configured

---

src/ext-test/java/org/opentripplanner/ext/flex/ScheduledDeviatedTripTest.java
src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
src/main/java/org/opentripplanner/graph_builder/module/ValidateAndInterpolateStopTimesForEachTrip.java
src/main/java/org/opentripplanner/gtfs/RepairStopTimesForEachTripOperation.java
src/main/java/org/opentripplanner/netex/NetexModule.java
src/test/java/org/opentripplanner/gtfs/GtfsContextBuilder.java

In https://github.com/opentripplanner/OpenTripPlanner/pull/4385#discussion_r948031481 I was asked to rename this class, so I pulled it separately. At the same time I applied some cleanups to it, and added it to the `NetexModule`, but without interpolation. Currently it will only filter invalid trips and generate issues in the issue store for suspicious trips for NeTEx bundles.

Rename and clean up RepairStopTimesForEachTripOperation

---

docs/sandbox/MapboxVectorTilesApi.md
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java

* Adds routes' gtfsType to stop vector tiles so we can draw stops differently when routes with certain submodes go through them
* Removed patterns from stop vector tiles
Sandbox changes so not needed.
We don't have tests for this?
Not needed
Updated sandbox documentation

Digitransit stop vector layer updates

---

src/main/java/org/opentripplanner/transit/model/timetable/Trip.java
src/test/java/org/opentripplanner/transit/model/timetable/TripTest.java

In https://github.com/opentripplanner/OpenTripPlanner/pull/4189, we accidentally removed the feature of copying the NeTEx submode from the route to the trip, if it is not set in the trip. Re-enable this feature.
Added test for behaviour of copying all necessary fields from the route to the trip.

Re-enable copying of submode to trip from route

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternForDate.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TripPatternForDateMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RoutingRequestTransitDataProviderFilter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDates.java
src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/SystemErrDebugLogger.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/besttimes/BestTimes.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/besttimes/SimpleBestNumberOfTransfers.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/heuristics/HeuristicsAdapter.java
src/main/java/org/opentripplanner/transit/raptor/service/DebugHeuristics.java
src/main/java/org/opentripplanner/util/lang/IntUtils.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TestRouteData.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/ResultPrinter.java

Even tough we are in process of moving to a new transit model, I noticed some possibilities of optimizing the RAPTOR adapter, after recent profiling. I also added some more statistics to be output from the SpeedTest
```
dev-2.x
Worker: 
==> mc_destination : [  478,  471,  470,  470,  470,  472,  470,  470,  470,  470 ] Avg: 471.1 Min:  470 Max:  478 Std dev:  2.4
Total:  
==> mc_destination : [  775,  753,  752,  751,  752,  754,  751,  751,  751,  751 ] Avg: 754.1 Min:  751 Max:  775 Std dev:  7.0
Use TIntList for offsets
Worker: 
==> mc_destination : [  475,  465,  462,  460,  476,  471,  466,  462,  460,  464 ] Avg: 466.1 Min:  460 Max:  476 Std dev:  5.6
Total:  
==> mc_destination : [  772,  729,  739,  737,  768,  757,  751,  738,  736,  744 ] Avg: 747.1 Min:  729 Max:  772 Std dev: …
```

Optimize RAPTOR adapter layer

---

src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializer.java
src/test/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializerTest.java

Currently an error is thrown if we receive a leg reference created with an older version of OTP. Fix this by allow lenient paring of service dates.

Allow parsing of legacy leg references

---

src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceImpl.java
src/main/java/org/opentripplanner/transit/model/site/RegularStop.java
src/main/java/org/opentripplanner/transit/model/site/StopLocation.java

When profiling with a dataset including GTFS-fares, i noticed that a large share of time was spent in calculating fares. In couple of places we could easily simplify to get some performance benefits.

Performance improvements for DefaultFareServiceImpl

---

src/main/java/org/opentripplanner/transit/raptor/api/response/StopArrivals.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/internalapi/Heuristics.java

Small code doc change to Raptor.
Related to #4410
Not relevant
✅

doc: Document why unused parameters in Raptor API should NOT be deleted.

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingResponseMapper.java

This happens eg. when forward search fails, and no search window/earliest departure time can be set.
Related to #4396

Do not crash if PageCursorFactory can't be created

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/performance/PerformanceTimersForRaptor.java
src/main/java/org/opentripplanner/transit/raptor/api/debug/RaptorTimers.java
src/main/java/org/opentripplanner/transit/raptor/service/HeuristicSearchTask.java

We need to modify the `PerformanceTimersForRaptor` in `HeuristicSearchTask` in order to contain the proper name for the search profile. 
Fixes #4302

Update heuristic profile name in performanceTimers

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/RaptorTransferIndex.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearch.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitData.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/RangeRaptorWorker.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/McStopArrivals.java

As with #4412, I noticed we spend quite lot of time in creating objects, which are not needed. This removes the instantiation of those objects.

Avoid creating unneeded objects in RAPTOR

---

docs/sandbox/VehicleParking.md
src/ext-test/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdaterTest.java
src/ext-test/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdaterTest.java
src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkToVehicleParkingMapper.java
src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdater.java
src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdaterParameters.java
src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/BicycleParkAPIUpdater.java
src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/CarParkAPIUpdater.java
src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdater.java
src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdaterParameters.java
src/main/java/org/opentripplanner/standalone/config/updaters/VehicleParkingUpdaterConfig.java
src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingDataSourceFactory.java

Adds `timeZone` parameter to HSL and parkapi updaters to determine the time zone for the opening hours. 
fixes #4428 
Updated tests.
Updated sandbox documentation.
Added for sandbox

Add timeZone parameter to hsl and parkapi vehicle parking updaters

---

src/main/java/org/opentripplanner/transit/service/StopModelIndex.java

The spatial index for `RegularStops` also contains other types of stops which causes `ClassCastExceptions` when you try to use the index. This fixes that.

Only index instances of RegularStop

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/AccessEgress.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TransferWithDuration.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/AbstractRaptorTransfer.java
src/main/java/org/opentripplanner/transit/raptor/util/ReversedRaptorTransfer.java

While profiling, I noticed that we spend quite a lot of time querying three fields from `RaptorTransfer`s. Currently we have multiple implementations of this interface, which makes `itable stub` quite a prominent part of the profile. This PR extracts the three fields used into an abstract class, which defines the getters as final, making it possible for JDK to create optimized bytecode.
```
Before
Round 1
Worker: 
==> mc_destination : [  490,  478,  487,  473,  483,  472,  467,  469,  474,  478 ] Avg: 477.1  (σ=7.2)
Total:  
==> mc_destination : [  738,  709,  731,  694,  711,  711,  697,  683,  688,  700 ] Avg: 706.2  (σ=16.8)
Round 2
Worker: 
==> mc_destination : [  472,  471,  471,  472,  470,  471,  469,  470,  470,  470 ] Avg: 470.6  (σ=0.9)
Total:  
==> mc_destination : [  704, …
```

Extract AbstractRaptorTransfer to improve performance

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/DefaultRoutingRequestType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
src/main/java/org/opentripplanner/api/common/RoutingResource.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgressRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
src/main/java/org/opentripplanner/routing/api/request/framework/DurationForEnum.java
src/main/java/org/opentripplanner/routing/api/request/preference/StreetPreferences.java
src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
src/main/java/org/opentripplanner/standalone/config/RoutingRequestMapper.java
src/test/java/org/opentripplanner/routing/api/request/framework/DurationForEnumTest.java

To fix this problem a utility method is added to the DurationForEnum witch does the downcast to int. To make the utility method available everywhere the StreetPreferences is changed, so it exposes the DurationForEnum type.
No issue exist
A unit tests is updated
Not changed

fix: TransmodelAPI fails to downcast board- and alight-slack

---

src/main/java/org/opentripplanner/common/pqueue/BinHeap.java
src/main/java/org/opentripplanner/routing/algorithm/astar/AStar.java
src/main/java/org/opentripplanner/routing/spt/ShortestPathTree.java

Currently the A* priority queue is always initialized to the same size, depending on the graph. We should set it differently depending on the context (access/egress or direct search). This PR makes that possible by moving the parameter from being hardcode to setting it in the SystemPreferences.
Also, we want to remove the RoutingContext (done in https://github.com/opentripplanner/OpenTripPlanner/pull/4432), so the property needs to be accessible form the routing request.

Hardcode initial capacities for a* search

---

docs/examples/skanetrafiken/Readme.md
docs/examples/skanetrafiken/router-config.json
docs/sandbox/SiriAzureUpdater.md
src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureUpdaterParameters.java
src/main/java/org/opentripplanner/standalone/config/updaters/azure/SiriAzureUpdaterConfig.java

Add feature switch for matching ET messages on stops
closes #4346 
No new unit tests added

Add feature switch for matching ET messages on stops

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareService.java
src/main/java/org/opentripplanner/api/mapping/FareMapper.java
src/main/java/org/opentripplanner/routing/core/ItineraryFares.java
src/test/java/org/opentripplanner/api/mapping/FareMapperTest.java

The Houston fare calculator in OTP1 produces fares that returned `null` instead of the empty list for the `fareConponents` object. Together with the rewrite of the API mapper code this led to an NPE when writing out the API response.
This PR deals with the null (as opposed to the empty list).
@miles-grant-ibigroup @optionsome This PR restores the `null` output but if we could return the empty list instead the code could be streamlined. Would that cause problems in your frontends?
Tests added.
n/a

Take into account null values for fare details

---

docs/sandbox/TransmodelApi.md
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/BannedInputType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/JourneyWhiteListed.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java

Allow specifying allowed/banned rental networks in the Transmodel API
Closes #4087

Allow specifying allowed/banned rental networks in the Transmodel API

---

src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java
src/main/java/org/opentripplanner/transit/service/TransitModel.java

This is a very simple PR that improves the error message when you have multiple time zones in your transit data. 
This makes it easy to figure out if there is a real problem or just a superficial like using both `America/New_York` and `US/Eastern`.
It also adds the number of constrained transfers to the graph entity size output, as this is important when debugging performance problems.

More graph stats, better exception message

---

src/main/java/org/opentripplanner/transit/model/basic/NonLocalizedString.java
src/main/java/org/opentripplanner/transit/model/framework/Deduplicator.java
src/test/java/org/opentripplanner/routing/trippattern/DeduplicatorTest.java

This PR add support for generic type arrays to the Deduplicator. This is needed in the #4450 
The Deduplicator unit test is updated.
No doc added.

Add support for Deduplicator generic object arrays

---

src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
src/main/java/org/opentripplanner/standalone/config/NodeAdapter.java
src/main/java/org/opentripplanner/standalone/config/OtpConfig.java
src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
src/test/java/org/opentripplanner/standalone/config/NodeAdapterTest.java

When we parse configuration accessing the same configuration node more than one time will cause the NodeAdaptor to report unused parameters, because a new NodeAdaptor is created every time a node is accessed. This PR look up if the 
node is accessed before and in that case return the existing NodeAdaptor.
This also remove an unused method and remove the dependency from NodeAdaptor to a specific log framework.
I also changed the log output, since it is usually not the spelling that is the problem. 
From:
```
Unexpected config parameter: 'foo.bar:false' in 'router-config.json'. Is the spelling correct?
```
To:
```
Unexpected config parameter: 'foo.bar:false' in 'router-config.json'
```
Unit tests are added.

Allow the same config node to be accessed twice

---

src/main/java/org/opentripplanner/graph_builder/module/GtfsModule.java
src/main/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessor.java
src/test/java/org/opentripplanner/graph_builder/module/GtfsModuleTest.java

When importing several GTFS feeds where one of them uses block-based interlining then all following imports regenerate the stay-seated transfers for all of the previous feeds. This leads to a huge number of constrained transfers which is terrible for performance.
Fixes #4467.
Test added.

Fix block-based interlining when importing several GTFS feeds

---

src/main/java/org/opentripplanner/transit/model/framework/FeedScopedId.java
src/main/java/org/opentripplanner/transit/model/organization/Agency.java
src/main/java/org/opentripplanner/transit/model/organization/Operator.java
src/main/java/org/opentripplanner/util/lang/StringUtils.java
src/test/java/org/opentripplanner/util/lang/StringUtilsTest.java

This PR improves the error message that OTP produces when asserting that an input data field is neither null nor empty.
The StringUtils.assertHasValue() is overloaded with a new method that takes a message format and message placeholders as optional parameters. They can be used to provide context-specific information in the error message.
No
Updated StringUtilsTest.assertValueExist()
No

Add error message for value assertion

---

src/main/java/org/opentripplanner/updater/stoptime/GtfsRealtimeHttpTripUpdateSource.java

When a GTFS-RT feed returns a 404 OTP doesn't log anything. Is was quite confusing to debug so I added an error message for this case.

Add error message when GTFS-RT feed returns 404

---

src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java

When an added trip specifies a different TransportMode than its referenced Line/Route, TransportMode needs to be set on the Trip-object.

Setting transportmode on added Trip 

---

docs/BuildConfiguration.md
docs/sandbox/Fares.md
src/ext-test/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/FaresConfiguration.java
src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareService.java
src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceFactory.java
src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceImpl.java
src/main/java/org/opentripplanner/routing/core/FareType.java

This is a port of IBI's OTP1 fare calculator for Atlanta, originally written by @daniel-heppner-ibigroup. It's almost entirely sandbox code apart from adding some fare types. I'm not sure if that is a controversial change. (With Fares V2 these fare types become obsolete.)
Added.
Added.
cc @demory

Atlanta fare service

---

src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdaterParameters.java
src/main/java/org/opentripplanner/standalone/config/updaters/SiriETGooglePubsubUpdaterConfig.java
src/main/java/org/opentripplanner/util/lang/ToStringBuilder.java
src/test/java/org/opentripplanner/util/lang/ToStringBuilderTest.java

This PR enable us to configure the initial timeout for fetching Siri-ET Google Pubsub messages. The default is 30 seconds.
No issue for this.
Unit tests updated.
These parameters are not documented.

Add initial get data timeout to SiriETGooglePubsubUpdater

---

docs/Configuration.md

This PR documents general recommendations on JVM tuning in a production environment.
No
No
Updated Configuration.md

Document JVM configuration options

---

docs/BuildConfiguration.md
src/main/java/org/opentripplanner/datastore/api/DataSource.java
src/main/java/org/opentripplanner/datastore/configure/DataStoreModule.java
src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceMetadata.java
src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceRepository.java
src/main/java/org/opentripplanner/datastore/https/HttpsFileDataSource.java
src/main/java/org/opentripplanner/util/HttpUtils.java
src/test/java/org/opentripplanner/datastore/https/HttpsDataSourceRepositoryTest.java
src/test/java/org/opentripplanner/datastore/https/HttpsFileDataSourceTest.java

This PR implements support for reading data sources from an HTTPS resource.
The data source provides only read operations.
Implements #4481
Updated BuildConfiguration.md

Add support for HTTPS datasource for Graph Building

---

docs/sandbox/ReportApi.md
src/ext/java/org/opentripplanner/ext/reportapi/model/GraphReportBuilder.java
src/ext/java/org/opentripplanner/ext/reportapi/model/TransfersReport.java
src/ext/java/org/opentripplanner/ext/reportapi/resource/ReportResource.java
src/main/java/org/opentripplanner/common/model/CachedValue.java

This adds a JSON endpoint which contains detailed statistics for the graph.
The output looks like this:
```
{
"street": {
"edges": {
"total": 7943430,
"types": {
"vehicleParkingEdge": 8014,
"streetTransitStopLink": 253432,
"areaEdge": 118628,
"elevatorHopEdge": 132,
"streetVehicleParkingLink": 1372,
"boardingLocationToStopLink": 36,
"streetEdge": 7561098,
"streetTransitEntranceLink": 82,
"elevatorAlightEdge": 159,
"freeEdge": 318,
"elevatorBoardEdge": 159
}
},
"vertices": {
"total": 3154188,
"types": {
"vehicleParkingEntranceVertex": 681,
"osmBoardingLocationVertex": 44,
"transitStopVertex": 76573,
"elevatorOffboardVertex": 159,
"exitVertex": 3212,
"barrierVertex": 1247,
"splitterVertex": 94660,
"osmVertex": 2977431,
"elevatorOnboardVertex": 159,
"transitEntranceVertex": 22
}
}
}, …
```

Add detailed graph statistics report

---

src/main/java/org/opentripplanner/datastore/api/DataSource.java
src/main/java/org/opentripplanner/datastore/file/AbstractFileDataSource.java
src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceMetadata.java
src/test/java/org/opentripplanner/datastore/file/DirectoryDataSourceTest.java
src/test/java/org/opentripplanner/datastore/file/FileDataSourceTest.java

This PR do a little cleanup of DataSource size and lastModified. It is based on #4482, and is a response to https://github.com/opentripplanner/OpenTripPlanner/pull/4482#discussion_r985545969. 
My original suggestion was to use `OptionalLong` to make the API safer, but that get a bit messy - mostly since most of the underlaying libraries already support returning `-1` as an `UNKNOW` value. So the changes I made are only to remove the `magic numbers`.
I also made on class in the http support package local.
No issue
Unit tests are updated.
JavaDoc ok.

Otp2 use optional in data source

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/TimetabledPassingTimeType.java
src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java

Currently we don't import `JourneyPattern`s with flex stops from NeTEx files. The support for adding these, as well as the corresponding change in GTFS handling was done in https://github.com/opentripplanner/OpenTripPlanner/pull/3757.

Remove filtering of flex patterns in NeTEX import

---

src/ext/java/org/opentripplanner/ext/reportapi/model/BicycleSafetyReport.java
src/main/java/org/opentripplanner/graph_builder/module/osm/HoustonWayPropertySetSource.java
src/main/java/org/opentripplanner/graph_builder/module/osm/WayProperties.java
src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertyPicker.java
src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySet.java
src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java
src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
src/test/java/org/opentripplanner/graph_builder/module/osm/HoustonWayPropertySetSourceTest.java

This adds a custom way property set for Houston where we want to remove indoor tunnels that connect buildings. These are rarely public and cause issues when a stop is linked to them.
I noticed a problem (?) where the specifier `highway=footway;layer=-1;tunnel=yes;indoor=yes` is quite greedy and matches things that are not footways so I had to add other permutations which, in my view, should not be necessary. I will investigate more and open an issue if I think it's a bug.
I also did some gentle refactoring. 
Added.
Added.

Add Houston WayPropertySet

---

docs/Configuration.md

Fix typo in parameter name used to activate Transparent Huge Pages.
No
No

Fix typo in JVM tuning configuration

---

src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java
src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdaterParameters.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdaterParameters.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
src/main/java/org/opentripplanner/standalone/config/updaters/SiriETGooglePubsubUpdaterConfig.java
src/main/java/org/opentripplanner/standalone/config/updaters/SiriETUpdaterConfig.java

After #4347, the fuzzyTripMatching was set to false in all SIR-ET updaters-except in the Azure updater. This PR adds the config option to other SIRI-ET updater modules, and cleans up the implementation, so that a SiriFuzzyTripMatcher is created only when the config parameter is set to true. This required some clean-up of the matcher, which is included in the PR.

Enable fuzzyTripMatching in other SIRI-ET updaters

---

src/main/java/org/opentripplanner/datastore/base/ZipStreamDataSourceDecorator.java
src/main/java/org/opentripplanner/datastore/file/AbstractFileDataSource.java
src/main/java/org/opentripplanner/datastore/file/TemporaryFileDataSource.java
src/test/java/org/opentripplanner/datastore/base/ZipStreamDataSourceDecoratorTest.java

This PR adds support for importing zip files that contain large entries ( > 2GB).
In the current implementation, zip entries are uncompressed in memory in a ByteArrayOutputStream. However ByteArrayOutputStream does not support arrays larger than MAX_INT bytes (~ 2GB).
This PR ensures that larger entries are offloaded to temporary files on disk.
Fix #4507
No.

Add support for importing zip datasets containing large entries

---

docs/sandbox/LegacyGraphQLApi.md
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLStopImpl.java
src/main/java/org/opentripplanner/index/IndexAPI.java
src/main/java/org/opentripplanner/routing/graphfinder/PatternAtStop.java
src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
src/main/java/org/opentripplanner/transit/service/TransitService.java
src/test/java/org/opentripplanner/routing/stoptimes/StopTimesHelperTest.java

Implements omitCanceled argument for some legacy graphQL stop time queries. The behavior of other APIs should remain the same.
Minor sandbox related change so no issue.
Not sure how complicated it would be to create tests for this.
No updates needed
TODO update sandbox changelog

Use omitCanceled argument for stop times queries

---

src/main/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSource.java
src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
src/test/java/org/opentripplanner/graph_builder/module/osm/WayPropertySetSourceTest.java
src/test/java/org/opentripplanner/openstreetmap/model/OSMWithTagsTest.java

Support overriding general access restrictions (`access=private`) with more specific ones (`foot=yes`).
closes #2669
Unit tests are extended.
No changes.

Specificity support for no-thru traffic restrictions

---

docs/RouterConfiguration.md
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriVMUpdater.java
src/main/java/org/opentripplanner/standalone/config/updaters/PollingStoptimeUpdaterConfig.java
src/main/java/org/opentripplanner/standalone/config/updaters/VehiclePositionsUpdaterConfig.java
src/main/java/org/opentripplanner/updater/DataSourceType.java
src/main/java/org/opentripplanner/updater/trip/PollingTripUpdater.java
src/main/java/org/opentripplanner/updater/trip/PollingTripUpdaterParameters.java
src/main/java/org/opentripplanner/updater/vehicle_position/PollingVehiclePositionUpdater.java
src/test/resources/standalone/config/router-config.json

In #4517 the field configType for GTFS-RT updaters was changed leading to users having to update their config files. This led me to investigate if the field is actually necessary and it turns out that it isn't!
Removing this field resolves a couple of long standing TODOs and will make configuration easier.
Updated.

Remove unnecessary sourceType attribute from GTFS-RT configuration 

---

src/main/java/org/opentripplanner/graph_builder/module/osm/FinlandWayPropertySetSource.java

Pull request #4515 changed OSM processing so that tags foot=yes and bicycle=yes enable traversal along ways tagged with access=private. OSM data in Finland contains so much incorrectly modeled entities that we cannot adopt the change immediately. 
In this PR,  original logic of walk and bike nothrough tag processing is restored using FinlandWayPropertySetSource.java.

Do not yet allow passthrough traffic by foot/bike=yes tags in Finland
