.github/workflows/performance-test.yml
test/performance/README.md
test/performance/baden-wuerttemberg/build-config.json
test/performance/germany/build-config.json
test/performance/norway/build-config.json

I've copied all the speed test input files onto the speed test server. They are all now available at: https://otp-performance.leonard.io/data/
This means that we can skip the caching and redownload the files for every run.

Move all speed test data onto speed test server

---

src/main/java/org/opentripplanner/transit/model/network/StopPattern.java
src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java
src/test/java/org/opentripplanner/transit/model/network/StopPatternTest.java

In https://github.com/opentripplanner/OpenTripPlanner/pull/3757 all `StopLocation`s were added to patterns. It works with RAPTOR, as area stops were always set as not allowed for boarding/alighting. The same should be done also for `GroupStops`. This changes that and adds a test to validate the behaviour

Do not allow boarding/alighting at GroupStops in RAPTOR

---

src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
src/main/java/org/opentripplanner/standalone/server/EtagRequestFilter.java
src/main/java/org/opentripplanner/standalone/server/OTPWebApplication.java
src/main/java/org/opentripplanner/standalone/server/VaryRequestFilter.java
src/test/java/org/opentripplanner/standalone/server/EtagRequestFilterTest.java

Improves the vector tile HTTP responses on slow network connections by adding ETag headers and honouring If-None-Match when sent by the client.
If anyone has an idea how I could add the filter to just the vector tile resource without checking for the content type, please let me know.
#4469 
Lots added.
cc @derhuerst

Add ETags handling to vector tile response

---

src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceRepository.java
src/main/java/org/opentripplanner/datastore/https/HttpsFileDataSource.java
src/main/java/org/opentripplanner/util/HttpUtils.java

As reported in #4552, the graph builder may fail at startup due to a read timeout while downloading from a HTTPS data source.
The default timeout, that is also used by the real time updaters, is 5s.
Testing with a real HTTPS data source shows that the latency could be up to 8s.
While it is desirable to have a short timeout for the real time updaters, this timeout can be relaxed for the graph builder where data sources are loaded only once and a timeout error would result in failing the build.
The timeout could be exposed as a configuration parameter. For simplicity, this PR simply extends the timeout for the HTTPS data sources to 20s.
Fix #4552
No

Increase connection timeout for HTTPS datasources

---

src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java

Ensure that previous real-time updates are removed when whole trip is cancelled.
This PR takes care of following edge case:
1. real-time module receives ET message for a trip (no cancellations at this point) 
new trip is create in real-time timetable.
2. real-time module receives another ET message, whole trip is cancelled
trip from scheduled timetabled changes status to CANCELLED
trip isn't removed from real-time timetable 
OTP performs new search and cancelled trip comes up as a valid result since it isn't cancelled in real-time timetable. 
- no new unit tests added
- no new documentation added

Handle cancelled trips correctly in SIRI ET module

---

src/ext/java/org/opentripplanner/ext/siri/TimetableHelper.java

If service date is present in ET message, use that data instead on calculating it based on first departure.
```
<FramedVehicleJourneyRef>
<DataFrameRef>2022-10-12</DataFrameRef>                        
<DatedVehicleJourneyRef>....</DatedVehicleJourneyRef>
</FramedVehicleJourneyRef>
```
In example above, service date should be **2022-10-12** as that's what is defined in message. We do not need to explicitly calculate it.
N/A
N/A
N/A

Read service date from ET messages

---

.github/workflows/cibuild.yml
.github/workflows/close_stale_pr_and_issues.yml
.github/workflows/performance-test.yml
.github/workflows/post-merge.yml

Github Actions is updating their node runtime version, so you see a large number of warnings to update to Actions version. Example: https://github.com/opentripplanner/OpenTripPlanner/actions/runs/3313424495
This PR updates the Actions that will stop working in the future.

Update GH Actions versions

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OSMFilter.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
src/main/java/org/opentripplanner/routing/edgetype/AreaEdgeList.java
src/main/java/org/opentripplanner/routing/edgetype/NamedArea.java
src/main/java/org/opentripplanner/routing/edgetype/StreetEdge.java
src/main/java/org/opentripplanner/routing/impl/StreetVertexIndex.java
src/test/java/org/opentripplanner/graph_builder/module/map/StreetMatcherTest.java

Remove unused StreetClasses from StreetEdge. The only class in use is the `link`, which was moved to be part of the flags

Remove unused StreetClasses from StreetEdge

---

.github/workflows/performance-test.yml
src/test/java/org/opentripplanner/transit/raptor/speed_test/SpeedTest.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/model/timer/MeterRegistrySetup.java
src/test/java/org/opentripplanner/transit/raptor/speed_test/model/timer/SpeedTestTimer.java
test/performance/README.md

Since the input data is the major factor on how fast the speed test is expected to run, I'm adding the follwoing numbers of the data set to the speed test results:
- number of stops
- trips
- patterns
and the JVM memory metrics.
Once we have that I will add it to Grafana.

Add meta data to speed test results

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLBikeParkImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLCarParkImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLVehicleParkingImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLTypes.java
src/ext/resources/legacygraphqlapi/schema.graphqls

Add translation support for parking in the legacy graphQL API.
No issue as minor sandbox change
None
Not needed
Maybe we should add a generic note to sandbox changelog about translation support?

Add translation support for parks in legacy GraphQL API

---

src/main/java/org/opentripplanner/transit/raptor/service/HeuristicToRunResolver.java
src/main/java/org/opentripplanner/transit/raptor/service/RangeRaptorDynamicSearch.java
src/test/java/org/opentripplanner/transit/raptor/service/HeuristicToRunResolverTest.java

Currently we run a forward heuristic search, if either EDT or LAT is not defined in the request. In https://github.com/opentripplanner/OpenTripPlanner/pull/3664, we changed the behaviour, so that the reverse heuristic doesn't require the LAT to be set anymore. However, we missed changing the criteria of when the search should be done. This PR changes that, so that LAT is not required anymore when the reverse heuristic search is done. Also the `RangeRaptorDynamicSearch` is fixed, as it previously expected the first search to always be the forward heuristic search.

Do not run forward heuristic to calculate LAT, it is calculated from data already

---

pom.xml

The scripts can not be in the main jar file. If included, we would not be able to release to mvn central.
This PR also rename the Maven profile `releaseMavenCentral` to `release` to be consistent with the doc and defacto naming standard. 
fixes #2634
Is up to date.
**NOTE!** This merges to `master`, so `master` MUST be merged to `dev-2.x` after this is merged. The reason we merge this to `master` and not `dev-2.x` is to be prepared to if we need to make a bugfix release.

Move scripts filtering to test-resource-plugin

---

src/test/java/org/opentripplanner/generate/doc/BuildConfigurationDocTest.java
src/test/java/org/opentripplanner/generate/doc/ConfigurationDocTest.java
src/test/java/org/opentripplanner/generate/doc/RouteRequestDocTest.java
src/test/java/org/opentripplanner/generate/doc/RouterConfigurationDocTest.java
src/test/java/org/opentripplanner/generate/doc/UpdaterConfigDocTest.java
src/test/java/org/opentripplanner/generate/doc/framework/DocsTestConstants.java
src/test/java/org/opentripplanner/generate/doc/framework/OnlyIfDocsExist.java
src/test/java/org/opentripplanner/generate/doc/framework/TemplateUtil.java
src/test/java/org/opentripplanner/standalone/config/ExampleConfigTest.java

When the unit-tests are run using the jar file, not a checked out project, then the doc folder might not be present. In this case we want to skip the doc generation, and not fail.
When fixing this I considered 3 different ways to do it:
1. Use JUnit tags, and exclude tests using Maven profile
2. Use annotation to include/exclude test
3. Check if the docs folder exist, if not exit test
I went for option 3 - the least complex one. It has the downside that you need to include
```
if(skipDocGeneration(BuildConfigurationDocTest.class)) {
return;
}
```
in every doc test (currently 5 places), but this is just slightly more code than using an JUnit annotation. There is no Maven config involved or build CI environment setup/changes needed.

test: Skip doc generation when the template file is not found.

---

src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/TransitGeneralizedCostFilter.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/TransitGeneralizedCostFilterTest.java

We recently changed the filtering to include a "waiting time" between two itineraries. While testing, we found out that this change to be more aligned with user expectations
Added test to differentiate between itineraries departing at the same time and at different times.

Use minimum diff of arrival/departure time in TransitGeneralizedCostFilter

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/DefaultAccessEgress.java
src/main/java/org/opentripplanner/transit/raptor/api/transit/RaptorAccessEgress.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapperTest.java
src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestAccessEgress.java
src/test/java/org/opentripplanner/transit/raptor/_data/transit/TestTripSchedule.java

Add cost of egress leg to the cost of the last transit leg if transit leg arrives at destination

---

src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java

Setting explicit TTL on AzureSiriUpdater subscription messages to avoid the default value which is unreasonably high.

Setting explicit TTL on AzureSiriUpdater subscription messages

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLQueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalPlacesLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalStationsLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/VehicleRentalVehiclesLayerBuilder.java
src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/VehicleRentalServiceDirectoryFetcher.java
src/main/java/org/opentripplanner/api/model/ApiRouterInfo.java
src/main/java/org/opentripplanner/api/resource/BikeRental.java
src/main/java/org/opentripplanner/routing/RoutingService.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/routing/vehicle_rental/VehicleRentalService.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/UpdatersConfig.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/PollingTripUpdaterConfig.java
src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java

This renames two classes that have a name which doesn't correctly reflect their purpose:
- `VehicleRentalStationService` is renamed to `VehicleRentalService`
- `PorllingStoptimeUpdaterConfig` is renames to `PollingTripUpdaterConfig`

Rename VehicleRentalStationService and PollingStoptimeUpdaterConfig

---

src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/main/java/org/opentripplanner/netex/mapping/OperatorToAgencyMapper.java
src/test/java/org/opentripplanner/netex/mapping/OperatorToAgencyMapperTest.java

This PR fixes #4587: when the name of an Operator is missing in a NeTEx dataset, the graph builder fails.
Since this field is not critical to journey planning, this should not prevent the graph building from completing.
This PR:
- adds an issue in the issue store when an operator name is missing.
- uses the NeTEx id of the operator as a substitute for the missing operator name.
fixes #4587
No

Add fallback for missing operator name

---

src/main/java/org/opentripplanner/routing/graph/SerializedGraphObject.java

When an I/O exception occurs while Kryo loads a serialized graph over a network connection, the error log message incorrectly suggests that the graph is binary incompatible with the current version of OTP:
`Unable to load graph. The deserialization failed. Is the loaded graph build with the same OTP version as you are using to load it? Graph: gs://marduk-production/graphs/streetGraph-otp2.obj org.opentripplanner.util.OtpAppException: Unable to load graph. The deserialization failed. Is the loaded graph build with the same OTP version as you are using to load it? Graph: gs://marduk-production/graphs/streetGraph-otp2.obj`
This PR improves the exception management by producing a specific log message for network errors.
Resulting message:
```
12:17:06.592 ERROR …
```

Improve error log message for I/O Exception during graph loading

---

test/performance/baden-wuerttemberg/speed-test-config.json
test/performance/germany/speed-test-config.json

@hannesj fixed the configuration in a previous PR but that actually led to some tests not returning results. This restores the behaviour from before that PR.

Remove configuration params of German speed tests

---

src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java

When reading in a leg from a leg reference, we don't fetch the alerts properly. This adds the functionality.

Add alerts to leg when reading in a leg reference

---

src/ext-test/java/org/opentripplanner/ext/vehicleparking/bikely/BikelyUpdaterTest.java
src/ext-test/resources/vehicleparking/bikely/bikely.json
src/ext/java/org/opentripplanner/ext/vehicleparking/bikely/BikelyUpdater.java
src/main/java/org/opentripplanner/transit/model/basic/LocalizedMoney.java

This adds the parsing of the recently added capacity information to the Bikely parking updater.
It also fixes a bug in `LocalizedMoney` which must accept `null` as a locale. :man_shrugging: 
Added.
cc @tsobuskerudbyen

Add capacity to Bikely updater

---

pom.xml
src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java

Recently we've seen random failures in the graph serialization test which started after the upgrade to slf4j 2. It seems that the internals of that library have changed and this trips up the object differ.
I think the fix would simply be to ignore the logger during the graph comparision. This is the right thing to do even if there wasn't a flaky test.

Ignore logger in graph serialization test in order to fix flaky test

---

src/main/java/org/opentripplanner/transit/raptor/rangeraptor/internalapi/HeuristicAtStop.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/internalapi/Heuristics.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/multicriteria/heuristic/HeuristicsProvider.java
src/main/java/org/opentripplanner/transit/raptor/rangeraptor/standard/heuristics/HeuristicsAdapter.java

Currently we call `Heuristics#reached` multiple times when calculating a heuristic at a stop. Optimize the creation by extracting internal versions without the check, and only do it once at the top level. Also cache the unreached stops in the array by using a static value.

Reduce the number of calls to Heuristics#reached

---

src/ext/java/org/opentripplanner/ext/traveltime/TravelTimeResource.java
src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
src/main/java/org/opentripplanner/routing/algorithm/astar/AStarBuilder.java
src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/EuclideanRemainingWeightHeuristic.java
src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/RemainingWeightHeuristic.java
src/main/java/org/opentripplanner/routing/algorithm/astar/strategies/TrivialRemainingWeightHeuristic.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/RaptorTransferIndex.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRequestTransferCache.java
src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
src/main/java/org/opentripplanner/routing/core/AStarRequestMapper.java
src/test/java/org/opentripplanner/routing/core/AStarRequestMapperTest.java

The recent move to separate `AStarRequest` and individual preference classes helps us to clean up code related to transfer requests.

Simplify TransferRequest by using AStarRequest

---

.github/workflows/cibuild.yml
doc-templates/Configuration.md
docs/Configuration.md
mkdocs.yml

This adds the CI configuration to deploy the docs from the master branch. The selected version to deploy it to is `latest` so it will end up at https://docs.opentripplanner.org/en/latest/.
After we have merged this we should also merge it back to dev-2.x.

Backport deployment of docs to master

---

doc-templates/Configuration.md
doc-templates/VehicleParking.md
docs/BuildConfiguration.md
docs/Configuration.md
docs/RouteRequest.md
docs/RouterConfiguration.md
docs/UpdaterConfig.md
docs/sandbox/VehicleParking.md
src/main/java/org/opentripplanner/framework/text/MarkdownFormatter.java
src/main/java/org/opentripplanner/standalone/config/buildconfig/NetexConfig.java
src/test/java/org/opentripplanner/generate/doc/framework/DocBuilderTest.java

This fixes an issue where the markdown generator doesn't correctly build line breaks.
The markdown syntax for this is two trailing spaces.
The PR also fixes a handfull of spelling errors.

Fix newlines in Markdown generation, spelling

---

src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TransitIdMapper.java

As described in #4646, querying a line in the GraphQL API with an empty ID generates a confusing error message.
This PR handles the special case of an empty id so that GraphQL returns a "null" value for such queries.
Fixes #4646
No

Fix empty value management in GraphQL FeedScopeID mapping

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java

This is essentially a partial revert of the following commit: https://github.com/opentripplanner/OpenTripPlanner/commit/0afeae15b3a68ff94f49e30733ef5fffb1febdd0. In particular, forBoarding and forAlighting on estimated calls in the transmodel API were forced to be true for cancelled calls. The result is that the values do not reflect the planned data (despite what the documentation said) nor the realtime data (which we would expect from the data in estimated calls).

fix: forBoarding and forAlighting on cancelled calls in transmodel api

---

src/ext/java/org/opentripplanner/ext/actuator/ActuatorAPI.java

closes #4673 by adding a wildcard `@Produces` on the `/otp/actuators/prometheus` endpoint method.

Make Prometheus endpoint take Accept header into account

---

CONTRIBUTING.md
README.md
docs/index.md

Since we decided in the last PLC meeting that Gitter is now an official channel, we can add it to documentation and project Readme.

Advertise Gitter channel in documentation [ci skip]

---

src/main/java/org/opentripplanner/graph_builder/issues/ParkAndRideUnlinked.java
src/main/java/org/opentripplanner/graph_builder/module/osm/AreaGroup.java
src/main/java/org/opentripplanner/graph_builder/module/osm/ParkingProcessor.java
src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
src/test/java/org/opentripplanner/graph_builder/module/osm/UnconnectedAreasTest.java

Right now if a parking area is not linked to the street network OTP discards it. However, it's a pretty common occurrence that no entrance ways are mapped.
This PR adds an artificial entrance vertex if none exists in OSM and then lets the street linker do the link to the centroid of the parking facility.
If it turns out that this is an unwanted default I can add a build config parameter.
Closes #1562
Added.

Add entrances to parking lots that are unconnected in OSM

---

src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/flex/trip/FlexTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/et/EstimatedCallType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/sx/PtSituationElementType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/TimetabledPassingTimeType.java

Expose:
- Service window for flex in passing times
- StopPlace in SIRI-SX situation
- SIRI-SX situations in StopPlace
Fix two bugs:
- Sort estimated calls for stop place if `numberOfDeparturesPerLineAndDestinationDisplay` is used
- Deduplicate NeTEx submodes in stop places
Improvements
- Make non-nullable fields non-nullable in schema

Add new fields to Transmodel API

---

src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java

OSM wiki says: amenity=ferry_terminal is a place where people, cars etc. can board and leave a ferry. This is exactly the purpose of boarding locations in OTP.

Add amenity=ferry terminal to boarding locations

---

.github/workflows/cibuild.yml

This adds a date based tag to the container image uploaded to Dockerhub. It makes it easier to spot from a single glance how old the version is.
An example of the new tag is `v2.3_2022-12-12T21-38`.
Note that this doesn't upload extra images, just extra tags to the registry.

Date-based tag for container image

---

src/main/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapper.java

DefaultMapper use the tag `surface=cobblestone:flattened`. OpenStreetMap wiki sites `surface=cobblestone:flattened` as a possible mistagging of [`surface=sett`](https://wiki.openstreetmap.org/wiki/Tag:surface=sett).
`surface=sett` is used 310 650 times, while `surface=cobblestone:flattened` is only used 5 431 times world wide.
This PR suggest to replace `surface=cobblestone:flattened` with `surface=sett` as a mixin spec, and to add a mixin spec for [`surface=unhewn_cobblestone`](https://wiki.openstreetmap.org/wiki/Tag:surface=unhewn_cobblestone).
Both are tags are already in use in NorwayMapper.

Replace surface=cobblestone:flattened with surface=set as a mixin spec in default OsmTagMapper

---

pom.xml
src/main/java/org/opentripplanner/standalone/server/OTPWebApplication.java

As of https://github.com/micrometer-metrics/micrometer/commit/e7b03bcb13ee747cd3a1b7964c63dad8e4fa245a this has been moved into micrometer-core.

Remove micrometer-jersey2 module

---

pom.xml

The primary change of this PR is the upgrade of the OneBusAway GTFS import library to take into account a change in the GTFS flex: https://github.com/MobilityData/gtfs-flex/commit/547200dfb580771265ae14b07d9bfd7b91c16ed2
However, since I was working on the POM anyways, I upgraded the other libraries as well. The Jackson update fixes a security warning.
I've run this PR with IBI's smoke test suit and it passes.
cc @miles-grant-ibigroup @demory

Upgrade dependencies to take newest GTFS Flex spec into account

---

doc-templates/Flex.md
docs/BuildConfiguration.md
docs/RouterConfiguration.md
docs/sandbox/Flex.md
docs/sandbox/VehicleParking.md
src/test/java/org/opentripplanner/generate/doc/BuildConfigurationDocTest.java
src/test/java/org/opentripplanner/generate/doc/ConfigurationDocTest.java
src/test/java/org/opentripplanner/generate/doc/FlexConfigurationDocTest.java
src/test/java/org/opentripplanner/generate/doc/RouteRequestDocTest.java
src/test/java/org/opentripplanner/generate/doc/RouterConfigurationDocTest.java
src/test/java/org/opentripplanner/generate/doc/UpdaterConfigDocTest.java
src/test/java/org/opentripplanner/generate/doc/VehicleParkingDocTest.java
src/test/java/org/opentripplanner/generate/doc/framework/DocBuilder.java
src/test/java/org/opentripplanner/generate/doc/framework/JsonExampleBuilder.java
src/test/java/org/opentripplanner/generate/doc/framework/TemplateUtil.java

Pretty-prints all JSON examples when generating the docs.
What has mainly changed is the formatting of arrays which were a little too compact before. Now, every array element starts on a new line.

Pretty-print all JSON examples in docs

---

src/test/java/org/opentripplanner/generate/doc/BuildConfigurationDocTest.java
src/test/java/org/opentripplanner/generate/doc/ConfigurationDocTest.java
src/test/java/org/opentripplanner/generate/doc/FlexConfigurationDocTest.java
src/test/java/org/opentripplanner/generate/doc/RouteRequestDocTest.java
src/test/java/org/opentripplanner/generate/doc/RouterConfigurationDocTest.java
src/test/java/org/opentripplanner/generate/doc/UpdaterConfigDocTest.java
src/test/java/org/opentripplanner/generate/doc/VehicleParkingDocTest.java
src/test/java/org/opentripplanner/generate/doc/framework/DocsTestConstants.java
src/test/java/org/opentripplanner/generate/doc/framework/GeneratesDocumentation.java
src/test/java/org/opentripplanner/standalone/config/ExampleConfigTest.java

This is just a small cleanup, merging the `@Tag("docs")` and `@OnlyIfDocsExist` into one annotation `@GeneratesDocumentation`. This make it a bit more robust since we want to tag ALL doc generating tests with "docs" and make sure they are safe - do not fail if run without the docs folder present.
JavaDoc is updated, tests run as before - also with filtering on `docs`.

Merge @Tag("docs") and @OnlyIfDocsExist into @GeneratesDocumentation

---

src/main/java/org/opentripplanner/openstreetmap/model/OSMWay.java
src/main/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySet.java
src/main/java/org/opentripplanner/openstreetmap/wayproperty/specifier/BestMatchSpecifier.java
src/main/java/org/opentripplanner/openstreetmap/wayproperty/specifier/Condition.java
src/main/java/org/opentripplanner/openstreetmap/wayproperty/specifier/ExactMatchSpecifier.java
src/main/java/org/opentripplanner/openstreetmap/wayproperty/specifier/OsmSpecifier.java
src/test/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapperTest.java
src/test/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySetTest.java
src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/BestMatchSpecifierTest.java
src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/ConditionTest.java
src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/ExactMatchSpecifierTest.java
src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/OsmSpecifierTest.java
src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/SpecifierTest.java
src/test/java/org/opentripplanner/openstreetmap/wayproperty/specifier/WayTestData.java

This PR both refactors wayproperty.specifier.Condition, to make it easer to make more conditions, and adds more conditions.
* The «Equals» condition now does what it says. Functionality for matching prefixed values like surface=cobblestone:flatten is removed and «wildcard» matching are moved to a new condition called «Present». 
* The assumption of right hand driving is removed from «WayPropertiesBuilder.getDataForWay», but there is still no support for left hand side driving when `:right` and `:left` postfixes are evaluated.
*  Support for matching of `:forward`, `:backward` and `:both` postfixes are added.
This PR also fix the to small following bugs:
* `maxspeed:reverse` should be `maxspeed:backward`
* #4695 
closes  #4695
Test concerning cobblestones:flattened is removed.
A testcase …

Refactor of wayproperty.specifier.Condition

---

renovate.json5

This adds two rules to make renovate less noisy:
- Only real graphql-java releases are used for updates
- mkdocs-material is only updated once a quarter

Configure renovate to be less noisy

---

docs/RouteRequest.md
src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
src/main/java/org/opentripplanner/api/common/RequestToPreferencesMapper.java
src/main/java/org/opentripplanner/api/common/RoutingResource.java
src/main/java/org/opentripplanner/raptor/api/request/SearchParams.java
src/main/java/org/opentripplanner/raptor/api/request/SearchParamsBuilder.java
src/main/java/org/opentripplanner/raptor/rangeraptor/path/configure/PathConfig.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java
src/main/java/org/opentripplanner/routing/api/request/framework/Units.java
src/main/java/org/opentripplanner/routing/api/request/preference/RaptorPreferences.java
src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
src/test/java/org/opentripplanner/raptor/util/paretoset/ParetoSetTest.java
src/test/java/org/opentripplanner/routing/api/request/framework/UnitsTest.java
src/test/java/org/opentripplanner/routing/api/request/preference/RaptorPreferencesTest.java

The RaptorPreferences was representing *not set* with any negative value instead of using `null`. A magic number from the Raptor internal model was leaked in the API and when this value was changed, the API changed. In addition, the RaptorPreferences `equals(..)` and `hashCode()` was implemented incorrect.
The `relaxGeneralizedCostAtDestination` allowed values should be: `null`(not set), `1.0 to 2.0` (0% to 100% relaxation). 
New unit tests on `RaptorPreferences` are added.

fix: relaxGeneralizedCostAtDestination leaks Raptor internal NOT_SET

---

docs/RouteRequest.md
docs/RouterConfiguration.md
src/main/java/org/opentripplanner/standalone/config/routerequest/ItineraryFiltersConfig.java
src/test/resources/standalone/config/router-config.json

It seems these were missed in https://github.com/opentripplanner/OpenTripPlanner/pull/4188 due to simultaneus upgrade to the new documentation generation.

docs: Add transitGeneralizedCostLimit fields in documentation

---

src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java

Currently we return a leg from a leg reference irrespective of whether the trip is actually running on the date in the reference. Check this when reconstructing the leg and return null, if the trip is not in service on the date.
This problem occurs, when the underlying transit data changes, and a specific trip does not run anymore on the service date. This currently only affects the `leg` query in the Transmodel API.

Do not return a leg from a leg reference, if trip does not exist on date

---

src/test/java/org/opentripplanner/raptor/moduletests/A01_SingeRouteTest.java
src/test/java/org/opentripplanner/raptor/moduletests/A02_SingeRouteRestrictionsTest.java
src/test/java/org/opentripplanner/raptor/moduletests/A04_BoardingTest.java
src/test/java/org/opentripplanner/raptor/moduletests/B01_AccessTest.java
src/test/java/org/opentripplanner/raptor/moduletests/B02_EgressTest.java
src/test/java/org/opentripplanner/raptor/moduletests/B03_AccessEgressTest.java
src/test/java/org/opentripplanner/raptor/moduletests/B04_AccessEgressBoardingTest.java
src/test/java/org/opentripplanner/raptor/moduletests/B10_FlexAccessTest.java
src/test/java/org/opentripplanner/raptor/moduletests/B11_FlexEgressTest.java
src/test/java/org/opentripplanner/raptor/moduletests/C01_TransferBoardAndAlightSlackTest.java
src/test/java/org/opentripplanner/raptor/moduletests/C02_BoardAndAlightSlackWithFlexAccessEgressTest.java
src/test/java/org/opentripplanner/raptor/moduletests/C03_OnStreetTransfersTest.java
src/test/java/org/opentripplanner/raptor/moduletests/E01_GuaranteedTransferTest.java
src/test/java/org/opentripplanner/raptor/moduletests/E02_NotAllowedConstrainedTransferTest.java
src/test/java/org/opentripplanner/raptor/moduletests/E11_GuaranteedTransferWithFlexAccessTest.java
src/test/java/org/opentripplanner/raptor/moduletests/F01_TransitModeReluctanceTest.java
src/test/java/org/opentripplanner/raptor/moduletests/support/RaptorModuleTestCase.java
src/test/java/org/opentripplanner/raptor/moduletests/support/RaptorModuleTestCaseBuilder.java
src/test/java/org/opentripplanner/raptor/moduletests/support/RaptorModuleTestConfig.java
src/test/java/org/opentripplanner/raptor/moduletests/support/RaptorModuleTestConfigSetBuilder.java

- This adds tests on several missed cases for raptor profiles
- It also make it much easier to add min_duration tests later(low coverage)
- The new builders make the expectations for each profile much more visible,
   this is important - because we want to highlight the differences. It
   illustrates well when a profile can be used and what you sacrifice.

Add more module tests to Raptor for all relevant profiles

---

src/ext/java/org/opentripplanner/ext/transferanalyzer/DirectTransferAnalyzer.java
src/ext/java/org/opentripplanner/ext/transferanalyzer/annotations/TransferCouldNotBeRouted.java
src/ext/java/org/opentripplanner/ext/transferanalyzer/annotations/TransferRoutingDistanceTooLong.java
src/main/java/org/opentripplanner/graph_builder/issue/api/DataImportIssue.java
src/main/java/org/opentripplanner/graph_builder/issues/HopSpeedSlow.java
src/main/java/org/opentripplanner/graph_builder/issues/HopZeroDistance.java
src/main/java/org/opentripplanner/graph_builder/issues/HopZeroTime.java
src/main/java/org/opentripplanner/graph_builder/issues/InterliningTeleport.java
src/main/java/org/opentripplanner/graph_builder/issues/RepeatedStops.java

Direct transfer analyzer crashed if it couldn't link a stop to the street network. Fix that and add a couple of priorities to the data import issues

Fix direct transfer analyzer

---

src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
src/main/java/org/opentripplanner/model/TripTimeOnDate.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TripPatternForDateMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilter.java
src/main/java/org/opentripplanner/routing/api/request/preference/TransitPreferences.java
src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
src/main/java/org/opentripplanner/transit/model/timetable/RealTimeState.java
src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
src/main/proto/gtfs-realtime.proto
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
src/test/java/org/opentripplanner/routing/api/request/preference/TransitPreferencesTest.java
src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java

GTFS-RT recently added a `DELETED` real-time state in https://github.com/google/transit/pull/352. Add support for this, as well as refactoring the internals of OTP, so that trips replaced by other patterns are marked as `DELETED`, while only real cancellations are marked as `CANCELED`. This also enables us to add a field `includeRealtimeCancellations` in the Transmodel API

Add support for deleted trips & including real-time cancelations in trip search

---

docs/RouteRequest.md
docs/sandbox/LegacyGraphQLApi.md
src/client/legacygraphql/graphiql/index.html
src/ext/resources/legacygraphqlapi/schema.graphqls
src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java

This PR achieves 3 things:
- updates the confusing documentation for board/alightSlackForMode
- updates the built-in GrapqhQL viewer to 2.3.0
- adds proper `@deprecated` tags to the input paramters of the `plan` resolver so that these don't show up in GraphiQL anymore

Add deprecation tags, improve docs, update GraphiQL

---

pom.xml
src/ext-test/java/org/opentripplanner/ext/transmodelapi/model/scalars/DateTimeScalarFactoryTest.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/scalars/DateTimeScalarFactory.java

Currently we can't parse times like `2023-01-27T12:59:00+0200`, which aren't technically ISO-8601 compatible, but widely enough used. Eg by RFC3339, see [errata](https://www.rfc-editor.org/errata/eid1584).
Also, it changes the timezone formatting used by `git-commit-id-maven-plugin` (see https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/575#issuecomment-959879324) to match ISO-8601, and not the erroneous format.

Make Transmodel API accept timezones without colons

---

src/main/java/org/opentripplanner/routing/api/request/request/filter/SelectRequest.java
src/main/java/org/opentripplanner/transit/model/basic/MainAndSubMode.java
src/test/java/org/opentripplanner/routing/api/request/request/filter/SelectRequestTest.java
src/test/java/org/opentripplanner/transit/model/basic/MainAndSubModeTest.java

Value types like `MainAndSubMode` in the internal OTP model should have short easy to read `toString()` implementations. These types are frequently read while debugging and in loggs, so less "stuff" printed means faster and easier reading. 
The `subMode` is optional, so I did the following 
- MainMode=BUS, SubMode=null  ==> `"BUS"`
- MainMode=BUS, SubMode=LOCAL  ==> `"BUS::LOCAL"`
We could use something like `BUS+LOCAL`, `BUS&LOCAL`, `BUS(LOCAL)`, or `BUS[LOCAL]`, but I think the `::` works fine - there is no change of collisions with real values, and we already use `:` as a separator in the `FeedScopedId` - this is kind of similar.
Several unit tests are added, I also added a few utility methods, which lead to DRY/easier readable code like the …

Improve logging of Modes and SelectFilter with modes

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLPatternImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
src/ext/resources/legacygraphqlapi/schema.graphqls

This PR exposes a originalTripPattern field in Pattern in graphql api. 
We have identified a need for this field in other project. 
This is tested locally and is working as expected.

Expose original trip pattern in pattern

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferIndexGenerator.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java

Currently the generation crashes if the `TripTransferPoint#getStopPositionInPattern()` is greater than `RoutingTripPattern#numberOfStopsInPattern`, or it would create a transfer between the wrong stop, if the pattern changed. This changes the handling so that we check the index and compare the stop at that point, and generate a constrained transfer only if it is the same stop, or its sibling, at the specified stop point in pattern.

Fix TPoint generation for real-time generated patterns

---

src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/VehicleRentalServiceDirectoryFetcher.java

In https://github.com/opentripplanner/OpenTripPlanner/pull/4147 code was added to always override the network name in the vehicle rental service directory service. This was not correct, instead the id should be read from the feed.

Do not override network name in the vehicle rental service directory service

---

ISSUE_TEMPLATE
README.md
docs/Developers-Guide.md
docs/Localization.md

Update documentation to point to Gitter chat room and not old dev mailing list.
Updated

Replace 'developer mailing list' with 'Gitter chat' in doc

---

src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
src/test/java/org/opentripplanner/updater/trip/TripUpdateBuilder.java

We talked about this at one of the meetings: the GTFS-RT tests previously used `LocalDate.now()` to get the service date but that is of course problematic.
This PR refactors the test so that it uses a fixed service date.

Refactor GTFS-RT tests to use fixed service date

---

src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java

Fix: All optional filters is added in the same place, except `removeItinerariesWithSameRoutesAndStops`.
No.
No functionallity  is changed.
No.

Small cleanup ItineraryListFilterChainBuilder

---

pom.xml
src/main/resources/Message_de.properties
src/main/resources/internals_hu.properties
src/test/java/org/opentripplanner/framework/i18n/LocalizedStringTest.java
src/test/java/org/opentripplanner/framework/resources/ResourceBundleSingletonTest.java

We've seen random Windows ci build failures and I believe this will fix the problem, so lets test it.
I have now converted all resources to UTF-8.

Fix windows CI build by specifying resource encoding

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PlanPlaceType.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/TripPlanMapper.java

This PR contains ~two~ one improvement:
- If an error is thrown from the parsing of the request, we generate a `TripPlan`, which we can show to the user together with the error. In this we include coordinates, which might be null, which will lead to an NPE. Instead pass in null all the way, and serialize it as 0 in the API, as it is a non-nullable type.
- ~Validation was made stricter to relaxGeneralizedCostAtDestination recently, which will throw an error if an invalid value is specified. Instead pre-validate the value and only set it if valid.~ Removed, as all clients are now fixed. However we should improve validation somehow already when parsing the value.

Improve resiliency of the Transmodel API

---

.github/workflows/cibuild.yml
pom.xml

This PR refactors the CI steps from a Matrix build to two separate jobs for Windows and Linux for the following reasons:
- Lately the Windows CI runners have become quite slow and flaky. I want to do as little works as needed there. It speeds up the Windows build from 12 to 8 minutes.
- Prettier is disabled on Windows as it was crashing on the CI machines. This introduces confusion and friction for Windows developers.
- The Windows and Linux builds had drifted apart quite significantly so it's not even a lot of duplication to have two jobs.
Fixes #4682

Introduce separate build step for windows

---

src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java

Make sure that SiriTimetableSnapshotSource.getTimetableSnapshot does not return null
N/A
N/A
N/A

Make sure that we do not return realtime snapshot that is null

---

src/main/java/org/opentripplanner/graph_builder/module/islandpruning/PruneIslands.java

StreeLinkerModule  tests the sum of incoming and outgoing edges before relinking transit stops to the healthy part of the graph. Therefore, when island pruning removes an island with stops, all edges attached to transit stops of the island should be removed. 
Currently some transit stops (the ones linked with BoardingLocationToStopLink) remain unlinked after island pruning. This change fixes the problem.

Remove all edges from stop vertex in island pruning

---

src/main/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapper.java
src/test/java/org/opentripplanner/openstreetmap/tagmapping/GermanyMapperTest.java

Treat bicycle_rodas and cyclestreets as safe as cycle networks.
The router currently does not prefer dedicated bicycle roads over other roads.
I followed the suggestion of @leonardehrenfried and just added the two tags to the existing three tags. https://github.com/opentripplanner/OpenTripPlanner/issues/3789#issuecomment-1008308140
Fixes #3789 (already closed as stale)
I have verified the intended behaviour manually.
I'm currently upstreaming my local patches and catching up with a year of refactorings, so this was tested to have the intended function before merging the refactoring.
I have added documentation to the code outlining the rationale.
https://github.com/opentripplanner/OpenTripPlanner/labels/skip%20changelog

Apply bike safety multiplier to cyclestreets and bicycle roads

---

docs/Container-Image.md

This PR fixes the commands given in the Container-Image documentation section.
The -v parameter does not accept relative paths, so we need to use pwd to get a absolute path.
#4853
`closes #4853`
No code changes, so no unit tests added
Fixed an existing documentation

Fix docker commands in Container-Image.md

---

src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
src/main/java/org/opentripplanner/inspector/raster/AreaEdgeRenderer.java
src/main/java/org/opentripplanner/inspector/raster/TileRendererManager.java
src/main/java/org/opentripplanner/street/model/edge/AreaEdgeList.java
src/test/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModuleTest.java

Boarding locations  (see https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/docs/BoardingLocations.md) are linked with surrounding area geometry using so called visibility points. The set of such points included previously only points, where the platform is joined with other street network. Unfortunately all those points can be obscured behind convex parts of the area geometry, and linking may become quite minimal. This may lead to strange walk routing to the boarding location.
This pull request adds more visibility points to be available in boarding location linking. Sufficient visibility point set will enable improved walk routing on areas in general (new development to appear after this pr).
The PR also adds a new visualization ability to the Debug UI, 'Areas'. Only area …

Improve boarding location linking on platforms

---

src/ext/java/org/opentripplanner/ext/dataoverlay/DataOverlayStreetEdgeCostExtension.java
src/main/java/org/opentripplanner/routing/vehicle_rental/RentalVehicleType.java
src/main/java/org/opentripplanner/street/model/StreetTraversalPermission.java
src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
src/main/java/org/opentripplanner/street/search/TraverseMode.java
src/main/java/org/opentripplanner/street/search/intersection_model/SimpleIntersectionTraversalCalculator.java
src/test/java/org/opentripplanner/street/model/edge/RentalRestrictionExtensionTest.java
src/test/java/org/opentripplanner/street/model/edge/StreetEdgeRentalTraversalTest.java

#4809 surfaced a bug where scooter rental legs are returned with mode `BICYCLE`. Beforehand that fact was papered over in `GraphPathToItineraryMapper`.
This fixes it by properly using `SCOOTER` as the traverse mode for scooter rental legs.
Closes #4847 
Lots added.

Return scooter rental legs with correct mode

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java

This fixes a bug in Seattle's ORCA fare calculator where nullable route names where not taken into account.
It is pure sandbox code.

Fix handling of nullable route names in ORCA fare calculator

---

src/main/java/org/opentripplanner/street/model/edge/VehicleRentalEdge.java

Currently we do not check available types when `realtimeAvailability` is false. This might produce wrong results, if the form factors allowed differ between pickup and drop off.

Always check allowed modes in VehicleRentalEdge

---

pom.xml

Closes #4914
This PR add support for building Docker image for the following architectures:
- x86-64 (amd64)
~- ARMv7 32-bit (arm32v7)~
- ARMv8 64-bit (arm64v8)
~- IBM POWER8 (ppc64le)~
~- IBM z Systems (s390x)~

Build a Docker image that support multiple architectures

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareService.java

Fixes a bug where a route short name of null leads to an NPE.
Added.

Take nullable route short name into account in Atlanta fare calculator

---

src/main/java/org/opentripplanner/netex/mapping/FlexStopsMapper.java
src/main/java/org/opentripplanner/transit/model/site/GroupStop.java
src/test/java/org/opentripplanner/netex/mapping/FlexStopsMapperTest.java

This PR fixes #4918: The OTP graph builder should ignore FlexibleStopPlaces of type UnrestrictedPublicTransportAreas when they do not contain any stop.
The FlexibleStopPlace is dropped and an issue is logged in the issue store.
Additionally a null-check is added in the GroupStop constructor to prevent the creation of a GroupStop without a centroid (that triggers NullPointerExceptions downstream in the code)
Fixes #4918
No

Ignore UnrestrictedPublicTransportAreas that do not contain regular stops

---

src/main/java/org/opentripplanner/inspector/vector/VectorTileResponseFactory.java
src/test/java/org/opentripplanner/inspector/vector/VectorTileResponseFactoryTest.java

This was a request from a frontend developer in one of my projects: he was struggling to find out what the available layer names for the vector tiles are and whether everything is configured correctly.
For this reason, this PR changes the code so that a 404 is returned (rather than a 200 with an empty tile) when at least one of the requested layers cannot be found. This will make it obvious to frontend developers that there is a problem and they should investigate.
Technically this is a breaking change but it will only affect you when you are used to requesting non-existing layers together with existing ones and expecting it to work.
Added.
cc @derhuerst @miles-grant-ibigroup

Return 404 when a requested vector tile layer cannot be found

---

src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/FilterMapper.java

This PR fixes a regression in the transmodel graphql api that was introduced with mapping to the new filters. banned.lines was incorrectly mapped to a select filter instead of a not filter.
Example in Entur's environment: [shamash query](https://api.entur.io/graphql-explorer/journey-planner-v3?query=%0A%23%20Welcome%20to%20GraphiQL%0A%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%0A%23%20GraphiQL%20is%20an%20in-browser%20IDE%20for%20writing%2C%20validating%2C%20and%0A%23%20testing%20GraphQL%20queries.%0A%23%0A%23%20Type%20queries%20into%20this%20side%20of%20the%20screen%2C%20and%20you%20will%0A%23%20see%20intelligent%20typeaheads%20aware%20of%20the%20current%20GraphQL%20type%20schema%20and%0A%23%20live%20syntax%20and%20validation%20errors%20highlighted%20within%20the%20text.%0A%23% …

fix: banned lines filter incorrectly mapped

---

src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ViaTripQuery.java

The viaTrip query field seems to be stable now so the deprecation marking can be removed.

Remove deprecation annotation from viaTrip query field

---

src/main/java/org/opentripplanner/graph_builder/GraphBuilderDataSources.java

Fixes #4928
the --loadStreet parameter is intended to load a street graph and build a transit graph on top of it:
> Load 'streetGraph.obj' and build transit data on top of it. The " +
>     "'--build' parameter is implied. Can be used with '--save' and '--serve'.
This PR ensures that not only the street graph is available, but also transit data are provided.
#4928
No

Validate missing transit data before building transit graph

---

.github/workflows/cibuild.yml

We have had some problems with the CI lately where during the packaging step the build would hang.
My current theory is that this is due to https://github.com/actions/runner-images/issues/1499.
If this is the case then the problem is that Maven keeps long running connections open which the Azure NAT closes.
For this reason I split the build into two steps: one for tests and one for building the jar.
Lets see if that fixes the issues.

Split maven CI build into two steps to avoid timeouts

---

.github/workflows/cibuild.yml
docs/RouterConfiguration.md
docs/examples/entur/router-config.json
src/main/java/org/opentripplanner/model/plan/PagingSearchWindowAdjuster.java
src/main/java/org/opentripplanner/raptor/api/request/DynamicSearchWindowCoefficients.java
src/main/java/org/opentripplanner/raptor/rangeraptor/transit/RaptorSearchWindowCalculator.java
src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/TransitRoutingConfig.java
src/test/java/org/opentripplanner/model/plan/PagingSearchWindowAdjusterTest.java
src/test/java/org/opentripplanner/raptor/rangeraptor/transit/RaptorSearchWindowCalculatorTest.java
src/test/resources/standalone/config/router-config.json
test/performance/skanetrafiken/speed-test-config.json

I believe we talked about this before: we want to start using durations in configuration everywhere rather than number of seconds or minutes.
This PR gets the ball rolling by implementing this for the raptor search window configuration.

Use durations for Raptor search window configuration

---

src/test/java/org/opentripplanner/graph_builder/module/ned/MissingElevationHandlerTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/filter/TransitAlertFilterTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternForDateTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
src/test/java/org/opentripplanner/updater/alert/AlertsUpdateHandlerTest.java

Mockito is used in couple of tests, where it is used just for an incomplete implementation of an interface. Replace those with concrete classes. Three classes remain, where we actually use functionality from Mockito.

Replace Mockito with concrete implementations where not used in test

---

src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoader.java

This PR moves a warning that is logged when the GBFS auto-discovery endpoint doesn't follow the naming convention of `gbfs.json`, also if it just lacks the extension `.json`. This naming convention was made optional as of v2.0. The warning just creates noise in the logs. The warning is now only logged if fetching the auto-discovery file fails.

Only log warning in GBFS updater if failed to fetch auto-discovery file

---

src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdaterParameters.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriETGooglePubsubUpdaterConfig.java

This PR adds support for specifying separate GCP project names for topic and subscription
Note: will also require a change in `router-config.json` from:
```
{
"type": "siri-et-google-pubsub-updater",
...
=>        "projectName":"entur-gcp-project", 
"topicName": "protobuf.estimated_timetables",
...
}
```
to e.g.:
```
{
"type": "siri-et-google-pubsub-updater",
...
=>        "topicProjectName":"entur-topic-project",
=>        "subscriptionProjectName":"entur-subscription-project",
"topicName": "protobuf.estimated_timetables",
...
}
```

Separating config of projectName for Pubsub topic/subscription

---

docs/Preparing-OSM.md

Just update the documentation to include areas when preparing OSM data.
We were following the documentation and ran into an issue, where platforms built as multipolygon areas were missing in our routing graph.

Add areas to documentation example for preparing osm data [ci skip]

---

src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java

Google now supports/recommends defining pubsub-authentication through "workload identity" (https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity).
This PR removes the check for the - now optional - ENV variable `GOOGLE_APPLICATION_CREDENTIALS`, and thus assumes that config is correct when starting up.

Remove check for (now optional) ENV-variable for GCP Authentication

---

src/ext-test/resources/smoovebikerental/smoove.json
src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSource.java

Uses `style` field instead of `operative` field to tell if a smoove station is on as unfortunately the `operative` field is always true even though the station is not operative.
No issue, minor sandbox change
Updated test data
Not needed.
Not needed

Use different logic in smoove updater to tell if the station is on

---

.github/workflows/cibuild.yml

Docker has announced that the free team account, which ours is, is going away.
For this reason I want to try out hosting the image on Github's container registry instead to find out if it really is as good as the documentation suggest.
The switch will happen in April so I want to publish to both for a while until we make a decision for the image's eventual location.

Publish container to Github Container Registry

---

src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java

Walkable area builder is able to detect unconnected areas, but left them in the graph. Such areas often lack so called visibilityVertices, which are required when linking stops to areas.  The result was that some isolated graph edges got linked with the stop, and island pruning did not discover to relink such stops after removal of the area.
It seems best to remove bad areas as soon as they get detected, instead of adding more complex code to deal with various linking problems. This PR does the required change. 
Attached  is a picture of a ferry platform, which got detached from the graph due to this bug.

Remove unconnected walking areas from graph

---

.github/workflows/performance-test.yml

When developing a performance-critical feature we sometimes run the speed test for every commit on a branch.
However, these days the full suite takes 65 minutes with more locations to come.
Therefore I'm changing the CI config that only Norway, Germany and Skane are run when you're on a branch.
The full suite of locations is run only after merge to dev-2.x.

Speed test profiles

---

src/main/java/org/opentripplanner/gtfs/mapping/StopMapper.java

Stop mapper now includes the GTFS stop id  in the exception it throws when expected stop reference is  pointing to a terminal. When the identifier is known, it is easy to find the error in the data (e.g. reference to a terminal in stop_times.txt).

Identify which terminal is the problem when throwing an exception

---

.github/workflows/cibuild.yml

The Maven prettier plugin often fails to download the nodejs binary.
Example: https://github.com/opentripplanner/OpenTripPlanner/actions/runs/4490450225/jobs/7897533439
```
[INFO] argLine set to -javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.8/org.jacoco.agent-0.8.8-runtime.jar=destfile=/home/runner/work/OpenTripPlanner/OpenTripPlanner/target/jacoco.exec
[INFO] 
[INFO] --- prettier-maven-plugin:0.19:check (default) @ otp ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:30 min
[INFO] Finished at: 2023-03-22T13:36:47Z
[INFO] ------------------------------------------------------------------------
Error:  Failed …
```

Fix prettier node download for CI

---

src/main/java/org/opentripplanner/netex/mapping/ServiceLinkMapper.java
src/test/java/org/opentripplanner/netex/mapping/ServiceLinkMapperTest.java

Fixes #4962
This PR adds validation logic to check that the number of ServiceLinks mapped to a JourneyPattern is consistent with the number of intervals between stops in the JourneyPattern.
If the mapping is inconsistent, an issue is logged in the issue store and the graph builder falls back to generating straight-line ServiceLinks  between the stops.
Note: the current mapping logic is fragile. It assumes that the position of the ServiceLink in the shape is the same as the position of the ServiceLinkInJourneyPattern element in the XML file. Instead the "order" field in the ServiceLinkInJourneyPattern should be used. This improvement is out-of-scope for this PR.
#4962
No

Validate the number of service links mapped to a JourneyPattern

---

src/main/java/org/opentripplanner/standalone/config/routerequest/WheelchairConfig.java
src/test/java/org/opentripplanner/standalone/config/routerequest/WheelchairConfigTest.java

Checks are added when configuring `AccessibilityPreferences` so that either `onlyConsiderAccessible: true` or `unknownCost`/`inaccessibleCost` may be specified to avoid misconfigurations.
#4973 
:x:
https://github.com/opentripplanner/OpenTripPlanner/labels/skip%20changelog
:x:

Add checks for configuring AccessibilityPreferences

---

src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/main/java/org/opentripplanner/astar/AStar.java
src/main/java/org/opentripplanner/astar/AStarBuilder.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
src/main/java/org/opentripplanner/routing/api/request/preference/StreetPreferences.java
src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
src/main/java/org/opentripplanner/standalone/api/OtpServerRequestContext.java
src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
src/main/java/org/opentripplanner/street/search/StreetSearchBuilder.java
src/main/java/org/opentripplanner/visualizer/GraphVisualizer.java
src/test/java/org/opentripplanner/TestServerContext.java
src/test/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModuleTest.java
src/test/java/org/opentripplanner/graph_builder/module/osm/TestIntermediatePlaces.java
src/test/java/org/opentripplanner/routing/api/request/preference/StreetPreferencesTest.java
src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
src/test/java/org/opentripplanner/street/integration/BarrierRoutingTest.java
src/test/java/org/opentripplanner/street/integration/BicycleRoutingTest.java
src/test/java/org/opentripplanner/street/integration/CarRoutingTest.java
src/test/java/org/opentripplanner/street/integration/SplitEdgeTurnRestrictionsTest.java
src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java

OTP have a global street router timeout(`streetRoutingTimeout`) set in router-config. This was not used in all cases. 
To fix this problem I moved the timeout into the street preferences and made it none-nullable. I also now trow an exception if AStar is created with a `null` timeout. I removed the timeout from the call-chain and context - it is now passed in the the AStarBuilder using the request. There are places witch does not use the build-config default request, but create a new request instead - I think this is wrong, but I have not changed it. In those place the timeout will now change from infinite to 5 seconds (code default).
I added `this.timeout = Objects.requireNonNull(timeout);` in the AStar constructor to prevent a similar error to occur in the future. It is difficult to …

Make sure the default streetRoutingTimeout is used

---

docs/RouterConfiguration.md
src/main/java/org/opentripplanner/standalone/config/BuildConfig.java
src/main/java/org/opentripplanner/standalone/config/OtpConfig.java
src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
src/main/java/org/opentripplanner/standalone/config/framework/json/NodeAdapter.java
src/main/java/org/opentripplanner/standalone/config/framework/json/ParameterBuilder.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/TransitRoutingConfig.java
src/test/java/org/opentripplanner/standalone/config/BuildConfigTest.java
src/test/java/org/opentripplanner/standalone/config/ExampleConfigTest.java
src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java
src/test/java/org/opentripplanner/standalone/config/framework/json/NodeAdapterTest.java
src/test/java/org/opentripplanner/standalone/config/sandbox/DataOverlayConfigMapperTest.java
src/test/java/org/opentripplanner/transit/speed_test/options/SpeedTestConfig.java

Enum values can be added or deleted; Hence to allow OTP to be forward and backward compatible unknown values must be logged(WARNING) and ignored. The Server should not terminate.
The new log items look like this:
```
13:45:56.208 WARN (NodeAdapter.java:172) The enum value 'Fake' is not legal. Expected one of [APIBikeRental, APIServerInfo, APIGraphInspectorTile, APIUpdaterStatus, ConsiderPatternsForDirectTransfers, DebugClient, FloatingBike, MinimumTransferTimeIsDefinitive, OptimizeTransfers, ParallelRouting, TransferConstraints, ActuatorAPI, AsyncGraphQLFetchers, DataOverlay, FaresV2, FlexRouting, GoogleCloudStorage, RealtimeResolver, ReportApi, SandboxAPIGeocoder, SandboxAPILegacyGraphQLApi, SandboxAPIMapboxVectorTilesApi, SandboxAPIParkAndRideApi, SandboxAPITransmodelApi, …
```

Allow OTP to start when unexpected enum values is encountered in config.

---

src/ext-test/java/org/opentripplanner/ext/siri/mapper/PickDropMapperTest.java
src/ext/java/org/opentripplanner/ext/siri/AddedTripBuilder.java
src/ext/java/org/opentripplanner/ext/siri/ModifiedTripBuilder.java
src/ext/java/org/opentripplanner/ext/siri/mapper/PickDropMapper.java
src/main/java/org/opentripplanner/transit/model/network/StopPattern.java

When a stop is cancelled, the PickDrop is always set to CANCELLED for both boarding and alighting. This causes e.g. trips without boarding to appear on departure-boards.
This PR checks if the existing PickDrop-status is routable before cancelling. If not, the status is kept as-is.
closes #5000
Tests are added to verify new criteria.

Avoid changing already non-routable stops when cancelling stops in realtime

---

src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java

In viaTrip query, all routing errors resulted in errors in logs and system error in response, including ones we expect, such as `noTransitConnectionInSearchWindow`.
Example request: [shamash](https://api.entur.io/graphql-explorer/journey-planner-v3?query=%7BviaTrip%28from%3A%7Bplace%3A%22NSR%3AStopPlace%3A58927%22%7Dto%3A%7Bplace%3A%22NSR%3AStopPlace%3A58927%22%7DsearchWindow%3A%22PT2H%22%20dateTime%3A%222023-04-27T18%3A04%3A00.000%2B02%3A00%22%20via%3A%5B%7Bplace%3A%22NSR%3AStopPlace%3A222%22%7D%5D%29%7BroutingErrors%7Bdescription%20inputField%20code%7DtripPatternsPerSegment%7BtripPatterns%7BexpectedStartTime%20expectedEndTime%20duration%20walkDistance%20legs%7BexpectedStartTime%20expectedEndTime%20mode%20distance%20line%7Bid%20publicCode%7D%7D%7D%7DtripPatternCombinations%7Bfrom%20to%7D% …

fix: Catch RoutingValidationException for ViaRoutingResponse

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/TransferIndexGenerator.java

Ensure that OTP does not crash totally if there is an error while generating transfer constraints
N/A
N/A

Catch and log exceptions when generating transfers

---

src/ext-test/java/org/opentripplanner/ext/realtimeresolver/RealtimeResolverTest.java
src/ext/java/org/opentripplanner/ext/realtimeresolver/RealtimeResolver.java
src/main/java/org/opentripplanner/transit/model/network/TripPatternBuilder.java

This PR fixes an issue where RealtimeResolver will drop the information about constrained transfers like "staySeated". This happens when the `RealtimeResolver` feature is on and a search is done using `ignoreRealtimeUpdates = true`.
This PR simply re-adds the original information that is not available in the response from `ScheduledTransitLegReference.getLeg()`. Other than that it is mostly testing and renaming.
I added testcases for the specific issue and also for the general functionality of `populateLegsWithRealtime()`. And I removed the old test since it is covered by the new tests.
There's a lot of lines spent on setting up the context for the test cases. I'm a bit new to the codebase, maybe there is an easier way?

Fix staySeated transfers in RealtimeResolver

---

src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFreeVehicleStatusMapper.java
src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFreeVehicleStatusMapperTest.java

Freefloating rental vehicles in GBFS don't have a name property but OTP maps the vehicle's id to its name.
This id is often very long, automatically rotated and then ends up in the UI.
In this PR I'm changing the name from the ID to the type of the vehicle (if it exists), otherwise the default one for that feed.
Added.
cc @derhuerst @hbruch

Use a more human-readable value for rental vehicle's name

---

src/ext-test/java/org/opentripplanner/ext/legacygraphqlapi/mapping/RouteRequestMapperTest.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/mapping/RouteRequestMapper.java
src/main/java/org/opentripplanner/model/modes/ExcludeAllTransitFilter.java

This fixes an issue where `banned.routes` was not taken into account when constructing the transit filters.
The problem was that `hasArgument("banned.routes")` doesn't work with names with a dot in them. Fortunately, the checks are not needed and can simply be removed as `callWith.argument()` already does the right thing.
Added.

Fix banning of route and agency in GraphQL API

---

src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripTest.java
src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
src/ext/java/org/opentripplanner/ext/siri/EntityResolver.java
src/main/java/org/opentripplanner/framework/time/ServiceDateUtils.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
src/test/java/org/opentripplanner/framework/time/ServiceDateUtilsTest.java

This PR fixes 2 errors related to DST adjustments. 
**Fix empty arriveBy search**
When selecting trip-pattern-for-day otp used ended up using the previous day for arrive-by search. This again cased OTP to search an empty set of patterns.
**fix SIRI alerts operatingDay resolving**
In some legacy cases the operatingDay is passed into OTP with time and zoneID. To get
the correct operating day we simply ignore time and zone-id.  The existing code was
wrong for days with DST forward adjustments. This only apply to the SIRI updaters.
No issue for this.
Unit test for the `ServiceDateUtils` is updated, but no module/integration test is added. The plan is to delete this code, and we can not reuse the tests.
No.

Bugs related to DST and service date

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TripPatternForDate.java

As detailed in #5006 , the calculation of the start and end of the transit period is wrong when a flexible line contains both fixed stops and flexible areas.
The construction of TripTimes in this case is necessary since Raptor makes use of flexible lines when they contain at least 2 fixed stops. Moreover these TripTimes are also used to provide flexible trip information in the TransModel API.
This PR relaxes the validation rule of the running period for flexible trips. Flexible trips are identified with Route.getFlexibleLineType() , so this fix covers only flexible lines imported from NeTEx datasets.
Partially fixes #5006 
No

Fix validation of running period for NeTEx flexible lines

---

docs/Logging.md
docs/Troubleshooting-Routing.md
mkdocs.yml
pom.xml
src/main/resources/logback.xml

This allows users of OTP to switch to JSON-formatted logs by setting an command line parameter like this:
```
java -Dotp.logging.format=json -jar otp.jar --load --serve data
```
A (pretty-printed) example of a log message looks like this:
```
{
"@timestamp": "2023-04-03T13:28:08.058026697+02:00",
"level": "INFO",
"logger_name": "org.opentripplanner.routing.graph.SerializedGraphObject",
"thread_name": "main",
"message": "Reading graph from 'tampere/graph.obj'"
}
```
I've also included Entur's configuration in this PR. We can discuss if this is necessary as you may have more customization needs that you don't want to upstream.
Closes #5015 
Added.
cc @derhuerst @hbruch

JSON logging

---

src/main/java/org/opentripplanner/netex/mapping/BookingInfoMapper.java
src/test/java/org/opentripplanner/netex/mapping/BookingInfoMapperTest.java

As detailed in #5020, the current algorithm for importing booking information from NeTEx flexible lines does not allow for fine-grained merging of the different booking properties specified at different levels (FlexibleLine, ServiceJourney, StopPointInJourneyPattern).
This PR changes the import logic to make it possible to define common properties at a higher level (for example contact information at the flexible line level), and define more specific properties at lower level.
closes #5020 
No

Fix precedence rules for NeTEx flexible line booking information

---

src/client/i18n/de.po
src/client/i18n/en.po
src/client/i18n/es.po
src/client/i18n/fr.po
src/client/i18n/hu.po
src/client/i18n/it.po
src/client/i18n/no.po
src/client/i18n/pl.po
src/client/i18n/pt.po
src/client/i18n/sl.po

Make `Transit & Rented Scooter` language string be different from the `Transit & Rented Bicycle` language string for the client UI.
I noticed that the strings are the same which is confusing.
I fixed the string (`Bicycle` -> `Scooter`) in English. I don't know the appropriate terms in the other languages and the `Rented Scooter` message itself is empty for all of them, therefore I removed the duplicate translation to enforce fallback to English for now.
Let me know if I did anything wrong. I tried looking through the contributing/developer guidelines, but could not find whether these files are actually intended to be edited or are generated via some tool.

Deduplicate lang string

---

docs/RouterConfiguration.md
src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/UpdatersConfig.java
src/main/java/org/opentripplanner/updater/TimetableSnapshotSourceParameters.java
src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
src/test/resources/standalone/config/router-config.json

While I was looking at how to configure Siri, I noticed that there is no documentation for the `timetableUpdates`. This PR adds that and also converts `snapshotFrequency` to a `Duration`.
Autogenerated.

Add documentation for timetable updater config, use duration

---

src/ext-test/java/org/opentripplanner/ext/siri/TimetableHelperTest.java
src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
src/main/java/org/opentripplanner/updater/spi/ResultLogger.java
src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionPatternMatcher.java

~I used the Siri-ET updater on a UK feed and noticed that it doesn't have arrival times in the middle of the trip (just the last stop). Therefore I'm using the departure time as a fallback when the arrival time doesn't exist.~
~Right now there is already code for that, but it's only applied to the first or last stop.~
~@lassetyr Will this change cause problems in Norway?~
This now does some very light refactoring and adds logging of the results to the Siri-ET updater.
Closes #5031

Log results of Siri-ET updates

---

src/main/java/org/opentripplanner/routing/api/request/preference/StreetPreferences.java
src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
src/test/java/org/opentripplanner/standalone/config/RouterConfigTest.java

Fixes issue with wrong `streetRoutingTimeout` value being used for initializing cached transfer requests.
closes https://github.com/opentripplanner/OpenTripPlanner/issues/5038
Improved existing test
Not needed
From title

Fix transferCacheRequests when custom streetRoutingTimeout is set

---

.github/workflows/cibuild.yml
magidoc.mjs

This generates a static HTML documentation for the GTFS GraphQL API.
This is useful for IBI customers who want to check out what the API can do without having to set up their own OTP instance.
If you want to check out what it looks like, here is an example: https://leonardehrenfried.github.io/OpenTripPlanner/api/dev-2.x/graphql-gtfs/v1/queries/agencies

Generate static documentation for GTFS GraphQL API

---

docs/BuildConfiguration.md
docs/RouteRequest.md
src/main/java/org/opentripplanner/graph_builder/module/osm/OpenStreetMapModule.java
src/main/java/org/opentripplanner/openstreetmap/tagmapping/ConstantSpeedMapper.java
src/main/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapper.java
src/main/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapperSource.java
src/main/java/org/opentripplanner/street/search/intersection_model/IntersectionTraversalCalculator.java
src/main/java/org/opentripplanner/street/search/intersection_model/IntersectionTraversalModel.java
src/test/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapperTest.java

Some minor changes in OSM tag mapping and intersection traversal modules to allow street routing, which finds shortest paths instead of optimising traversal time. This is achieved as follows:
- Car speed is requested via a tag mapper, so that full customisation is possible 
- New OSM tag mapper ignores speed limitation tagging of OSM and uses a single default speed
- The existing ConstantIntersectionTraversalCalculator is now available via configuration
Unit tests for the new OSM tag mapper included.

Constant speed street routing

---

pom.xml
src/main/java/org/opentripplanner/updater/spi/ResultLogger.java

In a previous PR #5023 I added JSON-formatted logging. This one actually uses that capability to its full power by adding so-called `StructuredMarkers` to logs statements.
This achieves that the (pretty-printed) log messages about the realtime updates in JSON look like this:
```
{
"@timestamp": "2023-04-18T22:59:58.514710284+02:00",
"level": "ERROR",
"logger_name": "org.opentripplanner.updater.spi.ResultLogger",
"thread_name": "GraphUpdater-2",
"message": "[feedId=MARTA type=gtfs-rt-trip-updates] 4 failures of errorType=NEGATIVE_DWELL_TIME: [MARTA:7675658{stopIndex=11}, MARTA:7700115{stopIndex=0}, MARTA:7819768{stopIndex=0}, MARTA:7674698{stopIndex=18}]",
"feedId": "MARTA",
"type": "gtfs-rt-trip-updates",
"errorType": "NEGATIVE_DWELL_TIME"
}
```
This allows you to filter out the messages …

Use structured log markers for realtime update results

---

doc-templates/SiriUpdater.md
doc-templates/UpdaterConfig.md
docs/RouterConfiguration.md
docs/UpdaterConfig.md
docs/sandbox/SiriUpdater.md
src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdaterParameters.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriSXUpdaterConfig.java
src/test/java/org/opentripplanner/generate/doc/SiriConfigDocTest.java
src/test/java/org/opentripplanner/generate/doc/UpdaterConfigDocTest.java
src/test/resources/standalone/config/router-config.json

This creates auto-generated documentation for the Siri-SX over HTTP updater.
It also uses a record for the parameters for the updater to reduce the number of lines.

Document Siri-SX updaters, use records for config

---

src/main/java/org/opentripplanner/updater/spi/PollingGraphUpdater.java
src/main/java/org/opentripplanner/updater/trip/GtfsRealtimeTripUpdateSource.java
src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java

When logging an exception for a polling updater, the call to log4j silently swallowed the exception due to a confusing method call.
By switching to string concatenation the method call correctly interprets the exception as such and logs it accordingly.
I added Javadoc about the reason for this unusual way of logging.
@hbruch

Fix logging of stacktraces for polling graph updater

---

src/main/java/org/opentripplanner/model/Timetable.java
src/main/java/org/opentripplanner/model/plan/FrequencyTransitLeg.java
src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
src/main/java/org/opentripplanner/transit/model/timetable/TripTimes.java
src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionPatternMatcher.java
src/test/java/org/opentripplanner/routing/trippattern/TripTimesTest.java
src/test/java/org/opentripplanner/updater/vehicle_position/VehiclePositionsMatcherTest.java

This is a follow up to #5078 where I realised that the vehicle positon code uses the stop index when it should use the GTFS sequence number.
This PR fixes that, refactors `TripTimes` lightly and improves the documentation.
Added.
Javadoc improved.

Use correct GTFS sequence number in vehicle position matcher

---

src/client/graphiql/index.html

This PR replaces #5095 and adds a select box so you can switch between the Transmodel and GTFS APIs in GraphiQL.
Closes #5095

Allow switching between GTFS and Transmodel APIs in GraphiQL

---

src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java

The SIRI ET PubSub updater does not release resources when it stops, preventing the server from shutting down gracefully.
This PR ensures that:
- the subscriber is properly closed on shutdown by calling Subscriber.stopAsync().
- the SubscriptionAdminClient is invoked inside a try-with-resource block, so that its internal resources are released.
No
No

Fix SIRI ET PubSub updater shutdown

---

.github/workflows/post-merge.yml

Ran into a problem that a post merge action was unable to update changelog even when rerunning the action. This should fix that issue but should we do this as this problem only occurs rarely?
This problem occured in https://github.com/opentripplanner/OpenTripPlanner/actions/runs/4948671568

Improve changelog update stability

---

src/main/java/org/opentripplanner/api/common/OTPExceptionMapper.java

Adds handling of JsonParseException - now returns a `400 Bad Request`. 
This typically occurs when GraphQL-requests contain malformed JSON.

Handle JsonParseException

---

src/main/java/org/opentripplanner/framework/lang/StringUtils.java
src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorSerializer.java
src/main/java/org/opentripplanner/netex/mapping/OperatorToAgencyMapper.java
src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionPatternMatcher.java
src/test/java/org/opentripplanner/framework/lang/StringUtilsTest.java

A common error in JavaScript is to set a request field to the string `"null"` and not use `null`. This is is logged on the OTP server side, and spam our logs. So I added a smal check for this. 
✅

fix: PageCursor decode of JS "null" (as String)

---

src/main/java/org/opentripplanner/standalone/config/framework/json/NodeAdapter.java
src/main/java/org/opentripplanner/standalone/config/framework/json/ParameterBuilder.java
src/test/java/org/opentripplanner/standalone/config/framework/json/NodeAdapterTest.java

Warnings in JSON config are not logged if they appear in a child element in the config.
I discovered this when testing PR #5106. 
Updated with a nested config element.
Not relevant.

fix: Log warnings in child nodes

---

src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPI.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
src/ext/java/org/opentripplanner/ext/transmodelapi/support/GraphQLToWebResponseMapper.java
src/main/java/org/opentripplanner/framework/concurrent/OtpRequestThreadFactory.java
src/main/java/org/opentripplanner/raptor/configure/RaptorConfig.java
src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
src/main/java/org/opentripplanner/standalone/OTPMain.java
src/main/java/org/opentripplanner/standalone/OtpStartupInfo.java
src/main/java/org/opentripplanner/standalone/server/GrizzlyServer.java
src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
src/main/resources/logback.xml
src/test/java/org/opentripplanner/OtpArchitectureModules.java
src/test/java/org/opentripplanner/raptor/RaptorArchitectureTest.java
src/test/resources/logback.xml

This PR contains a bit refactoring and small improvements . This is the base for 2 PR coming soon.
Recommend review commit by commit.
- refactor: Set thread names for better debugging and logg messages
- refactor: Extract mapper from GraphQL to Web response
- feature: Limit number of GraphQL errors returned in one request to 25 in the Transmodel API 
Some, not a lot - but most of this code is infrastructure and will break hard if there is bug.

Cleanup threads and error handling

---

src/main/java/org/opentripplanner/standalone/server/OTPWebApplication.java

The Jersey server is configured with the option ServerProperties.TRACING, but the provided value (Boolean.TRUE) is invalid and is ignored.
This results in a warning in the logs at application startup:
`There is no way how to transform value "true" [java.lang.Boolean] to type [java.lang.String].`
The value should be either "OFF" (default), "ON_DEMAND", or "ALL".
The documentation mentions that:
> the feature should not be switched on on production environment.
This PR removes the configuration of this parameter.
No
No

Remove broken Jersey tracing configuration

---

doc-templates/RouteRequest.md
docs/RouteRequest.md
mkdocs.yml
src/test/java/org/opentripplanner/generate/doc/RouteRequestDocTest.java
src/test/java/org/opentripplanner/generate/doc/framework/JsonExampleBuilder.java
src/test/java/org/opentripplanner/generate/doc/framework/TemplateUtil.java

Adds a JSON example to the route request documentation page.
It also moves the configuration item in the docs menu to the top level. To me this looks a lot less busy and feels quite natural.
Yes.

Add example JSON to route request documentation, move configuration to top level in menu

---

docs/RouteRequest.md
src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/transmodelapi/model/timetable/InterchangeType.java
src/main/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessor.java
src/main/java/org/opentripplanner/gtfs/mapping/TransferMapper.java
src/main/java/org/opentripplanner/model/TripStopTimes.java
src/main/java/org/opentripplanner/model/transfer/TransferConstraint.java
src/main/java/org/opentripplanner/model/transfer/TransferPriority.java
src/main/java/org/opentripplanner/netex/mapping/TransferMapper.java
src/main/java/org/opentripplanner/raptor/api/request/DynamicSearchWindowCoefficients.java
src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
src/test/java/org/opentripplanner/model/transfer/ConstrainedTransferTest.java
src/test/java/org/opentripplanner/model/transfer/TransferConstraintTest.java
src/test/java/org/opentripplanner/model/transfer/TransferServiceTest.java
src/test/java/org/opentripplanner/raptor/_data/transit/TestTransitData.java
src/test/java/org/opentripplanner/raptor/api/path/PathTest.java
src/test/java/org/opentripplanner/raptor/moduletests/E01_StaySeatedTransferTest.java
src/test/java/org/opentripplanner/raptor/moduletests/E02_GuaranteedTransferTest.java
src/test/java/org/opentripplanner/raptor/moduletests/E02_GuaranteedWalkTransferTest.java
src/test/java/org/opentripplanner/raptor/moduletests/E03_NotAllowedConstrainedTransferTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/constrainedtransfer/ConstrainedBoardingSearchTest.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainServiceConstrainedTest.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TestTransferBuilder.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransferGeneratorTest.java

Add/update Raptor module tests to document StaySeated/Interlining and Guaranteed transfers.
This PR is a response to a question raised as part of #5086. 
> Can staySeated/interline transfers with zero time to do the transfer have walking leg with a duration?
Answer: Yes, and the Raptor Module tests now documents this feature. 
✅  This PR only add tests.

Add stay seated test

---

.github/workflows/cibuild.yml
src/ext/resources/legacygraphqlapi/schema.graphqls

@miles-grant-ibigroup has pointed out that documentation about the flex fields for special pick up/drop off restrictions was missing so I added it.
Whilst I was working on the schema I also moved the deprecated fields of the `plan` query to the bottom.
It also improves the build pipeline for the static HTML docs so that they are pushed to Github Pages only when the schema has actually changed.

Add documentation about flex booking info, cleanup deprecated fields

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPI.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
src/ext/java/org/opentripplanner/ext/transmodelapi/support/AbortOnTimeoutExecutionStrategy.java
src/ext/java/org/opentripplanner/ext/transmodelapi/support/GraphQLToWebResponseMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/support/OtpExecutionResult.java
src/main/java/org/opentripplanner/api/common/OTPExceptionMapper.java
src/main/java/org/opentripplanner/api/resource/PlannerResource.java
src/main/java/org/opentripplanner/framework/application/OTPRequestTimeoutException.java
src/main/java/org/opentripplanner/framework/logging/ProgressTracker.java
src/main/java/org/opentripplanner/framework/time/TimeUtils.java
src/main/resources/logback.xml

We want to return HTTP Status code 422, and not 500 for timeouts.
Handle SYSTEM_ERROR and PROCESSING_TIMEOUT the same way. Timeout and
system-error will show up in the OTP Debug Client.   
The busyWaitOnce() is a method witch make it possible to test timeouts
without interfering with the interrupts.
The data-fetchers do not abort when a timeout occurs. This commit
improves on the situation and in the end causes the GraphQL instance
to exit with a timeout exception.
The "notprivacysafe.graphql" logger should be turned off to prevent
the TimeOut exception to be logged. The `AbortOnTimeoutExecutionStrategy`
will log the timeout. There might be more than 100 000 pending data-fetchers 
witch all are inerrupted with a timeout, so we use the progress logger:
```
17:51:02.872 INFO [grizzly-0] …
```

Graceful timeout error handling

---

src/main/java/org/opentripplanner/astar/AStar.java
src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
src/main/java/org/opentripplanner/street/search/state/State.java
src/test/java/org/opentripplanner/street/model/edge/StreetEdgeGeofencingTest.java

In #4841 I have overlooked a single statement returning `null` rather than the empty array. This fixes it and updates the tests.
Adjusted.

Don't return null from StreetEdge#traverse

---

src/ext/java/org/opentripplanner/ext/flex/edgetype/FlexTripEdge.java
src/main/java/org/opentripplanner/graph_builder/module/GraphCoherencyCheckerModule.java
src/main/java/org/opentripplanner/routing/graph/index/StreetIndex.java
src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
src/main/java/org/opentripplanner/street/model/edge/Edge.java
src/main/java/org/opentripplanner/street/model/vertex/Vertex.java

As detailed in #5128, a race condition can occur when a temporary edge is removed in a thread while another thread uses it for street routing.
This PR ensures that the "from" and "to" vertices connected to an edge are non-nullable and immutable, thus preventing concurrency issues.
- The "fromv" and "tov" fields in the Edge class are made final.
- The FlexTripEdge class is refactored to prevent it from modifying its vertices during construction.
- The Edge.remove() method is refactored so that it does not nullify the reference to vertices during removal.
- The Edge.removeEdge() method is refactored so that multiple calls do not trigger error messages. The method is idempotent, so multiple calls should not be problematic.
- Logic that tested fromv==null and tov==null is refactored
partially …

Fix vertex removal race condition

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPI.java

As fare as we know, the Transmodel GraphQL batch API is unused. We do not want to maintain this and do not see that there is a use-case for it. So this PR deletes it. If you are using this please let us know!

Remove batch query from Transmodel API

---

src/main/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessor.java
src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java
src/main/java/org/opentripplanner/model/calendar/CalendarServiceData.java
src/test/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessorTest.java

Changes block_id based interline generation to work according to the GTFS specification. This means that we check that trips share the same service date(s) instead of service id. Multiple transfers can be created from one from trip if one to trip doesn't cover all the service dates of the from trip.
closes #5099
Added tests
Not needed
from title

Check service dates instead of service ids for block id transfers

---

src/ext/java/org/opentripplanner/ext/siri/ModifiedTripBuilder.java
src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoader.java

1. Fetching data from a vehicle rental feed can fail, for example due to a temporary network error. This is retryable and should be logged at warning level, not error level.
2. The Siri updater logs 2 messages when receiving an invalid real time update. These 2 messages can be combined in one.
No
No

Improve updater log messages

---

src/main/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapper.java
src/test/java/org/opentripplanner/netex/NetexTestDataSupport.java
src/test/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapperTest.java

A NeTEx operating period can be defined either by a pair (start date, end date) or a pair (start operating day, end operating day).
This PR implements support for the latter.
No
No

Add support for mapping NeTEx operating day in operating period

---

src/ext-test/java/org/opentripplanner/ext/flex/FlexPathDurationsTest.java
src/ext/java/org/opentripplanner/ext/flex/FlexPathDurations.java
src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/FlexPath.java

The current validity check on flex trip duration is too strict. It is possible to have flex trips with null duration due to the timetable resolution (usually 1 min): a flex trip between two close stops may appear to take 0 second.
This is observed in our production environment where valid trips are rejected:
```
java.lang.IllegalArgumentException: The trip duration must be a positive number.
at org.opentripplanner.ext.flex.FlexPathDurations.<init>(FlexPathDurations.java:32)
at org.opentripplanner.ext.flex.template.FlexAccessTemplate.calculateFlexPathDurations(FlexAccessTemplate.java:133)
at org.opentripplanner.ext.flex.template.FlexAccessTemplate.lambda$createDirectGraphPath$0(FlexAccessTemplate.java:69)
at java.base/java.util.Optional.map(Optional.java:260)
at …
```

Relax validity check on flex trip with null duration

---

src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsStationStatusMapper.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSource.java

As reported in #5174, some GBFS updates fail with a NullPointerException when the status update refers to unexpected vehicle types.
This PR filters out unexpected vehicle types and logs a warning message for facilitating further analysis of this issue.
Partially closes #5174 
No

Log unexpected vehicle type in GBFS update

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
src/main/java/org/opentripplanner/api/resource/PlannerResource.java
src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
src/main/java/org/opentripplanner/routing/error/RoutingValidationException.java
src/main/java/org/opentripplanner/routing/service/DefaultRoutingService.java
src/test/java/org/opentripplanner/routing/core/RouteRequestTest.java

As detailed in #5163, The Transmodel API does not properly report invalid routing requests that do not define the origin or the destination of the search.
This PR adds validation for missing origin or destination in routing requests.
The Transmodel API returns then a specific error message:
```
{
"data": {
"trip": {
"nextPageCursor": null,
"previousPageCursor": null,
"tripPatterns": [],
"routingErrors": [
{
"code": "locationNotFound",
"inputField": "to",
"description": "Destination is unknown.  Can you be a bit more descriptive?"
}
]
}
}
}
```
The REST API returns also a specific error message:
```
{
"requestParameters": {
"date": "04-25-2023",
"mode": "FLEX_ACCESS,FLEX_EGRESS,TRANSIT",
"fromPlace": "61.11741770786395,10.451345443725588",
"time": "2:28pm"
},
"error": {
"id": 450,
"msg": …
```

Validate to/from in routing request

---

docs/RouterConfiguration.md
docs/examples/entur/router-config.json
docs/sandbox/SiriUpdater.md
src/ext-test/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandlerTest.java
src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
src/ext/java/org/opentripplanner/ext/siri/SiriHttpUtils.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdaterParameters.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriHelper.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdaterParameters.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
src/main/java/org/opentripplanner/framework/time/DurationUtils.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriETUpdaterConfig.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriSXUpdaterConfig.java
src/test/java/org/opentripplanner/framework/time/DurationUtilsTest.java
src/test/resources/standalone/config/router-config.json

Changing default value for `earlyStartSec` for SIRI SX-messages.
This value is [subtracted](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java#L150) from the actual validity defined in the message - causing validity-period to start a second later than defined. When a SX-message's validity is set to start from the planned departure-time, this will cause the message to not be included in trip-results.
I.e.: 
If message starts at 12:00:00, subtracting (-1) will make the message start at 12:00:01
Setting the default value to 0 will let the actual validity provided to be used.

Changing default value for earlyStartSec

---

src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/OptimizeTransferService.java

OTP may fail to optimize transfers due to code or data issues:
```
Unable to optimize transfers in path. Details: No value present, path: Walk 7s ~ 37439 ~ BUS 100 @12123 13:03 13:11 ~ 73210 ~ BUS 120 @12013 13:12 13:35 ~ 76169 ~ Walk 1s ~ 76168 ~ BUS 121 @12521 14:10 14:31 ~ 6675 ~ Walk 38m24s [13:02:53 15:09:24 2h6m31s 2tx $29759]
java.util.NoSuchElementException: No value present
at java.base/java.util.Optional.orElseThrow(Optional.java:377)
at org.opentripplanner.routing.algorithm.transferoptimization.services.TransferGenerator.findMinimumToStopTime(TransferGenerator.java:243)
at org.opentripplanner.routing.algorithm.transferoptimization.services.TransferGenerator.findAllPossibleTransfers(TransferGenerator.java:71)
at org.opentripplanner.routing.algorithm.transferoptimization.services. …
```

Reduce log severity for non-optimized transfers

---

src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/api/VehicleRentalServiceDirectoryFetcherParameters.java
src/main/java/org/opentripplanner/framework/io/HttpUtils.java
src/main/java/org/opentripplanner/updater/alert/GtfsRealtimeAlertsUpdater.java

Improve error handling and prevent OTP from going down when connecting to external http services.
The fix apply to all updaters using the `HttpUtils.getData()` methods. But, the error observed at Entur does only apply to the `VehicleRentalServiceDirectoryFetcher`. The fix improve the log messages for all Updaters when a remote service is unavailable.
The VehicleRentalServiceDirectoryFetcher went down with a IllegalSateException when the http endpoint failed (`getData(...)` retuned `null`. Instead of returning `null` in some error-cases and throwing IOExceptions in others the HttpUtils is changed to throw an IOException in all cases. This make it more robust, and the checked exception forces the client to handle it.
There is no issue for this.
No tests added.
Small improvement on JavaDoc …

Improve vehicle rental service directory error handling

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java

Removes walk between two trips that have a stay seated transfer. OTP1 did not have a walk leg in an interline transfer.
closes #5086
TODO
Not needed
From title

Remove walk leg in a stay seated transfer

---

docs/BuildConfiguration.md
src/main/java/org/opentripplanner/openstreetmap/tagmapping/ConstantSpeedMapper.java
src/main/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapperSource.java
src/test/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapperTest.java

- Default tag mapping is US specific and works badly in Finland, so derive constant speed mapping from Finnish rules
- Rename the tag mapper to reflect that it is now specific to Finland

Rename OSM constanspeed tag mapper and derive it from finland tag mapper

---

src/ext-test/java/org/opentripplanner/ext/transmodelapi/support/GqlUtilTest.java
src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/support/GqlUtil.java

Closes #4988 
This PR adds new arguments to StopPlace.name and Quay.name called `language` to replace the `lang` arguments, and marks the latter as deprecated. The datafetcher now uses GraphQLUtils.getLocale with the old argument value as a fallback.
The generated GraphQL schema is missing @deprecated directive on the old 'lang' arguments. This seems intentional: https://github.com/graphql-java/graphql-java/issues/1598, but I guess the generated schema is only used for verifying / testing.
When I run GraphiQL locally, the deprecated arguments can't be seen in the documentation explorer - there's no "Show deprecated" on StopPlace.name or Quay.name. In addition Graphiql doesn't recognize the deprecated argument (shows a squiggly red line). But when I run the query using the deprecated …

 Add "language" argument to Quay and StopPlace types in transmodel api and deprecate "lang" argument

---

src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/flex/FlexRouter.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLUtils.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLPlanner.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
src/ext/java/org/opentripplanner/ext/transmodelapi/support/OtpExecutionResult.java
src/main/java/org/opentripplanner/astar/AStar.java
src/main/java/org/opentripplanner/framework/application/OTPRequestTimeoutException.java
src/main/java/org/opentripplanner/framework/time/TimeUtils.java
src/main/java/org/opentripplanner/graph_builder/module/NearbyStopFinder.java
src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgressRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectFlexRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectStreetRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/FlexAccessEgressRouter.java
src/main/java/org/opentripplanner/routing/api/response/RoutingErrorCode.java
src/main/java/org/opentripplanner/routing/impl/GraphPathFinder.java
src/main/java/org/opentripplanner/routing/service/DefaultRoutingService.java
src/main/resources/logback.xml

In the Transmodel API plan query the `OTPProcessingTimeoutGraphQLException` was caught and retuned as a routing-error, this resulted in this error to be reported with HTTP status code 200, and not 422 as wanted. 
The `processingTimeout` is removed from the `RoutingErrorCode` enum (Transmodel API). This is a potensial breaking change if the client use some sort of API code generation, but it should not affect runtime - only compile time. The processing timeout was not added to the Legacy API.
No issue for this.
Code removed, no tests changed.
No
No
No

Allow timeout exception to propagate to Transmodel GraphQL error handling

---

src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
src/test/java/org/opentripplanner/graph_builder/linking/LinkStopToPlatformTest.java

1. Vertex linker now checks access restrictions (no thru traffic) when connecting new vertices with surrounding area edges. Previously there was a bug that walk routing could not exit areas tagged as access=private or access=destination.
2.  Vertex linker no longer connects linked vertex inside an area with all visibility points, if the vertex was snapped  to an existing visibility vertex due to small distance.  Snapped visibility vertex already has the  visibility connections, so there is no need to generate a new set of them. This fixes  extremely slow linking near vertices which have many (sometimes over 100) existing connections. 
3. Vertex linker now has upper limit for visibility point connections.  It is currently defined as class constant just like other linking parameters. It now …

Area vertex linking improvements

---

pom.xml
src/main/java/org/opentripplanner/netex/mapping/FlexStopsMapper.java
src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/main/java/org/opentripplanner/transit/model/site/RegularStop.java
src/test/java/org/opentripplanner/netex/mapping/FlexStopsMapperTest.java

Currently only the first FlexibleArea in a NeTEX FlexibleStopPlace is parsed. Modify the code to create a GrupStop if multiple areas exist.

Allow multiple FlexibleAreas in a FlexibleStopPlace

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceTest.java
src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
src/ext-test/resources/legacygraphqlapi/expectations/plan-fares.json
src/ext-test/resources/legacygraphqlapi/expectations/plan.json
src/ext-test/resources/legacygraphqlapi/queries/plan-fares.graphql
src/ext-test/resources/legacygraphqlapi/queries/plan.graphql
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/LegacyGraphQLIndex.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLDefaultFareProductImpl.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/datafetchers/LegacyGraphQLFareProductTypeResolver.java
src/ext/java/org/opentripplanner/ext/legacygraphqlapi/generated/LegacyGraphQLDataFetchers.java
src/ext/resources/legacygraphqlapi/schema.graphqls
src/main/java/org/opentripplanner/model/fare/FareProduct.java
src/main/java/org/opentripplanner/model/fare/ItineraryFares.java
src/main/java/org/opentripplanner/routing/core/FareComponent.java
src/main/java/org/opentripplanner/routing/core/FareType.java

After adding an improved API for fares in #4935 @daniel-heppner-ibigroup has tried it out and has requested there to be a change which accommodates a use case that is important for IBI customers: a discounted transfer ticket where a passenger pays a reduced fare. (We had originally debated that but decided not to do it.)
Since the debate how exactly it needs to be modeled has not been finished yet, I would like to pre-emptively make the `FareProduct` an interface so we don't need to rush to decide the correct type structure..
:bomb: This is a breaking API change :bomb: 
Relates to #4935
Tests updated.
API docs are automatically updated.

Preemptively make a GraphQL FareProduct an interface

---

pom.xml
src/main/java/org/opentripplanner/model/Timetable.java
src/main/java/org/opentripplanner/model/TimetableSnapshot.java
src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionPatternMatcher.java
src/test/java/org/opentripplanner/updater/vehicle_position/VehiclePositionsMatcherTest.java

@amy-corson-ibigroup has reported that the vehicle position updater can run into a `NullPointerException` that then stops all further updates.
This PR checks for that condition and returns a clean error so that other updates can continue. However, more research is necessary why this happens in the first place.
Added.
We discussed this in a previous dev meeting and we agreed that we want to try a new test reporter for the console, which are the changes in the pom.
It looks like this:

Prevent NPE in vehicle position matching

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2ServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2Service.java
src/ext/java/org/opentripplanner/ext/fares/model/Distance.java
src/ext/java/org/opentripplanner/ext/fares/model/FareLegRule.java
src/ext/java/org/opentripplanner/ext/fares/model/FareLegRuleBuilder.java
src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceRepository.java
src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
src/main/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapper.java
src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionPatternMatcher.java
src/test/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapperTest.java
src/test/java/org/opentripplanner/transit/model/timetable/TripTimesTest.java

The actual core of the PR is quite simple: the `FareLegMapper` was not null-aware and caused an NPE when no distance type was set.
On top of the actual bug fix, I made the following improvements:
- Introduce a builder for `FareLegRule` so that you don't have to pass so many `nulls` to the constructor
- Refactored some tests
A new unit test was added where I experimented with the `@TestFactory` annotation.
cc @lslangley @drewda

Fix fare leg rule mapper, introduce builder

---

pom.xml
src/ext/java/org/opentripplanner/ext/actuator/ActuatorAPI.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceMetadata.java
src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceRepository.java
src/main/java/org/opentripplanner/framework/io/OtpHttpClient.java
src/main/java/org/opentripplanner/standalone/server/EtagRequestFilter.java
src/main/java/org/opentripplanner/updater/spi/PollingGraphUpdater.java
src/main/resources/logback.xml
src/test/java/org/opentripplanner/datastore/DataStoreArchitectureTest.java
src/test/java/org/opentripplanner/datastore/https/HttpsDataSourceRepositoryTest.java
src/test/java/org/opentripplanner/datastore/https/HttpsFileDataSourceTest.java
src/test/java/org/opentripplanner/framework/FrameworkArchitectureTest.java

This PR upgrades the Apache HTTP client library from v4 to v5.
- The API remains mostly unchanged.
- v5 adds support for HTTP/2.
- v5 uses different Maven coordinates, upgrading will not impact transitive dependencies of other libraries. 
Note: v5 introduces also new default values for connection pooling and TTL. Since the OtpHttpClient is currently not reused, this has no impact.
OtpHttpClient reuse and HTTP connection pooling will be addressed in a separate PR.
No
No

Upgrade to Apache HTTP Client 5

---

src/test/java/org/opentripplanner/transit/speed_test/model/timer/MeterRegistrySetup.java
src/test/java/org/opentripplanner/transit/speed_test/model/timer/SpeedTestTimer.java

Version 1.11.1 of micrometer has [changed the behaviour of the `StepRegistry`](https://github.com/micrometer-metrics/micrometer/commit/b0be362f4a5fb2e092fb6ff0c4bc770b7edb7b91) which we use to collect the results of the speed test. This change has resulted in the speed test results being published twice for each run.
This PR attempts to work around this problem by allowing our custom micrometer repository to explicitly push to InfluxDB rather than doing it on close.
I agree that this isn't a particularly nice solution. In the future I would like to spend some time on rewriting this registry to make it more elegant.

Fix duplicate publishing of speed test data

---

src/ext/java/org/opentripplanner/ext/dataoverlay/EdgeUpdaterModule.java
src/ext/java/org/opentripplanner/ext/flex/FlexLocationsToStreetEdgesMapper.java
src/ext/java/org/opentripplanner/ext/transferanalyzer/DirectTransferAnalyzer.java
src/main/java/org/opentripplanner/graph_builder/issue/report/DataImportIssueReporter.java
src/main/java/org/opentripplanner/graph_builder/model/GraphBuilderModule.java
src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
src/main/java/org/opentripplanner/graph_builder/module/GraphCoherencyCheckerModule.java
src/main/java/org/opentripplanner/graph_builder/module/OsmBoardingLocationsModule.java
src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
src/main/java/org/opentripplanner/graph_builder/module/TimeZoneAdjusterModule.java
src/main/java/org/opentripplanner/graph_builder/module/TripPatternNamer.java
src/main/java/org/opentripplanner/graph_builder/module/geometry/CalculateWorldEnvelopeModule.java
src/main/java/org/opentripplanner/graph_builder/module/islandpruning/PruneIslands.java
src/main/java/org/opentripplanner/graph_builder/module/map/BusRouteStreetMatcher.java

Right now implementing a `GraphBuilderModule` forces you to add a `checkInputs` method. For 3/4 of the modules this is an empty method that does nothing and only a few have some actual logic .
For this reason I want to add a default implementation (a noop) and only have those few modules implement the method that need it.

Provide default implementation for checkInputs()

---

src/main/java/org/opentripplanner/street/model/edge/PathwayEdge.java
src/test/java/org/opentripplanner/street/model/edge/PathwayEdgeTest.java

If `traversal_time` was not specified for a pathway, the distance-based traversal time was calculated using `time = distance * speed` instead of `time = distance / speed`.
This updates the calculation.
:x:
:ballot_box_with_check: - existing tests are updated
No changes.
:x:

Fix pathway traversal time calculation when none is supplied

---

.github/workflows/performance-test.yml
src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripTest.java
src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParkingEntrance.java
src/main/java/org/opentripplanner/service/vehiclerental/street/VehicleRentalPlaceVertex.java
src/main/java/org/opentripplanner/street/model/vertex/ElevatorOffboardVertex.java
src/main/java/org/opentripplanner/street/model/vertex/ElevatorOnboardVertex.java
src/main/java/org/opentripplanner/street/model/vertex/IntersectionVertex.java
src/main/java/org/opentripplanner/street/model/vertex/LabelledIntersectionVertex.java
src/main/java/org/opentripplanner/street/model/vertex/OsmBoardingLocationVertex.java
src/main/java/org/opentripplanner/street/model/vertex/OsmVertex.java
src/main/java/org/opentripplanner/street/model/vertex/SplitterVertex.java
src/main/java/org/opentripplanner/street/model/vertex/StationElementVertex.java
src/main/java/org/opentripplanner/street/model/vertex/StreetLocation.java
src/main/java/org/opentripplanner/street/model/vertex/StreetVertex.java
src/main/java/org/opentripplanner/street/model/vertex/TransitStopVertex.java
src/main/java/org/opentripplanner/street/model/vertex/VehicleParkingEntranceVertex.java
src/main/java/org/opentripplanner/street/model/vertex/Vertex.java
src/main/java/org/opentripplanner/street/model/vertex/VertexFactory.java
src/test/java/org/opentripplanner/graph_builder/linking/LinkStopToPlatformTest.java
src/test/java/org/opentripplanner/graph_builder/module/geometry/CalculateWorldEnvelopeModuleTest.java
src/test/java/org/opentripplanner/street/model/_data/StreetModelForTest.java
src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
src/test/java/org/opentripplanner/street/model/vertex/IntersectionVertexTest.java
src/test/java/org/opentripplanner/street/model/vertex/SimpleVertex.java
src/test/java/org/opentripplanner/street/model/vertex/TemporaryVertexDisposeTest.java
src/test/java/org/opentripplanner/street/search/intersection_model/SimpleIntersectionTraversalCalculatorTest.java

Very few vertices have a name that provides useful information that is not already in the label, yet every instance needs to pass a name into the super constructor.
This is needlessly complex to implement and also wastes some memory.
For this reason I have refactored the `Vertex` base class to not store the name and each subclass is responsible for implementing the method. Most implementations don't provide any additional, useful information that's not already in the label but a handful do.
The savings are small, but visible: the heap space in the Norway graph is reduced by 20MB, so 0.5%.

Remove name from vertex constructor chain

---

src/main/java/org/opentripplanner/graph_builder/module/osm/EscalatorProcessor.java
src/main/java/org/opentripplanner/street/model/edge/EscalatorEdge.java
src/test/java/org/opentripplanner/street/model/edge/ElevatorHopEdgeTest.java
src/test/java/org/opentripplanner/street/model/edge/EscalatorEdgeTest.java
src/test/java/org/opentripplanner/street/model/edge/PathwayEdgeTest.java

While @nurmAV was [adding the new `EscalatorEdge`](https://github.com/opentripplanner/OpenTripPlanner/pull/5046/), @vpaturet also [refactored the edge construction](https://github.com/opentripplanner/OpenTripPlanner/pull/5221) so that you explicitly need to insert an edge into the graph.
These two features were merged at similar times so that now the escalator edges are not added to the graph.
This PR fixes that problem by introducing a factory method in line with all the other edges.

Insert escalators into graph after construction

---

src/main/java/org/opentripplanner/framework/io/HttpUtils.java
src/main/java/org/opentripplanner/inspector/vector/VectorTileResponseFactory.java
src/test/java/org/opentripplanner/inspector/vector/VectorTileResponseFactoryTest.java

When a client requests a vector tile layer that doesn't exist, then OTP returns a 404 with an error message.
However, the content type is set to "application/x-protobuf" causing browsers to not show the error message.
This PR changes this by setting an explicit content type.
cc @hbruch

Fix content type of vector tiles 404

---

src/test/java/org/opentripplanner/routing/core/MoneyTest.java

The behavior of money formatting for the nynorsk locale has been modified recently (https://bugs.openjdk.org/browse/JDK-8295564), making some tests fail.
This PR temporary disables these tests.
No
No

Disable nynorsk money tests

---

src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriHttpLoader.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java

This PR fixes a bug in the retry logic of the SIRI SX updater introduced in  #5213:
The SIRI SX updater maintains a session with the SIRI SX server by marking each SIRI request with a unique requestorRef.
The server uses this requestorRef to identify which messages have already been sent to that client and filter them out of the response.
When a network issue causes a request to fail, the session is left in an unknown state and the SIRI SX updater should reset it by sending a new requestorRef.
The ability to send a new requestorRef is broken since #5213.
No
No

Fix SIRI SX retry logic

---

src/main/java/org/opentripplanner/standalone/server/MetricsLogging.java
src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java
src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
src/main/java/org/opentripplanner/updater/spi/PollingGraphUpdater.java
src/main/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdater.java
src/test/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdaterTest.java
src/test/java/org/opentripplanner/updater/vehicle_rental/VehicleRentalUpdaterTest.java

This PR introduces a scheduled thread pool for polling graph updaters.
This allows for:
* Better controlling the parallelism of polling updaters.
This is important for OTP deployments where a large number of updaters are configured, especially for GBFS updaters that tend to be numerous and frequently updated.
In the current implementation, all updaters are launched at once during OTP startup, which may cause overloading issues. 
*  Replacing custom scheduling logic by standard Java features.
This PR sets the maximum number of parallel polling updater tasks to the number of available cores in the system, but no less than 6 to ensure a reasonable level of parallelism on instances with low core count. This can be made configurable in a subsequent PR if needed.
The behaviour of non-polling …

Configure scheduled thread pool for polling updaters

---

src/main/java/org/opentripplanner/routing/api/request/request/filter/SelectRequest.java
src/main/java/org/opentripplanner/routing/api/request/request/filter/TransitFilterRequest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RouteRequestTransitDataProviderFilterTest.java
src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java

As reported in #5255, filtering by submode does not work in the Transmodel API.
This PR fixes the logic for the special case where an exclusion filter (ex: banned authorities) is used together with a submode filter.
Closes #5255 
Added unit tests.
No

Fix filtering by submode

---

docs/Container-Image.md

When trying to build graph and start OTP using containers, there were some missing notes that are helpful when build or run fails. This PR addes minor notes to aid the "onboarding".
Error messages when building graph were not clear, that the GTFS files should contain the string "gtfs" in their names. Also when using a big osm.pbf file, users are much likely to see out-of-memory message. Adding parameter to use more memory should solve that issue.
No needed unit tests, as this PR only changes docs.
Changes to Container-Image.md file wihin /docs folder.

Adding minor notes to Container-Image.md doc file

---

.github/workflows/cibuild.yml
src/client/graphiql/index.html
src/ext/resources/gtfsgraphqlapi/schema.graphqls

There has been some confusion when implementing the new fare API so I thought I improve the documentation with illustrative examples of how useId and product id work together. I hope this will make implementation of this, admittedly complex, API a little easier.
I also upgraded GraphiQL and magidoc (HTML doc generator) to the newest version.

Add illustrations to fare docs, upgrade GraphiQL

---

src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/GraphQLIntegrationTest.java
src/ext-test/resources/gtfsgraphqlapi/expectations/patterns.json
src/ext-test/resources/gtfsgraphqlapi/expectations/plan-extended.json
src/ext-test/resources/gtfsgraphqlapi/queries/patterns.graphql
src/ext-test/resources/gtfsgraphqlapi/queries/plan-extended.graphql
src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/LegImpl.java
src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/generated/GraphQLDataFetchers.java
src/ext/resources/gtfsgraphqlapi/schema.graphqls
src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java

@binh-dam-ibigroup has reported that in the GTFS GraphQL API a leg's headsign (as opposed the trip's) is not available, even though the internal model already contains the field and it was previously returned in the REST API.
This PR adds it.
Added.
Added.

Add leg.headsign to GTFS GraphQL API

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelAPI.java

When receiving a GraphQL query in JSON format, the Transmodel API expects the query part to be a valid JSON string.
If the query part contains a structured object instead:
```
{
"query":{"q1":"Query1", "q2":"Query2"}
}
```
the request fails with the following message :
```
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap') class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
```
and returns an error code 500 - Internal Server Error.
This PR ensures that the client receives a meaningful error message and an error code 400 - Bad Request.
No …

Return client error for invalid Transmodel query JSON format

---

pom.xml
src/ext-test/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2ServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresService.java
src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2Service.java
src/ext/java/org/opentripplanner/ext/fares/model/FareLegRule.java
src/ext/java/org/opentripplanner/ext/fares/model/FareLegRuleBuilder.java
src/ext/java/org/opentripplanner/ext/fares/model/FareTransferRule.java
src/ext/java/org/opentripplanner/ext/fares/model/LegProducts.java
src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java
src/main/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/FareProductMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/FareTransferRuleMapper.java
src/main/java/org/opentripplanner/model/fare/FareProduct.java
src/main/java/org/opentripplanner/model/fare/FareProductBuilder.java
src/main/java/org/opentripplanner/model/fare/ItineraryFares.java
src/test/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapperTest.java
src/test/java/org/opentripplanner/gtfs/mapping/FareTransferRuleMapperTest.java

This updates OTP to support the changes made in https://github.com/OneBusAway/onebusaway-gtfs-modules/pull/221, it isn't complete and only makes the necessary changes to get OTP to compile and build successfully using the onebusaway-gtfs-modules changes.
Related to https://github.com/OneBusAway/onebusaway-gtfs-modules/pull/220, still need to create an issue in this repo for the changes to OTP
- Tests were only updated to support the type changes, no further verification was done
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205077941778171

Support Fares v2 FareMedium and update spec implementation

---

src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java
src/main/java/org/opentripplanner/graph_builder/module/ned/MissingElevationHandler.java
src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
src/main/java/org/opentripplanner/street/model/edge/StreetEdgeBuilder.java
src/main/java/org/opentripplanner/street/model/edge/StreetElevationExtension.java
src/main/java/org/opentripplanner/street/model/edge/StreetElevationExtensionBuilder.java
src/test/java/org/opentripplanner/graph_builder/module/ned/MissingElevationHandlerTest.java
src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java
src/test/java/org/opentripplanner/street/model/edge/StreetEdgeWheelchairCostTest.java
src/test/java/org/opentripplanner/street/model/edge/StreetElevationExtensionBuilderTest.java

When creating a split edge, some properties are copied from the parent edge to the split edge. Currently the copying happens after the split edge is constructed and connected to the graph, leaving a short time window where the split edge is not fully configured but already accessible from other threads.
This PR moves the copying of parent properties in the StreetEdge builder, before the edge is connected to the graph.
Note: only final fields initialized in the constructor are guaranteed to be thread-safe ([JLS 17.5](https://docs.oracle.com/javase/specs/jls/se17/html/jls-17.html#jls-17.5)). Since some of the copied fields are not final, it is still theoretically possible that they become visible from other threads before they are initialized.
No
No

Refactor copy properties from parent edge to split edge

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java
src/ext/java/org/opentripplanner/ext/transmodelapi/support/ExecutionResultMapper.java
src/main/java/org/opentripplanner/api/common/OTPExceptionMapper.java

Since #5192 client errors (bad requests) must be handled in TransmodelGraph, so the fix implemented in #5133 for mapping CoercingParseValueException does not work anymore and the API returns the following response with HTTP code _500 - Internal Server Error:_
```
{
"errors": [
{
"message": "Expected type 'DateTime' but was '2023-08'.",
"locations": [],
"extensions": {
"classification": "InternalServerError"
}
}
]
}
```
This PR ensures that CoercingParseValueException is mapped to HTTP code _400 - Bad Request_ with the following GraphQL response:
```
{
"errors": [
{
"message": "Expected type 'DateTime' but was '2023-08'.",
"locations": [],
"extensions": {
"classification": "BadRequestError"
}
}
]
}
```
**Note**: JSON parsing errors (JsonParseException) are caught before entering …

Map CoercingParseValueException

---

src/main/java/org/opentripplanner/routing/api/request/framework/LinearFunctionSerialization.java
src/test/java/org/opentripplanner/routing/api/request/framework/LinearFunctionSerializationTest.java
src/test/java/org/opentripplanner/test/support/TestTableParser.java

Som of the APIs expose the linear function to configure itinerary filters. Before the #5267 it was allowed to pass in a decimal number in the constant part of this function. In #5267 only a integer and a duration was allowed. This created an issue with existing clients(at Entur). I have now added support for decimal numbers. Support for integer and duration is kept.
There is no issue for this fix.
Unit tests are added for the regression tests.
We do not want people to pass in decimal numbers in the constant part of a linear function, so the doc is NOT changed.
Skip  chanelog, since this fixes a PR merged in the same version(2.4)
No

Add support for decimal numbers in the constant part of a linear function

---

src/main/java/org/opentripplanner/routing/api/request/preference/WalkPreferences.java
src/test/java/org/opentripplanner/routing/api/request/preference/ImmutablePreferencesAsserts.java
src/test/java/org/opentripplanner/routing/api/request/preference/WalkPreferencesTest.java

Fixes issue with walkBoardCost equal comparison used in transfer cache and adds escalatorReluctance to hash.
Closes #5309
Added
not needed
From title

Fix walk board cost comparison and add escalatorReluctance to hash

---

src/main/java/org/opentripplanner/service/vehiclerental/internal/DefaultVehicleRentalService.java

A number of requests fail in our production environment with the following error message:
```
Exception while fetching data (/bikeRentalStations) : null
java.util.ConcurrentModificationException: null
at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1784)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:62 …
```

Fix concurrent modification exception in vehicle rental service

---

src/main/java/org/opentripplanner/api/common/OTPExceptionMapper.java

This PR ensures that GraphQL requests with an incorrect JSON structure are mapped to the HTTP status code _400-Bad Request_
These requests are currently treated as code _500 - Internal Server Error_ and logged at error level:
```
Unhandled exception
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.HashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('query ($id: 41800) {
stopPlace(
id: $id
) {
name
id
estimatedCalls {
expectedDepartureTime
destinationDisplay {
frontText
}
serviceJourney {
line {
publicCode
transportMode
}
}
}
}
}')
at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1]
at …
```

Map mismatched input exception

---

src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
src/main/java/org/opentripplanner/updater/GraphUpdaterManager.java

This PR cleans up code in the SIRI-ET PubSub updater:
- remove deprecated method SubscriptionAdminClient.deleteSubscription
- separate message processing logic (`processSiriData`()) from PubSub infrastructure code (`EstimatedTimetableMessageReceiver`)
A dedicated thread factory is also added for the GraphWriter in order to more easily distinguish in the logs the real-time operations that run in that single thread.
No
No

Refactor SIRI-ET PubSub updater

---

src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/GraphQLIntegrationTest.java
src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/stepImpl.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/PathGuidanceType.java
src/main/java/org/opentripplanner/api/mapping/LegMapper.java
src/main/java/org/opentripplanner/api/mapping/WalkStepMapper.java
src/main/java/org/opentripplanner/graph_builder/module/AddTransitModelEntitiesToGraph.java
src/main/java/org/opentripplanner/model/plan/Leg.java
src/main/java/org/opentripplanner/model/plan/StreetLeg.java
src/main/java/org/opentripplanner/model/plan/StreetLegBuilder.java
src/main/java/org/opentripplanner/model/plan/WalkStep.java
src/main/java/org/opentripplanner/model/plan/WalkStepBuilder.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/GraphPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
src/main/java/org/opentripplanner/street/model/edge/ElevatorHopEdge.java
src/main/java/org/opentripplanner/street/model/edge/PathwayEdge.java
src/test/java/org/opentripplanner/model/plan/WalkStepTest.java
src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapperTest.java
src/test/java/org/opentripplanner/street/model/edge/PathwayEdgeTest.java
src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java

The REST API used to expose the ID of the first pathway on a street leg. This is a strange piece of the API that thankfully didn't make it into the GraphQL API.
Because of this, I'm removing it from the API and also do the associated internal clean up so that we don't needlessly pass the ID around.
Lastly, I renamed a few properties in `WalkStep` so they better reflect their meaning.
@miles-grant-ibigroup has confirmed that IBI is not using this field.

Remove pathway id from REST API

---

src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java
src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/QueryTypeImpl.java
src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/StopImpl.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TransitIdMapper.java
src/main/java/org/opentripplanner/api/common/LocationStringParser.java
src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializer.java
src/main/java/org/opentripplanner/routing/api/request/request/TransitRequest.java
src/main/java/org/opentripplanner/routing/api/request/request/filter/SelectRequest.java
src/main/java/org/opentripplanner/routing/graphfinder/PatternAtStop.java
src/main/java/org/opentripplanner/standalone/config/framework/json/ParameterBuilder.java
src/main/java/org/opentripplanner/transit/model/framework/FeedScopedId.java
src/test/java/org/opentripplanner/routing/algorithm/FilterTest.java
src/test/java/org/opentripplanner/transit/model/network/RouteTest.java
src/test/java/org/opentripplanner/transit/model/timetable/TripTest.java

This renames the static parsing methods in `FeedScopedId` so that the word "id" doesn't show up too many times when reading the code.

Rename FeedScopeId.parseId to FeedScopedId.parse

---

src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
src/main/java/org/opentripplanner/framework/retry/OtpRetry.java
src/test/java/org/opentripplanner/framework/retry/OtpRetryTest.java

During the setup phase of the SIRI-ET Google PubSub updater, a PubSub subscription is created.
This operation may fail and is currently not retried, causing the OTP instance to hang indefinitely:
```
Error while running updater org.opentripplanner.ext.siri.updater.SiriETGooglePubsubUpdater:
com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 59.857446361s. [closed=[], open=[[buffered_nanos=265252049, buffered_nanos=12074439, remote_addr=pubsub.googleapis.com/108.177.126.95:443]]]
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:94)
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
at …
```

Retry on failed SIRI-ET Pubsub subscription creation

---

src/main/java/org/opentripplanner/netex/loader/parser/ResourceFrameParser.java
src/test/java/org/opentripplanner/netex/loader/parser/ResourceFrameParserTest.java

In the Nordic NeTEx Profile, organisations are optional elements in the ResourceFrame.
Currently the graph builder fails with a NullPointerException if a ResourceFrame does not contain any organisations:
```
An uncaught error occurred inside OTP: java.lang.NullPointerException: Cannot invoke "org.rutebanken.netex.model.OrganisationsInFrame_RelStructure.getOrganisation_()" because "elements" is null
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.rutebanken.netex.model.OrganisationsInFrame_RelStructure.getOrganisation_()" because "elements" is null
at org.opentripplanner.netex.NetexModule.buildGraph(NetexModule.java:107)
at org.opentripplanner.graph_builder.GraphBuilder.run(GraphBuilder.java:175)
at org.opentripplanner.standalone.OTPMain.startOTPServer(OTPMain …
```

Parse NeTEx Resource frame without organisation

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/StopPlaceType.java

A stop place query where the id is empty:
```
{
stopPlace(
id: ""
) {
id
name
estimatedCalls(
startTime: "2023-08-18T09:37:30+0000",
timeRange: 24000,
includeCancelledTrips: false,
numberOfDepartures: 25
) {
realtime
aimedArrivalTime
aimedDepartureTime
expectedArrivalTime
expectedDepartureTime
date
forBoarding
forAlighting
destinationDisplay {
frontText
}
}
}
}
```
returns currently:
```
{
"errors": [
{
"message": "Exception while fetching data (/stopPlace) : Cannot invoke \"Object.hashCode()\" because \"pk\" is null",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"stopPlace"
],
"extensions": {
"classification": "DataFetchingException"
}
}
],
"data": {
"stopPlace": null
}
}
```
This PR ensures that the API returns a valid GraphQL response with a null stopPlace:
```
{
"data": { …
```

Return valid response when stop id is missing in Transmodel query

---

src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraph.java

When receiving a malformed GraphQL query that refers to an unexisting operation:
`{"query":"{\n  trip(\n    from: {place: \"NSR:StopPlace:58189\"}\n    to: {place: \"NSR:StopPlace:58287\"}\n    numTripPatterns: 5\n  ) {\n    tripPatterns {\n      duration\n      legs {\n        expectedStartTime\n        expectedEndTime\n        mode\n        distance\n        line {\n          id\n          publicCode\n        }\n        fromEstimatedCall {\n          destinationDisplay {\n            frontText\n          }\n        }\n        fromPlace {\n          name\n          quay {\n            publicCode\n          }\n        }\n        toPlace {\n          name\n          quay {\n            publicCode\n          }\n        }\n      }\n    }\n  }\n}\n","variables":null,"operationName":"j"}`
OTP …

Map GraphQL UnknowOperationException as bad request

---

pom.xml

The latest version of OneBusAway has added a dependency on `slf4j-simple` which produces the following warning when OTP starts up:
```
SLF4J: Class path contains multiple SLF4J providers.
SLF4J: Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@5e0e82ae]
SLF4J: Found provider [org.slf4j.simple.SimpleServiceProvider@6771beb3]
SLF4J: See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual provider is of type [ch.qos.logback.classic.spi.LogbackServiceProvider@5e0e82ae]
```
This PR excludes the dependency so that the warning goes away. I will work with upstream to resolve this there.

Exclude OBA's slf4j-simple

---

pom.xml
src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/GraphQLIntegrationTest.java
src/ext-test/java/org/opentripplanner/ext/gtfsgraphqlapi/mapping/StreetNoteMapperTest.java
src/ext-test/resources/gtfsgraphqlapi/expectations/alerts.json
src/ext-test/resources/gtfsgraphqlapi/queries/alerts.graphql
src/ext/java/org/opentripplanner/ext/gtfsgraphqlapi/datafetchers/AlertImpl.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/siri/sx/PtSituationElementType.java
src/main/java/org/opentripplanner/api/mapping/AlertMapper.java
src/main/java/org/opentripplanner/routing/alertpatch/TransitAlert.java
src/main/java/org/opentripplanner/routing/alertpatch/TransitAlertBuilder.java
src/test/java/org/opentripplanner/_support/text/I18NStrings.java
src/test/java/org/opentripplanner/updater/alert/AlertsUpdateHandlerTest.java

The return value of `TransitAlert#descriptionText` was producing NPE's in the GTFS GraphQL API so I made it and `url` return an explicit `Optional` so that call sites are forced to deal with this fact.
Since the API schema requires `descriptionText` to be non-null (which isn't the case for the GTFS-RT spec) I used some fallback logic so that it always returns a string.
If we don't want the fallback logic we will have to modify the schema. Let's discuss this at the dev meeting.
Test added.

Gracefully handle nullable fields in TransitAlert

---

src/main/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapper.java
src/test/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapperTest.java

A simple filtering of  ice and winter roads using Finland tag mapping. Ice roads are in use only some months per year, so they should be exluded from the street graph.
At later stage, we might consider implementing a configurable time period for such roads, or perhaps start supporting some OSM tags which limit the time period when the roads are available.

Remove ice roads from Finland routing

---

src/test/java/org/opentripplanner/graph_builder/module/GtfsModuleTest.java

This test is intermittently failing in our ci pipeline with error:
```
[ERROR]   GtfsModuleTest$Interlining.interline(List, int) » IllegalState stream has already been operated upon or closed
```
There is probably some kind of race condition. This PR fixes this by switching to using MethodSource.

Fix race condition in GtfsModuleTest

---

src/main/java/org/opentripplanner/gtfs/mapping/StationMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/StopMapper.java

Similarly to https://github.com/opentripplanner/OpenTripPlanner/pull/4993 this improves the error messages when an entry from a stops.txt has an incorrect location_type, for example when you try to generate a transfer from a station to a station.
cc @NVBWSeifert

Add ID to mapper error messages

---

src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdater.java
src/main/java/org/opentripplanner/framework/io/JsonDataListDownloader.java

HSL park updater failed to start because we now have a check that headers can't be null.
Minor sandbox problem, no issue
Not sure if feasible
Not needed
Not needed

Fix issue with null headers in HSL park updater

---

src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslFacilitiesDownloader.java
src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslHubToVehicleParkingGroupMapper.java
src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslHubsDownloader.java
src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkToVehicleParkingMapper.java
src/main/java/org/opentripplanner/framework/geometry/GeometryUtils.java
src/main/java/org/opentripplanner/framework/io/JsonDataListDownloader.java
src/main/java/org/opentripplanner/graph_builder/module/geometry/GeometryProcessor.java
src/main/java/org/opentripplanner/graph_builder/module/islandpruning/PruneIslands.java
src/main/java/org/opentripplanner/graph_builder/module/osm/AreaGroup.java
src/main/java/org/opentripplanner/graph_builder/module/osm/Ring.java
src/main/java/org/opentripplanner/inspector/raster/NoThruTrafficEdgeRenderer.java
src/main/java/org/opentripplanner/openstreetmap/model/OSMLevel.java
src/main/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySet.java
src/main/java/org/opentripplanner/standalone/config/CommandLineParameters.java
src/test/java/org/opentripplanner/astar/model/BinHeapTest.java

Minor performance code cleanup as suggested by Intellij and Sonar.
See the 5 commits:
- Use bulk operation on collections: bulk operations are more efficient
- Fix size of List.toArray() parameter: it used to be a best practice to provide an array with an explicit size in the method List.toArray(). This is not recommended anymore with Java 6+ and now less performant
- Use String.isEmpty() to test empty String: slight performance gain with String.isEmpty()
- Replace wrapper with primitive: performance gain
- Use short-circuit boolean operator: performance gain since only one operand is evaluated
No
No

Minor performance fixes

---

src/main/java/org/opentripplanner/openstreetmap/model/OSMNode.java
src/test/java/org/opentripplanner/graph_builder/module/osm/OsmModuleTest.java

The test, which tests barrier vertex pruning, turned out to be broken:
- test function was declared private
- wrong test file name
- path finder failed even with correct file name (for unknown reason, code is direct copy from another test)
The test is now modified so that it tests the actual barrier pruning. It asserts that removal of access restrictions from ending streets happens as a part of standard graph build actions. 
PR also contains a minor refactoring of an OSM node related method.

Fix barrier vertex pruning test

---

src/ext-test/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapperTest.java
src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/PassThroughLocationMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TransitIdMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/framework/PassThroughPointInputType.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/TripQuery.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/ViaLocationInputType.java
src/main/java/org/opentripplanner/raptor/api/request/PassThroughPoint.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java
src/main/java/org/opentripplanner/routing/api/request/PassThroughPoint.java
src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
src/main/java/org/opentripplanner/transit/service/TransitService.java
src/test/java/org/opentripplanner/raptor/api/request/PassThroughPointTest.java
src/test/java/org/opentripplanner/raptor/api/request/PassThroughPointsTest.java
src/test/java/org/opentripplanner/raptor/moduletests/J01_PassThroughTest.java
src/test/java/org/opentripplanner/raptor/rangeraptor/multicriteria/passthrough/BitSetPassThroughPointsServiceTest.java

Extension to the GraphQL Transmodel API for performing pass-through searches (popularly called _via-searches_, but that concept name is already taken). Raptor related changes was merged in #5249.
This is associated to issue #4887.

Transmodel GraphQL API for pass-through searches

---

src/main/java/org/opentripplanner/standalone/OtpStartupInfo.java

Add information about the Java version when OTP is starting:
`
OTP STARTING UP (version: 2.5.0-SNAPSHOT, ser.ver.id: 120, commit: 8d5490eb4c38ae7624f3e22df3790f159e250dc8, branch: dev-2.x) using Java 17.0.8
`
No
No

Log Java version info at startup

---

src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapperTest.java

As detailed in #5311, itinerary mapping fails if the path starts with a flex leg followed by a transfer leg.
This PR addresses this corner case.
Closes #5311
No

Fix flex access itinerary mapping

---

src/main/java/org/opentripplanner/graph_builder/module/interlining/InterlineProcessor.java
src/main/java/org/opentripplanner/model/calendar/CalendarServiceData.java

We have validation at the end of the graph build for when there is no service data configured with a slightly prettier error message.
No issue as of yet but the stack trace is:
<details>
03:05:03.302 ERROR [main]  (OTPMain.java:60) An uncaught error occurred inside O
TP: No service data is available
java.lang.IllegalStateException: No service data is available
at org.opentripplanner.model.calendar.CalendarServiceData.lambda$getFirs
tDate$1(CalendarServiceData.java:92)
at java.base/java.util.Optional.orElseThrow(Optional.java:403)
at org.opentripplanner.model.calendar.CalendarServiceData.getFirstDate(C
alendarServiceData.java:91)
at org.opentripplanner.graph_builder.module.interlining.InterlineProcess
or.<init>(InterlineProcessor.java:59)
at …

Don't crash interline processing if no service data

---

src/ext-test/java/org/opentripplanner/ext/fares/FaresFilterTest.java
src/ext-test/java/org/opentripplanner/ext/fares/impl/AtlantaFareServiceTest.java
src/ext-test/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceTest.java
src/ext-test/java/org/opentripplanner/ext/fares/impl/HSLFareServiceTest.java
src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/FaresToItineraryMapper.java
src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareService.java
src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareService.java
src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareServiceFactory.java
src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
src/main/java/org/opentripplanner/model/fare/ItineraryFares.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/BikeRentalSnapshotTest.snap
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/ElevationSnapshotTest.snap
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/TransitSnapshotTest.snap
src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-fares.json

https://github.com/opentripplanner/OpenTripPlanner/pull/5284 introduced a regression which broke IBI's fare calculators.
The problem was that leg products were not transferred correctly from the intermediary fares to the eventual result, which is fixed now.
Another problem was that HSL and IBI use different APIs for representing the fares. We hope to address this in #5396 
Relates to #5396
Lots added and adjusted.

Fix IBI fare calculators

---

src/main/java/org/opentripplanner/transit/model/basic/Money.java
src/test/java/org/opentripplanner/routing/core/MoneyTest.java

@fpurcell has reported (and I have independently also noticed) that when enabling Fares V2 `Money` objects fail serialization because they are not `Serializable`.
This PR fixes that.
~~I'd love to write one but I'm not sure if it's worth it.~~ Test added.

Make Money serializable

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedLegsFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedTransitLeg.java
src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
src/main/java/org/opentripplanner/model/plan/Leg.java

This fixes a problem when interlined legs area combined for fare calculation purposes: the fare products are associated to the wrong legs because the combined leg is not "deconstructed" into its parts when returning the results.
@binh-dam-ibigroup: this bugfix is relevant when Houston and SEPTA are going migrate the new Fares API.
Added.
Javadoc added.

Fix fare calculation for combined interlined legs

---

src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/preferences/TransitPreferencesMapper.java

When specifying a board slack by mode in a Transmodel query:
```
{
trip(
from: {
place: "NSR:StopPlace:58481"
},
to: {
place: "NSR:StopPlace:58482"
},
modes: {
transportModes: {
transportMode: water
transportSubModes: localPassengerFerry
}
},
numTripPatterns: 3,
arriveBy: true,
boardSlackList: {
slack: 10
modes: water
},
locale: us,
timetableView: true
) {
tripPatterns {
distance
}
fromPlace {
name
quay {
estimatedCalls(
arrivalDeparture: departures,
whiteListedModes: water,
numberOfDepartures: 10
) {
actualDepartureTime
aimedDepartureTime
date
expectedDepartureTime
destinationDisplay {
frontText
via
}
occupancyStatus
realtimeState
stopPositionInPattern
datedServiceJourney {
estimatedCalls {
actualDepartureTime
aimedDepartureTime
expectedDepartureTime
stopPositionInPattern
} …
```

Fix board slack list mapping in Transmodel API

---

src/ext/java/org/opentripplanner/ext/transmodelapi/model/stop/QuayType.java

When querying  a flexible quay in the Transmodel API:
```
query {
quay(
id: "SOF:FlexibleStopPlace:ef157b1b-58d7-4431-942d-dc6042f4cae3"
) {
name
id
estimatedCalls {
expectedDepartureTime
destinationDisplay {
frontText
}
serviceJourney {
line {
publicCode
transportMode
}
}
}
}
}
```
an exception is thrown:
```
Exception while fetching data (/quays[100689]/estimatedCalls) : class org.opentripplanner.transit.model.site.AreaStop cannot be cast to class org.opentripplanner.transit.model.site.RegularStop (org.opentripplanner.transit.model.site.AreaStop and org.opentripplanner.transit.model.site.RegularStop are in unnamed module of loader 'app')
java.lang.ClassCastException: class org.opentripplanner.transit.model.site.AreaStop cannot be cast to class …
```

Fix flexible quay querying in Transmodel API

---

src/main/java/org/opentripplanner/transit/service/StopModel.java
src/test/java/org/opentripplanner/transit/service/StopModelTest.java

As detailed in #5399, requesting a quay with an empty id or an id consisting only of spaces leads to an exception.
This PR ensures that a valid empty result is returned in this case.
Closes #5399
No

Fix Transmodel GraphQL query with empty quay id

---

src/main/java/org/opentripplanner/model/plan/legreference/LegReference.java
src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
src/test/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReferenceTest.java

When requesting a leg by reference in the Transmodel API:
```
query ($id: ID!) {
leg(
id: $id
) 
{
...
}
```
the request may fail with the following exception:
```
Exception while fetching data (/leg) : Cannot invoke "org.opentripplanner.transit.model.timetable.TripTimes.getServiceCode()" because "tripTimes" is null
java.lang.NullPointerException: Cannot invoke "org.opentripplanner.transit.model.timetable.TripTimes.getServiceCode()" because "tripTimes" is null
at org.opentripplanner.model.plan.legreference.ScheduledTransitLegReference.getLeg(ScheduledTransitLegReference.java:48)
at org.opentripplanner.model.plan.legreference.ScheduledTransitLegReference.getLeg(ScheduledTransitLegReference.java:19)
at org.opentripplanner.ext.transmodelapi.TransmodelGraphQLSchema.lambda$create$56(TransmodelG …
```

Add validation for scheduled transit leg reference

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java

The recent changes to fares which grouped legs by their feed ID broke the ORCA fare module's ability to calculate transfers between different agencies. This PR changes the ORCA fare module tests to also test the complexity contained in the super class. Then, it moves the feed grouping logic into an overrideable method which the ORCA module overrides to group all the legs together.  
The tests are updated and improved to ensure that this bug would be caught in the future, and then they are used to correct the bug. The results have been double checked by testing some trip plans.

Fix ORCA cross-agency fares

---

src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
src/test/java/org/opentripplanner/routing/stoptimes/StopTimesHelperTest.java

As detailed in #5400, querying estimated calls with a limit on the number of departures set to 0 leads to an exception.
This PR ensures that a valid empty result is returned in this case.
Closes #5400
No

Fix stop times helper when requesting zero departure

---

src/ext-test/java/org/opentripplanner/ext/siri/AddedTripBuilderTest.java
src/ext/java/org/opentripplanner/ext/siri/AddedTripBuilder.java

When a SIRI update creates a new trip without estimated calls, the update fails with the following error message:
```
Adding EstimatedJourney EstimatedVehicleJourney{EstimatedVehicleJourneyCode: 'GOA:ServiceJourney:20231003-921967', Operator: GOA:Operator:GOA, VehicleModes: [BUS], Line: GOA:Line:50} failed. java.lang.NullPointerException: null
at java.base/java.util.Objects.requireNonNull(Objects.java:209)
at java.base/java.util.ImmutableCollections.listFromArray(ImmutableCollections.java:190)
at java.base/java.util.List.of(List.java:1047)
at org.opentripplanner.transit.model.network.StopPattern.getStops(StopPattern.java:174)
at org.opentripplanner.transit.model.network.TripPattern.getStops(TripPattern.java:199)
at org.opentripplanner.transit.model.network.RoutingTripPattern.<init>(Routing …
```

Add validation for missing calls in SIRI update

---

docs/sandbox/GeocoderAPI.md
src/ext-test/java/org/opentripplanner/ext/geocoder/EnglishNgramAnalyzerTest.java
src/ext-test/java/org/opentripplanner/ext/geocoder/LuceneIndexTest.java
src/ext/java/org/opentripplanner/ext/geocoder/EnglishNGramAnalyzer.java
src/ext/java/org/opentripplanner/ext/geocoder/GeocoderResource.java
src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java
src/ext/java/org/opentripplanner/ext/geocoder/StopClusterMapper.java
src/main/java/org/opentripplanner/framework/geometry/WgsCoordinate.java
src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
src/test/java/org/opentripplanner/framework/geometry/WgsCoordinateTest.java

@miles-grant-ibigroup has requested the following changes to the sandbox geocoder:
- Fuzziness is improved through a more elaborate query strategy
- An NGram index is added which allows also matches in the middle of a word so "exanderp" matches "Alexanderplatz"
- The stop clusters, which group stops with the same name, now have a larger radius from 10m to 100m.
This PR also removes the street corners from the geocoding index, which improves startup time. @flaktack, who originally added it, [said that he would be fine if it was removed](https://matrix.to/#/!oXNNoHKzbaSOlFzLEt:gitter.im/$qp2RTLCsiGxZVHqGUxe-8CGn4CPMU1tw-WBsJ0NahCE?via=gitter.im&via=matrix.org&via=mafiasi.de).
Lots added.
Updated.

Improve geocoding fuzziness, remove street corners

---

src/ext-test/java/org/opentripplanner/ext/transmodelapi/mapping/TransitIdMapperTest.java
src/ext/java/org/opentripplanner/ext/transmodelapi/TransmodelGraphQLSchema.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/FilterMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/SelectRequestMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TransitIdMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/mapping/TripRequestMapper.java
src/ext/java/org/opentripplanner/ext/transmodelapi/model/plan/JourneyWhiteListed.java

As detailed in #5398, specifying a null id in the list of whitelisted lines for estimated calls causes an exception.
Null values should not be allowed as input parameters in this case.
This PR provides a general fix by filtering out null, empty and blank values when mapping ids to feed-scoped ids.
Closes #5398
No

Filter out null, empty and blank elements when mapping feed-scoped ids

---

src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializer.java
src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceType.java
src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
src/test/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializerTest.java
src/test/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReferenceTest.java
src/test/java/org/opentripplanner/routing/stoptimes/AlternativeLegsTest.java

As detailed in  #5423, transit leg references currently refer to stop position, not stop id: if the trip pattern is changed by a real-time update, the leg reference could point to the wrong physical stop.
This PR verifies that the referenced stop positions still refer to the same stop ids in the actual pattern.
As an exception, the reference is considered valid if the referenced stop is different but belongs to the same parent station: this covers for example the case of a last-minute platform change in a train station that typically does not affect the validity of the leg.
This PR modifies the structure of the serialized leg id by adding new fields, but guarantees that existing (legacy) references will be deserialized successfully.
Partially addresses #5423
No

Validate stop id in Transit leg reference

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/FareModelForTest.java
src/ext-test/java/org/opentripplanner/ext/fares/impl/HSLFareServiceTest.java
src/ext-test/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareService.java
src/ext/java/org/opentripplanner/ext/fares/model/FareAttribute.java
src/ext/java/org/opentripplanner/ext/fares/model/FareAttributeBuilder.java
src/main/java/org/opentripplanner/apis/gtfs/datafetchers/TicketTypeImpl.java
src/main/java/org/opentripplanner/gtfs/mapping/FareAttributeMapper.java
src/test/java/org/opentripplanner/gtfs/mapping/FareAttributeMapperTest.java
src/test/java/org/opentripplanner/gtfs/mapping/FareRuleMapperTest.java

Removes the fields "youth price" and "senior price" from the mapping of the GTFS fare_attribute. These fields were non-standard when they were added in 2016 and are still nowhere in the spec.
They references deployments in Seattle. Since IBI has taken over these deployments in the last couple of years, we can be sure that these fields are no longer used.
Another clean up of the code is the conversion of a float/currency field combination for the price into a `Money` instance which makes integration with the rest of the fares code a little easier.
Existing unit tests were updated.

Clean up fare attribute, remove non-standard senior and youth prices

---

src/main/java/org/opentripplanner/apis/gtfs/datafetchers/VehicleRentalStationImpl.java
src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
src/main/java/org/opentripplanner/apis/gtfs/generated/graphql-codegen.yml
src/main/java/org/opentripplanner/service/vehiclerental/model/RentalVehicleEntityCounts.java
src/main/java/org/opentripplanner/service/vehiclerental/model/RentalVehicleTypeCount.java
src/main/java/org/opentripplanner/service/vehiclerental/model/VehicleRentalStation.java
src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
src/test/java/org/opentripplanner/service/vehiclerental/internal/DefaultVehicleRentalServiceTest.java
src/test/java/org/opentripplanner/service/vehiclerental/model/TestVehicleRentalStationBuilder.java
src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java
src/test/resources/org/opentripplanner/apis/gtfs/expectations/vehicle-rental-station.json
src/test/resources/org/opentripplanner/apis/gtfs/queries/vehicle-rental-station.graphql

This PR adds `vehicleTypesAvailable` and `vehicleSpacesAvailable` to the `VehicleRentalStation` type. These fields return the count of each vehicle type available for pickup and drop-off, respectively. As an example, this is what the new fields look like in the `vehicleRentalStation` query:
```
...
"vehicleRentalStation": {
"stationId": "NYC:cc7b86cf-a2fb-4738-b967-de7b197dc930",
"name": "Ave A & E 14 St",
"vehiclesAvailable": 2,
"vehicleTypesAvailable": [
{
"vehicleType": {
"formFactor": "BICYCLE",
"propulsionType": "HUMAN"
},
"count": 0
},
{
"vehicleType": {
"formFactor": "BICYCLE",
"propulsionType": "ELECTRIC_ASSIST"
},
"count": 2
}
],
...
```
N/A
- GraphQL integration test added that runs the `vehicleRentalStation` query with the new fields
- Manual testing done with the interactive …

Add available types and spaces to `VehicleRentalStation`

---

src/main/java/org/opentripplanner/netex/mapping/FlexStopsMapper.java
src/main/java/org/opentripplanner/netex/mapping/OpenGisMapper.java
src/test/java/org/opentripplanner/netex/mapping/FlexStopsMapperTest.java

Currently the graph builder ignores some types of geometry errors when importing NeTEx flex data.
In particular self-intersecting polygons are imported without any validation error:
This PR applies a stricter validation when parsing polygons so that invalid areas are rejected (i.e. ignored)  during graph building.
No
No

Add stricter validation for flex areas

---

src/ext/java/org/opentripplanner/ext/realtimeresolver/RealtimeResolver.java
src/main/java/org/opentripplanner/model/plan/FrequencyTransitLeg.java
src/main/java/org/opentripplanner/model/plan/FrequencyTransitLegBuilder.java
src/main/java/org/opentripplanner/model/plan/Leg.java
src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
src/main/java/org/opentripplanner/model/plan/ScheduledTransitLegBuilder.java
src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializer.java
src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceType.java
src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegs.java
src/test/java/org/opentripplanner/model/plan/ScheduledTransitLegTest.java
src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
src/test/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializerTest.java
src/test/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReferenceTest.java
src/test/java/org/opentripplanner/routing/stoptimes/AlternativeLegsTest.java

As detailed in #5422, a transit leg reference should refer to a TripOnServiceDate id (i.e. dated service journey id) when one exists,
since a dated service journey provides a more stable id across deliveries of planned data.
The PR introduces also a builder for ScheduledTransitLeg and FrequencyTransitLeg.
Closes #5422
No

Add support for DSJ in transit leg reference

---

src/main/java/org/opentripplanner/raptor/rangeraptor/standard/ArrivalTimeRoutingStrategy.java
src/main/java/org/opentripplanner/raptor/rangeraptor/standard/MinTravelDurationRoutingStrategy.java

Width this PR, the Raptor heuristic search will iIgnore negative trip-times. Raptor is implemented to trust the transit-layer to provide increasing trip-times, but we have seen several cases where negative trip-times are passed into Raptor. This causes the search to fail "late" and we are clueless on witch data caused the error. This is also a critical issue. If the heuristic fails, then all trips searches may fail depending on the case.
This PR only add a defensive check to the code - for a situation witch should not be possible. No unit test added, the code should prevent such data form existence. The test should be on the transit model, not Raptor. 
I have testet this with the [performance test](https://otp-performance.leonard.io/d/9sXJ43gVk/otp-performance?orgId=1&var-category=transit& …

Ignore negative travel-times in Raptor

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/costfilter/MinCostPathTailFilter.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/passthrough/PassThroughPathTailFilter.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainService.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/TransitPathLegSelector.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainServiceTest.java

The optimized path service relay on sorting transfer between two trips on the toTrip boardStopPosition. The sort function used board time, witch in most cases works. But, it is allowed to use the same time for two stops next to each other. Many trip schedules only uses minutes precision, so two stops close to each other can be visited within the same minute.
Closes #5444
A regression unit-test is added.
Not applicable.
✅ This is a minor bugfix.
No

Fix sort order bug in optimized transfers

---

docs/sandbox/SiriUpdater.md
src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/ext/java/org/opentripplanner/ext/siri/updater/EstimatedTimetableSource.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriFileLoader.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriHttpLoader.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriLoader.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriSXUpdater.java
src/main/java/org/opentripplanner/framework/time/CountdownTimer.java
src/main/java/org/opentripplanner/framework/tostring/ToStringBuilder.java
src/main/java/org/opentripplanner/model/TimetableSnapshot.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriETUpdaterConfig.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriSXUpdaterConfig.java
src/test/java/org/opentripplanner/framework/time/CountdownTimerTest.java
src/test/java/org/opentripplanner/framework/tostring/ToStringBuilderTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/groupids/GroupByDistanceTest.java

Add support for loading xml files for Siri SX and EX updates. This feature make it much simpler to test realtime updates. This PR also has a few minor improvements and code cleanup.
In a busy updater it does not matter if we commit early or late, as long as we throttle the update commits to happen with a given frequency. But, when testing OTP manually, it is easy to do mistakes and assume that an update is applied when you
see (log):
> INFO 1 of 1 update messages were applied successfully (success rate: 100.0%)
In OTP before this commit, the update was not committed, waiting to fill up the "buffer", and if not other update was applied - nothing happened. 
Use the `url` to set a directory. The updater will use the directory instead of connecting to a http resource. The file loader will …

Siri file loader

---

src/ext/java/org/opentripplanner/ext/interactivelauncher/views/MainView.java
src/ext/java/org/opentripplanner/ext/interactivelauncher/views/StartOtpButtonView.java

Set focus on the Start button in the `InteractiveOtpMain` app.
No
No
No
No
No

Run OTP with one key push in interactive OTP launcher

---

src/main/java/org/opentripplanner/model/plan/SortOrder.java
src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorFactory.java
src/main/java/org/opentripplanner/model/plan/pagecursor/PageCursorFactoryParameters.java
src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainBuilder.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/ListSection.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/MaxLimitFilter.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/NumItinerariesFilter.java
src/main/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/NumItinerariesFilterResults.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RouteRequestToFilterChainMapper.java
src/main/java/org/opentripplanner/routing/algorithm/mapping/RoutingResponseMapper.java
src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
src/test/java/org/opentripplanner/model/plan/pagecursor/PageCursorFactoryTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/MaxLimitFilterTest.java
src/test/java/org/opentripplanner/routing/algorithm/filterchain/deletionflagger/NumItinerariesFilterTest.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/RoutingResponseMapperTest.java

This PR pulls functionality to limit the number of itineraries to the numItineraries parameter into a separate filter from the MaxLimitFilter because of the need to keep more information about the filtered itineraries than just the first one that is removed. The NumItinerariesFilterResults contains information used in the creation of page cursors currently, as well as information that will be used in the future deduplication feature.
N/A
Updated relevant unit tests and added a unittest for the new filter.
Added JavaDoc.
N/A
N/A

Create the NumItinerariesFilter and the associated NumItinerariesFilterResults to limit itineraries based on the numItineraries parameter.

---

src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdaterParameters.java
src/main/java/org/opentripplanner/updater/spi/ResultLogger.java

Add logging and metrics in SiriAzureETUpdater
Also use the service bus endpoint instead of the dataInitializationUrl as the url tag in metrics, since this is the more relevant url.

Add logging of siri errors to SiriAzureETUpdater

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
src/main/java/org/opentripplanner/transit/model/basic/Money.java
src/test/java/org/opentripplanner/routing/core/MoneyTest.java

This is just a few more fixes for ORCA agencies
This includes a new test for non ORCA agencies. It needs some more work, but that should go along with a refactor of `ItineraryFares` to fully utilize Leg Products.

Orca Fixes Part 2

---

pom.xml
src/main/java/org/opentripplanner/netex/loader/parser/ServiceCalendarFrameParser.java
src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
src/main/java/org/opentripplanner/netex/loader/parser/SiteFrameParser.java
src/main/java/org/opentripplanner/netex/loader/parser/TimeTableFrameParser.java
src/main/java/org/opentripplanner/netex/mapping/GroupOfStationsMapper.java
src/main/java/org/opentripplanner/netex/mapping/StationMapper.java
src/main/java/org/opentripplanner/netex/mapping/StopAndStationMapper.java
src/main/java/org/opentripplanner/netex/mapping/StopPlaceTypeMapper.java
src/main/java/org/opentripplanner/netex/mapping/TransportModeMapper.java
src/main/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapper.java
src/main/java/org/opentripplanner/netex/support/JAXBUtils.java
src/test/java/org/opentripplanner/netex/NetexTestDataSupport.java
src/test/java/org/opentripplanner/netex/loader/parser/ServiceCalendarFrameParserTest.java
src/test/java/org/opentripplanner/netex/loader/parser/SiteFrameParserTest.java
src/test/java/org/opentripplanner/netex/mapping/RouteMapperTest.java
src/test/java/org/opentripplanner/netex/mapping/StationMapperTest.java
src/test/java/org/opentripplanner/netex/mapping/StopAndStationMapperTest.java
src/test/java/org/opentripplanner/netex/mapping/StopPlaceTypeMapperTest.java
src/test/java/org/opentripplanner/netex/mapping/TransportModeMapperTest.java

The release 2.0.15 aims primarily at synchronizing the Entur fork of the NeTEx XML schema with the upstream version hosted by CEN at https://github.com/NeTEx-CEN/NeTEx
This introduces breaking changes at the Java object model level.
See https://github.com/entur/netex-java-model/releases/tag/netex-java-model-2.0.15 for details
**Note:** v2.0.15 supports JakartaEE 10, dependencies in OTP are upgraded accordingly.
JakartaEE 10 deprecates obsolete JAXB features and is otherwise backward compatible with Jakarta EE 9.
No
Added missing unit test coverage for NeTEx parsing.
No

Update NeTEx Java Model 2.0.15

---

src/main/java/org/opentripplanner/graph_builder/GraphBuilder.java
src/main/java/org/opentripplanner/service/worldenvelope/model/WorldEnvelopeBuilder.java
src/test/java/org/opentripplanner/graph_builder/module/geometry/CalculateWorldEnvelopeModuleTest.java

This improve OTP graph build when the transit data is broken.
No
No, this only change the error messages and error handling, no tests added.
No, doc on this.
No - too small.
No

Improve graph builder start up

---

src/main/java/org/opentripplanner/apis/gtfs/datafetchers/ItineraryImpl.java
src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
src/test/resources/org/opentripplanner/apis/gtfs/expectations/plan-extended.json
src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-extended.graphql

@binh-dam-ibigroup has requested that the property `numberOfTransfers` which was part of the REST API be exposed in the GTFS GraphQL API.
GraphQL tests added.

Expose `numberOfTransfers` in GTFS GraphQL API

---

src/main/java/org/opentripplanner/transit/service/StopModel.java
src/main/java/org/opentripplanner/transit/service/StopModelBuilder.java
src/test/java/org/opentripplanner/routing/graph/GraphSerializationTest.java

The problem with the current code is that the stop model builders are created at the same time as the GraphBuilderModules. When the models are merged back the StopModel change, and only the first GraphBuilderModule is allowed to merge its result - this happens, because a stop model is only allowed to be merged with the model it originated from.
- To solve this, we can create a stop model builder late to allow other graph builder models to complete their work before we continue. 
- Or, we can change the stop model builder and stop model merge so more than one builder can exist at once. 
This PR take the second approach. It is easier, because we do not have to change the dependency injection. We kan inject the stop model builder at graph builder modules construction time. And we allow for …

Allow early creation of StopModelBuilder

---

docs/BuildConfiguration.md
docs/RouterConfiguration.md
docs/UpdaterConfig.md
docs/sandbox/VehicleParking.md
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/GtfsRealtimeAlertsUpdaterConfig.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/MqttGtfsRealtimeUpdaterConfig.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/PollingTripUpdaterConfig.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/VehicleParkingUpdaterConfig.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/WebsocketGtfsRealtimeUpdaterConfig.java
src/test/resources/standalone/config/build-config.json
src/test/resources/standalone/config/router-config.json

@markstos has correctly pointed out that the `feedId` is incorrectly documented as optional.
This fixes the config schema and docs.
Closes #5499.

Make `feedId` required for realtime updaters

---

.github/workflows/performance-test.yml
src/main/java/org/opentripplanner/routing/graph/kryosupport/AtomicIntegerSerializer.java
src/main/java/org/opentripplanner/routing/graph/kryosupport/KryoBuilder.java

This fixes #5507 by introducing a custom serializer for `AtomicInteger`.
Closes #5507.
The speed tests were run on this branch.

Fix serialization of `AtomicInteger`

---

src/ext-test/java/org/opentripplanner/ext/flex/FlexIntegrationTest.java
src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
src/main/java/org/opentripplanner/routing/graph/Graph.java
src/main/java/org/opentripplanner/routing/graph/index/StreetIndex.java
src/main/java/org/opentripplanner/street/model/vertex/StreetVertex.java
src/main/java/org/opentripplanner/street/model/vertex/TransitStopVertex.java
src/test/java/org/opentripplanner/ConstantsForTests.java
src/test/java/org/opentripplanner/_support/geometry/Coordinates.java
src/test/java/org/opentripplanner/graph_builder/module/StreetLinkerModuleTest.java
src/test/java/org/opentripplanner/graph_builder/module/TestStreetLinkerModule.java
src/test/java/org/opentripplanner/graph_builder/module/VehicleParkingLinkingTest.java
src/test/java/org/opentripplanner/graph_builder/module/osm/UnconnectedAreasTest.java
src/test/java/org/opentripplanner/routing/TestHalfEdges.java
src/test/java/org/opentripplanner/routing/algorithm/StreetModeLinkingTest.java
src/test/java/org/opentripplanner/routing/linking/LinkStopToPlatformTest.java
src/test/java/org/opentripplanner/routing/vehicle_parking/VehicleParkingTestGraphData.java
src/test/java/org/opentripplanner/routing/vehicle_parking/VehicleParkingTestUtil.java
src/test/java/org/opentripplanner/street/model/_data/StreetModelForTest.java
src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java

As shown in #5498 adding stops which are far away from walkable edges to flex trips can lead to catastrophic results.
This PR improves the situation as follows:
- flex stops are first linked to walkable edges
- if these edges are _not_ drivable then a second link to drivable edges is created
This leads to desirable results like these
There is a slight problem though: the extra link for the flex trip is also accessible for pedestrians.
We can improve this by making the links mode specific. I suggest that we improve this problem in this PR and follow up later.
Closes #5498
Some added plus a bit of refactoring of the existing tests.
Javadoc.

Improve linking of fixed stops used by flex trips

---

src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
src/main/java/org/opentripplanner/model/plan/ScheduledTransitLegBuilder.java
src/test/java/org/opentripplanner/model/plan/ScheduledTransitLegBuilderTest.java

When converting a `ScheduledTransitLeg` to a builder the field `zoneId` was not transferred correctly, which this PR fixes.

Fix transfer of zoneId in `ScheduledTransitLegBuilder`

---

src/ext-test/java/org/opentripplanner/ext/flex/trip/UnscheduledTripTest.java
src/ext/java/org/opentripplanner/ext/flex/template/FlexEgressTemplate.java
src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java

#5376 introduced a bug in the way Flex egresses are created: the from and to stops were inverted.
This PR fixes it.
No issue
Fixed unit test
No

Fix flex egress stop index

---

src/main/java/org/opentripplanner/netex/mapping/FlexStopsMapper.java
src/main/java/org/opentripplanner/netex/mapping/TransportModeMapper.java
src/test/java/org/opentripplanner/netex/mapping/FlexStopsMapperTest.java

As detailed in #5506, when mapping "fixedStopAreaWide" FlexibleStopPlaces  (i.e. "UnrestrictedPublicTransportAreas" stop areas), group stops should include only regular stops that match the transport mode of the FlexibleStopPlace.
Note: The Nordic NeTEx profile defines the transport mode as a mandatory field of a FlexibleStopPlace. If the transport mode is unset or unknown in the input dataset, no stop will be mapped.
Closes #5506
Updated unit tests.
No.

Check transport mode when mapping GroupStops

---

src/main/java/org/opentripplanner/raptor/rangeraptor/standard/MinTravelDurationRoutingStrategy.java

This fixes and improve the logging af a critical error inside Raptor on negative-travel times.
🟥  No issue for this, too small.
🟥 No tests, only logging changed.
🟥 No doc
🟥 Too small.
🟥  Not relevant.

Fix small bug in time-travel logging

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
src/main/java/org/opentripplanner/street/search/state/State.java
src/test/java/org/opentripplanner/_support/geometry/Coordinates.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransferTest.java

As discussed in today's dev meeting and described in #5509 absurdly high transfer costs can lead to an integer overflow in RAPTOR.
This PR adds a safety limit when transfer costs are being calculated. This limit is still pretty high (several days of transit-equiavalence) but well below `Integer.MAX_VALUE`.
Closes #5509
Javadoc.
cc @miles-grant-ibigroup @binh-dam-ibigroup

Transfer cost limit

---

src/main/java/org/opentripplanner/framework/lang/ObjectUtils.java
src/main/java/org/opentripplanner/framework/token/Deserializer.java
src/main/java/org/opentripplanner/framework/token/FieldDefinition.java
src/main/java/org/opentripplanner/framework/token/Serializer.java
src/main/java/org/opentripplanner/framework/token/Token.java
src/main/java/org/opentripplanner/framework/token/TokenBuilder.java
src/main/java/org/opentripplanner/framework/token/TokenDefinition.java
src/main/java/org/opentripplanner/framework/token/TokenDefinitionBuilder.java
src/main/java/org/opentripplanner/framework/token/TokenSchema.java
src/main/java/org/opentripplanner/framework/token/TokenType.java
src/main/java/org/opentripplanner/framework/token/package.md
src/test/java/org/opentripplanner/framework/lang/ObjectUtilsTest.java
src/test/java/org/opentripplanner/framework/token/AdvancedTokenSchemaTest.java
src/test/java/org/opentripplanner/framework/token/TokenSchemaConstants.java
src/test/java/org/opentripplanner/framework/token/TokenSchemaTest.java

This adds a component to specify a very simple schema for a token. The schema is a list of versioned token definitions and the encode/decode methods enforce versioning, and forward and backward compatibillity. It also allow definitions to be merged. We only need to support one OTP version. So after every release of OTP we can merge the definitions older then the last release.
This module is not integrated into OTP code, but should be used in:
Closes #5451
```Java
// v1:  (mode: byte)
var builder = TokenSchema.ofVersion(1).addByte("mode");
// v2:  (mode: byte, searchWindow : Duration, numOfItineraries : int)
builder.newVersion().addDuration("searchWindow").addInt("numOfItineraries");
// v3:  (mode: byte, @deprecated searchWindow : Duration, numOfItineraries : int, name : String)
builder = …
```

Token serializer for paging and Leg.ID

---

.github/workflows/prune-container-images.yml

We push a lot of container images (50-100 per month) to the Dockerhub repository but we never clean them up making navigating the tags page quite hard.
This PR introduces a tool that deletes all container images that have not been pulled in over a year.

Remove container images that have not been pulled for over a year

---

src/ext/graphql/transmodelapi/schema.graphql
src/ext/java/org/opentripplanner/ext/transmodelapi/model/EnumTypes.java
src/main/java/org/opentripplanner/routing/alternativelegs/AlternativeLegsFilter.java

This PR adds the ability to filter for same submode in the alternative legs filter.
Closes #5300 
All existing unit tests pass. Additionally tested manually by running locally.
This is a trivial addition to existing functionality.

Add same submode in alternative legs filter

---

src/main/java/org/opentripplanner/netex/mapping/GroupNetexMapper.java
src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/main/java/org/opentripplanner/netex/mapping/TransferMapper.java

When netex data contains duplicate JourneyPatterns the scheduledStopPointsIndex will get duplicates of all the stop points for those JourneyPatterns during graph build. When the graph is loaded this will result in strange IndexOutOfBoundsExceptions in the TransferMapper.
NetexMapper uses a `Multimap` for the scheduledStopPointsIndex. But the semantics of a multimap is that putting to a key that already exists will extend any existing data that has already been added. This is not really the behaviour we want in this case.
This PR fixes this issue by replacing the `Multimap` with a `Map<List>`. This way we will replace the current values when calling putAll().
I suppose that duplicate JourneyPatterns could cause all kinds of other problems, so to solve the underlying issue we should really …

Fix issue where stop points are sometimes added twice to index

---

pom.xml

This work as a short alias to enable this from the command line. To skip
prettier, set the 'ps' system property with the '-D ps' parameter:
> \# mvn test -D ps
🟥 
🟥 
✅ Explained in pom file only
🟥 
🟥

refactor: Add "-Dps" as alias for -P prettierSkip

---

src/main/java/org/opentripplanner/transit/model/timetable/ScheduledTripTimes.java
src/test/java/org/opentripplanner/transit/model/timetable/ScheduledTripTimesTest.java

Some trips last for more than 10 days, so we relax this sanity check to 20 days.
Closes #5560
✅  Unit test added.
🟥 
🟥  - The bug was introduced after the last release.
🟥

Relax TripTimes validation to [-12h, 20d] to allow support for "Hurtigruten"

---

src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
src/main/java/org/opentripplanner/framework/application/ApplicationShutdownSupport.java
src/main/java/org/opentripplanner/standalone/OTPMain.java
src/main/java/org/opentripplanner/standalone/OtpStartupInfo.java
src/main/java/org/opentripplanner/standalone/server/GrizzlyServer.java

* Don't execute updater teardown logic twice on shutdown.
* Consistently handle the edge-case where the JVM is already on its way to terminate when the shutdown code is scheduled.
* Improve Azure ServiceBus subscriptions removal.
* The code design would for sure look more satisfactory if just `teardown()` was called on each updater in a simple loop.
* However, some of the updaters performs external remote calls, which may run for a long time - potentially never succeeding.
* If executed synchronously in a serialized matter, this could mean that some updaters never get the chance to execute.
* Therefore, these updaters could/should execute their code in a thread. Currently this is done by scheduling their own JVM shutdown hook, which makes them asynchronous.
* The issue (that this PR …

Improve shutdown logic

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java

Community Transit and Everett Transit do not allow cash to be used for senior fares, so this change makes the calculator use the regular fare for senior non-electronic.
The tests are also updated to match.

Orca Fares: No senior discount for cash payments

---

src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETHttpTripUpdateSource.java

When working with a Siri feed in Germany, I noticed that OTP returns a confusing error code when the journey could not be resolved to a trip. This is fixed now.
It also fixes an exception when there is a Siri object that doesn't have a service delivery.

Use TRIP_NOT_FOUND when Siri journey cannot be resolved

---

src/main/java/org/opentripplanner/routing/service/DefaultRoutingService.java

We should include at least one error (code) when the router fails to find any results (zero itineraries). This is important so the client knows what to do. The client may retry the same query, abort, goto next/prev page or change the input - depending on the error code. If we do not provide an error code it become hard to know what to do.
🟥  This is a minor problem which came up in a developer meeting.
🟥 We do not unit-test logging.
✅ No doc added, but proper logging is also doc.
🟥 Too minor
🟥 No state cahnged.

Warn if routing is empty and there are no errors in the result

---

src/main/java/org/opentripplanner/routing/api/request/preference/BikePreferences.java
src/main/java/org/opentripplanner/routing/api/request/preference/TransitPreferences.java
src/main/java/org/opentripplanner/routing/api/request/preference/VehicleRentalPreferences.java

While working on some related things, I noticed some wrong equal checks on Costs. This fixes those and adds one missing field from a toString.
No issue as these are minor fixes but this can solve issues with transfer cache but most of these fixed fields are not exposed through any API.
Not updated, we might want to refactor tests related to these comparisons more in the future.
Not updated
From title

Fix preference cost comparisons

---

src/main/java/org/opentripplanner/framework/error/DefaultOtpError.java
src/main/java/org/opentripplanner/framework/error/OtpError.java
src/main/java/org/opentripplanner/transit/model/timetable/ScheduledTripTimes.java
src/test/java/org/opentripplanner/transit/model/timetable/ScheduledTripTimesTest.java

This causes problems in the current Entur import with FLEX routes. Flex should not be imported as regular Scheduled trips, but until this is fixed we need to add this workaround. When encountering invalid trip-times, this PR will report it in the data issue report and continue the graph-build. It will not crash as it did before. 
🟥  No issue for this.
✅ Unit tests are updated.
🟥 Not relevant.
🟥 This is a problem isolated to the current 2.5-SNAPSHOT.
🟥 No state change.

 Report and throw away trip-times which fail sanity check

---

src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
src/main/java/org/opentripplanner/netex/mapping/TripPatternMapperResult.java
src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java

As a follow-up to #5552, this PR reports an issue to the issueStore if there are duplicate journeypatterns in the Netex data.
- A small refactor to make TripPatternMapper less stateful and also make it easier to get the tripPatternId.
- Report DuplicateJourneyPattern issue for duplicate journey patterns.
Had to do some minor touches to the TripPatternMapperTest.
No

Report issue for duplicate journey patterns in NeTEx

---

docs/Basic-Tutorial.md

Mention [Protomaps](https://app.protomaps.com/) as an alternative tool for making OSM extracts.
I am a beginner to using opentripplanner and I personally found the tool a lot easier to use than any of the other
options mentioned. It does not require any downloading of new programs since it is just a website.

doc: mention protomaps in basic tutorial

---

src/ext/java/org/opentripplanner/ext/siri/SiriAlertsUpdateHandler.java
src/main/java/org/opentripplanner/apis/transmodel/model/siri/sx/PtSituationElementType.java
src/main/java/org/opentripplanner/routing/alertpatch/TransitAlert.java
src/main/java/org/opentripplanner/routing/alertpatch/TransitAlertBuilder.java
src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql

Exposes the version-field from a SIRI SX-message in the TransmodelGraphQL-api - if it exists.

Adding situation-version to TransmodelGraphQL API

---

.github/workflows/cibuild.yml
.github/workflows/debug-client.yml
.github/workflows/post-merge.yml
.gitignore
client-next/README.md
client-next/vite.config.ts

This adds a new CI workflow that:
- builds the new debug client
- pushes the compiled output to a separate repo [like this](https://github.com/opentripplanner/debug-client-assets/commit/1e2f3502d3ba24a5ea3543182cb751fe4fa3fdc6)
- adjusts the index.html so that the assets are fetched from [CDN URLs](https://cdn.jsdelivr.net/gh/opentripplanner/debug-client-assets@main/2023-12-16T14-49/assets/index-caa4bace.js)
- commits the updated index.html to the main OTP repo
This has the advantage of not needing to faff with npm when you do local development of OTP.
#5330 
Line comments.

Deploy new debug client to a CDN

---

docs/Developers-Guide.md

@abyrd has pointed out that the instructions for joining the dev meeting are confusing and I agree.
I think rather than linking to the calendar HTML page we should point to CONTRIBUTING.md which contains the latest information.
Lets discuss this.

Update dev meeting calendar instructions [ci skip]

---

doc-templates/UpdaterConfig.md
docs/RouterConfiguration.md
docs/UpdaterConfig.md
docs/sandbox/SiriUpdater.md
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/MqttGtfsRealtimeUpdaterConfig.java
src/test/resources/standalone/config/router-config.json

@abyrd has correctly pointed out that we don't have any docs about the streaming MQTT updater, which is definitely an innovative feature that we should advertise more. Threfore I added some documentation about it.

Add documentation about MQTT updater [ci skip]

---

docs/apis/GTFS-GraphQL-API.md
magidoc.mjs
src/client/graphiql/index.html
src/main/java/org/opentripplanner/apis/APIEndpoints.java
src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLAPI.java
src/main/java/org/opentripplanner/framework/graphql/GraphQLResponseSerializer.java

Changes the official path of the GTFS GraphQL API to `otp/graphql/gtfs/v1` and keeps the old one around for backwards-compatibility. We can remove the backwards-compat when all known users have migrated their systems off it, which I expect to take quite a long time.
It also removes the batch functionality which is confusing, unintuitive and in the age of HTTP2 doesn't have performance benefits.
#4052
Updated.
cc @hbruch @vesameskanen @binh-dam-ibigroup @miles-grant-ibigroup

Add new path for GTFS GraphQL API, remove batch feature

---

client-next/package-lock.json
client-next/package.json
client-next/src/components/MapView/ContextMenuPopup.tsx
client-next/src/components/MapView/GeometryPropertyPopup.tsx
client-next/src/components/MapView/LayerControl.tsx
client-next/src/components/MapView/MapView.tsx
client-next/src/components/MapView/useMapDoubleClick.ts
client-next/src/style.css
src/main/java/org/opentripplanner/apis/vectortiles/DebugStyleSpec.java
src/main/java/org/opentripplanner/apis/vectortiles/GraphInspectorVectorTileResource.java
src/main/java/org/opentripplanner/apis/vectortiles/model/LayerParams.java
src/main/java/org/opentripplanner/apis/vectortiles/model/LayerStyleBuilder.java
src/main/java/org/opentripplanner/apis/vectortiles/model/LayerType.java
src/main/java/org/opentripplanner/apis/vectortiles/model/StyleBuilder.java
src/main/java/org/opentripplanner/apis/vectortiles/model/StyleSpec.java
src/main/java/org/opentripplanner/apis/vectortiles/model/TileSource.java
src/main/java/org/opentripplanner/apis/vectortiles/model/VectorSourceLayer.java
src/main/java/org/opentripplanner/apis/vectortiles/model/ZoomDependentNumber.java
src/main/java/org/opentripplanner/inspector/vector/edge/EdgeLayerBuilder.java
src/main/java/org/opentripplanner/inspector/vector/edge/EdgePropertyMapper.java
src/main/java/org/opentripplanner/inspector/vector/edges/EdgeLayerBuilder.java
src/main/java/org/opentripplanner/inspector/vector/edges/EdgePropertyMapper.java
src/main/java/org/opentripplanner/inspector/vector/vertex/VertexLayerBuilder.java
src/main/java/org/opentripplanner/inspector/vector/vertex/VertexPropertyMapper.java
src/test/java/org/opentripplanner/apis/vectortiles/DebugStyleSpecTest.java
src/test/resources/org/opentripplanner/apis/vectortiles/style.json

This iteration adds switchable debug layers for edges to the Debug UI.
I expect there to be many more iterations where we add more layers, styles and information to help debugging.
I also implemented an automatic pan to the area defined by the world envelope service.
#5330 
Updated.

Switchable debug tiles for new UI

---

src/ext/java/org/opentripplanner/ext/restapi/mapping/TripTimeMapper.java
src/ext/java/org/opentripplanner/ext/restapi/model/ApiTripTimeShort.java
src/ext/java/org/opentripplanner/ext/restapi/model/ApiVehicleParkingWithEntrance.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/CarSnapshotTest.snap

#5535 has inadvertently introduced a breaking change to the REST API by changing the spelling of `realtime` to `realTime` in the API model classes.
This has caused some IBI frontend code to break, therefore I'm reverting this change.  
@amy-corson-ibigroup Can you confirm that it's correct now?
cc @miles-grant-ibigroup @daniel-heppner-ibigroup

Revert REST API spelling change of real-time

---

docs/sandbox/ReportApi.md
src/ext/java/org/opentripplanner/ext/reportapi/model/TransitGroupPriorityReport.java
src/ext/java/org/opentripplanner/ext/reportapi/resource/ReportResource.java
src/main/java/org/opentripplanner/framework/logging/Throttle.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/PriorityGroupConfigurator.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitDataCreator.java
src/test/java/org/opentripplanner/framework/logging/ThrottleTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/PriorityGroupConfiguratorTest.java

This add a report (pure text) to the Report API for listing out all transit-groups used by transit-group-priority. This feature is configured in the router-config, but there is not way to see the effect of the config, before now!
🟥 No
✅ Unit test on core features improved. There is no unit-test on the report. 
✅ Sandbox doc updated
🟥 This is a Sandbox feature
🟥 Not relevant

Transit group report

---

docs/apis/TransmodelApi.md
src/client/graphiql/index.html
src/main/java/org/opentripplanner/apis/APIEndpoints.java
src/main/java/org/opentripplanner/apis/transmodel/TransmodelAPI.java

This PR changes the path of the Transmodel API to `/otp/transmodel/v3`. In line with others it is totally backwards-compatible and you can keep using the old path for the time being.
In line with @t2gran's suggestion the endpoint at `/otp/routers/default/transmodel/live` has been removed as it simplified the migration of this path a lot.
#4052
Updated.

Change Transmodel API path to `/otp/transmodel/v3`

---

src/main/java/org/opentripplanner/framework/lang/ObjectUtils.java
src/main/java/org/opentripplanner/framework/tostring/ToStringBuilder.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleWithOffset.java
src/main/java/org/opentripplanner/transit/model/network/RoutingTripPattern.java
src/test/java/org/opentripplanner/framework/lang/ObjectUtilsTest.java
src/test/java/org/opentripplanner/framework/tostring/ToStringBuilderTest.java

This is a small improvement in the logging when negative trip-times occurs in Raptor due to inconsistent trip-times. The source of the problem is probably the updaters, but to find it we need the Trip/SJ id and TripPattern id.
At Entur we see the following error in the logs:
```
ERROR 2024-01-23T11:59:59.189249241Z [resource.labels.containerName: otp2] Traveling back in time is not allowed. Board time: 23:38:34+2d, alight stop pos: 0, stop arrival time: 00:23:34+3d, trip: TripScheduleWithOffset{trip: BUS RE10B @27235, depart: 11:47:27}.
```
🟥  No issue for this exist.
✅   Relevant Unit tests added.
✅ JavaDoc updated
🟥  This is too minor to be in the changelog.
🟥  Not needed.

Log trip and pattern id when negative trip-times occurs in routing.

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapperTest.java

Pass-through and transit-group-priority uses the same Raptor feature and can not be use at the same time (for now - if needed we can fix this). In OTP now pass-through is disabled if transit-priority is enabled. This is a bit unfortunate since transit-priority is a more general thing that might be set up as a default configured feature, while pass-through is always specific to a request. So, it make more sense to turn it around and only allow transit-group-priority if no pass-through-stops exist in the request. This PR does exactly this.
🟥 This issue was reported internally at Entur, and no issue was created for it. The fix is very simple.
✅ Added a regression test and a smoke test on the mapping of pass-through-points
🟥 No doc added
🟥  This bug did not exist tín the previous version of …

Pass-through should override transit-group-priority

---

src/main/java/org/opentripplanner/transit/model/site/GroupStopBuilder.java
src/test/java/org/opentripplanner/transit/model/site/GroupStopTest.java

It now simply adds the geometry of the location to the geometry collection of the GroupStop. It was unclear what the large (100x100 degree) envelopes around regular stops were doing. It  looked like a bug, and the geometry of GroupStops appears unused so it should be safe to change.
Added unittests for geometry and encompassingAreaGeometry in GroupStop. Existing unittests pass and local runs look good.

Refactor GroupStopBuilder addLocation method

---

docs/RouteRequest.md
src/ext/java/org/opentripplanner/ext/restapi/resources/RequestToPreferencesMapper.java
src/main/java/org/opentripplanner/apis/gtfs/mapping/RouteRequestMapper.java
src/main/java/org/opentripplanner/routing/api/request/preference/VehicleWalkingPreferences.java
src/main/java/org/opentripplanner/standalone/config/routerequest/VehicleWalkingConfig.java
src/main/java/org/opentripplanner/street/model/edge/BikeWalkableEdge.java
src/test/java/org/opentripplanner/routing/api/request/preference/VehicleWalkingPreferencesTest.java
src/test/java/org/opentripplanner/street/integration/BikeWalkingTest.java
src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java

This renames hopCost and hopTime to mountDismountCost and mountDismountTime in the internal model and in router-config.json as the old naming was confusing.
This is related to https://github.com/opentripplanner/OpenTripPlanner/issues/4803
Updated tests
Updated docs
From title

Rename hopCost/Time -> mountDismountCost/Time  in router-config.json

---

src/main/java/org/opentripplanner/transit/model/site/GroupStop.java

This was an oversight earlier. Returning the list of coordinates of the memberstops of a GroupStop is confusing when an area is expected.

Change the GroupStop's getEncompassingAreaGeometry method to return an empty optional if the group stop is not defined as an area

---

src/ext-test/java/org/opentripplanner/ext/stopconsolidation/DecorateConsolidatedStopNamesTest.java
src/ext/java/org/opentripplanner/ext/stopconsolidation/DecorateConsolidatedStopNames.java
src/ext/java/org/opentripplanner/ext/stopconsolidation/StopConsolidationService.java
src/ext/java/org/opentripplanner/ext/stopconsolidation/internal/DefaultStopConsolidationService.java
src/ext/java/org/opentripplanner/ext/stopconsolidation/model/ConsolidatedStopLeg.java
src/main/java/org/opentripplanner/model/plan/Place.java

During client review, we noticed that the logic for the consolidated stops are not quite as specified which is rectified with this PR.
@miles-grant-ibigroup can you test that this satisfies the requirements?
Adapted.

Improve business logic for consolidated stops

---

src/main/java/org/opentripplanner/apis/transmodel/mapping/RequestModesMapper.java
src/test/java/org/opentripplanner/apis/transmodel/mapping/RequestModesMapperTest.java

This PR changes the behavior of the modes field so that the "WALK" defaults are applied also when some of the access, egress, and direct modes are set. Previously the default would only be applied if none of the three are set.
Added new unittest for the mapping of GraphQL modes to OTP internal modes.
Updated javadoc.

Set defaults of the modes WALK, even if one and not the others are set

---

docs/RouteRequest.md
src/main/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferences.java
src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
src/test/java/org/opentripplanner/routing/api/request/preference/StreetPreferencesTest.java

In a previous PR #5381 I set the flex accessEgress penalty to the same value as Park&Ride. It turns out that this is too aggressive and I lowered the value accordingly.
Autogenerated.

Reduce flex default access/egress penalty

---

docs/sandbox/MapboxVectorTilesApi.md
src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
src/main/java/org/opentripplanner/apis/support/TileJson.java
src/main/java/org/opentripplanner/framework/io/HttpUtils.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/VectorTileConfig.java
src/test/java/org/opentripplanner/apis/support/TileJsonTest.java
src/test/java/org/opentripplanner/framework/io/HttpUtilsTest.java

@fpurcell has requested that the `attribution` in `tilejson.json` be made configurable as the automatically generated one can become very long when there are many feeds in the graph.
Closes #5661

Allow configuring a custom attribution for vector tiles

---

.github/workflows/debug-client.yml
client-next/package-lock.json
client-next/package.json
client-next/src/components/ItineraryList/ItineraryList.test.tsx
client-next/src/components/SearchBar/SearchBar.test.tsx
client-next/vite.config.ts

Basic smoke test, to build more confidence in PRs, especially dependency upgrades.

Debug UI smoke tests

---

docs/BuildConfiguration.md
src/main/java/org/opentripplanner/openstreetmap/tagmapping/HamburgMapper.java
src/main/java/org/opentripplanner/openstreetmap/tagmapping/OsmTagMapperSource.java
src/test/java/org/opentripplanner/openstreetmap/tagmapping/HamburgMapperTest.java

Adds a custom OSM mapper for Hamburg to improve routing.
Closes #5700 
The build configuration was updated with new enum value.
- unit tests were added to test updated behaviour

Add Hamburg OSM mapper

---

src/ext/java/org/opentripplanner/ext/siri/ModifiedTripBuilder.java
src/ext/java/org/opentripplanner/ext/siri/mapper/PickDropMapper.java
src/ext/java/org/opentripplanner/ext/stopconsolidation/StopConsolidationModule.java
src/main/java/org/opentripplanner/framework/lang/MemEfficientArrayBuilder.java
src/main/java/org/opentripplanner/transit/model/network/StopPattern.java
src/main/java/org/opentripplanner/transit/model/network/TripPattern.java
src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
src/test/java/org/opentripplanner/framework/lang/MemEfficientArrayBuilderTest.java
src/test/java/org/opentripplanner/model/TripPatternTest.java
src/test/java/org/opentripplanner/netex/mapping/ServiceLinkMapperTest.java
src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java

Realtime updates (at least Siri ET) should in general not be treated as cumulative updates. This make the logic complicated, you need to account for all kind of updates when applying a new on top of others. In the case of a malicious update, resending a ok one will not fix the problem as well. 
This PR changes the stop-pattern logic so that a update is applied on top of the planned stop-pattern and not the last version from the previous update. ~~There are a few places where this happens, so I included a few commits witch revert the changes if needed. The plan is either to drop those commits or to squash them.~~ (I have removed these commits now, since no one requested them).
I would like to see som tests of this with various updators:
At Entur we applied the following update several time …

Avoid cumulative real-time updates

---

src/main/java/org/opentripplanner/raptor/rangeraptor/transit/AccessPaths.java
src/test/java/org/opentripplanner/raptor/rangeraptor/transit/AccessPathsTest.java

A critical bug was introduced with the #5715. The effect of the bug was that all normal access was filtered out when an access with time-penalty existed. So, normal transit with walk access would dissapaer from the result. When setting the access mode to WALK the system would work as normal, only if an access with opening-hours exist would the walk access be filtered away.
This was discovered at Entur 2 days ago, and we have not created an issue for it.
✅  The unit tests are updated to cover this case.
🟥  This bug was introduced in 2.5-SNAPSHOT, so it does not exist in the last release of OTP; Hence, do not belong in the change log.
🟥  The model is not changed.

Fix error in access filter when access with time-penalty exits

---

src/main/java/org/opentripplanner/framework/io/OtpHttpClient.java

On one of my deployments we also use Entur's Lamassu with ~70 GBFS feeds. OTP's regular GBFS downloading was 
leading another developer looking after Lamassu to think that a load test was underway. :flushed: 
For this reason I'm setting a user agent identifying HTTP calls that originate from OTP.
cc @derhuerst @hbruch

Add user agent to HTTP client

---

src/main/java/org/opentripplanner/service/worldenvelope/model/WorldEnvelope.java
src/main/java/org/opentripplanner/service/worldenvelope/model/WorldEnvelopeBuilder.java
src/test/java/org/opentripplanner/service/worldenvelope/model/WorldEnvelopeTest.java

I was working with a UK data set today and noticed that half of the debug tiles were not displayed correctly.
The cut off went right through the middle of London near the Greenwich meridian.
It turns out that the lower left tile boundaries in the debug client, which are derived from the world envelope builder, are too far east. 
The fix was a tiny change to the `WorldEnvelopeBuilder`: the problem was that when we have a data set crossing the meridian, we need to go as far west as possible but using the smallest (most negative) number, not the largest one, which would be around Greenwich.
Added.
Added.

Fix world envelope builder when crossing Greenwich meridian

---

docs/sandbox/siri/SiriAzureUpdater.md
src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureUpdaterParameters.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/azure/SiriAzureUpdaterConfig.java

Adjust SIRI ServiceBus-client parameters to improve performance
* Move to ServiceBusReceiveMode.RECEIVE_AND_DELETE instead of PEEK_LOCK. In this mode the message is deleted from the subscription as soon as it has been delivered. In case of an error this means that the message is lost but 1) the data is applied to the graph in another thread anyway and 2) there is nothing that indicates that a second attempt on the same message data would be more successful.
* Fetch more than one message at a time, greatly improving message throughput even with small values. Roundtrip latency of the message fetching can in some situations otherwise lead to the client falling behind. Add config parameter 'prefetchCount' with a default value of 10 messages.
* Lower the AutoDeleteOnIdle of subscriptions from …

Adjust SIRI ServiceBus-client parameters to improve performance

---

.github/workflows/performance-test.yml
test/performance/skanetrafiken/build-config.json

Fix and re-enable skanetrafiken performance tests
Closes #5702

Fix skanetrafiken performance test

---

README.md

The link referred to the older URL of the awesome-transit list, which is redirected to the new repository

Update Link in README.md [ci skip]

---

src/main/java/org/opentripplanner/updater/alert/GtfsRealtimeAlertsUpdater.java
src/main/java/org/opentripplanner/updater/trip/MqttGtfsRealtimeUpdater.java

This makes the messages output by the MQTT GTFS Realtime updater more similar to those produced by other updaters. It just makes the logs more uniform and slightly more informative.
It has been tested in local usage with a connection to the Digitransit MQTT RT feeds.
The code formatting rules make the toString method harder to read, so maybe this should be converted to a StringBuilder or equivalent.

Make logging of MQTT realtime updater more uniform

---

client-next/src/components/MapView/GeometryPropertyPopup.tsx
client-next/src/style.css

This is a small improvement to the new debug client: add the ability to link from the geometry popup to osm.org so you can quickly cross-reference the data.

Add link to osm.org from new debug client

---

pom.xml
src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/TestTransitService.java
src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapperTest.java
src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stops/RealtimeStopsLayerTest.java
src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerTest.java
src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/VehicleParkingGroupsLayerTest.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/DigitransitVehicleParkingGroupPropertyMapper.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehicleparkings/StadtnaviVehicleParkingPropertyMapper.java

The vector tiles code uses the json-simple library to convert data into JSON format. This library has been released last in 2012 and of course duplicates the functionality of our other JSON library, Jackson.
In the interest of keeping the dependencies as low as possible, I'm removing it and replacing all the uses with Jackson.
I added new tests for the station mapper and updated other tests where the JSON functionality was used. The stop layer test was split into two: one for the regular one and another one for the realtime layer.
None, because it is just refactoring.

Remove dependency on org.json-simple

---

.github/workflows/cibuild.yml
.github/workflows/performance-test.yml

The old Codcov Github Action is being phase out so I'm using the new one which requires a token.

Upgrade Codecov action and use token [ci skip]

---

doc-templates/VehicleParking.md
docs/RouterConfiguration.md
docs/UpdaterConfig.md
docs/sandbox/VehicleParking.md
docs/sandbox/siri/SiriAzureUpdater.md
docs/sandbox/siri/SiriUpdater.md
src/ext-test/java/org/opentripplanner/ext/vehicleparking/noi/NoiUpdaterTest.java
src/ext-test/resources/org/opentripplanner/ext/vehicleparking/noi/stations.json
src/ext/java/org/opentripplanner/ext/vehicleparking/noi/NoiUpdater.java
src/ext/java/org/opentripplanner/ext/vehicleparking/noi/NoiUpdaterParameters.java
src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParking.java
src/main/java/org/opentripplanner/standalone/config/framework/json/OtpVersion.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/VehicleParkingUpdaterConfig.java
src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingDataSourceFactory.java
src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingSourceType.java
src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdater.java
src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
src/test/java/org/opentripplanner/graph_builder/module/VehicleParkingLinkingTest.java
src/test/java/org/opentripplanner/routing/vehicle_parking/VehicleParkingHelperTest.java
src/test/java/org/opentripplanner/routing/vehicle_parking/VehicleParkingTestUtil.java
src/test/java/org/opentripplanner/street/model/_data/StreetModelForTest.java
src/test/java/org/opentripplanner/street/model/edge/VehicleParkingEdgeTest.java
src/test/java/org/opentripplanner/street/model/edge/VehicleParkingPreferredTagsTest.java
src/test/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdaterTest.java
src/test/resources/standalone/config/router-config.json

Adds a sandbox vehicle parking updater for the Italian region of South Tyrol. 
It also tightens up the vehicle parking data model so that you must supply an id and a coordinate, which required some changes in the test code.
Added.
Added.

Parking updater for NOI Open Data Hub

---

src/main/java/org/opentripplanner/openstreetmap/model/OSMWay.java
src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
src/main/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapper.java
src/main/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapper.java
src/test/java/org/opentripplanner/openstreetmap/model/OSMWayTest.java
src/test/java/org/opentripplanner/openstreetmap/model/OSMWithTagsTest.java
src/test/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapperTest.java
src/test/java/org/opentripplanner/openstreetmap/tagmapping/FinlandMapperTest.java
src/test/java/org/opentripplanner/openstreetmap/wayproperty/WayPropertySetTest.java

Cycling on bicycle=use_sidepath is no longer banned but discouraged with safety values. foot=use_sidepath has no same effect for walking. For Finland mapper, also walking is discouraged when bicycle=use_sidepath is used.
This fixes some occurances where we get a route through a road with cars with walking even though there is a walking path close to the road that is tagged to the car road in OSM with either foot=use_sidepath or bicycle=use_sidepath.
For example https://www.openstreetmap.org/way/574874058
No issue as minor OSM mapper change.
Updated tests
No need to update
From title

Discourage instead of ban cycling on use_sidepath ways and do the same for walking on foot=use_sidepath

---

src/main/java/org/opentripplanner/apis/transmodel/mapping/RequestModesMapper.java
src/test/java/org/opentripplanner/apis/transmodel/mapping/RequestModesMapperTest.java

Overwrite default WALK directMode when it is not set in the request, but modes is set. Defaulting it to walk when it was not set caused issues when the user expected no results because transportModes are defined.
Updated existing unit test to pass. Also verified that the results are as expected with the related [Entur Shamash Query](https://api.staging.entur.io/graphql-explorer/journey-planner-v3?query=query%28%24from%3ALocation%21%24to%3ALocation%21%24dateTime%3ADateTime%21%24arriveBy%3ABoolean%21%24whitelistedAuthorities%3A%5BID%5D%21%24blacklistedAuthorities%3A%5BID%5D%21%24blacklistedLines%3A%5BID%5D%21%24whitelistedLines%3A%5BID%5D%21%24modes%3AModes%24searchWindow%3AInt%24numTripPatterns%3AInt%21%24includeRealtimeCancellations%3ABoolean%24includePlannedCancellations%3ABoolean%24trans …

Overwrite default WALK directMode when it is not set in the request, but modes is set

---

src/main/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializer.java
src/test/java/org/opentripplanner/model/plan/legreference/LegReferenceSerializerTest.java

When OTP fails to base64-decode an invalid serialized leg reference, this is currently reported as a server error with the following error message :
```
Exception while fetching data (/leg) : Last unit does not have enough valid bits
java.lang.IllegalArgumentException: Last unit does not have enough valid bits
at java.base/java.util.Base64$Decoder.decode0(Base64.java:872)
at java.base/java.util.Base64$Decoder.decode(Base64.java:570)
at java.base/java.util.Base64$Decoder.decode(Base64.java:593)
at org.opentripplanner.model.plan.legreference.LegReferenceSerializer.decode(LegReferenceSerializer.java:54)
at org.opentripplanner.apis.transmodel.TransmodelGraphQLSchema.lambda$create$56(TransmodelGraphQLSchema.java:1605)
at graphql.execution.ExecutionStrategy.invokeDataFetcher(ExecutionStrategy.ja …
```

Improve handling of invalid leg reference

---

src/main/java/org/opentripplanner/framework/geometry/GeometryUtils.java
src/main/java/org/opentripplanner/graph_builder/module/ned/ElevationModule.java

When profiling something else, I noticed during test setup `GeometryUtils` takes up to 500ms to initialize. That is because it does quite an expensive lookup of a coordinate reference system in a HSQL embedded database.
Why is this bad?
I strive to write tests that execute quite quickly so having 500ms startup time for a test is a reason for me to investigate. If I move the initialization into `ElevationModule` investigating slow tests will be less noisy.

Move expensive `WGS84_XY` constant setup into ElevationModule

---

src/main/java/org/opentripplanner/netex/mapping/TripPatternMapper.java
src/test/java/org/opentripplanner/netex/mapping/NetexTestDataSample.java
src/test/java/org/opentripplanner/netex/mapping/TripPatternMapperTest.java

As detailed in #5793, querying passing times for a replaced DatedServiceJourney fails currently with a NullPointerException.  
The root cause is the creation of a duplicated Trip object during graph building when resolving the reference to the ServiceJourney associated with a replaced DatedServiceJourney.
Since looking up a given Trip in a Timetable is based on object identity rather than object equality (see https://github.com/opentripplanner/OpenTripPlanner/blob/d15e61655f485f4f1b8c9de1e5c2468444b9f8f5/src/main/java/org/opentripplanner/model/Timetable.java#L119), the lookup fails and leads to a NullPointerException.
The issue can be solved by using a deduplicator when creating the Trip object during graph building.
Close #5793 
No

Fix trip duplication in Graph Builder DSJ mapping

---

src/main/java/org/opentripplanner/transit/model/basic/Money.java
src/test/java/org/opentripplanner/routing/core/MoneyTest.java

I found a rather embarrassing bug where the vehicle parking updater would randomly add and remove parking lots. This was due to the fact that `equals` and `hashCode` in `VehicleParking` were not symetric.
I traced it down to `Money` not having implemented `hashCode`. :flushed: 

Implement `hashCode` for `Money` class

---

src/main/java/org/opentripplanner/raptor/rangeraptor/standard/heuristics/HeuristicsAdapter.java
src/main/java/org/opentripplanner/raptor/spi/RaptorCostCalculator.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/CostCalculatorFactory.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/DefaultCostCalculator.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/PatternCostCalculator.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/WheelchairCostCalculator.java
src/test/java/org/opentripplanner/raptor/_data/RaptorTestConstants.java
src/test/java/org/opentripplanner/raptor/_data/transit/TestTransitData.java
src/test/java/org/opentripplanner/raptor/moduletests/B05_EgressStopTransferCostTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/DefaultCostCalculatorTest.java

This PR fixes an issue in the heuristics optimization in raptor where the stopTransferCost is not correctly subtracted for egress legs. We found a case in skånetrafiken where this caused an optimal path to be discarded.
The issue is that during cost calculation, the stopTransferCost is added to all alightings, and if it later turns out that this is an egress leg that cost is later subtracted. However this is not done in the heuristic cost calculation. Thus there are some cases where the heuristics will give a higher cost estimate than what the actual cost is going to be and this causes incorrectly pruned paths.
I updated the costCalculator to subtract the stop transfer cost and also renamed `calculateMinCost()` to `calculateRemainingMinCost()` in order to clarify that it doesn't do a …

Fix bug in heuristics cost calculation for egress legs

---

docs/index.md

My understanding is that a decision was made to use the mailing list only for announcements, and the Gitter chat for all other support and discussion. We are still getting questions posted to the mailing list, which then requires someone to reply encouraging the person to use Gitter, which means the whole list will receive these questions and response emails. I went looking for why this was happening, and see that the landing page of the docs still says "The fastest way to get help is to use our Gitter chat room where most of the core developers are. You can also send questions and comments to the mailing list...". This PR changes the part about the mailing list to say it's used only for announcements.

De-emphasize mailing list in landing page

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java

Kitsap Transit allows cash users to have free transfers. This modification to the fare module allows us to keep track of cash transfer value per-agency instead of only for the itinerary as a whole.
The tests were modified to check the Kitsap cash transfer policy and to ensure that it doesn't collide with KC Metro cash transfers.

ORCA Fares: Add free cash transfers for Kitsap transit

---

docs/apis/GTFS-GraphQL-API.md

It is possible to misread the `/graphiql` URL as `/graphql`, see #5824. This change adds an additional hint to the documentation reader.
Closes #5824

docs: point to additional i in GraphiQL URL [ci skip]

---

README.md

As pointed out by @leonardehrenfried, the update to the docs about the mailing list also needed to be copied into the top-level readme.

Copy mailing list information from docs to readme [ci skip]

---

src/main/java/org/opentripplanner/apis/transmodel/mapping/RequestModesMapper.java
src/test/java/org/opentripplanner/apis/transmodel/mapping/RequestModesMapperTest.java
src/test/java/org/opentripplanner/apis/transmodel/mapping/TripRequestMapperTest.java

If the `modes` section is present but the nested `access` or `egress` parameters are not, then only transit that originates from/arrives directly at the stop should be used for the trip, just as if the parameter was present and set to null.
Fix this by setting the corresponding mode to NOT_SET in the cases where `modes` is specified but the parameter is not.
This is a regression as compared to OTP 2.4.
Adapt and add tests to cover these cases better.
Manually verified most of the permutations of cases.

Fix handling of implicit access and egress mode parameters.

---

docs/Codestyle.md

Small change to docs explaining how to perform only formatting.

Add prettier:write to docs and rephrase slightly [ci skip]

---

src/main/java/org/opentripplanner/netex/NetexModule.java
src/main/java/org/opentripplanner/transit/service/TransitModel.java
src/test/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReferenceTest.java

Just a minor cleanup to not expose a mutable map and instead provide `TransitModel.addTripOnServiceDate()`
Encapsulation, loose coupling etc.

Don't expose mutable tripOnServiceDates in TransitModel

---

docs/BuildConfiguration.md
docs/RouteRequest.md
docs/RouterConfiguration.md
docs/examples/entur/router-config.json
docs/examples/skanetrafiken/router-config.json
src/main/java/org/opentripplanner/model/Timetable.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitLayer.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitTuningParameters.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/CostCalculatorFactory.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/cost/DefaultCostCalculator.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRoutingRequestTransitData.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/api/TransferOptimizationParameters.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/configure/TransferOptimizationServiceConfigurator.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTail.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/model/StopPriorityCostCalculator.java
src/main/java/org/opentripplanner/routing/algorithm/transferoptimization/services/OptimizePathDomainService.java
src/main/java/org/opentripplanner/standalone/config/buildconfig/GtfsConfig.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/TransitRoutingConfig.java
src/main/java/org/opentripplanner/standalone/config/routerequest/TransferConfig.java
src/test/java/org/opentripplanner/raptor/_data/transit/TestTransitData.java
src/test/java/org/opentripplanner/raptor/moduletests/B05_EgressStopBoardAlightTransferCostTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapperTest.java
src/test/java/org/opentripplanner/routing/algorithm/transferoptimization/model/OptimizedPathTailTest.java
src/test/resources/standalone/config/router-config.json
test/performance/norway/speed-test-config.json
test/performance/skanetrafiken/speed-test-config.json
test/performance/switzerland/speed-test-config.json

The stop-specific costs that are applied for boarding and alighting during transfers is poorly named as discussed in #5783. The list is inconistently named throughout the code and is sometimes called `stopTransferCosts` and sometimes `stopBoardAlightCosts`. But neither of these names capture the behaviour that it is applied both for boarding and alighting but only during transfers.
This PR fixes this by renaming it to `stopBoardAlightTransferCost` as suggested in #5783. While the new name is not obvious, at least it will prompt readers of the code to read the documentation.
The router configuration parameter `stopTransferCost` that is used to map netex stop priorities to costs is renamed to `stopBoardAlightDuringTransferCost`. I'm not 100% sure about this name and am open to other …

Make naming of stopTransferCosts/stopBoardAlightCosts consistent

---

src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls

Mark the banned stops feature as deprecated in the GraphQL API.
Closes #5840
Relates to #2843
Will be auto-generated.

Mark banned stops as deprected in GTFS GraphQL API [ci skip]

---

src/ext/java/org/opentripplanner/ext/ridehailing/service/uber/UberService.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriETGooglePubsubUpdater.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriHttpLoader.java
src/ext/java/org/opentripplanner/ext/siri/updater/azure/AbstractAzureSiriUpdater.java
src/ext/java/org/opentripplanner/ext/smoovebikerental/SmooveBikeRentalDataSource.java
src/ext/java/org/opentripplanner/ext/vehicleparking/bikely/BikelyUpdater.java
src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslFacilitiesDownloader.java
src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslHubsDownloader.java
src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdater.java
src/ext/java/org/opentripplanner/ext/vehiclerentalservicedirectory/VehicleRentalServiceDirectoryFetcher.java
src/main/java/org/opentripplanner/datastore/https/HttpsDataSourceRepository.java
src/main/java/org/opentripplanner/datastore/https/HttpsFileDataSource.java
src/main/java/org/opentripplanner/framework/io/JsonDataListDownloader.java
src/main/java/org/opentripplanner/framework/io/OtpHttpClient.java
src/main/java/org/opentripplanner/framework/io/OtpHttpClientFactory.java
src/main/java/org/opentripplanner/updater/alert/GtfsRealtimeAlertsUpdater.java
src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
src/main/java/org/opentripplanner/updater/spi/GenericJsonDataSource.java
src/main/java/org/opentripplanner/updater/trip/GtfsRealtimeTripUpdateSource.java
src/main/java/org/opentripplanner/updater/vehicle_position/GtfsRealtimeHttpVehiclePositionSource.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoader.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSource.java
src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/VehicleRentalDataSourceFactory.java
src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFeedLoaderTest.java
src/test/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsVehicleRentalDataSourceTest.java

Removes OtpHttpClient's own logger and passes in loggers from where it's used from. Adds a trace log for http responses in case there is an error response coming from an external API.
closes #5761
New tests will not be added.
Not needed
Not sure if needed

Add trace log for HTTP error responses

---

src/ext/java/org/opentripplanner/ext/restapi/mapping/TripMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
src/main/java/org/opentripplanner/transit/model/timetable/Trip.java
src/main/java/org/opentripplanner/transit/model/timetable/TripBuilder.java
src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java
src/test/java/org/opentripplanner/transit/model/timetable/TripTest.java

Today I noticed that there is a field on `Trip` which appears to be both non-standard and unused: the fare ID.
It's not used internally and only exposed through the REST API. I think it's fair to remove it.

Remove non-standard trip fare ID

---

src/ext-test/java/org/opentripplanner/ext/siri/SiriEtBuilder.java
src/ext-test/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSourceTest.java
src/ext/java/org/opentripplanner/ext/siri/EntityResolver.java
src/main/java/org/opentripplanner/framework/time/DateUtils.java
src/main/java/org/opentripplanner/model/Timetable.java
src/test/java/org/opentripplanner/DateTimeHelper.java
src/test/java/org/opentripplanner/transit/model/_data/TransitModelForTest.java

This PR is part of the realtime refactor work.
It mainly contains tests for SiriTimetableSnapshotSource. The purpose is to:
1) Verify that the transit model is updated correctly given different siri ET messages.
2) Make it easier to refactor the realtime behaviour without breaking functionality.
3) Document existing behaviour.
Currently the tests are on a pretty high level and basically generate Siri ET messages, apply them using SiriTimetableSnapshotSource and then verify the changes to the realtime parts of the transit model.
There are also two minor bugfixes:
- ~~Comparison of feedId in timetable.~~ (moved this to a separate PR)
- NPE fix in `EntityResolver.resolveServiceDate()` when the list of calls is empty.

SiriTimetableSnapshot tests

---

src/main/java/org/opentripplanner/model/Timetable.java
src/test/java/org/opentripplanner/model/TimetableTest.java

Change comparison of feedId in Triptimes to use `.equals()` instead of `==`. In practice it doesn't cause any issues currently, but the current code is dangerous since anyone using this method will expect structural comparison.
Discussion:
There was some concern raised that the original code might use `==` for performance reasons. But for that case there is a method `getTripTimes(Trip trip)` that uses referential equality and then we could change the performance critical code to use that method instead.
Added a unit test to illustrate the issue.
Nope

Fix comparison of feedId

---

src/main/java/org/opentripplanner/apis/transmodel/model/stop/QuayType.java
src/main/java/org/opentripplanner/apis/transmodel/model/stop/StopPlaceType.java
src/main/java/org/opentripplanner/apis/transmodel/support/GqlUtil.java
src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
src/test/java/org/opentripplanner/apis/transmodel/support/GqlUtilTest.java

The timeRange parameter in the TransModel GraphQL API lacks documentation and validation logic.
It fails with a non-descriptive error message when provided with a null value:
```
"Exception while fetching data (/stopPlace/estimatedCalls) : Cannot invoke "java.lang.Integer.longValue()" because "timeRangeInput" is null
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.longValue()" because "timeRangeInput" is null
at org.opentripplanner.apis.transmodel.model.stop.StopPlaceType.lambda$create$17(StopPlaceType.java:360)
at graphql.execution.ExecutionStrategy.invokeDataFetcher(ExecutionStrategy.java:329)
```
or a negative value:
```
Exception while fetching data (/stopPlace/estimatedCalls) : 2024-04-27 < 2024-04-28
java.lang.IllegalArgumentException: 2024-04-27 < 2024-04-28
at …
```

Document and validate timeRange GraphQL parameter

---

src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stops/RealtimeStopsLayerTest.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitRealtimeStopPropertyMapper.java

A badge needs to be displayed on the map for stops without traffic on the service day. The vectortile layer for realtime stops checks if stop times exist for a particular stop and returns the result.
- A badge needs to be displayed on the map for stops without traffic on the service day. 
- Added the new value to the RealtimeStopsLayerTest.
- Functionality was manually verified.

Realtime stops vectortile layer checks whether there are stoptimes on the service day

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitLayer.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/RaptorRequestTransferCache.java
src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java

With this change it's possible to differentiate between entries added because of configuration and those from runtime requests, the latter being candidates for the former.
From config:
```
Initializing cache with request: StreetRelevantOptions{transferMode: WALK, walk: WalkPreferences{speed: 0.69, boardCost: $0}, street: StreetPreferences{accessEgress: AccessEgressPreferences{maxDuration: DurationForStreetMode{default:50m, WALK:48m10s}}, maxDirectDuration: DurationForStreetMode{default:1h1m40s, CAR:1d}}}
```
From runtime:
```
Adding runtime request to cache: StreetRelevantOptions{transferMode: WALK, street: StreetPreferences{accessEgress: AccessEgressPreferences{maxDuration: DurationForStreetMode{default:50m}}, maxDirectDuration: DurationForStreetMode{default:1h1m40s, CAR:1d}}}
```
This …

Log the origin of a request that causes a transfer cache addition.

---

src/ext-test/java/org/opentripplanner/ext/siri/SiriEtBuilder.java
src/ext-test/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSourceTest.java
src/ext/java/org/opentripplanner/ext/siri/SiriFuzzyTripMatcher.java

As detailed in #5864 , some SIRI updates fail with a NullPointerException. The root cause is a missing aimed departure date on the first call in the estimated vehicle journey (mandatory field in the Nordic SIRI profile).
This PR: 
- improve the error message when  aimed departure date is missing on the first call.
- add test coverage for additional use cases (SIRI updates matched by framed vehicle journey ref, fuzzy-matching)
**Note**: the null-check on aimed departure date is moved early enough in the process to provide context for the error message, but without changing the outcome.
**Note**: the SIRI test framework is extended to support:
-  the creation of  invalid SIRI messages (missing mandatory date fields),
-  the creation of  SIRI messages matched by framed vehicle journey ref,
- …

Fix handling of missing aimed departure time

---

src/main/java/org/opentripplanner/apis/transmodel/OTPRequestTimeoutInstrumentation.java
src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraph.java

The OTP request timeout feature provides a way to periodically check if the thread running an API request has been interrupted at a higher level (web server level).
This allows for cancelling long-running queries.
However this assumes that the running query will touch the code that checks for the interruption status.
While this works well for trip planning queries, other categories of query may never touch the check points.
This PR adds an extra level of protection by checking periodically the OTP request timeout status at the GraphQL level, while data is being fetched.
No.
No.
No.

Add OTP request timeout GraphQL instrumentation

---

src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
src/main/java/org/opentripplanner/apis/gtfs/datafetchers/FeedImpl.java
src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
src/main/java/org/opentripplanner/apis/gtfs/generated/graphql-codegen.yml
src/main/java/org/opentripplanner/apis/gtfs/model/FeedPublisher.java
src/main/java/org/opentripplanner/transit/model/organization/FeedPublisher.java
src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
src/test/resources/org/opentripplanner/apis/gtfs/expectations/feedinfo.json
src/test/resources/org/opentripplanner/apis/gtfs/queries/feedinfo.graphql

Add fetchers for FeedInfo publisherName and publisherUrl information.
Feedinfo test query added.
In gtfs graphql schema.

Add feed publisher name and url to GTFS GraphQL API

---

src/ext-test/java/org/opentripplanner/ext/flex/FlexTripsMapperTest.java
src/ext-test/java/org/opentripplanner/ext/flex/flexpathcalculator/FlexPathTest.java
src/ext-test/java/org/opentripplanner/ext/flex/trip/FlexTripsMapperTest.java
src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/FlexPath.java
src/ext/java/org/opentripplanner/ext/flex/flexpathcalculator/TimePenaltyCalculator.java
src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
src/main/java/org/opentripplanner/gtfs/mapping/GTFSToOtpTransitServiceMapper.java
src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
src/main/java/org/opentripplanner/routing/api/request/framework/TimePenalty.java
src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java

After merging of #5796 I realised that I missed a couple of renames where I still used the old name for time penalty (modifier, factors). This is fixed in this PR.
I also cleaned up the modifcation logic a bit: the check for `isZero` is no longer necessary as the default is a value that doesn't modify at all.
Lastly, I added a test that makes sure that the mapper sets the correct default value.

Small clean up of flex duration factor/offset

---

src/ext-test/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSourceTest.java
src/main/java/org/opentripplanner/transit/model/timetable/TripTimesStringBuilder.java

Inspired by the raptor module tests I wanted to make the assertions easier to work with in SiriTimetableSnapshotSourceTest.
The previous assertions were pretty verbose since you had to assert each call by itself. Now you can write something along the lines:
```
assertEquals(
"UPDATED | A1 0:00:15 0:00:15 | B1 0:00:25 0:00:25",
env.getRealtimeTimetable(env.trip1)
);
```
instead of this:
```
var tripTimes = env.getTripTimesForTrip(env.trip1);
assertEquals(RealTimeState.UPDATED, tripTimes.getRealTimeState());
assertEquals(11, tripTimes.getArrivalTime(0));
assertEquals(15, tripTimes.getDepartureTime(0));
assertEquals(20, tripTimes.getDepartureTime(1));
assertEquals(25, tripTimes.getArrivalTime(1));
```
There are a lot of open PRs touching this piece of code so there might be some conflicts. …

Add nicer assertions to SiriTimetableSnapshotSourceTest

---

pom.xml
src/test/resources/gbfs/lillestrombysykkel/gbfs.json

When the GBFS model moved to MobilityData an inadvertent change was made to the implementing class mapper, so gbfs.json pointed to the generated class for v2.3, which does not work. The upgrade includes https://github.com/MobilityData/gbfs-json-schema/pull/129 which reverts to the original behavior of mapping to the hand-written class.
Closes #5889  
Test case courtesy of @leonardehrenfried (https://github.com/ibi-group/OpenTripPlanner/commit/ff938e31573837df9bf770ecfd0ebe3857b6cffb)

Fix parsing of GBFS feeds

---

client-next/src/hooks/useServerInfo.ts
client-next/src/hooks/useTripQuery.ts
client-next/src/util/getApiUrl.ts

Debug client is broken if VITE_API_URL is a relative path (which it is by default). This is due to a breaking change in v7.0.0 of graphql-request, which I overlooked when approving the upgrade: https://github.com/jasonkuhrt/graphql-request/releases/tag/7.0.0
This PR checks validity of VITE_API_URL by passing it to the URL constructor. If exception is thrown, we prefix it with the window's origin (which used to be the default behavior).
~~I still need to test this PR~~ Tested locally.

Fix debug client after breaking change in dependency graphql-request

---

src/ext/java/org/opentripplanner/ext/siri/SiriTripPatternCache.java
src/ext/java/org/opentripplanner/ext/siri/updater/SiriHelper.java

While I was investigating how to handle cancellations for Siri and GTFS (for later unification) I stumbled over a peculiar piece of complicated logic that appears to be completely unused: keeping the pattern -> stop relationship of realtime-added patterns in `SiriTripPatternCache`.
It seems that once upon a time the API was directly requesting some information from the cache but the method `getAddedTripPatternsForStop` is now completely unused. 
I believe that it can be removed.
The best way to review this, would be to look at the code yourself and start removing the dead code to see what else can also be removed.
#4816

Remove unused Siri code

---

src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
src/main/java/org/opentripplanner/graph_builder/module/nearbystops/MinMap.java
src/main/java/org/opentripplanner/graph_builder/module/nearbystops/NearbyStopFinder.java
src/main/java/org/opentripplanner/graph_builder/module/nearbystops/PatternConsideringNearbyStopFinder.java
src/main/java/org/opentripplanner/graph_builder/module/nearbystops/StraightLineNearbyStopFinder.java
src/main/java/org/opentripplanner/graph_builder/module/nearbystops/StreetNearbyStopFinder.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/AccessEgressRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/DirectFlexRouter.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/street/FlexAccessEgressRouter.java
src/test/java/org/opentripplanner/astar/strategy/MaxCountSkipEdgeStrategyTest.java

This PR is a pure refactor and shouldn't change any behaviour.
The NearbyStopsFinder has three different behaviours depending on two different parameters:
- Default street search, used if the graph has a street network.
- Straight line search, used if the graph doesn't have a street network.
- A special search considering TripPatterns that is used in conjunction with one of the above. Used if the `ConsiderPatternsForDirectTransfers` feature is enabled.
The different branches makes the code difficult to understand and difficult to test. This PR refactors this code to use the strategy pattern by extracting a common interface and having one class for each behaviour.
This work is in preparation of some work I need to do on access/egress search as part of #5848.
Unfortunately there is no tests …

Refactor NearbyStopsFinder to follow strategy pattern

---

src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java

This fixes senior fares not being allowed with cash. It was thought that senior discount was only allowed with an ORCA card, but that wasn't correct.

fix(orca-fares): allow senior fares with cash

---

doc-templates/sandbox/siri/SiriGooglePubSubUpdater.md
docs/RouterConfiguration.md
docs/examples/entur/router-config.json
docs/sandbox/VehicleParking.md
docs/sandbox/siri/SiriGooglePubSubUpdater.md
src/ext/java/org/opentripplanner/ext/siri/updater/google/SiriETGooglePubsubUpdaterParameters.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/SiriETGooglePubsubUpdaterConfig.java
src/test/java/org/opentripplanner/generate/doc/SiriGooglePubSubConfigDocTest.java
src/test/resources/standalone/config/router-config.json

This PR:
- removes unused parameters in the Google PubSub SIRI updater,
- documents the parameters,
- adds a dedicated markdown page for this updater.
**Removed parameters:**
- the parameter `projectName` is deprecated and removed. It is replaced by the now-mandatory parameters `topicProjectName` and `subscriptionProjectName`
- the parameter `purgeExpiredData` is managed in the section `timetableUpdates` . It does not need to be specified in this updater.
- the parameter `type` is managed by the configuration framework. It does not need to be specified in this updater.
No
Updated documentation test

Update Google Pubsub updater configuration

---

src/main/java/org/opentripplanner/apis/gtfs/GtfsGraphQLIndex.java
src/main/java/org/opentripplanner/apis/support/graphql/LoggingDataFetcherExceptionHandler.java
src/main/java/org/opentripplanner/apis/transmodel/LoggingDataFetcherExceptionHandler.java
src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraph.java
src/main/java/org/opentripplanner/apis/transmodel/support/AbortOnUnprocessableRequestExecutionStrategy.java
src/main/resources/logback.xml

GraphQL Java v22 removed support for logging errors in data fetchers (see https://github.com/graphql-java/graphql-java/pull/3403). This used to be controlled through the `notprivacysafe.graphql` logger.
This PR adds back this feature by creating a custom DataFetcherExceptionHandler that logs at WARN level all errors thrown from data fetchers.
This applies to the Transmodel API and the GTFS API.
The logger is disabled by default in the logback.xml file shipped with OTP (as was the case with  `notprivacysafe.graphql`)
No
No
No

Add back GraphQL data fetcher error logging

---

src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotManager.java

@vpaturet has reported that in one the previous realtime-related PRs, I didn't correctly move the Javadoc for the `snapshot` field in `TimetableSnapshotManager`.

Fix Javadoc of `TimetableSnapshotManager.snapshot`

---

.git-blame-ignore-revs
docs/apis/GraphQL-Tutorial.md
pom.xml
src/test/resources/org/opentripplanner/apis/gtfs/queries/alerts.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/feedinfo.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/nearest.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/patterns.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-extended.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-fares.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-stop-positions.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/plan-tutorial.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/planConnection.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/routes-extended.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/routes-tutorial.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/stops.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/vehicle-parking.graphql
src/test/resources/org/opentripplanner/apis/gtfs/queries/walk-steps.graphql

Use prettier to format graphql test and documentation files

Format GraphQL test and documentation files with prettier

---

docs/BuildConfiguration.md
docs/RouterConfiguration.md
src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsFeedParameters.java
src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsFeedParametersBuilder.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransfersMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapper.java
src/main/java/org/opentripplanner/transit/model/site/RegularStop.java
src/main/java/org/opentripplanner/transit/model/site/Station.java
src/main/java/org/opentripplanner/transit/model/site/StopLocation.java
src/main/java/org/opentripplanner/transit/model/site/StopTransferPriority.java
src/main/java/org/opentripplanner/transit/service/StopModel.java
src/main/java/org/opentripplanner/transit/service/StopModelIndex.java

In some cases (transit period filtering) stops can be dropped after they are created. This causes the stop-index(used in routing) to contain holes in it. This happens because the stop index is assigned to a stop when it is created. In this PR, I have gone over the code to make sure holes in the stop-index is handled correctly and no NPE is thrown.
After enabling `stopBoardAlightDuringTransferCost` I got NPE locally during testing of OTP. This fixes the NPE in TransitLayerMapper and cleans up the code a bit.
🟥  I have not added any unit-tests for this. Instead I chose to improve logging and annotated with `@Nullable` in the appropriate place.
🟥  I have just updated the JaveDoc - if relevant.
✅  This is a minor bug fix.
✅  The order of the `StopTransferPriority` enums are changed. This may …

Fix NullPointerException in stop transfer priority cost vector generation

---

src/main/java/org/opentripplanner/routing/api/request/framework/LinearFunctionSerialization.java
src/test/java/org/opentripplanner/routing/api/request/framework/LinearFunctionSerializationTest.java

A request that specifies a time penalty with an incorrect duration format:
```
accessEgressPenalty: [{
streetMode: flexible
timePenalty: "600ss + 1.3 t"
costFactor: 1.3
}],
```
fails with an HTTP 500 error:
```
"Text cannot be parsed to a Duration: '600ss' java.time.format.DateTimeParseException: Text cannot be parsed to a Duration: '600ss'
at org.opentripplanner.framework.time.DurationUtils.duration(DurationUtils.java:121)
at org.opentripplanner.routing.api.request.framework.LinearFunctionSerialization.parse(LinearFunctionSerialization.java:68)
at org.opentripplanner.apis.transmodel.model.scalars.DoubleFunctionFactory$1.parseValue(DoubleFunctionFactory.java:59)
at org.opentripplanner.apis.transmodel.model.scalars.DoubleFunctionFactory$1.parseLiteral(DoubleFunctionFactory.java:73)
at …
```

Fix duration parsing error handling

---

src/main/java/org/opentripplanner/apis/transmodel/model/EnumTypes.java
src/main/java/org/opentripplanner/apis/transmodel/model/stop/MonoOrMultiModalStation.java
src/main/java/org/opentripplanner/apis/transmodel/model/stop/StopPlaceType.java
src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql

This PR exposes stop transfer priority in the TransModel API.
"Stop transfer priority" is used to specify the relative preference of a stop when several stops can be used for a transfer.
In the TransModel API `transfers` are referred to as `interchanges`.
The naming of the existing field `weighting` was confusing and the data fetching was never implemented (it returned always the same value)
It is replaced by `stopInterchangePriority` whose name matches more clearly the name `interchangePriority`, that is the  priority set on interchanges. 
The NeTEx enum values are also confusing, in particular `interchangeNotAllowed`. It is replaced by `discouraged` which matches the actual behaviour of OTP (not banning but discouraging the transfer at a given stop). 
No
No
Updated API documentation

Expose stop transfer priority in Transmodel API

---

src/main/java/org/opentripplanner/model/TimetableSnapshot.java
src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java

This PR makes use of immutable data structures in the timetable snapshot.
This ensures that attempts to modify the data structures after the snapshot is committed will fail fast.
In addition the immutable maps created by` Map.copyOf()` and `ImmutableSetMultimap.copyOf()` cannot contain null keys or values, providing a way to fail fast if these conditions are not fulfilled.
To further prevent attempts to modify a published timetable snapshot, methods that modify the states are either made private or are guarded by a condition on the `readOnly` field.
**Note**: It does not seem that in today's code any of these requirements on immutability is broken: the write API is not called after the timetable snapshot is created, null keys and values are not used, the collections are not modified after …

Enforce immutability of published timetable snapshot

---

src/test/java/org/opentripplanner/transit/service/DefaultTransitServiceTest.java

This PR fixes a merge conflict that occured when removing a setter method in TimetableSnapshot in one PR that was used in a unit test in another PR.
This PR refactors the unit test to create the test context method without using the setter method.
No
Fixed unit test
No

Fix TimetableSnapshot merge conflict

---

src/main/java/org/opentripplanner/netex/mapping/MultiModalStationMapper.java
src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
src/main/java/org/opentripplanner/transit/model/site/MultiModalStation.java
src/test/java/org/opentripplanner/netex/mapping/MultiModalStationMapperTest.java
src/test/java/org/opentripplanner/transit/model/site/MultiModalStationTest.java

When querying a multimodal station without coordinates through the GraphQL API, the call fails with a NullPointerException:
```
Exception while fetching data (/trip/tripPatterns[0]/legs[5]/intermediateEstimatedCalls[7]/quay/stopPlace) : Cannot invoke "org.opentripplanner.framework.geometry.WgsCoordinate.latitude()" because the return value of "org.opentripplanner.transit.model.site.StopLocationsGroup.getCoordinate()" is null
java.lang.NullPointerException: Cannot invoke "org.opentripplanner.framework.geometry.WgsCoordinate.latitude()" because the return value of "org.opentripplanner.transit.model.site.StopLocationsGroup.getCoordinate()" is null
at org.opentripplanner.transit.model.site.StopLocationsGroup.getLat(StopLocationsGroup.java:25)
at …
```

Enforce non-null coordinates on multimodal station

---

src/ext-test/java/org/opentripplanner/ext/siri/AddedTripBuilderTest.java
src/ext/java/org/opentripplanner/ext/siri/AddedTripBuilder.java
src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
src/main/java/org/opentripplanner/transit/service/TransitEditorService.java
src/main/java/org/opentripplanner/transit/service/TransitModel.java
src/main/java/org/opentripplanner/transit/service/TransitModelIndex.java
src/main/java/org/opentripplanner/transit/service/TransitService.java

As detailed in #5965, some Transit model indexes are modified concurrently in the real-time updaters without proper synchronization, causing data inconsistencies in reader threads.
This PR aims at refactoring the code to better identify and document the root causes of these concurrency issues.
This PR does not fix these concurrency issues.
Another goal of this PR is to bring the code closer to the target design (immutable transit model) [where the transit model is updated exclusively through a  TransitEditorService](https://github.com/entur/OpenTripPlanner/blob/otp2_refactor_transit_model/src/main/java/org/opentripplanner/transit/model/package.md#services-and-its-context)
The classes `SiriTimetableSnapshotSource` and `AddedTripBuilder` currently have direct access to the collections in …

Use transit editor service in SIRI timetable snapshot source

---

src/main/java/org/opentripplanner/model/TimetableSnapshot.java

This PR refactors the TimetableSnapshot class to make its shared state final.
The intent is:
1) making clear that the TimetableSnapshot fields are immutable after publication.
2) preparing further refactoring steps  where the snapshot could be published without using a lock.
According to the Java Memory Model (https://docs.oracle.com/javase/specs/jls/se7/html/jls-17.html#jls-17.5), final fields provide additional protection against re-ordering and can be used to implement thread-safe immutable objects without synchronization.
**Note**: the field TimetableSnapshot.dirty remains mutable, but is not used by reader threads.
No
No
No

Make TimetableSnapshot state final

---

docs/Container-Image.md

Just a small clarification to the docker documentation.
No issue.
Not needed
Updated
Skipped

Clarify where the logback extensions file should be mounted to when running an OTP container [ci skip]

---

src/ext-test/java/org/opentripplanner/ext/siri/AddedTripBuilderTest.java
src/main/java/org/opentripplanner/graph_builder/module/DirectTransferGenerator.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransfersMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapper.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TripPatternForDateMapper.java
src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
src/main/java/org/opentripplanner/transit/service/TransitEditorService.java
src/main/java/org/opentripplanner/transit/service/TransitModel.java
src/main/java/org/opentripplanner/transit/service/TransitModelIndex.java
src/main/java/org/opentripplanner/transit/service/TransitService.java
src/main/java/org/opentripplanner/updater/vehicle_position/PollingVehiclePositionUpdater.java
src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
src/test/java/org/opentripplanner/routing/graph/DefaultRoutingServiceTest.java
src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironment.java
src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
src/test/java/org/opentripplanner/updater/trip/moduletests/addition/AddedTest.java
src/test/java/org/opentripplanner/updater/trip/moduletests/delay/DelayedTest.java
src/test/java/org/opentripplanner/updater/trip/moduletests/delay/SkippedTest.java

This PR encapsulates the `TransitModelIndex` so that it is accessed only through the `TransitService`/`TransitEditorService` interfaces.
This prepares for further refactoring steps where the mutable state that is currently stored in the `TransitModelIndex`, the `TimetableSnapshot` and the `TransitLayer` will be handled in a more consistent and unified way.
This also brings the code closer to the target design (immutable transit model) where all transit model updates are performed through the `TransitEditorService`.
**Note**:
* The `TransitService` service should not provide direct read/write access to the underlying collections in the index. Ideally, all accessors should return an unmodifiable view of these collections. This is currently not always the case. This PR fixes this issue in a …

Encapsulate transit model index

---

src/ext/java/org/opentripplanner/ext/siri/SiriTimetableSnapshotSource.java
src/main/java/org/opentripplanner/model/TimetableSnapshot.java
src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
src/main/java/org/opentripplanner/updater/spi/TimetableSnapshotFlush.java
src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotManager.java
src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
src/test/java/org/opentripplanner/GtfsTest.java
src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironment.java
src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotManagerTest.java
src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java

In the current implementation, the timetable snapshot can be committed:
- from the graph writer thread when applying updates (see https://github.com/opentripplanner/OpenTripPlanner/blob/8391674772e122e92cf940453d166a4ea44dadba/src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotManager.java#L141)
- from reader threads when lazy-loading a snapshot (see https://github.com/opentripplanner/OpenTripPlanner/blob/359cb7368cc8942219c544981027d2d8b6c00e3e/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java#L518)
Committing the snapshot from a reader thread should be avoided: it delays the API call and it makes the implementation more complex and fragile due to synchronization between threads.
This PR modifies the snapshot lazy-loading logic so that it does not …

Publish timetable snapshot in background

---

client/.env
client/README.md
src/main/java/org/opentripplanner/apis/transmodel/model/EnumTypes.java
src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql

Now that the new debug UI uses the Transmodel API @hbruch has reported that car rental is missing from its street modes.
This PR adds it.
It also makes a new line change in the `/client` folder in order to trigger a rebuild of the debug UI so that the GraphQL schema is also rebuild and the new item shows up in the debug UI.

Add car rental to Transmodel street mode options

---

src/main/java/org/opentripplanner/netex/support/NetexVersionHelper.java
src/test/java/org/opentripplanner/netex/support/NetexVersionHelperTest.java

NeTEx allows the version of an entity to use the special string `any` which is defined as follows:
> Use "any" if the VERSION is unknown (note that this will trigger NeTEx's XML automatic consistency check).
@vpaturet has said that in they Entur pipeline an `any` value is converted to `0` before it reaches OTP.
For this reason, I am adding some special logic to the version parser that uses a fallback for this case. The fallback value existed previously and communicates the fact that the version is unknown.
https://github.com/noi-techpark/odh-mentor-otp/issues/191
Relates to #3640 
Added.
Javadoc.

Handle NeTEx `any` version

---

src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stops/StopsLayerTest.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/stops/DigitransitStopPropertyMapper.java

@miles-grant-ibigroup has reported that the field `parentId` is not correctly converted to a string in the vector tiles layer.
This was because the id was of type `FeedScopedId` and the vector tile library was silently ignoring it.
Added.

Fix conversion of parent station id in vector tiles

---

src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitLayer.java
src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerMapper.java
src/test/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapperTest.java
src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/TransitLayerTest.java

I noticed that there is a completely unused field in `TransitModel` which can be removed without replacement.

Remove unused field from TransitLayer

---

doc-templates/VehicleParking.md
docs/RouterConfiguration.md
docs/sandbox/VehicleParking.md
src/ext-test/java/org/opentripplanner/ext/vehicleparking/sirifm/SiriFmUpdaterTest.java
src/ext-test/resources/org/opentripplanner/ext/vehicleparking/sirifm/siri-fm.xml
src/ext/java/org/opentripplanner/ext/vehicleparking/bikeep/BikeepUpdaterParameters.java
src/ext/java/org/opentripplanner/ext/vehicleparking/hslpark/HslParkUpdaterParameters.java
src/ext/java/org/opentripplanner/ext/vehicleparking/noi/NoiUpdaterParameters.java
src/ext/java/org/opentripplanner/ext/vehicleparking/parkapi/ParkAPIUpdaterParameters.java
src/ext/java/org/opentripplanner/ext/vehicleparking/sirifm/SiriFmDatasource.java
src/ext/java/org/opentripplanner/ext/vehicleparking/sirifm/SiriFmUpdater.java
src/ext/java/org/opentripplanner/ext/vehicleparking/sirifm/SiriFmUpdaterParameters.java
src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParking.java
src/main/java/org/opentripplanner/routing/vehicle_parking/VehicleParkingService.java
src/main/java/org/opentripplanner/standalone/config/routerconfig/updaters/VehicleParkingUpdaterConfig.java
src/main/java/org/opentripplanner/updater/configure/UpdaterConfigurator.java
src/main/java/org/opentripplanner/updater/vehicle_parking/AvailabilityDatasourceFactory.java
src/main/java/org/opentripplanner/updater/vehicle_parking/AvailabiltyUpdate.java
src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingAvailabilityUpdater.java
src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingDataSourceFactory.java
src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingSourceType.java
src/main/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdaterParameters.java
src/test/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingAvailabilityUpdaterTest.java
src/test/java/org/opentripplanner/updater/vehicle_parking/VehicleParkingUpdaterTest.java
src/test/resources/standalone/config/router-config.json

Following up on #5946 this adds a vehicle parking updater that consumes SIRI-FM.
It introduces a new model for parking updates: rather than being able to add parking lots through a realtime updater, this only updates the availability.
We can discuss in the dev meetings, if these two update types should be handled in the same updater.
Added.
For the time being, this is a draft as I want to wait until #5946 has been merged.

SIRI-FM vehicle parking updates

---

src/ext-test/java/org/opentripplanner/ext/geocoder/EnglishNgramAnalyzerTest.java
src/ext-test/java/org/opentripplanner/ext/geocoder/LuceneIndexTest.java
src/ext/java/org/opentripplanner/ext/geocoder/EnglishNGramAnalyzer.java
src/ext/java/org/opentripplanner/ext/geocoder/LuceneIndex.java

This PR improves the sandbox geocoder by shortening the minimal n-gram to 3 from 4.
This is so that the stop name of "Meridian Ave N & N 148th St" is matched when the users search for "Meridian Ave N & N 148". Previously "148th" would only be tokenised to "148t" but not "148".
~~This also changes one of the regression test cases: When you search for "arts" you now also get "arthur place" which before you didn't. @miles-grant-ibigroup said that this is fine.~~
Added.

Improve geocoder matches for numeric adjectives

---

src/main/java/org/opentripplanner/service/realtimevehicles/internal/DefaultRealtimeVehicleService.java
src/test/java/org/opentripplanner/service/realtimevehicles/internal/DefaultRealtimeVehicleServiceTest.java

When storing realtime vehicle positions by pattern the realtime added patterns are not taken into account correctly.
This PR uses the original pattern as the key for the storage map.
Added.
Explained it in Javadoc.

Take realtime patterns into account when storing realtime vehicles

---

client/src/components/ItineraryList/ItineraryLegDetails.tsx
client/src/style.css

Update to the OTP Debug client.
Removed some spacing in the itinerary list to make the view more compact. 
https://github.com/opentripplanner/OpenTripPlanner/issues/5330#issuecomment-2273311110
This is to address the following:
UX - Less line spacing on expanded legs to make it easier to compare two itineraries.
The code is only some simple css and html changes to make the element more compact. See screenshots of before and after.

Debug client itinerary list style improvements

---

src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/VehicleRentalLayerTest.java
src/ext/java/org/opentripplanner/ext/vectortiles/layers/vehiclerental/mapper/DigitransitRentalVehiclePropertyMapper.java

Added isAllowPickup value to rental vehicle map layer return values as a user might not want to see disabled vehicles on map.
Disabled vehicles are shown on the map with no way to distinguish them from the available ones.
Added the new value to VehicleRentalLayerTest.

Rental vehicle map layer should show vehicle availability

---

src/ext-test/java/org/opentripplanner/ext/accessibilityscore/DecorateWithAccessibilityScoreTest.java
src/ext/java/org/opentripplanner/ext/accessibilityscore/DecorateWithAccessibilityScore.java

I changes the computation of the sandbox accessibility score so that it's only computed for walking and transit legs but not cycling, driving or scootering.

Compute accessibility score for walking legs only

---

src/main/java/org/opentripplanner/netex/validation/JourneyPatternSJMismatch.java
src/test/java/org/opentripplanner/netex/validation/JourneyPatternSJMismatchTest.java

As described in #6036 OTP doesn't consider pass-trough stops in `ServiceJourneyPattern`s. This modifies the validation slightly so that these are removed before comparing the number of links with the passing times.
Closes #6036
Added.
I also added some builder classes which might also become useful for other tests.
Javadoc

Allow NeTEx ServiceJourneyPatterns with stopUse=passthrough

---

pom.xml

One of the first actions as a maintainer was to deploy all OBA artifacts on Maven Central so the Maven Repo camsys-apps.com is no longer needed.
The main changes in the library code itself are 
- Removal of compatibility code for very old drafts of GTFS Flex
- Addition of cars_allowed
cc @villepihlava

Upgrade OBA, remove camsys-apps.com from Maven repos

---

src/main/java/org/opentripplanner/graph_builder/module/osm/OsmDatabase.java
src/main/java/org/opentripplanner/openstreetmap/issues/FloorNumberUnknownAssumedGroundLevel.java
src/main/java/org/opentripplanner/openstreetmap/issues/FloorNumberUnknownGuessedFromAltitude.java
src/main/java/org/opentripplanner/openstreetmap/model/OSMLevel.java

OSM level and layer processing generates lots of data issue reports. Those used to be fairly useless because the report did not specify which OSM entity had the problem.
Now  each reported ambiquity contains a link to the OSM item.

OSM data links added to the graph build report about ambiguous levels and layers

---

client/.env
client/.env.development
client/src/components/ItineraryList/ItineraryGraphiQLAuthorityLink.tsx
client/src/components/ItineraryList/ItineraryGraphiQLLineLink.tsx
client/src/components/ItineraryList/ItineraryGraphiQLQuayLink.tsx
client/src/components/ItineraryList/ItineraryLegDetails.tsx
client/src/components/SearchBar/GraphiQLRouteButton.tsx
client/src/components/SearchBar/SearchBar.tsx
client/src/hooks/useTripQuery.ts
client/src/static/query/authorityQuery.tsx
client/src/static/query/lineQuery.tsx
client/src/static/query/quayQuery.tsx
client/src/static/query/tripQuery.tsx

This feature provides the following new functionality for the debug client:
A new button that when pressed will take the parameters set and create a GraphQL trip query that opens in GraphiQL.
Links in the leg lists will now take you to GraphQL queries in GraphiQL for the different entities.
This should resolve issue 1. and 2. listen under this: https://github.com/opentripplanner/OpenTripPlanner/issues/5330#issuecomment-2273311110 issue.

Add links for Debug UI to GraphiQL

---

src/main/java/org/opentripplanner/apis/transmodel/model/TripTimeOnDateHelper.java
src/main/java/org/opentripplanner/apis/transmodel/model/plan/JourneyWhiteListed.java
src/main/java/org/opentripplanner/apis/transmodel/model/plan/LegType.java
src/main/java/org/opentripplanner/apis/transmodel/model/siri/et/EstimatedCallType.java
src/main/java/org/opentripplanner/apis/transmodel/model/timetable/DatedServiceJourneyType.java
src/main/java/org/opentripplanner/apis/transmodel/model/timetable/ServiceJourneyType.java
src/main/java/org/opentripplanner/model/StopTimesInPattern.java
src/main/java/org/opentripplanner/routing/TripTimeOnDateHelper.java
src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java

The class initially named `TripTimeShort` was renamed to `TripTimeOnDate`, but the method names and class names that refer to it were not updated, which is confusing.
This PR replaces all references to `TripTimeShort` by `TripTimeOnDate`.
**Note**: there are 2 related classes `APITripTimeShort` and `ApiPatternShort` in the REST API that are left untouched.
No
No
No

Rename TripTimeShort to TripTimeOnDate in method and class names

---

src/main/java/org/opentripplanner/transit/model/timetable/Trip.java

The Javadoc is missing on the Trip class.
This PR attempts to clarify the definition of a Trip and show how Trip interacts with other entities in the model.
No
No
Added Javadoc

Add Javadoc for Trip

---

doc/user/Deployments.md

This add the Iceland (nationwide) travelplanner to the list of deployments. They are currently using OTP 1, but have plans to migrate to OTP 2. They have used OTP since 2015.
Not relevant.
Not relevant.
✅  Deployment doc updated
Not relevant
Not relevant

Add Iceland to the list of deployments [ci skip]

---

src/main/java/org/opentripplanner/framework/io/OtpHttpClient.java

When working with large downloads in build-config.json I noticed that starting up OTP was quite slow and using a lot of bandwidth before the graph build, and therefore download, even started.
I traced it down to a problematic method that was supposed to fetch HTTP headers but instead downloaded the entire file.
The Javadoc clearly states that a HEAD request should be executed but the in the acutal implementation this is not the case: https://github.com/opentripplanner/OpenTripPlanner/blob/dc4cdb81ea15c8d0195a6e2f8928a51ece461608/src/main/java/org/opentripplanner/framework/io/OtpHttpClient.java#L70-L73
I could write a test spinning up a HTTP server, but I don't think we want that.

Use correct HEAD request when fetching HTTP headers

---

src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java

During #5796 I made a mistake by interpreting the safe_duration_offset as a number of seconds. The spec clearly states though that it's a number of _minutes_.
https://github.com/MobilityData/gtfs-flex/pull/79
Updated.

Fix incorrect mapping of flex safe duration offset

---

client/src/components/ItineraryList/ItineraryHeaderContent.tsx
client/src/components/ItineraryList/LegTime.tsx
client/src/components/ItineraryList/useHeaderLegContentStyleCalculations.ts
client/src/components/MapView/LegLines.tsx
client/src/static/query/tripQuery.tsx
client/src/util/getColorForLeg.ts

This is a quality of life improvement for the debug UI:
- adds the full ISO date time to the `title` property, so it shows up on hover
- uses the line's colours when visualising legs and their geometries

Add full ISO times and colours to debug UI 

---

src/main/java/org/opentripplanner/apis/transmodel/model/timetable/DatedServiceJourneyQuery.java
src/main/java/org/opentripplanner/framework/collection/CollectionUtils.java
src/main/java/org/opentripplanner/framework/collection/ListUtils.java
src/main/java/org/opentripplanner/transit/api/request/TripOnServiceDateRequest.java
src/main/java/org/opentripplanner/transit/api/request/TripOnServiceDateRequestBuilder.java
src/main/java/org/opentripplanner/transit/model/filter/expr/AndMatcher.java
src/main/java/org/opentripplanner/transit/model/filter/expr/BinaryOperator.java
src/main/java/org/opentripplanner/transit/model/filter/expr/ContainsMatcher.java
src/main/java/org/opentripplanner/transit/model/filter/expr/EqualityMatcher.java
src/main/java/org/opentripplanner/transit/model/filter/expr/ExpressionBuilder.java
src/main/java/org/opentripplanner/transit/model/filter/expr/Matcher.java
src/main/java/org/opentripplanner/transit/model/filter/expr/OrMatcher.java
src/main/java/org/opentripplanner/transit/model/filter/transit/TripOnServiceDateMatcherFactory.java
src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
src/main/java/org/opentripplanner/transit/service/TransitService.java
src/test/java/org/opentripplanner/framework/collection/CollectionUtilsTest.java
src/test/java/org/opentripplanner/transit/model/filter/expr/AndMatcherTest.java
src/test/java/org/opentripplanner/transit/model/filter/expr/ContainsMatcherTest.java
src/test/java/org/opentripplanner/transit/model/filter/expr/EqualityMatcherTest.java
src/test/java/org/opentripplanner/transit/model/filter/expr/OrMatcherTest.java
src/test/java/org/opentripplanner/transit/model/filter/transit/TripOnServiceDateMatcherFactoryTest.java

Also make use of it in the DatedServiceJourneyQuery
This is the first simple implementation of a filter using the unified matcher API.
#5630
Added unit tests for each matcher and the new TripOnServiceDateMatcherFactory. Also ensured that the API in local runs behaves as expected.
Added JavaDoc.

Add a matcher API for filters in the transit service used for datedServiceJourneyQuery

---

src/ext-test/java/org/opentripplanner/ext/fares/FareRuleSetTest.java
src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceFactory.java
src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareFactory.java
src/ext/java/org/opentripplanner/ext/fares/model/FareRuleSet.java

ORCA agencies have occasionally left in fare attributes with no associated rules. OTP will match these against any leg, and if the fare is lower than the correct fare, it will take priority. There does not seem to be a well defined behavior for this edge case in the GTFS spec, but to avoid changing the behavior of OTP in general, I have added a one liner to remove these fare attributes lacking rules when using the ORCA fare module.
I'm not sure how to test this or if it's necessary, since this change happened in the ORCA fare factory which is untested.

fix(orca-fares): remove fare attributes with no rules

---

src/main/java/org/opentripplanner/apis/gtfs/datafetchers/LegImpl.java
src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StoptimeImpl.java
src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
src/main/java/org/opentripplanner/apis/gtfs/generated/graphql-codegen.yml
src/main/java/org/opentripplanner/apis/gtfs/mapping/RealtimeStateMapper.java

After #6045 was merged I realised that we should have a proper mapper for the realtime state since this forces you to correctly deal with all enum types.
Case in point, the current code would break with the real time state `DELETED`. I've mapped it to `CANCELLED`.
None.
None.

Add mapper for GTFS GraphQL real time state

---

DEVELOPMENT_DECISION_RECORDS.md
doc/user/Developers-Guide.md

Commit 27eb36ca5518866c71f1656bcf334f5c22a3f8a4 renamed `CODE_CONVENTIONS.md` to be `NamingConventions.md` and moved it to another location. This PR adjusts sources to changes.

doc: update `NamingConventions.md` reference [ci skip]

---

src/main/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapper.java
src/test/java/org/opentripplanner/openstreetmap/tagmapping/DefaultMapperTest.java

Copies over the rules from Norway mapper for disabling the elevation usage for the for the following tag value combinations to the default mapper as well:
cutting=*
location=underground
indoor=yes
Related to https://github.com/opentripplanner/OpenTripPlanner/issues/6092
Added some
Not needed
From title

Don't use elevation data directly for ways with cutting=*, location=underground or indoor=yes tags in the default mapper

---

doc/user/Container-Image.md

This PR adds Docker memory command line parameters to ensure that it does not error out due to lack of memory.

Add more memory for docker container [ci skip]

---

src/main/java/org/opentripplanner/street/model/edge/EscalatorEdge.java
src/test/java/org/opentripplanner/street/model/edge/EscalatorEdgeTest.java

When I debugged a problem inside a station, I noticed that escalators are not shown in the new debug UI. This is because they don't have a geometry.
For this reason, this PR adds one that is generated on the fly.

Add geometry for `EscalatorEdge`

---

src/main/java/org/opentripplanner/openstreetmap/model/OSMWithTags.java
src/main/java/org/opentripplanner/openstreetmap/wayproperty/NoteProperties.java
src/test/java/org/opentripplanner/openstreetmap/model/OSMWithTagsTest.java

Small cleanup. Pure refactoring.
- Add `@Nullable` to some nullable return values.
- `generateI18NForPattern()` will never be called with a null value in practice, so I removed the null check.
- `getTagsByPrefix()` didn't need to return null so I removed that case.
See #6048 
No tests for this.

Minor cleanup of some OSM classes

---

client/src/components/MapView/MapView.tsx
client/src/components/MapView/NavigationMarkers.tsx

Add map cursors to the debug client to indicate what is interactive:
- `pointer` when an item is clickable (part of an interactive layer)
- `grab` when an item may be dragged
- `grabbing` while dragging an item

debug client: update the map cursor when interactive

---

src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StopImpl.java
src/main/java/org/opentripplanner/model/TimetableSnapshot.java
src/main/java/org/opentripplanner/routing/stoptimes/StopTimesHelper.java
src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
src/main/java/org/opentripplanner/transit/service/TransitService.java
src/main/java/org/opentripplanner/updater/siri/SiriFuzzyTripMatcher.java
src/main/java/org/opentripplanner/updater/siri/SiriTimetableSnapshotSource.java
src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotManager.java
src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
src/test/java/org/opentripplanner/updater/trip/TimetableSnapshotSourceTest.java
src/test/java/org/opentripplanner/updater/trip/moduletests/delay/SkippedTest.java

Code clean-up and documentation/clarification in TimetableSnapshot:
- Clarify the name and purpose of the realTimeAdded* and realTimeModified*  indexes: realTimeAdded* indexes contains data related to added trips (extra journeys), while realTimeModified* indexes contains data related to modified trips (that is: pre-existing scheduled trips modified by a real-time update).
- Align getter names with the project naming convention.
- Minor code clean-up.
#6048
No
No

Timetable snapshot code cleanup

---

src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java

Currently, if only one of the `safe_duration_offset` or `safe_duration_factor` is set, OTP crashes.
This PR fixes that by providing default for the other one if only of them is set.
No.
Unit tests added.
No

Fix GTFS-Flex duration offset and factor parsing when only one of them is set

---

doc/dev/decisionrecords/Codestyle.md
doc/user/Developers-Guide.md

We have too strict rules for ordering things inside classes which are not always followed either by accident or because following them would cause nasty conflicts when things need to be moved inside classes. This pr updates the code style for ordering things inside classes to have less rules.
No issue
Not needed
Updated code style documentation.
No change log entry since this is meant for developers

Update code style for ordering things inside classes

---

src/main/java/org/opentripplanner/netex/NetexModule.java
src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
src/main/java/org/opentripplanner/transit/service/TransitModel.java
src/main/java/org/opentripplanner/transit/service/TransitModelIndex.java
src/test/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReferenceTest.java
src/test/java/org/opentripplanner/transit/service/TransitModelTest.java
src/test/java/org/opentripplanner/updater/trip/RealtimeTestEnvironmentBuilder.java

In this PR:
- Hide most of the maps in `TransitModelIndex`.
- Make collections returned by `TransitModelIndex` unmodifiable.
- Remove functionality from `TransitModelIndex` that already exists in `TransitModel`.
See #6048 
Some of the stuff in TransitModelIndex is untested. I didn't add any tests.
Didn't add any documentation.
I guess, since I'm changing the signature of the TransitModel?

Make TransitModelIndex more immutable

---

.github/workflows/cibuild.yml

It appears that python and pip have become stricter and don't allow you to install into system directories anymore. However, since we are using a throwaway VM it's fine to do this anyway.

Install mkdocs with --break-system-packages

---

application/src/main/java/org/opentripplanner/model/TimetableSnapshot.java
application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TransitLayerUpdater.java
application/src/test/java/org/opentripplanner/model/TimetableSnapshotTest.java

As detailed in #6135, a memory leak has been identified in the `TransitLayer`.
This bug was introduced in #6017.
The set of dirty timetables in `TimetableSnapshot` (that is: the set of timetables currently being modified and to be added to the next snapshot) should contain only one modified timetable per trip pattern and per service date.
Prior to #6017, if a timetable was modified several times when building the next snapshot, the same `Timetable` instance would be reused and updated, thus guaranteeing uniqueness.
In #6017, `Timetable` is immutable and the previous Timetable instance cannot be modified : it must be swapped with a new `Timetable` instance that integrates the latest changes.
However the code fails to remove the previously modified timetable before adding the new one and …

Fix duplicated dirty timetables

---

application/src/main/java/org/opentripplanner/apis/transmodel/mapping/TripViaLocationMapper.java
application/src/main/java/org/opentripplanner/apis/transmodel/model/plan/ViaLocationInputType.java
application/src/main/java/org/opentripplanner/routing/api/request/via/PassThroughViaLocation.java
application/src/main/java/org/opentripplanner/routing/api/request/via/VisitViaLocation.java
application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
application/src/test/java/org/opentripplanner/apis/transmodel/mapping/TripViaLocationMapperTest.java

The list of ids inside passThroughPoints is allowed to be empty or null. We cannot change this - that would be a breaking change. So, when the via search enforced this, the API was not backward compatible anymore. This commit reverts the behavior and just ignores the passThroughPoints if the list of ids is null or empty. This bug was
introduced in PR #6084.
This PR also changes the graphql schema for via search - the assumtion is that no one has put it in production jet. The list of stop ids are med required. This was initially optional, because we want to add coordinates. But, it should be relaxed when the coordinates are added, not now. At least one id or coordinate must be set anyway!
🟥  There is not OTP issue for this.
✅  Regression unit tests are added to via and passthrough in the …

Fix regression error in passThroughPoints in the Transmodel API

---

application/src/ext/java/org/opentripplanner/ext/fares/impl/CombinedInterlinedTransitLeg.java
application/src/ext/java/org/opentripplanner/ext/flex/FlexibleTransitLeg.java
application/src/main/java/org/opentripplanner/model/plan/Leg.java
application/src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
application/src/main/java/org/opentripplanner/model/plan/UnknownTransitPathLeg.java
application/src/main/java/org/opentripplanner/netex/mapping/ServiceLinkMapper.java
application/src/main/java/org/opentripplanner/transit/model/network/Route.java
application/src/main/java/org/opentripplanner/transit/model/timetable/Trip.java
application/src/test/java/org/opentripplanner/GtfsTest.java

Add `@Nullable` annotiation to stuff that can be null in `Trip` and `Leg`. Also reorder the fields in Trip to be more in order of importance.
#6048 
No tests
The fields in `Trip` are reordered, but this should not change serialization.

Add @Nullable annotations to Trip and Leg

---

application/src/main/java/org/opentripplanner/framework/application/OTPRequestTimeoutException.java
application/src/main/java/org/opentripplanner/raptor/api/request/RaptorEnvironment.java
application/src/main/java/org/opentripplanner/raptor/api/request/RaptorTuningParameters.java
application/src/main/java/org/opentripplanner/raptor/api/view/ArrivalView.java
application/src/main/java/org/opentripplanner/raptor/configure/RaptorConfig.java
application/src/main/java/org/opentripplanner/raptor/rangeraptor/RangeRaptor.java
application/src/main/java/org/opentripplanner/raptor/rangeraptor/support/TimeBasedBoardingSupport.java
application/src/main/java/org/opentripplanner/raptor/service/RangeRaptorDynamicSearch.java
application/src/main/java/org/opentripplanner/raptor/service/ViaRangeRaptorDynamicSearch.java
application/src/main/java/org/opentripplanner/raptor/spi/BoardAndAlightTime.java
application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripScheduleBoardSearch.java
application/src/main/java/org/opentripplanner/standalone/config/configure/ConfigModule.java
application/src/main/java/org/opentripplanner/standalone/config/routerconfig/RaptorEnvironmentFactory.java
application/src/main/java/org/opentripplanner/standalone/config/routerconfig/TransitRoutingConfig.java
application/src/test/java/org/opentripplanner/TestServerContext.java
application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java

A few small cleanup tasks to Raptor to prepare for making it a separate Maven module.
Part of: #6155 
This only contains simple refactorings, no tests added or changed.
No
No
Not needed

Remove unwanted dependencies in Raptor code

---

application/src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
application/src/test/java/org/opentripplanner/street/integration/BikeWalkingTest.java

Allows bike walking through bicycle no thru traffic areas.
Fixes #6178
Added 3 tests to verify bicycle traverse through bicycle no through edges (the restricted edge is in the start - middle - end).

Allow bike walking through bicycle no thru traffic areas

---

application/src/main/java/org/opentripplanner/model/plan/Itinerary.java
application/src/test/java/org/opentripplanner/routing/algorithm/filterchain/ItineraryListFilterChainTest.java

Make the test itinerary instance non-static as it's modified in some tests.
Specifically, an itinerary can be flagged for deletion in one test, which affects the assertions in the next test.
Without this, tests may fail if they are executed in a certain order. This may be because LC_COLLATE is not set in the environment.
Searching for this idiom in the tree:
```
private static final Itinerary INSTANCE = newItinerary( ... );
```
...reveals other usages, although that presently they do not cause build problems. But in the worst case, it could be that a test passes because a previously executed test provides the wanted state.
`Itinerary.isFlaggedForDeletion()` calls `getSystemNotices()` which in turn makes a copy of the `systemNotices` collection. This seems wasteful and just generates GC …

Fix race in execution of tests

---

application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/TripMetadataType.java
application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql

The GraphQL tooltip incorrectly states that the searchWindowUsed is in seconds, when it's actually minutes. This change fixes that.

Change GraphQL tooltip for searchWindowUsed to say minutes, instead of seconds

---

application/src/main/java/org/opentripplanner/gtfs/mapping/TransitModeMapper.java
application/src/test/java/org/opentripplanner/gtfs/mapping/TransitModeMapperTest.java

Fix GTFS extended route types for trolleybus (8xx).
This replaces #6086 for trolleybuses only, and add tests for existing modes (except 200-299).
None yet
added for more existing modes
None

Interpret GTFS extended route types 801-899 also as trolleybus service

---

application/src/main/java/org/opentripplanner/framework/io/OtpHttpClient.java
application/src/main/java/org/opentripplanner/framework/io/OtpHttpClientFactory.java

This avoids problems where a connection could be blocked by an intermediate proxy that disallows protocol upgrades. 
In OTP PR #6079 the Apache HTTP client was upgraded 5.4. They in turn enabled protocol upgrades by default in [HTTPCLIENT-751](https://issues.apache.org/jira/browse/HTTPCLIENT-751). This means that the client/server will try upgrading a plain HTTP connection to a TLS one (among other upgrades).
Unfortunately this causes problems in our deployment as we run an Envoy proxy server on top of our instances (specifically our SIRI updaters can't connect to the history service). Envoy currently doesn't support protocol upgrades by default and will answer the request with 403.
For the curious, Envoy have issues open on the subject: Envoy …

Disable protocol upgrades for the HTTP client by default.

---

application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelAPI.java
application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchema.java
application/src/main/java/org/opentripplanner/apis/transmodel/model/plan/TripQuery.java
application/src/main/java/org/opentripplanner/raptor/api/request/DynamicSearchWindowCoefficients.java
application/src/main/java/org/opentripplanner/routing/algorithm/mapping/PagingServiceFactory.java
application/src/main/java/org/opentripplanner/routing/api/request/RouteRequest.java
application/src/main/java/org/opentripplanner/standalone/config/RouterConfig.java
application/src/main/java/org/opentripplanner/standalone/config/routerconfig/TransitRoutingConfig.java
application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplication.java
application/src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
application/src/test/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchemaTest.java
application/src/test/java/org/opentripplanner/routing/core/RouteRequestTest.java
doc/user/RouterConfiguration.md

The PagingService was initialized with the dynamic max-search-window value, and not the request max search-window. This commit also updates the Transmodel API doc.
This was reported at Entur yesterday. It is a minor fix, so I have not created an issue for it.
This was an error in the wiring of the application - creating a good test for this is expensive and give little value.
✅  The Transmodel API doc is updated.
✅  JavaDoc and code comments is updated/added
🟥   The GTFS API is not updated - someone who knows the API should do this
✅
Not needed.

Fix max search-window when paging

---

application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/frequency/TripFrequencyAlightSearch.java
application/src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/request/TripPatternForDatesTest.java

This fixes a problem when search backwards with a frequency-based trip.
Fixes #6102 
Added
None needed. Pure bug fix only.

Fix NullPointerException when searching backwards with a frequency-based trip

---

client/codegen.ts
client/package-lock.json
client/package.json
renovate.json5

According to https://github.com/dotansimha/graphql-code-generator/issues/10167#issuecomment-2441459241 you can get the generated types back by changing the config and bumping the version.
Fixes #6169

Fix @graphql/client-preset

---

doc/dev/decisionrecords/Codestyle.md
doc/dev/decisionrecords/NamingConventions.md
doc/dev/decisionrecords/RecordsPOJOsBuilders.md
doc/dev/decisionrecords/UseDecisionRecords.md
doc/dev/decisionrecords/_TEMPLATE.md
doc/dev/onboarding-checklist.md

Cleans up miscellaneous typos, grammatical errors, style inconsistencies, etc. in documentation. This will improve readability for those accessing and referencing the docs, especially for new contributors.
There doesn't appear to be a formatter-enforced line length, so this PR uses 80 characters as that seems to be the loose consensus across other Markdown files in this directory. For stylistic choices like list indents or Oxford commas, this PR makes no decision and preserves existing usage. In general, this PR always favors consistency with existing choices over any standardization of style.
For now, I've touched only the `doc/dev` Markdown files. I can clean up the Markdown files for other docs as well in the future.

Clean up `doc/dev` documentation files

---

.github/workflows/cibuild.yml
pom.xml

Whenever I need to look at a CI log, I have to scroll past a very long list of URLs that Maven has downloaded and I never had any use from these at all.
For this reason I'm proposing to completely hide these URLs from the CI log.
On top of this, the PR also enables colour output for the CI logs and adds some Unicode characters.
It looks like this:
I also removed the hardcoded path to the coverage file and I hope that this will automatically lead to sub-module's coverage data being discovered.
Codecov has a new feature where they allow you to upload test data, which I want to try out. It's doesn't work out of the box with JUnit yet, but I'm working on it: https://github.com/codecov/feedback/issues/304#issuecomment-2454739120

Hide transfer URLs from Maven CI logs, upload test data to codecov

---

application/src/main/java/org/opentripplanner/apis/transmodel/model/framework/InfoLinkType.java
application/src/main/java/org/opentripplanner/apis/transmodel/model/siri/sx/PtSituationElementType.java
application/src/main/java/org/opentripplanner/framework/i18n/I18NString.java
application/src/main/java/org/opentripplanner/routing/alertpatch/AlertUrl.java
application/src/main/java/org/opentripplanner/updater/siri/SiriAlertsUpdateHandler.java
application/src/test/java/org/opentripplanner/framework/i18n/I18NStringTest.java
application/src/test/java/org/opentripplanner/updater/siri/SiriAlertsUpdateHandlerTest.java

In the Transmodel API the `/stopPlace/quays[]/situations[]/infoLinks` is none-null, but the current code returns `null`if no infoLinks exist. This PR return an empty list instead. 
There is no issue for this. This bug was reported by T. Sverdvik, Ruter yesterday in \\#shared-entur-ruter-utvikling at Entur.
No test is added.
Not changed.
Probably to small of a fix to be notable.
Not needed.

Return empty list if there is no siriUrls in situations/infoLinks

---

application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/AlertImpl.java
application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLTypes.java
application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/alerts.json
application/src/test/resources/org/opentripplanner/apis/gtfs/queries/alerts.graphql

This deprecates old alert translations fields from GTFS API and add language param to normal fields.
Minor GraphQL API update, no issue
Updated tests
Not needed
From title

Deprecate old alert translations in the GTFS API and add language param to a few alert fields

---

application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/DatedServiceJourneyType.java
application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/ServiceJourneyType.java

This PR fixes a bug on the quay filter on the serviceJourney GraphQL type: https://github.com/opentripplanner/OpenTripPlanner/blob/46be411361388514c21453e0d6162528d4df8834/application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/ServiceJourneyType.java#L181-L232
The filter was not applied because the comparisons of first and last to the length of the list are reversed. This change flips the comparisons so that they are applied. Also removes some code that was commented out for some reason.
To reproduce the current bug with Entur's data, go to:
https://api.entur.io/graphql-explorer/journey-planner-v3?query=%7BserviceJourney%28id%3A%22KOL%3AServiceJourney%3A1006_240513063897572_2110%22%29%7Bid%20quays%28first%3A1%29%7Bname%7D%7D%7D&variables=
No unit tests changed but I …

Fix stop index filtering on ServiceJourney Transmodel GraphQL API

---

application/src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
application/src/test/java/org/opentripplanner/street/model/edge/StreetEdgeGeofencingTest.java

Fixes #6054 
It turns out that the egress search ended up on a rental bike at all possible stops so StreetNearbyStopFinder.findNearbyStops didn't find anything. Based on my reading and debug runs, it is caused by the branch in StreetEdge.splitStatesAfterHavingExitedNoDropOffZoneWhenReverseSearching not having a walk state as one of the option.
I further think, but did not include in this PR, that the networks generated here should be filtered by what networks are allowed in the request. Now it generates everything allowed by the vertex, ignoring the request. This is not a correctness issue but affects performance.
Closes #6054 
Also closes #6244
I added a short test which failed before but succeeds now.
Maybe there should be a larger scope test which replicates the situation as …

Fix rental searches when destination is in a no-drop-off zone

---

application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapper.java
application/src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/RaptorRequestMapperTest.java

Currently `transitGroupPriority` is turned off for non-via requests, due to `hasPassThroughOnly()` being `true` for a request without any via locations:
```
request.getViaLocations().stream().allMatch(ViaLocation::isPassThroughLocation)
```
This updates `hasPassThroughOnly()` and `hasViaLocationsOnly()` to also check that the request is actually a `isViaSearch()`.
New tests are added to verify that `transitPriorityCalculator()` is set for non-via and visit-via searches.

Set transit-group-priority for requests without via points

---

client/src/components/MapView/LayerControl.tsx

#6146 introduced a regression: on initial load of the debug client, stop layers (regular, area, group) are not clickable.
Luckily this is easily fixed.

Make stop layers clickable again in debug client

---

application/src/ext-test/java/org/opentripplanner/ext/flex/FlexStopTimesForTest.java
application/src/ext-test/java/org/opentripplanner/ext/flex/flexpathcalculator/ScheduledFlexPathCalculatorTest.java
application/src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripIntegrationTest.java
application/src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripTest.java
application/src/ext-test/java/org/opentripplanner/ext/flex/trip/UnscheduledTripTest.java
application/src/ext/java/org/opentripplanner/ext/flex/FlexTripsMapper.java
application/src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
application/src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
application/src/main/java/org/opentripplanner/model/StopTime.java
client/src/components/ItineraryList/ItineraryLegDetails.tsx

This brings OTP in line with the GTFS spec by allowing flex and continuous stopping in the same trip as long as it's not mixed in the very same stop time.
There is also a small improvement to the debug UI where routes without a publicCode/shortName use the long name as the fallback.
Closes #6230
The majority of the code is test refactoring. Lots of tests for this behavior added.
n/a
I'm changing static method on a file that is being serialised so I'm bumping just in case.

Relax rejection of GTFS flex trips that also contain continuous stopping

---

application/src/main/java/org/opentripplanner/gtfs/mapping/BikeAccessMapper.java
application/src/test/java/org/opentripplanner/gtfs/mapping/BikeAccessMapperTest.java
application/src/test/resources/gtfs/simple/routes.txt
application/src/test/resources/gtfs/simple/trips.txt

This removes the parsing of legacy `bikes_allowed` information. The fields `trip_bikes_allowed` and `route_bikes_allowed` were discussed early in the GTFS spec process but have never made it into the specification.
It has been deprecated in onebusaway-gtfs for many years and removed in the latest version.
None.
Existing ones updated.

Remove legacy bike access mapping

---

application/src/main/java/org/opentripplanner/graph_builder/module/osm/SafetyValueNormalizer.java
application/src/main/java/org/opentripplanner/osm/tagmapping/FinlandMapper.java
application/src/main/java/org/opentripplanner/osm/tagmapping/OsmTagMapper.java
application/src/test/java/org/opentripplanner/osm/tagmapping/ConstantSpeedMapperTest.java
application/src/test/java/org/opentripplanner/osm/tagmapping/FinlandMapperTest.java
application/src/test/java/org/opentripplanner/osm/tagmapping/OsmTagMapperTest.java

According to OSM guide lines, ways tagged as service=parking_aisle,driveway,alley,emergency_access,drive-through are not intended for pass through traffic. It seems that at least in Finland, such ways often lack explicit access restriction tagging (e.g. access=private).
This PR extends the pass through traffic restrictions of Finland tag mapping for car routing to include such service ways. We may consider if the same logic should be applied in the default tag mapper class. 
Two pass through methods are now renamed. Double negation in the names made those hard to understand.
A test for a service way added.
Self-documenting code.

Apply stricter motor vehicle nothrough traffic rules in Finland

---

client/src/components/MapView/LegLines.tsx
client/src/util/getColorForLeg.ts

@t2gran has complained that the fallback colours for transit legs in the debug UI can be hard to see. For this reason I added an outline to those lines.

Improve visibility of map lines in debug UI

---

application/src/ext/java/org/opentripplanner/ext/flex/template/AbstractFlexTemplate.java
application/src/ext/java/org/opentripplanner/ext/flex/template/FlexDirectPathFactory.java
application/src/main/java/org/opentripplanner/routing/algorithm/mapping/RaptorPathToItineraryMapper.java
application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/Transfer.java
application/src/main/java/org/opentripplanner/street/search/request/StreetSearchRequest.java
application/src/main/java/org/opentripplanner/street/search/state/EdgeTraverser.java
application/src/test/java/org/opentripplanner/_support/geometry/Coordinates.java
application/src/test/java/org/opentripplanner/routing/algorithm/mapping/CarPickupSnapshotTest.java
application/src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/CarPickupSnapshotTest.snap
application/src/test/java/org/opentripplanner/street/search/state/EdgeTraverserTest.java
application/src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java

(This builds on #6237)
In `EdgeTraverser` when traversing edge lists multiple states could be returned which was not handled correctly.
This updates `EdgeTraverser˙ and its uses to allow multiple states.
Closes #6210
Unit tests are added for `EdgeTraverser`. To test the updated transfer and leg traversal a `CAR_PICKUP` snapshot test is added and then updated.

Allow multiple states during transfer edge traversals

---

application/src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
application/src/test/java/org/opentripplanner/street/model/edge/StreetEdgeGeofencingTest.java

Do not speculate use of rental networks which are not allowed by the request. They just cause extra states,
which in the end will not reach targets anyway.
The speculative fanout of extra rental network states can be massive in pathological cases, and serious
in accidental difficult cases.
The existing test StreetEdgeGeofencingTest did not find as many new states as it used to, and this
shows exactly what the fix is about. The expectation of the result was changed accordingly.
I can get better code coverage if this is not rejected outright.
No documentation change, no high-level visible behavior state except execution speed.
Could consider skip changelog.
No.

Improve performance of speculative rental vehicle use in reverse search

---

application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
application/src/main/java/org/opentripplanner/transit/service/TimetableRepository.java
application/src/main/java/org/opentripplanner/transit/service/TimetableRepositoryIndex.java
application/src/main/java/org/opentripplanner/transit/service/TransitService.java
application/src/main/java/org/opentripplanner/updater/GtfsRealtimeFuzzyTripMatcher.java
application/src/main/java/org/opentripplanner/updater/trip/TimetableSnapshotSource.java
application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
application/src/test/java/org/opentripplanner/model/TripTimeOnDateTest.java
application/src/test/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReferenceTest.java
application/src/test/java/org/opentripplanner/routing/algorithm/raptoradapter/transit/mappers/TripPatternForDateMapperTest.java
application/src/test/java/org/opentripplanner/transit/model/_data/TimetableRepositoryForTest.java
application/src/test/java/org/opentripplanner/transit/service/DefaultTransitServiceTest.java
application/src/test/java/org/opentripplanner/updater/GtfsRealtimeFuzzyTripMatcherTest.java
application/src/test/java/org/opentripplanner/updater/vehicle_position/RealtimeVehicleMatcherTest.java

It allows the fuzzy trip matching of GTFS-RT trips even when they have a trip id as these often don't match the timetable data.
#6226
The test was rewritten which was the main task here. It used to build a full graph with OSM and GTFS and this was replaced with a much faster setup. Execution time drops from 13s to 30ms.

Allow GTFS fuzzy trip matching even when trip descriptor has an id

---

application/src/main/java/org/opentripplanner/model/projectinfo/OtpProjectInfo.java
application/src/main/java/org/opentripplanner/standalone/OTPMain.java
application/src/main/java/org/opentripplanner/standalone/OtpStartupInfo.java
application/src/main/java/org/opentripplanner/standalone/config/CommandLineParameters.java
application/src/test/java/org/opentripplanner/standalone/config/CommandLineParametersTest.java
application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java

This small PR add the main operations OTP is instructed to do from the command line to the startup and shutdown log events. The new log event lok like this:
```
14:21:36.700 INFO [main]  (OtpStartupInfo.java:40) OTP STARTING UP - Build Street Graph - version: 2.7.0-SNAPSHOT ...
14:29:19.308 INFO [main]  (OtpStartupInfo.java:40) OTP STARTING UP - Build Transit Graph - version: 2.7.0-SNAPSHOT ...
14:33:49.023 INFO [main]  (OtpStartupInfo.java:40) OTP STARTING UP - Build Street & Transit Graph - version: 2.7.0-SNAPSHOT ...
14:34:28.785 INFO [main]  (OtpStartupInfo.java:40) OTP STARTING UP - Run Planner - version: 2.7.0-SNAPSHOT ...
14:35:17.095 INFO [main]  (OtpStartupInfo.java:40) OTP STARTING UP - Build Street & Transit Graph, Run Planner - version: 2.7.0-SNAPSHOT ...
```
```
14:29:19.416 …
```

Add main operation to startup/shutdown logging

---

application/src/ext/java/org/opentripplanner/ext/restapi/mapping/BookingInfoMapper.java
application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/BookingInfoImpl.java
application/src/main/java/org/opentripplanner/transit/model/timetable/booking/BookingInfo.java
application/src/main/java/org/opentripplanner/transit/model/timetable/booking/RoutingBookingInfo.java
application/src/test/java/org/opentripplanner/apis/gtfs/datafetchers/BookingInfoImplTest.java
application/src/test/java/org/opentripplanner/netex/mapping/BookingInfoMapperTest.java
application/src/test/java/org/opentripplanner/transit/model/timetable/booking/BookingInfoTest.java

It fixes a NPE in `BookingInfoImpl` when `minimumBookingNotice` is null.
Closes #6273
Added. The reason that I didn't add a new file to `GraphQLIntegrationTest` is that only flex legs can currently have a booking info, which would require me to add a flex leg and update all assertion files.

Avoid NullPointerException in GTFS GraphQL API

---

application/src/main/java/org/opentripplanner/osm/tagmapping/FinlandMapper.java
application/src/main/java/org/opentripplanner/osm/tagmapping/OsmTagMapper.java
application/src/test/java/org/opentripplanner/osm/tagmapping/FinlandMapperTest.java
application/src/test/java/org/opentripplanner/osm/tagmapping/OsmTagMapperTest.java
doc/user/osm/Finland.md
doc/user/osm/Germany.md
doc/user/osm/OsmTag.md
doc/user/osm/UK.md

Make OSM ways tagged with `motorroad=yes` car-only.
Closes #6287 
Added.
Autogenerated.

Make `motorroad=yes` car-only

---

application/pom.xml
pom.xml
raptor/pom.xml
shaded-jar/pom.xml
utils/pom.xml

Creating the `otp-2.7.0-SNAPSHOT-shaded.jar` takes a bit of time (12.5s) on my machine. Most developers never uses this, at least during regular development. So, I think this should go into a separate maven module and I will enable developers to skip it using `-DskipShadeJar`.
No issue exist.
🟥  This is changing the build configuration only.
✅  I added some comments to the Maven `pom.xml` files to explain "non standard" config.
🟥  Skip
🟥  Not needed.

Split the shaded jar out of application

---

application/src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
application/src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java

There has been a bit of unfortunate back-and-forth when writing the spec draft for the GTFS flex duration extension. We agreed that we want to switch the field `safe_duration_offset` to mean seconds as other duration in the spec also us this unit.
https://github.com/MobilityData/gtfs-flex/pull/79
Updated.
No.

Switch GTFS flex `safe_duration_offset` back to seconds

---

.github/workflows/performance-test.yml
README.md
doc/user/Getting-OTP.md

Fix the broken performance test and a few references to the shaded jar in in doc.
🟥  No issue for this.
🟥  Not relevant.
✅  Updated.
🟥  Not relevant.
🟥  Not relevant.

Fix references to the shaded jar for performance tests and in doc

---

application/src/ext/java/org/opentripplanner/ext/geocoder/StopClusterMapper.java

This is a sandbox-only PR for the geocoder cluster feature: it reduces the radius for which clusters are formed.
No.
No.

Reduce geocode cluster radius

---

application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelAPI.java

This PR add a read-only endpoint (HTTP GET) for fetching the Transmodel GraphQL Schema. The schema can be fetched today using the GraphQL introspection, but this is a bit technical and the result need to be translated into SDL (if needed). 
We will use this to generate the input controls for the trip search in the OTP Debug UI. It can also be used for "human introspection".
🟥  No issue, but this is part of making a generic input control for the Debug UI.
🟥  This is just one line of code with logic - only using library code. The schema is for
✅  The usage is documented with a comment included at the top of the schema file.
🟥  The endpoint is not documented outside the code - this should be sufficient since it is not intended
for production/integration - only for the convenience of …

Add endpoint to download Transmodel GraphQL Schema

---

application/src/main/java/org/opentripplanner/standalone/config/framework/file/IncludeFileDirective.java
application/src/test/java/org/opentripplanner/standalone/config/framework/file/IncludeFileDirectiveTest.java
doc/templates/Configuration.md
doc/user/Configuration.md

This detects `[]` in addition to `{}` when including JSON in config files.
Fixes #6305
Added for JSON array in addition for JSON object
Updated
Not needed

Detect JSON array in addition to JSON objects when including a file in the config.

---

application/src/main/java/org/opentripplanner/street/model/edge/Edge.java
application/src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
application/src/test/java/org/opentripplanner/graph_builder/module/osm/naming/SidewalkNamerTest.java
application/src/test/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapperTest.java
application/src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java

The method `StreetEdge#setName` is called during post-processing and updates the edge's name. This happens only during the "custom naming" phase where new names are assigned to those which where previous marked as having a "bogus name".
A bogus name means that its name is derived from its attributes, so it's "tunnel" or "path".
For this reason I'm changing the code so that the bogus name property is set to false when the name is set.
The final goal is for the mapping from edges to steps to introduce a new step when it encounters such a renamed edge. Currently, this doesn't happen when two edges with "bogus names" are encountered consecutively.
Added.
Javadoc around the concept of a bogus name updated.
cc @hbruch @stadtnavimanager

Improve "bogus name" handling when setting StreetEdge's name during postprocessing

---

application/src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java
client/src/util/generateTextColor.ts
utils/src/main/java/org/opentripplanner/utils/color/Brightness.java
utils/src/main/java/org/opentripplanner/utils/color/ColorUtils.java
utils/src/test/java/org/opentripplanner/utils/color/ColorUtilsTest.java

This is a rework of #5490 . It uses the WCAG recommendation to decide if the text color should be black (on a light background) or white (on a dark background).
The color calculation is refactored out into a separate util module such that it is testable, and is changed to use the official sRGB color space formula.
The luminance threshold is 0.179 according to the WCAG formula (where the previous code used 0.5). It has an effect of considering red (255, 0, 0) a light color that black text (instead of white) should be placed on red background, as black has a greater contrast with red than white per accessibility guidelines. This will need some discussion. 
None
Added for color calculation.
Javadoc

Use WCAG recommendation to fill in GTFS route text color if it is missing

---

.github/workflows/performance-test.yml
README.md
doc/user/Basic-Tutorial.md
doc/user/Developers-Guide.md
doc/user/Getting-OTP.md
otp-shaded/pom.xml
pom.xml
script/otp
script/run-and-test-otp
shaded-jar/pom.xml

Add back the shaded jar as an Maven artifact. 
> **NOTE!** The new name is `otp-shaded-<version>.jar` (not `otp-<version>-shaded.jar`)
This will keep adding the "one-jar" as an artifact to Maven Central for the next release. The doc
is updated. I updated to the next version number where apropriate, since the path in Maven Central
will change. Therefore, the new path does not exist yet - it will exist when the next release (**2.7.0**) is made.
This is related to #6267
🟥  Not relevant.
✅  All scripts and documentation referencing the shaded jar is updated.
✅  This is relevant for everyone maintaining OTP deployments - so to "spreed the news" we will to include this 
in the chagelog - even if it is not relevant to product owners.
🟥  Not needed.

Add shaded jar artifact

---

application/src/main/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferences.java
application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
application/src/test/java/org/opentripplanner/routing/api/request/preference/StreetPreferencesTest.java
doc/user/RouteRequest.md

The CAR & CAR_PICKUP can be used in access/egress, but no default time-penalty was set.
**We need to clearify if tipe-penalty should apply to CAR!** 
🟥  There is not issue for this. This is just a something we forgot to do. All CAR modes that can be used as access/egress should have a time-penalty, maybe except CAR. 
✅  Unit tests are updated.
✅  Unit tests are updated.
✅  The bug exist in 2.6
🟥  Not needed

Add default penalty to all car API modes

---

client/src/components/ItineraryList/ItineraryDetails.tsx
client/src/components/ItineraryList/ItineraryLegDetails.tsx
client/src/static/query/tripQuery.tsx
client/src/style.css
client/src/util/formatDuration.ts

This adds the generalized cost for legs and itineraries to the debug UI. It looks like this:
In order to make some room, I formatted the leg duration a bit more compactly.

Show generalized cost in debug UI

---

application/src/main/java/org/opentripplanner/graph_builder/module/StreetLinkerModule.java
application/src/main/java/org/opentripplanner/street/model/vertex/TransitStopVertex.java
application/src/test/java/org/opentripplanner/graph_builder/module/StreetLinkerModuleTest.java

It links flex stops also to the drivable street network even when they are already linked to an OSM boarding location.
Closes #6299
Added.
Javadoc.

Make flex linking work together with boarding locations

---

application/src/test/java/org/opentripplanner/test/support/ResourceLoader.java

This pull request fixes test failures when building OpenTripPlanner in a folder containing URL-encodable characters (such as space, Chinese characters, etc.).
Please refer to https://stackoverflow.com/a/13470643 for details.
fixes #6337
Updated
None
Not needed
Not needed

Fix test failure when building OTP in a path with special characters

---

application/src/main/java/org/opentripplanner/osm/tagmapping/OsmTagMapper.java
application/src/main/resources/WayProperties.properties
application/src/main/resources/WayProperties_de.properties
application/src/main/resources/WayProperties_fi.properties
application/src/main/resources/WayProperties_fr.properties
application/src/main/resources/WayProperties_hu.properties
application/src/main/resources/WayProperties_nl.properties
application/src/main/resources/WayProperties_no.properties
application/src/main/resources/WayProperties_sv.properties
application/src/test/java/org/opentripplanner/osm/tagmapping/OsmTagMapperTest.java

Many types of OSM ways have a fallback name like "path", "stairs" or "tunnel" but those tagged with `highway=corridor` do not. This PR adds it.
Added.

Add fallback name for corridors

---

application/pom.xml
application/src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java

This updates the GTFS entities that are part of Fares V2. These are skipped unless you enable the `FaresV2` feature flag, because FaresV2 is still new and feeds frequently provide invalid data. Updating this list means that OTP will be ignoring more invalid FaresV2 data.
This PR also updates the OBA library to the latest version because previous ones had duplicate types for `StopArea` and `Area`, which are really the same thing.

Update list of GTFS Fares v2 classes

---

application/src/main/java/org/opentripplanner/model/plan/ScheduledTransitLeg.java
application/src/main/java/org/opentripplanner/model/plan/ScheduledTransitLegBuilder.java
application/src/test/java/org/opentripplanner/model/plan/ScheduledTransitLegBuilderTest.java

This fixes a bug where transit alerts where not copied when using the leg to get a new builder.
This PR only fixes the bug but I will work on making the `ScheduledTransitLeg` completely immutable so this doesn't happen again (we have the same problem with the fares).
Added.

When using ScheduledTransitLeg's copy builder, also copy alerts

---

application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchema.java
application/src/main/java/org/opentripplanner/apis/transmodel/support/GqlUtil.java

This ignores null members in lists of arguments. Today this fails with NullPointerExceptions deeper in the stack, which is difficult for users to interpret.
Tested with local runs.
Current error message:
`Exception while fetching data (/serviceJourneys) : Cannot invoke \"Object.equals(Object)\" because \"this.value\" is null`
New behavior is to just ignore the null in an argument set to: [null].
To recreate current error: https://api.entur.io/graphql-explorer/journey-planner-v3?query=query%20GetDepartureStops%28%24authorities%3A%5BString%5D%24privateCodes%3A%5BString%5D%24dateYesterday%3ADate%24date%3ADate%29%7BserviceJourneys%28authorities%3A%24authorities%20privateCodes%3A%24privateCodes%20activeDates%3A%5B%24dateYesterday%24date%5D%29%7Bid%20stopsYesterday%3AestimatedCalls%28date%3A%24d …

Improve handling of null values in argument lists to the serviceJourneys graphQL method in the Transmodel API

---

application/src/client/graphiql/index.html

One of my deployments is using rate limiting and API keys so I would like to be able to set headers in GraphiQL, which this PR adds.
While I was there I also upgraded GraphiQL to the latest version.
cc @fahrplaner

Add HTTP headers to GraphiQL, upgrade version

---

application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
application/src/main/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferences.java
application/src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
application/src/test/resources/standalone/config/router-config.json
doc/user/RouteRequest.md
doc/user/RouterConfiguration.md

This PR adds a mode-specific version of the `maxStopCount` parameter (`maxStopCountForMode`) to the router config. This can be useful for setting higher limits for modes that can travel larger distances such as cars. Setting the parameter to a higher value has the downside of requiring more computation.
This is a follow-up PR related to issue https://github.com/opentripplanner/OpenTripPlanner/issues/5875
No unit tests created, manual testing has been performed
Changes to `RouteRequest.md`

Add 'maxStopCountForMode' to the router config

---

application/src/main/java/org/opentripplanner/apis/transmodel/mapping/BookingInfoMapper.java
application/src/main/java/org/opentripplanner/apis/transmodel/mapping/RelativeDirectionMapper.java
application/src/main/java/org/opentripplanner/apis/transmodel/model/EnumTypes.java
application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/BookingArrangementType.java
application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
application/src/test/java/org/opentripplanner/apis/transmodel/mapping/BookingInfoMapperTest.java
application/src/test/java/org/opentripplanner/apis/transmodel/model/EnumTypesTest.java

@t2gran had to fix a bug I introduced in #6385 which I feel a bit bad about. In order for this to not repeat itself I extracted a mapper for the field in question and added lots and lots of tests.
The line coverage in the mapper is 100% and the branch coverage 93%.
In #6343 we introduced a new internal enum value for RelativeDirection. We don't want to expose the type ever in the API so I introduced mapper to get rid of it. In that process I noticed that there are unmapped enum values in the Transmodel API, which I also mapped away.
@t2gran has requested that instead we add the enum values to the API which I did.
There was already a test for the enum serialisation which also tests the new values.
Relates to #6384 
Added.
Javadoc.

Extract mapper for Transmodel `bookWhen`, new values for `relativeDirection`

---

.github/workflows/schema-validation.yml

Adds CI workflow that uses [schema inspector](https://the-guild.dev/graphql/inspector) to validate that there are no breaking schema changes and to list changes. 
This was shortly discussed in a dev meeting this week
No
No
Skipped

Add ci workflow for validating schema changes

---

.github/workflows/debug-client.yml

This action is run today in entur downstream fork when someone changes a file under `/client/**`. The action is aborted, but it clutter up the list of run actions. I am not an expert on workflows, but I chaned it slightly so the trigger now filter on both path and branch for pushes. This also make the script a bit cleaner, since the branch filter does not need to be repeated in the run section.
> **Note!** If you use `dev-2.x` in the fork as a active branch the this PR will not prevent this workflow from running, as @optionsome mentions in a comment below. 
🟥  There is no issue for this.
🟥  This is CI config change, we do not have tests for this.
🟥  I have not changed/added doc.
🟥  There is no changes to the OTP code.

Only run "Debug Client" workflow on `dev-2.x` branch

---

doc/user/System-Requirements.md

The suggested machine types for Google Cloud is outdated, Entur uses now a more recent version.
No
No
Skip changelog

Update suggested machine type for Google Cloud [ci skip]

---

application/src/main/java/org/opentripplanner/model/OtpTransitService.java
application/src/main/java/org/opentripplanner/model/impl/OtpTransitServiceBuilder.java
application/src/main/java/org/opentripplanner/model/impl/OtpTransitServiceImpl.java
application/src/main/java/org/opentripplanner/netex/NetexModule.java
application/src/main/java/org/opentripplanner/netex/loader/parser/NetexDocumentParser.java
application/src/main/java/org/opentripplanner/netex/loader/parser/ServiceFrameParser.java
application/src/main/java/org/opentripplanner/netex/mapping/NetexMapper.java
application/src/main/java/org/opentripplanner/transit/service/DefaultTransitService.java
application/src/main/java/org/opentripplanner/transit/service/TimetableRepository.java
application/src/main/java/org/opentripplanner/transit/service/TransitService.java
application/src/main/java/org/opentripplanner/updater/siri/EntityResolver.java
application/src/test/java/org/opentripplanner/transit/service/TimetableRepositoryTest.java
application/src/test/java/org/opentripplanner/updater/siri/EntityResolverTest.java

Even though the various documents on SIRI and NeTEx are quite unclear, even contradictory what exactly an EstimatedCall's `StopPointRef` should refer to, all the experts agree that a scheduled stop point is a valid target (as an alternative to the quay).
We discussed this at length at https://public.3.basecamp.com/p/TcEEP5WrNZJPBxrJU9GAjint
For this reason, this adds support for SIRI to refer to scheduled stop point.
Closes #6340
I added some for the EntityResolver and the TimetableRepository.
I didn't want to duplicate the documentation for this in several places so I opted to document it in the innermost layer (TimetableRepository) and link to it in other places.
cc @rcavaliere

Allow SIRI's StopPointRef to refer to a NeTEx scheduled stop point

---

application/pom.xml
application/src/main/java/org/opentripplanner/inspector/raster/TileRendererManager.java
application/src/main/java/org/opentripplanner/inspector/raster/WheelchairEdgeRenderer.java
application/src/main/java/org/opentripplanner/standalone/configure/ConstructApplicationModule.java
application/src/main/java/org/opentripplanner/standalone/server/DefaultServerRequestContext.java
application/src/test/java/org/opentripplanner/GtfsTest.java
application/src/test/java/org/opentripplanner/TestServerContext.java
application/src/test/java/org/opentripplanner/apis/transmodel/mapping/TripRequestMapperTest.java
application/src/test/java/org/opentripplanner/transit/speed_test/SpeedTest.java
pom.xml

Today I got a merge conflict when rebasing the via coordinates So I have refactored and cleaned up the `DefaultServerRequestContext`  to avoid these kind of problems in the futue. This also improve the readability.
A reminder - why do we keep things (fields, arguments and methods) sorted in code:
- Reduce merge conflicts: Insert B, T, in (A, F, T) - If two PRs append then you have a merge conflict, if you insert in the right place there is no conflict.
- Easier to avoid duplicates, reuse.
- Easier to find/read, if you look for `transit` you can skip to this end.
🟥  There is not issue for this, but this is in our coding standards.
🟥  This is a "pure" refactoring, the code should work as before.
I added a few comments.
🟥  Not needed

Cleanup DefaultServerRequestContext

---

application/pom.xml
application/src/main/java/org/opentripplanner/updater/siri/updater/google/GooglePubsubEstimatedTimetableSource.java

Replaces the usage of proprietary protobuf-format for SIRI ET-data with standard XML.
The protobuf-solution was very sensitive to changes, and upgrading protobuf-java (e.g. as in #6342) caused OTP to no longer being able to process SIRI ET-data.

Replacing protobuf-format in SIRI-Updater with standard xml

---

application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java

This PR disable OptimizeTransfers for via search. The OptimizeTransfers does not work with via search as is. It is not implemented yet. 
The plan is to support the via in TransferOptimization soon, but until then merging this PR into your code will make the via work.
There is no issue for this - this is a known limitation due to the fact that we have not implemented support for the feature. 
A comment is added to the code to explain why the TransferOptimization is temporarily turned off.
🟥  Not needed

Disable OptimizeTransfers for via search temporarily.

---

client/src/components/MapView/LayerControl.tsx
client/src/components/MapView/MapView.tsx
client/src/util/map.ts

@t2gran asked in today's meeting if it was possible to click on stops in the debug view. This feature existed for a while but was inadvertently broken in #6370 as the stops are not clickable when you first load the map. They only become clickable after opening the right hand panel.
This PR restores it. It seems that I'm the Chief Restorer of Clickable Stops, since this is actually the second time I'm fixing this: https://github.com/opentripplanner/OpenTripPlanner/pull/6261
This also removes the animation from the map pan when loading the app.

Restore ability to click on stops in debug UI on first map load

---

application/pom.xml

Right now dev-2.x is broken because of what looks like a problem during generation of the maven-metadata file for a transitive dependency: https://github.com/netplex/json-smart-v2/issues/240
In order to continue our work, we decided to upgrade the library that is causing the issue (even though it's not the library's fault).

Update `azure-identity` to fix build

---

application/src/main/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferences.java
application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql
application/src/test/java/org/opentripplanner/routing/api/request/preference/StreetPreferencesTest.java
doc/user/RouteRequest.md

This PR removes the default accessegress penalty for car modes that use transit.
This is a follow-up PR related to issue https://github.com/opentripplanner/OpenTripPlanner/issues/5875
Automatically generated changes.

Remove default accessegress penalty for car modes that use transit

---

application/src/main/java/org/opentripplanner/model/plan/legreference/ScheduledTransitLegReference.java

Fix logging in ScheduledTransitLegReference. The problem was that tripId was logged but not set for trip-on-service-day.
🟥  This is a minor fix.
🟥  No test on logging
🟥  Log messages are slightly changed by appending the LogReference 
🟥  This is too small
🟥   Not needed

Fix logging in ScheduledTransitLegReference

---

application/src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
application/src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java

Two changes for fares:
- Adds support for Community Transit's flex service (which is a different agency ID) to the fare module
- Adjusts the reduced fares after Mar 1 2025 to $1. The code that checks the date can be removed after Mar 1. 
I'm not writing a test for the date since it's temporary and would require a reconfiguration of the test utilities to support specifying a date. I have modified a test to check the flex fare works.

Add CT Fares for Mar 1 fare changes + flex support

---

application/src/ext-test/java/org/opentripplanner/ext/fares/impl/HSLFareServiceTest.java
application/src/ext/java/org/opentripplanner/ext/fares/impl/HSLFareService.java

When there are many suitable fare options (the same price), the HSL fare service should prefer a fare that has an identical set of zones to the required zones if such a fare exists. 
When the journey happens only within a single zone, the service returns a two-zone fare when a single zone fare also exists. Currently single zone fares are never returned.
Manually verified.
Fixed the unit test. (The unit test for zone D journey should originally have failed as the service gave it a CD fare in a real world case, however the CD fare in the test had an incorrect price, making it more expensive than a D fare.)

HSL prefers fares with zones identical to those required by the journey

---

application/src/main/java/org/opentripplanner/transit/service/TimetableRepository.java

In #6415 I introduced a bug which would cause API calls that involved alerts to crash with an NPE. This is because there is questionable initialization logic of `TransitAlertService` in `TimetableRepository`.
@t2gran has pointed out that there is probably a better fix that works in more case: you simply reset the `transitAlertService` after setting the `graphUpdaterManager`. 
This means that you always get a `TransitAlertService` even in cases where no real time updates at all were configured.
None. However, I think we should remove this brittle initialisation logic and let Dagger manage the lifecycle of `UpdaterManager` and `TransitAlertService`.
I opted to document the behaviour instead.
New Javadoc.

Fix initialisation logic of transit alert service

---

application/src/main/java/org/opentripplanner/routing/graph/index/StreetIndex.java
application/src/main/java/org/opentripplanner/street/model/vertex/TemporaryStreetLocation.java
application/src/test/java/org/opentripplanner/astar/AStarTest.java
application/src/test/java/org/opentripplanner/routing/algorithm/GraphRoutingTest.java

The other temporary vertex, TemporarySplitterVertex, is left as is. This is getting its id(label) from the splitter.
🟥  No issue.
🟥  No test, a few tests failed after the change - these are fixed.
🟥  No doc.
🟥  Not relevant.
🟥  Not needed.

Remove the usage of UUID in TemporaryStreetLocation

---

application/src/main/java/org/opentripplanner/updater/trip/siri/ModifiedTripBuilder.java
application/src/test/java/org/opentripplanner/updater/trip/siri/moduletests/InterpolationTest.java

The code for matching siri calls to the stops in the tripPattern has a bit of magic and does some time interpolation stuff. Time interpolation in siri is controversial and not something we want to do in general.
This PR tries to highlight the current behaviour by adding a test that shows what happens when we get a siri message with an incomplete list of calls. I also add logging when the time interpolation happens so that we can see if this is actually being used in production or if we can retire this piece of code.
- Add test to illustrate time interpolation.
- Refactor the call matching code slightly to make the logic a bit more clear.
- Add logging when we do time interpolation.
I'm adding a realtime test.
No

Illustrate current behaviour of siri time interpolation

---

application/src/main/java/org/opentripplanner/osm/model/OsmEntity.java
application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/BoardingLocationTest.java
doc/user/BoardingLocations.md

Since https://github.com/opentripplanner/OpenTripPlanner/pull/6247 it has been possible to link transit data to the streetgraph for linear ways and not just nodes and areas. The list of tags in IsBoardingLocation() was not appropriate for this with regards to buses which use tag highway=platform for linear ways. This PR therefore adds highway=platform to the function.
Closes #6433
None
Docs were updated and now mention both highway=platform and railway=platform in addition to the previous list of tags.

Add highway=platform to IsBoardingLocation()

---

application/src/ext/java/org/opentripplanner/ext/dataoverlay/api/DataOverlayParameters.java
application/src/main/java/org/opentripplanner/routing/algorithm/raptoradapter/router/TransitRouter.java
application/src/main/java/org/opentripplanner/routing/api/request/framework/DurationForEnum.java
application/src/main/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferences.java
application/src/main/java/org/opentripplanner/routing/api/request/preference/MaxStopCountLimit.java
application/src/main/java/org/opentripplanner/standalone/config/routerequest/RouteRequestConfig.java
application/src/test/java/org/opentripplanner/routing/api/request/preference/AccessEgressPreferencesTest.java
application/src/test/java/org/opentripplanner/routing/api/request/preference/MaxStopCountLimitTest.java
application/src/test/java/org/opentripplanner/routing/api/request/preference/StreetPreferencesTest.java

Refactor max stop count limit so that the map is merged with any new definition of max stop counts. This also fixes an issue with default max stop count limit for mode being overridden by an empty map when using transfer cache requests.
This replaces https://github.com/opentripplanner/OpenTripPlanner/pull/6488
No issue
Updated
Not needed
From title

Use default max stop count for mode from routing defaults in transfer requests

---

application/src/main/java/org/opentripplanner/apis/transmodel/model/plan/ModeInputType.java
application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql

This PR fixes a typo in the Transmodel GraphQL API documentation.
No
No
Updated
Skipped

Fix typo in access mode documentation

---

application/src/main/java/org/opentripplanner/updater/trip/metrics/StreamingTripUpdateMetrics.java

This PR sets a default value to the producer tag on the prometheus realtime metrics. The current state leaves the producer tag empty when there is no producer on the result, which leads to metrics not updating because prometheus metrics have to have the same tags.
Warning we get currently:
```
The meter (MeterId{name='streaming_trip_updates.failed', tags=[tag(configRef=SIRI_ET_GOOGLE_PUBSUB_UPDATER),tag(errorType=UNKNOWN),tag(feedId=RB),tag(url=http://realtime-cache.dev.entur.internal/et)]}) registration has failed: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'streaming_trip_updates.failed' containing tag keys [configRef, errorType, feedId, producer, url]. The meter you are attempting to register has keys …
```

Add default unknown_producer tag value to the producer tag of the StreamingTripUpdateMetrics

---

application/src/main/java/org/opentripplanner/osm/tagmapping/OsmTagMapper.java
application/src/main/resources/WayProperties.properties
application/src/main/resources/WayProperties_de.properties
application/src/main/resources/WayProperties_fi.properties
application/src/main/resources/WayProperties_fr.properties
application/src/main/resources/WayProperties_hu.properties
application/src/main/resources/WayProperties_nl.properties
application/src/main/resources/WayProperties_no.properties
application/src/main/resources/WayProperties_sv.properties
application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/walkablearea/ConcaveHoleTest.java
application/src/test/java/org/opentripplanner/osm/tagmapping/OsmTagMapperTest.java

We recently allowed routing through areas tagged with `indoor=area` but we haven't assigned a namer to it, which this PR fixes.
Added.
N/a
skip

Add edge name for indoor area

---

application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchema.java

This fixes an error introduced in https://github.com/opentripplanner/OpenTripPlanner/pull/6423 where an empty ID list was treated like a "list all" instead of a "list none" in the stopPlaces API.
Note that this change just reverts to the previous functioning version of the API. It does not improve on the previous state, for instance how `arg=null` is handled (it could be handled as an unset arg or the empty value for the arg), nor does implement any kind of paging for when all results are requested (which is what causes the error today). These are noted and will be handled in future improvements.
Erroring API call: https://api.dev.entur.io/graphql-explorer/journey-planner-v3?query=query%20stopPlaces%28%24ids%3A%5BString%21%5D%24lines%3A%5BID%5D%24startTime%3ADateTime%29%7BstopPlaces%28ids% …

Fixes issue where empty ids list was causing errors.

---

application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/VehiclePositionImpl.java
application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
application/src/main/java/org/opentripplanner/service/realtimevehicles/RealtimeVehicleRepository.java
application/src/main/java/org/opentripplanner/service/realtimevehicles/internal/DefaultRealtimeVehicleService.java
application/src/main/java/org/opentripplanner/updater/vehicle_position/GtfsRealtimeHttpVehiclePositionSource.java
application/src/main/java/org/opentripplanner/updater/vehicle_position/PollingVehiclePositionUpdater.java
application/src/main/java/org/opentripplanner/updater/vehicle_position/RealtimeVehiclePatternMatcher.java
application/src/main/java/org/opentripplanner/updater/vehicle_position/VehiclePositionUpdaterRunnable.java
application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
application/src/test/java/org/opentripplanner/service/realtimevehicles/internal/DefaultRealtimeVehicleServiceTest.java
application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/patterns.json
application/src/test/resources/org/opentripplanner/apis/gtfs/queries/patterns.graphql

The real time vehicle service does not correctly remove the data from the previous download which this PR fixes.
It introduces copy-on-write semantics for the service rather than explicit removal by the calling code, reducing the number of places where mutable state is handled.
It also adds a new GraphQL property so that the last update is now expressed as an ISO date time rather than number of seconds since the epoch.
n/a
Added.
Javadoc
cc @whitneys-pm

Fix removal of old vehicle positions

---

application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/DatedServiceJourneyType.java
application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/ServiceJourneyType.java
application/src/main/resources/org/opentripplanner/apis/transmodel/schema.graphql

As a consequence of #6245, the TransModel API can return `null` for the list of `estimatedCalls` of a given `ServiceJourney` or `DatedServiceJourney`, if the trip does not run on the given date. Before this change, the API would return an empty list `[]`.
This is not consistent with the rest of the API: On `quays` and `stopPlaces`, `estimatedCalls` are expected to be non-null. The same applies for `serviceJourneyEstimatedCalls` and `intermediateEstimatedCalls` in other parts of the API.
This PR:
- reverts to the original behavior where the API returns an empty list instead of null.
- aligns the behavior of `estimatedCalls` on `ServiceJourney` and `DatedServiceJourney` with the rest of the API, by making them explicitly non-nullable: `[EstimatedCall!]!`
**Note**: while making a nullable …

Make estimated calls non nullable in the TransModel API

---

application/src/main/java/org/opentripplanner/apis/transmodel/TransmodelGraphQLSchema.java
application/src/main/java/org/opentripplanner/apis/transmodel/mapping/TransitIdMapper.java
application/src/main/java/org/opentripplanner/apis/transmodel/support/GqlUtil.java
application/src/main/java/org/opentripplanner/transit/api/model/FilterValues.java
application/src/main/java/org/opentripplanner/transit/api/model/FilterValuesNullIsEverything.java
application/src/main/java/org/opentripplanner/transit/api/request/TripRequest.java
application/src/main/java/org/opentripplanner/transit/api/request/TripRequestBuilder.java
application/src/main/java/org/opentripplanner/transit/model/filter/transit/TripMatcherFactory.java
application/src/test/java/org/opentripplanner/transit/model/filter/transit/TripMatcherFactoryTest.java

This PR changes the behaviour of the ServiceJourneys Transmodel API endpoint so that null or unset values match everything, but empty lists match nothing.
This is different from today's production where arguments set to empty lists match everything, just like null or unset values. For example: https://api.entur.io/graphql-explorer/journey-planner-v3?query=%7BserviceJourneys%28authorities%3Anull%29%7Bid%7D%7D
Today's behaviour where everything is returned causes errors:
While the new behaviour causes empty lists to be returned (because nothing is matched):
Behaviour for null or unset arguments is the same (error because of too many results).
#5630
Tested with unit tests on the matcher resulting from the TripMatcherFactory, and by running locally.

Change the TripRequest and builder to work with include lists instead of just the FilterValues

---

doc/dev/decisionrecords/Codestyle.md
doc/dev/decisionrecords/NamingConventions.md

As discussed in a recent meeting, this adds a short explanation of why some variables have underscore-separated units as part of their names, defying standard camelCase.
It seems a little strange to update an already existing decision record, but this is a very minor point and probably less likely to be seen if it were split out into a separate style document.

Add explanation of underscore-separated units in variable names [ci skip]

---

application/src/ext/java/org/opentripplanner/ext/restapi/resources/IndexAPI.java
application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/PatternImpl.java
application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/RouteImpl.java
application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StopImpl.java
application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/TripImpl.java
application/src/main/java/org/opentripplanner/apis/transmodel/model/timetable/ServiceJourneyType.java
application/src/main/java/org/opentripplanner/routing/alertpatch/EntitySelector.java
application/src/main/java/org/opentripplanner/routing/impl/DelegatingTransitAlertServiceImpl.java
application/src/main/java/org/opentripplanner/routing/impl/TransitAlertServiceImpl.java
application/src/main/java/org/opentripplanner/routing/services/TransitAlertService.java
application/src/test/java/org/opentripplanner/updater/alert/siri/SiriAlertsUpdateHandlerTest.java

This is a pure refactor. It doesn't change any functionality.
This fixes some warnings of the type:
```
non-varargs call of varargs method with inexact argument type for last parameter
```
Also a minor improvement: adding a method `TransitAlertService.getTripAlerts(FeedScopedId trip)` so you don't have to do `TransitAlertService.getTripAlerts(trip, null)`. 
This is mostly a cleanup of some test code.
Nope

Fix warnings in SiriAlertsUpdateHandlerTest

---

application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/BikeRentalStationImpl.java
application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/RentalVehicleImpl.java
application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/RoutingErrorImpl.java
application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/VehicleRentalStationImpl.java
application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/stepImpl.java

Updates data fetchers to use the GraphQL utils for determining the locale for translations so that the `locale` param in plan queries is respected if no accept-language header is used.
No issue
Not sure if needed
No
From title

Use locale param from plan queries for all translations in the GTFS API if accept-language header is not set

---

application/src/ext-test/java/org/opentripplanner/ext/accessibilityscore/DecorateWithAccessibilityScoreTest.java
application/src/ext/java/org/opentripplanner/ext/accessibilityscore/DecorateWithAccessibilityScore.java

@amy-corson-ibigroup has requested the following change to the accessibility score: only those itineraries which are walk-only or have a transit leg should receive an itinerary-level score.
Added.
Skip
No

Only add accessibility score to itinerary when it's walk-only or transit

---

application/src/main/java/org/opentripplanner/routing/algorithm/RoutingWorker.java

We get a NullPointerException for via search after #6535 was merged. One return statement was missed when converting to use Result DTO in RoutingWorker.
🟥  There is no issue.
🟥  We do not have integration test on this - we probably should.
🟥  This is a regression, no feature changes.
🟥  The PR #6535 is in the same version as this.
🟥  Not needed, no changes to model.

Fix NPE in RoutingWorker after #6535 was merged

---

application/src/ext-test/java/org/opentripplanner/ext/fares/FaresFilterTest.java
application/src/ext-test/java/org/opentripplanner/ext/fares/impl/DefaultFareServiceTest.java
application/src/ext-test/java/org/opentripplanner/ext/fares/impl/FaresIntegrationTest.java
application/src/ext-test/java/org/opentripplanner/ext/fares/impl/OrcaFareServiceTest.java
application/src/ext-test/java/org/opentripplanner/ext/realtimeresolver/RealtimeResolverTest.java
application/src/ext/java/org/opentripplanner/ext/fares/ItineraryFaresDecorator.java
application/src/ext/java/org/opentripplanner/ext/fares/impl/AtlantaFareService.java
application/src/ext/java/org/opentripplanner/ext/fares/impl/DefaultFareService.java
application/src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresService.java
application/src/ext/java/org/opentripplanner/ext/fares/impl/GtfsFaresV2Service.java
application/src/ext/java/org/opentripplanner/ext/fares/impl/HighestFareInFreeTransferWindowFareService.java
application/src/ext/java/org/opentripplanner/ext/fares/impl/NoopFareServiceFactory.java
application/src/ext/java/org/opentripplanner/ext/fares/impl/OrcaFareService.java
application/src/main/java/org/opentripplanner/model/fare/ItineraryFare.java
application/src/main/java/org/opentripplanner/model/plan/Itinerary.java
application/src/main/java/org/opentripplanner/model/plan/ItineraryBuilder.java
application/src/main/java/org/opentripplanner/routing/algorithm/RoutingResult.java
application/src/main/java/org/opentripplanner/routing/fares/FareService.java
application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
application/src/test/java/org/opentripplanner/routing/core/ItineraryFareTest.java

Small fixes suggest in the review of #6535.
Renaming [`ItineraryFares` to `ItineraryFares`](https://github.com/opentripplanner/OpenTripPlanner/pull/6539/commits/fa6efcbdd0958b3d67d8cc2f44f5743bbed74969) is debatable:
- In old Java conventions plural is used for naming variables and classes witch are of collection type, not necesseraly extending the java collections, but something containing a collection of the singular form.
- Note that `ItineraryFare` is related to the itinerary, it does contain a collection of fares for legs - but only one fare for the total Itinerary. 
Alternative name: `ItineraryFareInfo`
🟥  This is code cleanup
🟥  No new functional changes
✅  JavaDoc is updated
🟥  This is code cleanup
🟥  No changes to serialized classes

Fix itinerary cost review

---

application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureETUpdaterParameters.java

The serviceBusUrl in the siri azure parameters is optional, but there is a NPE when it's unset.
Pure sandbox code.
Nope

Fix null issue in SiriAzureETUpdaterParameters

---

application/src/main/java/org/opentripplanner/graph_builder/module/osm/TurnRestrictionUnifier.java
application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/TurnRestrictionsTest.java
application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/_support/RelationBuilder.java
application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/_support/TestOsmProvider.java
application/src/test/java/org/opentripplanner/test/support/GeoJsonIo.java

Throwing out restrictions based on a heuristic was wrong. We still continue adding issues to the issue store for them.
The code in question is really old, and no one really remembered why it is written this way. Maybe OSM data used to be worse, these days this check seems counterproductive.
Fixes #6536 
None existed in the first place.
I left a comment explaining the logic.
No.
No.

do not discard turn restrictions where the turn description and angle do not match, just add an issue

---

doc/user/Accessibility.md

@vpaturet has correctly pointed out that the example configuration for the accessibility feature suggests an absurdly large value which we should change.
I'm not sure how it happened but 50 means that for every percent you go over the limit you will multiply the edge cost by 50 which might lead to integer overflows.
A value of 1 doubles the cost for every percent over the limit which is enough of a penalty, I feel.
[Gitter chat](https://matrix.to/#/!oXNNoHKzbaSOlFzLEt:gitter.im/$tcGyq09eBy_3fYn387MEzIZRzKOdLMkxANEKfwbru1g?via=gitter.im&via=matrix.org&via=builtin.io)

Make `slopeExceededReluctance` example more realistic [ci skip]

---

application/src/ext-test/java/org/opentripplanner/ext/vectortiles/VectorTilesResourceTest.java
application/src/ext/java/org/opentripplanner/ext/vectortiles/VectorTilesResource.java
application/src/main/java/org/opentripplanner/apis/support/TileJson.java
application/src/main/java/org/opentripplanner/apis/vectortiles/GraphInspectorVectorTileResource.java
application/src/main/java/org/opentripplanner/standalone/config/routerconfig/VectorTileConfig.java
application/src/test/java/org/opentripplanner/apis/support/TileJsonTest.java
application/src/test/java/org/opentripplanner/standalone/config/routerconfig/VectorTileConfigTest.java

@miles-grant-ibigroup has reported that the tilejson `minzoom` and `maxzoom` values are hard-coded and don't take into account the configuration values of the layers themselves.
So if you have a config like
```
"vectorTiles": {
"layers": [
{
"name": "stops",
"type": "Stop",
"mapper": "Digitransit",
"maxZoom": 20,
"minZoom": 2,
"cacheMaxSeconds": 600
}
]
```
Then the tilejson would still use the hard-coded `minzoom` value of 9.
This is fixed with this PR.
Added.
Skip

Take layer configuration into account when computing tilejson min/max zoom

---

application/src/ext/java/org/opentripplanner/ext/restapi/model/ApiLeg.java
application/src/main/java/org/opentripplanner/netex/index/api/ReadOnlyHierarchicalVersionMapById.java
application/src/main/java/org/opentripplanner/routing/api/request/preference/TransferPreferences.java

Tiny PR that fixes some compiler warnings where methods are documented as deprecated but not annotated as such.
Nope

Add @Deprecated to methods that are documented as deprecated [ci skip]

---

application/src/main/java/org/opentripplanner/framework/graphql/GraphQLUtils.java
application/src/test/java/org/opentripplanner/framework/graphql/GraphQLUtilsTest.java

Previously if both accept-language header and locale param were defined, env would be used. This changes the prioritization so that the locale param is used.
No issue
Update tests
Not needed
From title

Use locale param if one is defined over accept-language header in GTFS APIs

---

doc/user/Deployments.md

Plannerstack is no longer active as an organisation, the URLs dont work and there is no longer an independent service running OTP. It seems another entity ahs taken over assets, I will ask them to contribute their reference to the docs
Small bugfix
n/a
Documentation only fix

Remove reference to Plannerstack in documentation

---

application/src/main/java/org/opentripplanner/model/plan/WalkStepBuilder.java
application/src/main/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapper.java
application/src/test/java/org/opentripplanner/routing/algorithm/mapping/StatesToWalkStepsMapperTest.java
application/src/test/java/org/opentripplanner/street/model/_data/StreetModelForTest.java
application/src/test/java/org/opentripplanner/street/search/state/TestStateBuilder.java

Prevents removing of walksteps with entrance information
Closes #6528
Write a few words on how the new code is tested.
-
-
The [changelog file](https://github.com/opentripplanner/OpenTripPlanner/blob/dev-2.x/doc/user/Changelog.md)
To exclude the PR from the changelog add the label `skip changelog` to the PR.
-

Fix entrances being removed from walk steps

---

application/src/main/java/org/opentripplanner/graph_builder/module/osm/ElevatorProcessor.java
application/src/main/java/org/opentripplanner/osm/model/OsmEntity.java
application/src/main/java/org/opentripplanner/osm/model/OsmWay.java
application/src/main/java/org/opentripplanner/street/model/edge/ElevatorHopEdge.java
application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/BoardingLocationTest.java
application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/ElevatorTest.java
application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/_support/TestOsmProvider.java
application/src/test/java/org/opentripplanner/graph_builder/module/osm/moduletests/walkablearea/SimpleAreaTest.java
application/src/test/java/org/opentripplanner/street/model/edge/ElevatorHopEdgeTest.java

Elevators can now also have a hh:mm:ss format duration tag in OSM, and we recognize them.
The way we handled elevator duration tags was against OSM data spec.
The OsmProcessors are hard to test, and because of that are undertested. I added one here.
Yes.
Yes.

Handle duration tags for elevators in the same way as for escalators

---

application/src/main/java/org/opentripplanner/gtfs/graphbuilder/GtfsModule.java
application/src/test/java/org/opentripplanner/gtfs/GtfsContextBuilder.java
application/src/test/java/org/opentripplanner/gtfs/graphbuilder/GtfsModuleTest.java

GTFS Fares V2 allows you to leave out the field `fare_product_id`, `from_leg_group_id`, `to_leg_group_id`, however when you do so exceptions are thrown during graph building.
This PR fixes it.
cc @miles-grant-ibigroup 
n/a
I would like to add some but I would have to refactor `GtfsModule` quite a bit. Given that Thomas is working on the same classes I will defer that to another PR.
There is a tiny bit of clean up of the test code.
n/a

Fix NPEs when processing FaresV2 feeds

---

application/src/test/java/org/opentripplanner/netex/mapping/calendar/DayTypeAssignmentMapperTest.java

This PR adds unit tests for parsing a NeTEx operating period whose From and To dates are identical.
OTP maps this as a period containing exactly one operating day.
This is true both for periods specified with `<FromDate>` and `<ToDate>` and periods specified with `<FromDateRef>` and `<ToDateRef>`
The Nordic NeTEx profile specifies that the end date of an operating period should be considered inclusive
https://enturas.atlassian.net/wiki/spaces/PUBLIC/pages/728727624/framework#OperatingPeriod
When the operating period is specified with `<FromDate>` and `<ToDate>`, the time component of the DateTime is ignored. 
No
No

Add unit tests for parsing one-day NeTEx operating periods

---

doc/dev/decisionrecords/APIGraphQLDesign.md

This adds a policy for doing breaking-changes to the API. This is just a suggestion, we will discuss the details in
a developer meeting 
Ref: #6540
No.
Doc only
Yes.
No
No

Document policy for doing breaking changes the the APIs.

---

application/src/ext/java/org/opentripplanner/ext/debugrastertiles/api/resource/DebugRasterTileResource.java
application/src/ext/java/org/opentripplanner/ext/debugrastertiles/api/resource/MIMEImageFormat.java
application/src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
application/src/main/java/org/opentripplanner/api/parameter/package-info.md
application/src/test/java/org/opentripplanner/api/parameter/QualifiedModeSetTest.java

The deprecated `plan` query doesn't correctly set the transfer mode for scooter rental access/egress queries, which this PR fixes. This deprecated query is still used by the German Digitransit fork Stadtnavi.
During the removal of the REST API I was also a little overzealous in removing the test for the QualifiedModeSet, which wasn't necessary. I restored it in this PR.
There was also class that was only used the by debug raster tiles, which I moved to the correct package.
https://github.com/stadtnavi/digitransit-ui/issues/907
Some restored and some added.
cc @hbruch @stadtnavimanager

Set correct transfer modes for scooters in deprecated `plan` query

---

application/src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
application/src/test/java/org/opentripplanner/routing/linking/LinkStopToPlatformTest.java

VertexLinker no longer assumes that a non-overlapping area visibility vertex is found.
Closes #6596 
Unit test to verify the regression fix added.

 Boarding location linking accepts very short links instead of throwing an exception

---

application/src/ext-test/java/org/opentripplanner/ext/flex/filter/FilterMapperTest.java
application/src/main/java/org/opentripplanner/transit/api/model/EmptyIsEverythingFilter.java
application/src/main/java/org/opentripplanner/transit/api/model/FilterValues.java
application/src/main/java/org/opentripplanner/transit/api/model/NullIsEverythingFilter.java
application/src/main/java/org/opentripplanner/transit/api/model/RequiredFilterValues.java
application/src/main/java/org/opentripplanner/transit/api/request/TripOnServiceDateRequest.java
application/src/main/java/org/opentripplanner/transit/api/request/TripOnServiceDateRequestBuilder.java
application/src/test/java/org/opentripplanner/transit/api/model/EmptyIsEverythingFilterTest.java

In #6421 @t2gran has requested that the implementations of `FilterValues` be renamed and they be made package private. I changed it in this PR.

Rename FilterValues implementations, make them package-private

---

application/src/main/java/org/opentripplanner/standalone/config/framework/json/OtpVersion.java

Add OTP Version `v2.8` tag. This is used to tag new parameters in the cinfiguration.
No issue.
No test.
No Doc.
No relevant.
Not needed.

feature: Add version 2.8 to OtpVersion

---

.github/workflows/schema-validation.yml

Splits schema validation actions workflow into two jobs so we always see the validation results from both validation runs.
No issue
None
None
Skipped

Split schema validation actions workflow into two jobs

---

application/src/main/java/org/opentripplanner/updater/trip/siri/SiriRealTimeTripUpdateAdapter.java
application/src/main/java/org/opentripplanner/updater/trip/siri/SiriTripPatternCache.java

In today's real time meeting we talked about the indexing of trip patterns in the `SiriTripPatternCache` and we came to the following conclusion:
- we don't really know why the cache key contains the service date
- even though we are uneasy about it, @vpaturet agreed to just try it out on Entur's staging system to find out if there are negative consequences
#4002

Remove service date from cache key of SiriTripPatternCache

---

application/src/main/java/org/opentripplanner/api/parameter/QualifiedModeSet.java
application/src/test/java/org/opentripplanner/api/parameter/QualifiedModeSetTest.java

This fixes the transfer mode setting for the deprecated `plan` query. This is very similar to #6597 but for bike and car rental.
My suspicion is that this behaviour changed during @VillePihlava's refactoring of the transfers so we have to adapt this API.
https://github.com/public-transport/transitous/issues/1092
Unit tests added.
cc @hbruch

Fix transfer for rental modes in deprecated `plan` query

---

application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/RentalVehicleImpl.java
application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLDataFetchers.java
application/src/main/java/org/opentripplanner/service/vehiclerental/model/VehicleRentalVehicle.java
application/src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/GbfsFreeVehicleStatusMapper.java
application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
application/src/test/java/org/opentripplanner/service/vehiclerental/model/TestFreeFloatingRentalVehicleBuilder.java
application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/rental-vehicle.json
application/src/test/resources/org/opentripplanner/apis/gtfs/queries/rental-vehicle.graphql

This PR adds availability information to  the rental vehicle model and GraphQL API by using the `available_until` field of the vehicle_status.json in GBFS.
https://github.com/opentripplanner/OpenTripPlanner/issues/6547
The PR handles the first two steps in this commend: https://github.com/opentripplanner/OpenTripPlanner/issues/6547#issuecomment-2752085568
This field can be used to better inform the user about the availability of the vehicle.
Also this field can later be used, to consider it the routing as described in the linked issue.
It does not consider the new more complex GBFS extension(vehicle_availability.json), linked in the issue, because the GBFS model does not exist in the library yet.
- considers the `available_until` field in the GraphQLIntegrationTest

Add availableUntil to rental vehicles in the GTFS GraphQL API

---

application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureSXUpdater.java
application/src/ext/java/org/opentripplanner/ext/siri/updater/azure/SiriAzureUpdater.java

Fixed Siri SX alerts handling with dedicated wrapper
Fix SIRI SX alerts with dedicated wrapper class
Fixes a bug where SIRI SX alerts weren't being processed because SiriAzureUpdater wasn't recognized as a TransitAlertProvider.
Created a specialized SxWrapper subclass that implements TransitAlertProvider and gets registered in the alert service registry. This ensures the TransitAlertServiceImpl inside SiriAzureSXUpdater is properly discovered without affecting the ET updater functionality.
Verification was done using Skånetrafiken SX tests. They did not pass before the fix and passed after the fix.
Also ran the Skånetrafiken ET test to verify that they still worked.

Fixed Siri SX alerts handling with dedicated wrapper

---

application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls

The field `vertexType` in the GTFS API hasn't been maintained for years and is of questionable value. It also uses oddly specific street routing language.
For this reason I would like to deprecatate it.

Deprecate vertexType in GTFS API

---

application/src/ext/java/org/opentripplanner/ext/debugrastertiles/api/resource/DebugRasterTileResource.java
doc/user/sandbox/DebugRasterTiles.md

Updated path for debug raster tiles from `/otp/debugrastertiles/{layer}/{z}/{x}/{y}.png` to `/otp/debug/rastertiles/{layer}/{z}/{x}/{y}.png` (inspired by #6631)
No issue
No
Updated
Skipped

Update path for debug raster tiles

---

application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StopImpl.java
application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls

The field `Stop.vehicleType` always returns null and there is an alternative, so I want to deprecate it.

Deprecate vehicle type in GTFS API

---

application/pom.xml
application/src/main/java/org/opentripplanner/gtfs/mapping/StopTimeMapper.java
application/src/main/java/org/opentripplanner/model/StopTime.java
application/src/test/java/org/opentripplanner/gtfs/mapping/StopTimeMapperTest.java

It upgrades onebusaway to version 7. This version [stops parsing a lot of fields](https://github.com/OneBusAway/onebusaway-gtfs-modules/pull/346) that never made it into the GTFS spec and occasionally cause problems when parsing feeds that, for inexplicable reasons, still contain those fields.
We had a tiny bit of mapping code for those fields but it was only used in a test, so can go away, too.

Upgrade to OBA 7, remove unused fields

---

application/src/main/java/org/opentripplanner/routing/algorithm/filterchain/filters/transit/group/RemoveOtherThanSameLegsMaxGeneralizedCost.java
application/src/test/java/org/opentripplanner/model/plan/TestItineraryBuilder.java
application/src/test/java/org/opentripplanner/routing/algorithm/filterchain/filters/transit/group/RemoveOtherThanSameLegsMaxGeneralizedCostTest.java

Fixes a bug in `RemoveOtherThanSameLegsMaxGeneralizedCost`-filter.
The core reason for the issue is that the leg cost in OTP is not guaranteed to be accurate and the sum of the leg costs might be significantly higher than the cost for the itinerary in some cases.
This can cause the filter to create a negative `Cost`, and the `Cost` constructor throws an IllegalArgumentException on negative values.
The PR fixes this by enforcing the costs to be non-negative.
An example of an itinerary where the leg costs are higher than the itinerary cost is: if we have a transit leg that ends at a stop with a high `stopBoardAlightTransferCost` followed by an egress leg. In this case raptor puts the alight cost on the transit leg and then reduces the cost of the egress leg by the same amount (because the …

Fix negative cost in filter

---

application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/StopImpl.java
application/src/test/java/org/opentripplanner/apis/gtfs/GraphQLIntegrationTest.java
application/src/test/resources/org/opentripplanner/apis/gtfs/expectations/stations.json
application/src/test/resources/org/opentripplanner/apis/gtfs/queries/stations.graphql

When a station is returned by the `nearest` query _and_ you apply a filter to the `routes` resolver a NPE occurs as the routes of a station are defined to be `null`.
Sadly, `Station` uses the same GraphQL type as `Stop` so you can apply a filter even though the routes are always null.
This PR fixes the problem.
None.
Added.
Nullability annotation added.
cc @miles-grant-ibigroup @fpurcell

Fix route filter application for stations in GTFS API

---

application/src/main/java/org/opentripplanner/gtfs/mapping/AgencyMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/FareAttributeMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/FareProductMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/FareTransferRuleMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/IdFactory.java
application/src/main/java/org/opentripplanner/gtfs/mapping/LocationGroupMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/LocationMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/PathwayMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/RouteMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/ServiceCalendarDateMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/ServiceCalendarMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/ShapePointMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/StationMapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/StopMappingWrapper.java
application/src/main/java/org/opentripplanner/gtfs/mapping/TripMapper.java
application/src/test/java/org/opentripplanner/gtfs/mapping/FareLegRuleMapperTest.java
application/src/test/java/org/opentripplanner/gtfs/mapping/GtfsTestData.java
application/src/test/java/org/opentripplanner/gtfs/mapping/IdFactoryTest.java
application/src/test/java/org/opentripplanner/gtfs/mapping/LocationMapperTest.java
application/src/test/java/org/opentripplanner/gtfs/mapping/ServiceCalendarDateMapperTest.java
application/src/test/java/org/opentripplanner/gtfs/mapping/ServiceCalendarMapperTest.java
application/src/test/java/org/opentripplanner/gtfs/mapping/ShapePointMapperTest.java
application/src/test/java/org/opentripplanner/gtfs/mapping/TripMapperTest.java

@daniel-heppner-ibigroup has reported that it's difficult to read error messages of null IDs during the GTFS mapping process. He wasn't sure if the problem was with OTP or his feed.
@habrahamsson-skanetrafiken has also mentioned in #6586 that we are too tolerant of null values when mapping GTFS IDs and it's not clear which IDs are truly nullable.
For this reason I've reworked the GTFS import's `IdFactory`:
- it now adds the name of the entity that has a null id to the error message
- it distinguishes between nullable and non-nullable ids and it's clear from the method name which one is which
I changed many method calls to make the null handling more strict but there are a few where I'm not sure. I've left those as they were.
It should be noted that the core data model already enforces the …

Improve error message for null IDs during GTFS mapping

---

application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/StreetModeMapper.java
application/src/test/java/org/opentripplanner/apis/gtfs/mapping/routerequest/StreetModeMapperTest.java

Fix the string formatting of an error message in StreetModeMapper
Fixes #6322
added for `StreetModeMapper.getStreetModeForRouting`
Not needed
Not needed
Not needed

Fix error message in StreetModeMapper

---

application/src/ext/java/org/opentripplanner/ext/interactivelauncher/debug/raptor/RaptorDebugModel.java
application/src/main/java/org/opentripplanner/routing/api/request/DebugRaptor.java
application/src/main/java/org/opentripplanner/routing/api/request/DebugRaptorBuilder.java
application/src/test/java/org/opentripplanner/routing/api/request/DebugRaptorTest.java
utils/src/main/java/org/opentripplanner/utils/collection/EnumSetUtils.java
utils/src/test/java/org/opentripplanner/utils/collection/EnumSetUtilsTest.java

The DebugRaptor class fails with an NullPointerException when initialized.
<details>
<summary>StackTrace</summary>
<pre>
java.lang.NullPointerException: Cannot invoke "java.util.Set.clear()" because "this.eventTypes" is null
at org.opentripplanner.routing.api.request.DebugRaptorBuilder.withEventTypes(DebugRaptorBuilder.java:71)
at org.opentripplanner.routing.api.request.DebugRaptorTest.testToString(DebugRaptorTest.java:66)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
</pre>
</details>
🟥  No issue, detected when debugging production problem
✅  Regression unit tests added.
✅  JavaDoc
🟥  The DebugRaptor request is part of the serialized …

Fix initialization bug in DebugRaptor request DTO

---

script/CUSTOM_RELEASE_README.md
script/custom-release.py

This PR improve the`custom_release.py` with enhanced logic on setting the correct `serialization.version.id`. The new logic work as follows:
> The script will resolve what the next serialization version id (SID) should be. This is a complex task.
> Here is an overview:
>  1. If the --serVerId option exist, then the latest SID is bumped and used.
>  2. If the --release option exist, then the current pom.xml SID is validated, if ok it is used,
>     if not the script exit.
>  3. All merged in PRs are checked. If a PR is labeled with 'bump serialization id' and the the
>     HEAD commit is not in the latest release, then the last release SID is bumped and used.
>  4. Finally, the script look at the upstream SID for the last release and the base. If the SID
>     is not the same the SID of …

Skip new ser-ver-id for --release option (custom-release)

---

application/src/ext-test/java/org/opentripplanner/ext/stopconsolidation/model/ConsolidatedStopLegBuilderTest.java
application/src/main/java/org/opentripplanner/model/plan/leg/ScheduledTransitLeg.java
application/src/test/java/org/opentripplanner/raptorlegacy/_data/transit/TestTripSchedule.java

This resolves a bit of technical debt by making `startTime`, `endTime` and `serviceDate` required.
It needed some light refactoring of tests.

Make leg's startTime, endTime, serviceDate required

---

application/src/main/java/org/opentripplanner/graph_builder/module/configure/GraphBuilderModules.java
application/src/main/java/org/opentripplanner/graph_builder/module/osm/OsmModule.java
application/src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
application/src/main/java/org/opentripplanner/osm/DefaultOsmProvider.java

`OsmDatabase` is an object which contains some very large collections. This object is stored as an instance variable in `OsmModule` and therefore not garbage collected until the graph build is complete. For large graphs this is a problem because not only is the Graph itself stored in memory but also the raw OSM data, which is a massive waste.
For this reason, I'm changing it to be a local variable that is passed through method calls. This means that it is garbage-collected as soon as the module is finished.
There is also a very small clean up of `DefaultOsmProvider`.
n/a
Comments on the variable.

Reduce graph build memory by gc-ing OsmDatabase early

---

application/src/main/java/org/opentripplanner/apis/gtfs/datafetchers/LegImpl.java
application/src/main/java/org/opentripplanner/apis/gtfs/generated/GraphQLTypes.java
application/src/main/java/org/opentripplanner/apis/gtfs/support/filter/StopArrivalByTypeFilter.java
application/src/main/java/org/opentripplanner/apis/gtfs/support/filter/StopsByTypeFilter.java
application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
application/src/test/java/org/opentripplanner/apis/gtfs/datafetchers/BookingInfoImplTest.java
application/src/test/java/org/opentripplanner/apis/gtfs/datafetchers/DataFetchingSupport.java
application/src/test/java/org/opentripplanner/apis/gtfs/datafetchers/LegImplTest.java
application/src/test/java/org/opentripplanner/apis/gtfs/support/filter/StopArrivalByTypeFilterTest.java
application/src/test/java/org/opentripplanner/model/TripTimeOnDateTest.java
application/src/test/java/org/opentripplanner/transit/model/_data/TimetableRepositoryForTest.java
application/src/test/java/org/opentripplanner/updater/trip/TripInput.java

Allows the itinerary's `intermediatePlaces` and `intermediateStops` fields to be optionally filtered by stop type.
This is useful if you have trips that mix flex and static stops and you're only interested in seeing a particular type.
Lots added.
Schema and Javadoc.
Requested by @miles-grant-ibigroup

Allow filtering of intermediate stops in GraphQL API

---

client/src/components/SearchBar/AccessSelect.tsx
client/src/components/SearchBar/DepartureArrivalSelect.tsx
client/src/components/SearchBar/DirectModeSelect.tsx
client/src/components/SearchBar/EgressSelect.tsx
client/src/components/SearchBar/ItineraryFilterDebugSelect.tsx
client/src/components/SearchBar/MultiSelectDropdown.tsx
client/src/style.css

On my screen the debug UI search fields always overflow into two rows:
With a little bit of CSS, this looks nicer:

Finetune CSS layout of search bar

---

application/src/main/java/org/opentripplanner/street/model/edge/StreetEdge.java
application/src/test/java/org/opentripplanner/street/model/edge/StreetEdgeTest.java

Remove the code which adds walk distance at turns. It results in inaccurate walk distance being returned.
None
Added
None
Not needed

Do not add turn duration into walk distance

---

application/src/main/java/org/opentripplanner/apis/gtfs/mapping/routerequest/LegacyRouteRequestMapper.java
application/src/main/java/org/opentripplanner/apis/transmodel/mapping/TripRequestMapper.java
application/src/main/java/org/opentripplanner/routing/api/request/request/TransitRequest.java
application/src/main/java/org/opentripplanner/routing/api/request/request/TransitRequestBuilder.java
application/src/main/resources/org/opentripplanner/apis/gtfs/schema.graphqls
application/src/test/java/org/opentripplanner/routing/api/request/request/TransitRequestTest.java

This feature has never worked in OTP2 so I'm deprecating it in the GTFS API schema (since some US users were confused).
I'm also removing it from the internal model because it isn't used at all.
I also removed the mapping code from the Transmodel API. In its schema doesn't it doesn't even exist so this is copy and paste code from ancient times.

Remove preferred agencies and routes

---

raptor/src/main/java/org/opentripplanner/raptor/api/model/RaptorTransfer.java

Small JavaDoc change. The comment deleted was forgotten when the RaptorTransfer was split in two (Transfer and AccessEgress), it only apply to access and egress.
Closes #6823
This issue is NOT fixed, but I will explain way in the issue.
No code changed
✅ 
🟥 
Not needed

Doc: Update JavaDoc RaptorTransfer

---

application/src/main/java/org/opentripplanner/graph_builder/module/osm/SafetyValueNormalizer.java
application/src/main/java/org/opentripplanner/graph_builder/module/osm/WalkableAreaBuilder.java
application/src/main/java/org/opentripplanner/routing/linking/VertexLinker.java
application/src/main/java/org/opentripplanner/street/model/edge/Area.java
application/src/test/java/org/opentripplanner/routing/linking/LinkStopToPlatformTest.java

- No through traffic properties are now assigned more accurately to created edges 
- Area safety properties are now assigned as well
- Walkable area builder uses consistent parent entity in vertex generation. previously,  a random entity from the area group was used.  
- Some method renaming  
One unit test added to verify that area safety factors are considered
NOTE: The test is a bit flaky, apparently because of double to float conversion. Test values are chosen to avoid value drifting.
Javadoc added to explain the no through logic.

Minor improvements in vertex to area linking

---

application/src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapperTest.java
application/src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapper.java

Digitransit stop map layer already returned raw gtfs type of routes using the stop, but terminals did not have this information.  Nowadays there are tram terminals of a specific gtfs route type 900, and we need to be able to identify them. 
Unit tests updated.

Add raw gtfs type of routes to digitransit map stations

---

application/src/main/java/org/opentripplanner/framework/i18n/NonLocalizedString.java
application/src/test/java/org/opentripplanner/routing/algorithm/mapping/__snapshots__/CarSnapshotTest.snap

Minor performance improvement: the hashcode() method in NonLocalizedString unnecessarily re-hashes the wrapped String, which also defeats hashcode caching in the String class.
No
Updated snapshot for CarSnapshotTest.
The generated name for a "from" and "to" location ("corner of A and B") depends on the arbitrary order of A and B when iterating a HashSet of I18NString:
https://github.com/OpenTripPlanner/OpenTripPlanner/blob/0d92ded063ab6c7537748e82665058d47b5d7905/application/src/main/java/org/opentripplanner/street/model/vertex/StreetVertex.java#L46
Thus changing the hashcode may change the order.
No
skipped
No

Fix hashcode in NonLocalizedString

---

application/src/ext-test/java/org/opentripplanner/ext/flex/trip/FlexTripsMapperTest.java
application/src/ext-test/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTripTest.java
application/src/ext-test/java/org/opentripplanner/ext/flex/trip/UnscheduledDrivingDurationTest.java
application/src/ext-test/java/org/opentripplanner/ext/flex/trip/UnscheduledTripTest.java
application/src/ext-test/resources/org/opentripplanner/ext/flex/aspen-flex-on-demand.gtfs/calendar_dates.txt
application/src/ext-test/resources/org/opentripplanner/ext/flex/aspen-flex-on-demand.gtfs/stop_times.txt
application/src/ext/java/org/opentripplanner/ext/flex/FlexTripsMapper.java
application/src/ext/java/org/opentripplanner/ext/flex/template/FlexTemplateFactory.java
application/src/ext/java/org/opentripplanner/ext/flex/trip/ScheduledDeviatedTrip.java
application/src/ext/java/org/opentripplanner/ext/flex/trip/UnscheduledTrip.java
application/src/main/java/org/opentripplanner/model/StopTime.java
application/src/test/java/org/opentripplanner/graph_builder/module/StreetLinkerModuleTest.java

Both the GTFS and NeTEx specs require flex trips, just like regular ones, to have at least 2 stop times/passing times.
Even though our flex routing engine doesn't produce a result when you have a trip with a single stop time, we nevertheless import the data anyway and then do nothing with it. It may end up in API response which can be quite confusing.
For this reason, this PR rejects flex trips with fewer than 2 stop times and adds an issue to the store.
No.
Added.

Enforce flex rule: at least two stop times per trip

---

.github/pull_request_template.md
.github/workflows/integration-test.yml
.github/workflows/post-merge.yml
doc/user/Developers-Guide.md
renovate.json5
script/CUSTOM_RELEASE_README.md
script/custom-release.py

To make it easier to add labels I have divided the labels into 3 categoris:
- `!` Type of issue or PR - exact one of these SHOULD be assigned to all PRs and Issues
- `+` Classify a PR or Issue into categories we frequently use. Labels used in the CI/CD fall into this category, as well as the tagging components for easier review (+Roadmap, +Sandbox, +Debug UI, +Real-Time, +Skip Changelog, +Bump Serialization Id ...). PRs and Issues might have zero, one or more of these assigned.
- Everything else. 
Related to #6866
Partly documented in  #6866

Add prefix ! and + to GitHub labels

---

application/src/ext-test/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapperTest.java
application/src/ext/java/org/opentripplanner/ext/vectortiles/layers/stations/DigitransitStationPropertyMapper.java

@josh-willis-arcadis has requested that the field `code` is added to the station vector tiles layer. This is because sometimes stations have a different code from their ID or no code at all and Arcadis would like to indicate this in their UI.
While we want to keep the vector tiles data small and fast, we made an exception here, because we also include the code in the stop layer.
Added.
Skip, because it's a sandbox feature.

Add `code` to station vector tile layer

---

application/src/main/java/org/opentripplanner/updater/vehicle_rental/GeofencingVertexUpdater.java

Replaces expensive geometry.intersects() calls with JTS PreparedGeometry to pre-compute spatial indices. This improves performance by more than two orders of magnitude according to my local tests.
No unit tests added.
No new methods, configuration or api.

fix: use PreparedGeometry in geofencing zone <-> street edge intersect check

---

application/src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/gbfs/v2/GbfsStationInformationMapper.java
application/src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/gbfs/v3/GbfsStationInformationMapper.java

When a GBFS feed contains invalid stations, the corresponding entries are ignored and the event is logged.
This can lead to a large number of messages in the logs.
This PR reduces the verbosity of this log message from INFO to DEBUG.
The PR also rewrites the log format so that it uses the built-in parameterization support in slf4j.
No
No
No
skip

Reduce log verbosity in GBFS station mapper

---

application/src/main/java/org/opentripplanner/apis/vectortiles/DebugStyleSpec.java
application/src/main/java/org/opentripplanner/apis/vectortiles/DebugVectorTilesResource.java
application/src/main/java/org/opentripplanner/inspector/vector/KeyValue.java
application/src/main/java/org/opentripplanner/inspector/vector/geofencing/GeofencingZonesLayerBuilder.java
application/src/main/java/org/opentripplanner/inspector/vector/geofencing/GeofencingZonesPropertyMapper.java
application/src/main/java/org/opentripplanner/inspector/vector/vertex/VertexPropertyMapper.java
application/src/test/java/org/opentripplanner/apis/vectortiles/DebugStyleSpecTest.java
application/src/test/resources/org/opentripplanner/apis/vectortiles/style.json

This adds geofencing zones layers to the debug ui's map style spec, by refitting the old geofencing zones property mapper that was left unused from the previous debug client. Turns out we actually keep the zone geometry in otp. 
Note that this PR does not add any new zone properties. OTP only uses "no-drop-off" and "no-traversal", even though zone rules have become more complex since this was implemented. Everything that doesn't fit these two are considered a "business area", which could be misleading with newer data.
Styling is up for discussion / feedback.
_Note: My proposal is that we deal with Debug UI changes in a follow up PR - specifically handling showing popups for overlapping areas._

Show GBFS Geofencing zones in debug UI

---

application/src/main/java/org/opentripplanner/api/model/serverinfo/OtpBadgeGenerator.java
application/src/main/java/org/opentripplanner/api/resource/ServerInfo.java
application/src/main/java/org/opentripplanner/api/resource/ServerInfoResource.java
application/src/main/java/org/opentripplanner/apis/APIEndpoints.java
application/src/test/java/org/opentripplanner/api/model/serverinfo/OtpBadgeGeneratorTest.java

OTP already have an HTTP GET endpoint for fetching OTP server info (version info). This PR add a new endpoint witch return the version information (OTP server version and ser.ver.id) as an SVG xml image. This is useful in CI/CD pipelines where you can add the badge to your deployment status page or to the forked GitHub main README. 
The html to generate a badge:
> http://localhost:8080/otp/version-badge.svg?color=firebrick&label=My%20Label
The returned badge look like this:
> <img width="228" height="24" alt="Skjermbilde 2025-09-18 kl  14 01 26" src="https://github.com/user-attachments/assets/a040148c-86ef-4f44-91fa-7f726929024b" />
The background color used for the version is the same as the OTP logo.
🟥  There is no issue for this. 
✅  There is a unit test for the svg file generation. …

Add OTP Badge to ServerInfo

---

application/src/ext/java/org/opentripplanner/ext/flex/AreaStopsToVerticesMapper.java

This PR has gone through a few iterations but I just noticed that there is an extremely simple solution to my problem: JTS has so-called prepared geometries which speed up the expensive `contains` checks enormously. This makes it really easy to achieve massive speed ups.
Javadoc.
No.
No.

Use prepared geometries to speed up flex zone computation

---

application/src/ext-test/java/org/opentripplanner/updater/vehicle_rental/datasources/gbfs/v3/GbfsStationInformationMapperTest.java
application/src/main/java/org/opentripplanner/updater/vehicle_rental/datasources/gbfs/v3/GbfsStationInformationMapper.java

We experience exceptions when parsing GBFS v3 stations:
```
Error while running polling updater VehicleRentalUpdater{source: org.opentripplanner.updater.vehicle_rental.datasources.gbfs.GbfsVehicleRentalDataSource@64912c72}
java.lang.IllegalArgumentException: Empty localized field
at org.opentripplanner.updater.vehicle_rental.datasources.gbfs.v3.GbfsFeedMapper.localizedString(GbfsFeedMapper.java:185)
at org.opentripplanner.updater.vehicle_rental.datasources.gbfs.v3.GbfsStationInformationMapper.mapStationInformation(GbfsStationInformationMapper.java:59)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
at …
```

Improve GBFS v3 station validation
